### ISSUE TITLE
[Suggestion] Focus on the message box after hitting reply

### ISSUE THREAD

**Issue by tinchou** [zhukov/webogram#1000]
I think it'd be a better UX if the message text box was automatically focused after hitting the reply button. I usually start typing right after hitting reply without noticing I need to first grab the mouse, click on the message textbox, and then start typing.

Thanks!

**Comment by zhukov** [comment]
It does focus for me in Chrome and Firefox for me. What browser and OS are you using?

**Comment by tinchou** [comment]
Ubuntu Wily and Chromium.

Steps:

1. hit a message to select it
1. hit the reply button
1. the message textbox has no focus

**Comment by zhukov** [comment]
Can you open browser javascript console and paste following `Config.Navigator.touch` and press enter?

**Comment by tinchou** [comment]
true. Also, I noticed it doesn’t autofocus after selecting a conversation
either.
On Thu, Dec 10, 2015 at 7:53 AM Igor Zhukov <notifications@github.com>
wrote:

Can you open browser javascript console and paste following
> Config.Navigator.touch and press enter?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zhukov/webogram/issues/1000#issuecomment-163578000>.
>
​

**Comment by tinchou** [comment]
I just checked and it works perfectly on the same computer with Windows 10 and Chrome.

**Comment by tinchou** [comment]
Hey,

I cloned the repo and tracked down the issue. As you pointed out, it's an issue with the `Config.Navigator.touch` property. My laptop has a touch screen, so I assume this is correct behavior.

If you want, I can try to fix this. Let me know if you have any [pointers](https://xkcd.com/138/)!

**Comment by tinchou** [comment]
Sorry to bother. I noticed in many places you choose not to focus `if (!Config.Navigator.touch)`. What's the idea behind that? Do mobile devices focus when you are scrolling and you are trying to prevent it?

Maybe we need to change that with `if (!Config.Navigator.mobile)`?

**Comment by zhukov** [comment]
The idea is to prevent screen keyboard from opening on any user interaction.

Yep, let's move to `Config.Navigator.mobile`. Will you provide PR?

**Comment by tinchou** [comment]
Sure.
