### ISSUE TITLE
the image received in telegram doesnot automatically gets saved in gallery

### ISSUE THREAD

**Issue by PRIYANKA-KS** [zhukov/webogram#1002]
opened the telegram app
received a image file from lumia phone
checked for the image file in the gallery but unfortunately it was not saved
then tried manually to save but that was also a failure

**Comment by zhukov** [comment]
can you please provide screenshots? what browser / OS are you using?

**Comment by PRIYANKA-KS** [comment]
![settings](https://cloud.githubusercontent.com/assets/13289806/11712311/3661775e-9f52-11e5-8797-3080a1f59b73.jpg)
