### ISSUE TITLE
features to implement / bugs to fix

### ISSUE THREAD

**Issue by arieljannai** [zhukov/webogram#1004]
Hi,

How can I find the features/bugs that are just waiting for someone to take them?
I want to help improve the project, so I'm looking for something useful to begin with.

Thanks :sunglasses: 
Ariel

**Comment by zhukov** [comment]
Feel free to choose any issue you like and write in comments how are you going to implement it.

I suggest something like this:
https://github.com/zhukov/webogram/issues/765
https://github.com/zhukov/webogram/issues/968
https://github.com/zhukov/webogram/issues/1003

**Comment by mehrab68** [comment]
Hi
