### ISSUE TITLE
Bot deep linking does not go through login

### ISSUE THREAD

**Issue by dht** [zhukov/webogram#1006]
https://core.telegram.org/bots#deep-linking

If I send a user to telegram web using a deep link, for instance:
https://telegram.me/ExampleComBot?start=vCH1vGWJxfSeofSAs0K5PA
And he is not logged in, he is re-routed to the login screen, after he logs in he is not redirected to the desired deep link.

This causes a complicated workflow where a user is explained to:
1) Go to web.telegram.org.
2) Enter your phone number and login with the SMS you receive.
3) Return here and click the following link:  https://telegram.me/ExampleComBot?start=vCH1vGWJxfSeofSAs0K5PA

If deep linking worked it would just be one stage:
1) Click the following link: https://telegram.me/ExampleComBot?start=vCH1vGWJxfSeofSAs0K5PA and follow instructions.

**Comment by zhukov** [comment]
Telegram Web doesn't support telegram.me links until user is logged in.

How do you force user to open web.telegram.org without him using the web app?

**Comment by thibauld** [comment]
I actually have the same issue, I am dragging a lot of new users to Telegram (via webogram) and I would need the deep linking functionality to work through the login/signup process. Obviously, I understand that the https://telegram.me/MyBot?start=token could not work. But having 
https://web.telegram.org/#/im?p=@MyBot&start=token would be really neat ! 

* If the user is already logged in then, it would bring him to @MyBot welcome screen with the start button and the associated token linked to it.
* If the user is not logged in, it would do the signin / signup process and remember to direct the user to @MyBot once done, dragging along the deep linking information with it.

That would make the on-boarding process so much better for the user and easier for the developer.
