### ISSUE TITLE
Bug in code snippet parser

### ISSUE THREAD

**Issue by Rufflewind** [zhukov/webogram#1009]
The code snippet parser does not format the messages correctly.  Tested on Chrome 47 on Arch Linux.

Example input:

    ```
    Here we have some code
    ```
    
    Here we have some `inline` code

Expected behavior:

>     Here we have some code
>
> Here we have some `inline` code

Actual behavior:

>     Here we have some code
>
> Here we have some in`line c`ode

As you can see, the inline portion is offset by 2 characters to the right.

**Comment by zhukov** [comment]
Thanks for the good bug report.
