### ISSUE TITLE
getFile function in Telegram API and Telegram Bot API

### ISSUE THREAD

**Issue by nournia** [zhukov/webogram#1013]
Hi,
I wanted to use `getFile` function for retrieving files from telegram server. In [API documentation page for this function](https://core.telegram.org/method/upload.getFile) it needs [InputFileLocation](https://core.telegram.org/type/InputFileLocation) object which consists of three values: `volume_id`, `local_id` and `secret`.

I have these three values for files that I want to download, but in [Telegram Bot API](https://core.telegram.org/bots/api#getfile), `getFile` function uses `file_id` that to me seems kind of hashed value of those three variables. Is it possible, to fetch url of one file using its `InputFileLocation` object?

**Comment by zhukov** [comment]
Sorry, this repo has nothing to do with Bot API. You can try to reach Bot Platform Support here: https://telegram.me/botsupport.
