### ISSUE TITLE
Can't use drag to send photo on chrome in mobile view

### ISSUE THREAD

**Issue by cocoaguy** [zhukov/webogram#1017]
When I try to drag to send a photo in mobile view, it just doesn't do anything.
Possible fix could be moving the drag to send image box up to the chat area like it is on telegram desktop.

**Comment by Ryuno-Ki** [comment]
@cocoaguy Could you add your OS/browser combination?

HTML5 native Drag & Drop shall [be a disaster](http://blog.durandal.io/2015/09/22/aurelia-klondike-solitaire-and-dragula/).

Libraries like [Dragula](https://bevacqua.github.io/dragula/) may help.
