### ISSUE TITLE
 Bot API: list chat rooms

### ISSUE THREAD

**Issue by aurium** [zhukov/webogram#1020]
Is there a way to know where my bot is, with the current bot API?

I Believe `getMe` should return a list of chats where the bot is listening https://core.telegram.org/bots/api#getme

**Comment by 39bit** [comment]
This is not the repository for Telegram or Telegram API, but rather a web-based client for Telegram.

**Comment by zhukov** [comment]
Exactly. 
@aurium please refer to bots api instead: https://core.telegram.org/bots/api.
