### ISSUE TITLE
"Message preview" setting to supress message text in notification

### ISSUE THREAD

**Issue by opatut** [zhukov/webogram#1023]
At work I keep webogram open, but sometimes private contacts write things I'd rather not have shown on screen in the professional environment, things my coworkers just aren't supposed to see.

I would like the option "Message Preview" from the Android client so I would only see *who*'s writing, not *what*.

**Comment by zhukov** [comment]
We already have this setting in settings.

**Comment by zhukov** [comment]
<img width="451" alt="screen shot 2016-01-14 at 8 44 35 pm" src="https://cloud.githubusercontent.com/assets/775173/12332469/aac9acba-baff-11e5-96dc-26982e8a4b96.png">
