### ISSUE TITLE
PHONE_MIGRATE_

### ISSUE THREAD

**Issue by siml173** [zhukov/webogram#1024]
hi.
my project worked fine finally :-) , but there is a small problem here, i will be really glad if any body help me.
problem is:
in some phone number in login action i get your phone number registered on X dc. i did search a lot, many people said i have to change my dc, my question is should i change it at run time ? for example put those in array and check them in for loop?
please help.

**Comment by zhukov** [comment]
Hi. sorry, this issue is not webogram-related. Please contact Telegram API support.
