### ISSUE TITLE
Telegram is using the wrong audio channel on Firefox OS

### ISSUE THREAD

**Issue by floppyrom** [zhukov/webogram#1025]
The problem is that when you listen to an mp3 on Firefox OS, the music stops when Telegram sends an audio notification.

Please see the comment 4 here: https://bugzilla.mozilla.org/show_bug.cgi?id=1202136

**Comment by zhukov** [comment]
I don't know how to specify correct audio channel. The code for notifications sound is here: https://github.com/zhukov/webogram/blob/master/app/js/services.js#L3622

**Comment by autra** [comment]
According to [the mdn doc of audio channels API](https://developer.mozilla.org/en-US/docs/Web/API/Audio_Channels_API), you can use the `mozaudiochannel` attribute on your audio tag. I guess it should have a value of `normal`.

**Comment by mozfreddyb** [comment]
*If* you want the notification sound to work like an incoming SMS / email sound, you probably want to get a higher priority than games, websites and music. This would briefly pause playing music and prioritize the notification sound and then continue with music. In this case, you'd want a value of `notification` (not `normal`). Using the `notification` value requires a specific permission, as explained in the document which @autra linked to.

Of course, if the user doesn't want the notification at all, then the app should provide a way to disable in the settings.

**Comment by autra** [comment]
Wait, the default mozaudiochannel should already be 'normal'. The doc is a bit unclear though, so maybe this needs testing.
