### ISSUE TITLE
How to Download a bunch of media easily

### ISSUE THREAD

**Issue by Akronix** [zhukov/webogram#1026]
Hello.

I sometimes receive a set of photos or some files and I want to download them all in one step. I have tried to use the DownThemAll! add-on for Firefox but it doesn't work with webogram.

Gmail has an interesting feature for this which allows to the receiver of a mail to download all the attachments in a .zip compressed file.
webogram could have something close to this: adding a download button when one media is selected and downloading as a .zip file when many media messages are selected.

I'm happy to help with this.

**Comment by kosmodrey** [comment]
Also, it would be nice to download chat history too :+1:

**Comment by Ryuno-Ki** [comment]
@kosmodrey You could use [telegram-history-dump](/tvdstaaij/telegram-history-dump) which utilises the telegram-cli to download your history.

**Comment by kosmodrey** [comment]
@Ryuno-Ki this method requires [telegram-cli](https://github.com/vysheng/tg) which can't be easily complicated on Windows, but [I'll try](https://github.com/vysheng/tg/blob/master/README-Cygwin.md). Thank you for the tip.

**Comment by zhukov** [comment]
We have no plans to support this in web app.
