### ISSUE TITLE
Question: How is the project getting Amazon link metadata

### ISSUE THREAD

**Issue by robcalcroft** [zhukov/webogram#1028]
I'm building a project with similar metadata scraping functionality and I'm trying to work out how you're getting Amazon metadata when you paste a link into a chat. Amazon doesn't have any image meta tags on their page, are you using the API or is there a embed schema i'm missing?

Thanks!

**Comment by zhukov** [comment]
Webogram is a client-side app and fetching metadata is done on server-side. Please contact Telegram support

**Comment by robcalcroft** [comment]
Ahh! Thanks
