### ISSUE TITLE
Messages from @gif are not displayed in Chrome app version.

### ISSUE THREAD

**Issue by YorikSar** [zhukov/webogram#1029]
> The message is not supported on your version of Telegram Web. Update the app to view: web.telegram.org.

This message keeps bothering me again and again in Chrome version. It looks like Chrome version doesn't support some type of messages while web version works fine.

**Comment by lapo-luchini** [comment]
It seems the web version does support this (but not sending them); that's still better than nothing, I hope a new Chrome App version will be packaged from the web sources shortly.

**Comment by ookOok101** [comment]
i use the web.telegram.org version and i can't find and send gifs too

**Comment by alindt** [comment]
Indeed, please update the Chrome packed app to at least support receiving @gif messages

**Comment by zhukov** [comment]
Will publish it very soon.

**Comment by zhukov** [comment]
Done

**Comment by mohammad6006** [comment]
please update to 5.4 chrome extention
