### ISSUE TITLE
Logo is blurred on 175% zoom -> Convert to SVG or Webfont

### ISSUE THREAD

**Issue by julianxhokaxhiu** [zhukov/webogram#1031]
Hi,

Honestly I would never expect that the Telegram logo was a PNG. Can this maybe be converted in SVG? This is how it looks like on a 175% zoom.

![tw](https://cloud.githubusercontent.com/assets/1237070/12391408/dbea62b8-bde7-11e5-8014-84557705e18c.png)

Thanks in advance,
Julian

**Comment by theus** [comment]
What's font family of Telegram logo?

**Comment by julianxhokaxhiu** [comment]
I don't know. I just asked the official Telegram account on Twitter. Meanwhile I found this, which may anyway help us: https://commons.wikimedia.org/wiki/File:Telegram_text_logo.svg

**Comment by julianxhokaxhiu** [comment]
FYI I just made it white so you can directly use it: 
[Telegram_text_logo_white.zip](https://github.com/zhukov/webogram/files/94405/Telegram_text_logo_white.zip)

**Comment by theus** [comment]
@julianxhokaxhiu I would do but you've done o/

**Comment by julianxhokaxhiu** [comment]
@zhukov wanna integrate it?

**Comment by theus** [comment]
I made the correction in theus@a8858a1 . I fix the SVG that @julianxhokaxhiu commented to stay in same width that previous PNG.

**Comment by julianxhokaxhiu** [comment]
Maybe can you do a PR to this project?

**Comment by theus** [comment]
I could. I'd rather wait @zhukov for make a PR. I never send a PR to a repo open-source before :flushed:

**Comment by Ryuno-Ki** [comment]
Um, what it be possible to minify the SVG? We don't to let the world know, that it was created in Adobe Illustrator ;-)

Why wasn't text used for the logo? I assume it is "Helvetica Neue Light" (as per the rest of their web presence).

**Comment by julianxhokaxhiu** [comment]
It is created with Inkscape...and about the font I didn't got any official reply though.

**Comment by Ryuno-Ki** [comment]
Okay, so it was touched by both.

Concerning font, there are tools like [What The Font](https://www.myfonts.com/WhatTheFont/) or [What Font Is](http://www.whatfontis.com/) to ease that job ;-)

In this case, I went to telegram.org and fired up the Developer Tools, though.

**Comment by theus** [comment]
> Um, what it be possible to minify the SVG? We don't to let the world know, that it was created in Adobe Illustrator ;-)

Maybe because I saved with Illustrator :flushed:
I minified the SVG in theus@d579a31 :)

**Comment by Ryuno-Ki** [comment]
+1

**Comment by codefuhrer** [comment]
I have another SVG version for logo (drawn for my webogram fork).

**Original:**
![original](https://cloud.githubusercontent.com/assets/2178368/12589774/78340b22-c470-11e5-8065-1549e217ce90.png)

**Mine:**
![mine](https://cloud.githubusercontent.com/assets/2178368/12589785/824f1b74-c470-11e5-8513-17a6424f54c2.png)

**Yours:**
![yours](https://cloud.githubusercontent.com/assets/2178368/12589780/7d32660a-c470-11e5-81d6-6962ba118c76.png)

Can PR if you like it.

**Comment by julianxhokaxhiu** [comment]
if @zhukov accepts, for me it's fine. Yours looks totally better :)

**Comment by zhukov** [comment]
@codefuhrer can you please provide PR with minified version?
