### ISSUE TITLE
PEER_FLOOD from an innocent account

### ISSUE THREAD

**Issue by HankAviator** [zhukov/webogram#1032]
Hi, whichever version Telegram I use, I can't reply messages to non-contacts (but they can send me messages). Despite the fact I never spammed any non-contact users (because I was even never given a chance to do so), I get this error message:
```
Method: messages.sendMessage
Result: {"_":"rpc_error","error_code":400,"error_message":"PEER_FLOOD"}
Stack: Error
    at u (https://web.telegram.org/js/app.js:32:3911)
    at https://web.telegram.org/js/app.js:32:5210
    at l (https://web.telegram.org/js/app.js:15:11957)
    at https://web.telegram.org/js/app.js:15:12129
    at m.$eval (https://web.telegram.org/js/app.js:15:19535)
    at m.$digest (https://web.telegram.org/js/app.js:15:17966)
    at https://web.telegram.org/js/app.js:15:19622
    at i (https://web.telegram.org/js/app.js:14:3039)
    at https://web.telegram.org/js/app.js:14:4493
    at n (https://web.telegram.org/js/app.js:3:17076)
```
and confirmed by Telegram volunteer, my account was not restricted. This error happens to my Android Telegram too.
![screenshot_20160120-123634](https://cloud.githubusercontent.com/assets/8069557/12440039/82fdb43e-bf72-11e5-9aae-96db255424b2.png)
I always use a proxy to login to Telegram because it's banned in our region.

**Comment by zhukov** [comment]
You should contact Telegram support.
