### ISSUE TITLE
Telegram on Firefox OS 2.6 (dogfood): a lot of data connections (and battery drain)

### ISSUE THREAD

**Issue by Flore-mozfr** [zhukov/webogram#1038]
Hello,
This issue is related to issue #899 which I filled a few months ago. And I still encounter it, although other people don't seem to see it.
For example, today, I used my Z3C for a few texts, checking emails. After 8 hours, half my battery is gone and it consumed 56 Mb of data (of which 10 MB were used by TFE RSS, which leaves 46 MB).
But the new thing is that I spend 3 days with another SIM card (Singtel in Singapore) from another provider (same phone, same all) and it was not using that much data or draining battery that fast.
Which leads me to wonder, is there any issue with telegram and my regular ISP (Free telecom in France). That would explain why few people are impacted.
I would be very happy if we can find and maybe fix this issue.
Will send screenshots and detailed logs later

**Comment by zhukov** [comment]
Can't do anything without logs. But I don't think this is ISP-related issue. Could be account-related. 
Duplicate issue, closing. Use the original one if you get any practically useful info.
