### ISSUE TITLE
Open links that lead to Telegram Bots in the same window.

### ISSUE THREAD

**Issue by lososerg** [zhukov/webogram#1042]
All links that are generated via [Formatting options](https://core.telegram.org/bots/api#formatting-options) are opened in the new window.

There are scenarios where the link would direct to Telegram bots themselves, for example with deep linking:
`https://telegram.me/SomeBotName?start=somecode` this link would also be opened in the new window, which is not right, because duplicate web telegram window would be opened.

I suggest to check if the link starts with `https://telegram.me/` and then decide whether to open it in the new window or not.

**Comment by ihoru** [comment]
Moreover, ability to use bot's commands in href attribute of anchors comes in handy!

**Comment by ihoru** [comment]
And not to show confirmation window if trying to visit links in this cases.

**Comment by Ryuno-Ki** [comment]
> And not to show confirmation window if trying to visit links in this cases.

Could also be a browser feature. Do you have a screenshot?

**Comment by lososerg** [comment]
> Could also be a browser feature.

It is not a browser feature. It is a [documented behavior](https://core.telegram.org/bots/api#formatting-options)

>Note that Telegram clients will display an **alert to the user before opening an inline link** (‘Open this link?’ together with the full URL).

Yet it would be more convenient and correct not to show such alerts if the links lead to bots/channels within Telegram

**Comment by Ryuno-Ki** [comment]
[window.confirm](https://developer.mozilla.org/en-US/docs/Web/API/Window/confirm) was on my mind.

**Comment by Nixon1979** [comment]
Want to invoke android share or open whats app using "whatsapp://send?text=....." to share messages from telegram to whats app. was trying to open using URL in inline_keyboard. But Telegram says BAD URL. Is there a way I can open an external browser from telegram so that my URL call to Whats app works? Or is there a better way?
