### ISSUE TITLE
Chrome web app is not updated

### ISSUE THREAD

**Issue by portaloffreedom** [zhukov/webogram#1053]
https://chrome.google.com/webstore/detail/telegram/clhhggbfdinjmjhajaheehoeibfljjno

I'm a chrome os user, I like very much the having telegram/webogram in a separate app. 
But it's been some time it did not receiving any update. Still no gif support (while web.telegram.org does).

Can someone give it some care? Thanks :)

**Comment by zhukov** [comment]
Duplicate #1029
