### ISSUE TITLE
Add requested Transifex languages ..to Transifex

### ISSUE THREAD

**Issue by GotDemBallsOfSteel** [zhukov/webogram#1056]
So people can form a team and submit translations. Thank you!

**Comment by zhukov** [comment]
Sorry, I don't maintain Transifex and translations.

**Comment by GotDemBallsOfSteel** [comment]
Dear @zhukov! I understand, and that's okay. But who is the maintainer then? How can we contribute to get more languages included in the web version? Thank you!

**Comment by Ryuno-Ki** [comment]
@GotDemBallsOfSteel Check out [the Contribution section about localization](https://github.com/zhukov/webogram/blob/master/CONTRIBUTING.md#localization).

They point to the [Telegram Translation Manual](https://core.telegram.org/translating_telegram) and the [localization guide](https://github.com/zhukov/webogram/blob/master/app/js/locales/README.md).
