### ISSUE TITLE
messages.sendBroadcast is not working

### ISSUE THREAD

**Issue by khalilst** [zhukov/webogram#1057]
Hello
I cloned Webogram and did some changes to its source code to implement messages.sendBroadcast.
This is the code:

        apiPromise = MtpApiManager.invokeApi('messages.sendBroadcast', {
          contacts: list,
          random_id: randomIDs,
          message: text,
          media: { '_': 'inputMediaEmpty' }
        }, sentRequestOptions);

There's no error in client side.
But after sendubg message, an error dialog appears and says:
    
    One of the params is missing or invalid.

And Technical info for this error is:

```

Method: messages.sendBroadcast
Url: N/A
Result: {"_":"rpc_error","error_code":400,"error_message":"UNKNOWN"}
Stack: mtpInvokeApi/rejectPromise@http://localhost:8000/app/js/lib/mtproto_wrapper.js:136:95
mtpInvokeApi/performRequest/<@http://localhost:8000/app/js/lib/mtproto_wrapper.js:246:13
processQueue@http://localhost:8000/app/vendor/angular/angular.js:14745:28
scheduleProcessQueue/<@http://localhost:8000/app/vendor/angular/angular.js:14761:27
$RootScopeProvider/this.$get</Scope.prototype.$eval@http://localhost:8000/app/vendor/angular/angular.js:15989:16
$RootScopeProvider/this.$get</Scope.prototype.$digest@http://localhost:8000/app/vendor/angular/angular.js:15800:15
$RootScopeProvider/this.$get</Scope.prototype.$evalAsync/<@http://localhost:8000/app/vendor/angular/angular.js:16028:15
completeOutstandingRequest@http://localhost:8000/app/vendor/angular/angular.js:5507:7
Browser/self.defer/timeoutId<@http://localhost:8000/app/vendor/angular/angular.js:5784:7
handleMessage@http://localhost:8000/app/js/lib/polyfill.js:119:9

```
Whats wrong with this code? What's the UNKNOWN error?!
Any help appreciated in advance

**Comment by zhukov** [comment]
messages.sendBroadcast is not supported since the channels arrived.
https://telegram.org/blog/channels
