### ISSUE TITLE
create channel and send message to channel

### ISSUE THREAD

**Issue by aghamohammadi** [zhukov/webogram#1058]
Hi
i want to create channel in telegram and send message to channel, also invite user to channel .
I try to do , that created channel but also happen this error :

"try to parse TLSharp.Core.MTProto.Updates, but incompatible type TLSharp.Core.MTProto.Messages_channelMessagesConstructor"

i use this schema fro create channel!
channels.createChannel#f4893d7f flags:# broadcast:flags.0?true megagroup:flags.1?true title:string about:string = Updates;

how invite to channel?
how send message to channel?
plz help me

**Comment by zhukov** [comment]
Sorry, this is a place for webogram-related issues only.
