### ISSUE TITLE
Non-ascii symbols are rendered as entities in some places

### ISSUE THREAD

**Issue by codefuhrer** [zhukov/webogram#1060]
For example, send button:
![tr](https://cloud.githubusercontent.com/assets/2178368/12963384/35c33ea6-d05b-11e5-9275-a772438e55ed.png)

Expected: Gönder
Browser: Firefox

Possible fix: [`user-select: none`](https://developer.mozilla.org/en-US/docs/Web/CSS/user-select) in `.nocopy` class, instead of `::before` stuff.

**Comment by zhukov** [comment]
Fixed
Unfortunately, text with `user-select: none;` is copied to clipboard.

**Comment by codefuhrer** [comment]
Same issue, but another reason. File uploader:
![screenshot](https://cloud.githubusercontent.com/assets/2178368/12977350/3c247a8c-d0db-11e5-96b2-d57e5ca1ab76.png)
