### ISSUE TITLE
Do not collapse space in messages

### ISSUE THREAD

**Issue by IVBakker** [zhukov/webogram#1062]
I saw that when writing a conversation, white space are replace by ```&nbsp``` to avoid collasping. But when sending messages with a bot this is not converted.
The best fix for that I think is to add this style to 
```
.im_message_text {
    white-space: pre;
}
```
in ```app.css:1499```

**Comment by zhukov** [comment]
That's not intended behaviour for the web. If you want to have spaces not collapsed, use backticks for code or pre.
