### ISSUE TITLE
Gifs not showing (Chromium)

### ISSUE THREAD

**Issue by Angelogeb** [zhukov/webogram#1063]
Inline bots are currently displaying but gifs are still not rendered on Chromium

**Comment by zhukov** [comment]
Can you open javascript console and check if any errors are present?
also please try to play mp4 video here: http://camendesign.com/code/video_for_everybody/test.html

**Comment by Angelogeb** [comment]
I don't see any error in the console.

Apparently the problem is that Chromium does not support mp4 videos. In fact the video displays as webm for this browser.

**Comment by zhukov** [comment]
Sorry, Telegram doesn't have webm files for the GIFs. The only format for new GIFs is MP4
