### ISSUE TITLE
Strange scrollbar appears/disappears all the time

### ISSUE THREAD

**Issue by runn1ng** [zhukov/webogram#1064]
Video is worth thousand pictures. This is what happens with my Telegram app:

https://www.youtube.com/watch?v=DHceyBnAPd8

I have 0.5.3 version from chrome app store. I am running Ubuntu 15.10 64-bit and Chrome 47.0.2526.80.

It is *very* annoying.

**Comment by runn1ng** [comment]
I will add that it didn't do that around yesterday, so it must be the new version uploaded today/yesterday.

**Comment by zhukov** [comment]
Reproduced, will fix.
As a temp solution: resize window to make bigger height.

**Comment by runn1ng** [comment]
:+1:
