### ISSUE TITLE
Encoding error open link (in German)

### ISSUE THREAD

**Issue by codingyourlife** [zhukov/webogram#1066]
Just came here to report a small bug in the German version:
![encoding](https://cloud.githubusercontent.com/assets/10122382/13085809/5c980aaa-d4e0-11e5-821c-083aeab328b2.JPG)

Besides that nice work people. Could you please all join the WhatsApp team, they are way behind and need some help ;-)

**Comment by codefuhrer** [comment]
This issue has already been resolved: #1060 

Are you using the [official app](https://web.telegram.org)? Everything's working fine there:
![shot](https://cloud.githubusercontent.com/assets/2178368/13305653/dac45b66-db6d-11e5-8a57-2880620d4b33.png)

**Comment by codingyourlife** [comment]
I have v0.5.3 and came here through hamburger-menu>info>github. I've sent a picture today and problem still exists see here:
![prodvis](https://cloud.githubusercontent.com/assets/10122382/13367626/3073b256-dce4-11e5-88df-82b34c3ac53b.JPG)

I use Chrome portable which tells me it's version 48.0.2564.109 (not sure if that's true, it's from portableapps.com) but also have chrome installed with Version 48.0.2564.116 (recent one).

**Comment by codefuhrer** [comment]
This problem was fixed after v.0.5.3 had been released :unamused:

So you should either wait until the new version releases (then the packaged app in Chrome Store will be updated), or use [online version](https://web.telegram.org) (it's up-to-date with Github repo).

**Comment by zhukov** [comment]
So are you using Chrome Webstore version or a web one (web.telegram.org)?

**Comment by codingyourlife** [comment]
This one:
![v0 5 3](https://cloud.githubusercontent.com/assets/10122382/14293584/8724a4b4-fb6d-11e5-86a4-2d85d81b1f23.JPG)

So you say known issue and will be fixed in next release. That's fine for me -> closed
