### ISSUE TITLE
Не работает превью стикеров

### ISSUE THREAD

**Issue by wotgl** [zhukov/webogram#1070]
При добавлении стикеров (по внешней ссылке) не отображается превью.
![screenshot 2016-02-24 at 21 08 01](https://cloud.githubusercontent.com/assets/7968712/13295607/bb085256-db3a-11e5-8c0e-30d52e0519fa.png)

**Comment by codefuhrer** [comment]
@wotgl, что в консоли (<kbd>ctrl</kbd> + <kbd>shift</kbd> + <kbd>K</kbd> в Firefox)? Какая версия Webogram?

У меня в 0.5.3 всё работает:
![shot](https://cloud.githubusercontent.com/assets/2178368/14062931/322441a8-f3cb-11e5-937c-074a15d63d8c.png)

**Comment by wotgl** [comment]
@codefuhrer 
Chrome OS, Google Chrome Версия 49.0.2623.95 (64-bit)
Telegram Web Version 0.5.3
Лог http://pastebin.com/dhiLyfVF

Проблема возникает именно при добавлении стикеров, которых еще нет в моем наборе. То есть, если перейду по ссылке с уже добавленными стикерами, то все ОК.

**Comment by zhukov** [comment]
А переход происходит по ссылке внутри Вебограма? Или внутри браузера?
Вообще это web.telegram.org или Chrome webstore приложение?

**Comment by zhukov** [comment]
Уже вижу, что web.telegram.org.
Достаточно ли свободного места на диске? Пробовали перезапускать браузер и повторять?
Еще можно попробовать очистить кэш, как описано на скриншоте ниже, перезагрузить страницу и попробовать снова.
![screen shot 2016-04-04 at 12 53 22 pm](https://cloud.githubusercontent.com/assets/775173/14244590/8a7a29c2-fa64-11e5-8e85-82aefaa53851.png)

**Comment by wotgl** [comment]
@zhukov Да, почистил кеш - проблема решена, спасибо!

**Comment by zhukov** [comment]
Duplicate #677
