### ISSUE TITLE
[ @automemebot || @gif ] Number of pictures available lower than Mobile or Desktop app

### ISSUE THREAD

**Issue by julianxhokaxhiu** [zhukov/webogram#1071]
Hi @zhukov,

I noticed these days that while I was using the `@automemebot` the number of pictures available in the scrollable area is really less than the one available on the Desktop app or Mobile ( Android currently ) app.

The same applies for `@gif` bot.

Is this a bug or are you limiting the number of pictures shown? Is it possible to remove this limit in case?

Thanks in advance,
Julian

**Comment by julianxhokaxhiu** [comment]
@zhukov any update for this?

**Comment by julianxhokaxhiu** [comment]
This project feels dead to me. So bad...

**Comment by zhukov** [comment]
I've seen the issue, but it's not a top priority for now. I don't have enough time for the project recently. Any help is welcome.
