### ISSUE TITLE
https://vesta.web.telegram.org/apiw1 is unreachable

### ISSUE THREAD

**Issue by Chaz6** [zhukov/webogram#1072]
Telegram web is currently down as https://vesta.web.telegram.org/apiw1 is unreachable.

IPv6:
 4:  2a00:14f0:1:2::2                                     22.588ms asymm  3
 5:  ae3.core-1.maylands.hml.uk.as29017.net               20.006ms asymm  4
 6:  xe-0-0-0.border-1.sov.lon.uk.as29017.net             25.651ms asymm  5
 7:  xe-0-0-1.border-1.thn.lon.uk.as29017.net             24.302ms asymm  6
 8:  lonap.he.net                                         23.901ms asymm  6
 9:  ge-5-3-2.edge4.London.Level3.net                     31.001ms asymm  8
10:  vl-4061.edge4.Paris1.Level3.net                      37.219ms asymm  8
11:  vl-4060.edge3.Frankfurt1.Level3.net                  43.757ms asymm  9
12:  vl-4082.edge4.Frankfurt1.Level3.net                  45.131ms asymm 10
13:  vl-4060.edge4.Dusseldorf1.Level3.net                 48.903ms asymm 11
14:  vl-4080.edge3.Dusseldorf1.Level3.net                 50.077ms asymm 12
15:  vl-4040.edge3.Amsterdam1.Level3.net                  52.771ms asymm 13
16:  no reply
17:  6-1-3-151.bear1.Russia2.Level3.net                   49.892ms !A

IPv4:
 6:  manc-bb-1c-ae1-0.network.virginmedia.net             15.271ms
 7:  86.85-254-62.static.virginmediabusiness.co.uk        28.243ms
 8:  213.46.182.58                                        31.242ms
 9:  telegram.amster32.ams.seabone.net                    29.835ms !H

**Comment by zhukov** [comment]
@Chaz6 Thanks for the report. Should work fine now. Please try again.

**Comment by Chaz6** [comment]
Yes it is working fine now, thanks!

**Comment by oskar456** [comment]
Looks like server vesta.web.telegram.org is unreachable over IPv6:

    $ telnet vesta.web.telegram.org 443
    Trying 2001:67c:4e8:100a:3:0:811:240...
    telnet: connect to address 2001:67c:4e8:100a:3:0:811:240: Connection timed out
    Trying 149.154.167.124...
    Connected to vesta.web.telegram.org.
    Escape character is '^]'.

This is making the Telegram app for chrome unusable behind a NAT64 network.
