### ISSUE TITLE
We need action one or 2 click to delete chat.

### ISSUE THREAD

**Issue by dikiaap** [zhukov/webogram#1073]
Actually I trouble to remove some individual chat.

**Comment by objcchobo** [comment]
@dikiaap did you figure out how to remove a chat? By "chat", I mean the conversation consisting of multiple messages. I could use 'slide to the left' in an iOS app but can't find an equivalent in webogram.

**Comment by dikiaap** [comment]
@objcchobo It's hidden on webogram. Click your friends profile, there an available "More" button, click that, and you can see "Delete chat". But it's for individual chat.

**Comment by objcchobo** [comment]
@dikiaap Thanks for the quick clarification:)

**Comment by dikiaap** [comment]
#1085
