### ISSUE TITLE
[UI] RTL text overlaps emoticon button

### ISSUE THREAD

**Issue by silicakes** [zhukov/webogram#1076]
When Writing with a RTL language, the text overlaps the emoticon button.

<img width="578" alt="ngwajyt" src="https://cloud.githubusercontent.com/assets/1759539/13424644/bc869f9c-dfaa-11e5-9fc5-c43900f23c22.png">

**Comment by stek29** [comment]
#851 Duplicate

**Comment by zhukov** [comment]
Was fixed recently.
