### ISSUE TITLE
UI bugs when check mark ("✔") shows as "&#10004;" in avatar

### ISSUE THREAD

**Issue by Kenya-West** [zhukov/webogram#1077]
Earlier, it looks fine, but 2 days ago I've spotted that "✔" issue when its displaying in avatar.
![telegram_avatar_issue_1](https://cloud.githubusercontent.com/assets/12271104/13426644/12919d46-dff2-11e5-8338-c0114acc2e2a.png)

**Specs and use of**:
• Windows 10 Pro x64 latest stable;
• Chrome x64 stable latest;
• Telegram is using in Chrome wrapper (as standalone app);

**Comment by zhukov** [comment]
Duplicate #1099 
already fixed.
