### ISSUE TITLE
Can't create account with home telephone number

### ISSUE THREAD

**Issue by djolie** [zhukov/webogram#1078]
![telegram web - mozilla firefox](https://cloud.githubusercontent.com/assets/17225898/13437224/b0a6c1b4-e015-11e5-93a4-75ca1ffcfeb5.png)
how I resolve it??

**Comment by Ryuno-Ki** [comment]
Since you'll [receive a SMS](https://telegram.org/faq#login-and-sms), provide a mobile phone number.

**Comment by zhukov** [comment]
Sorry, this is not Webogram-related issue. Please contact Telegram support.
