### ISSUE TITLE
Feature to resend previous message

### ISSUE THREAD

**Issue by kiddick** [zhukov/webogram#1080]
What about such feature?
May be with possibility to edit the message?

**Comment by git7ub** [comment]
Thanks

**Comment by ferfarz** [comment]
Gracias

**Comment by magicgoose** [comment]
I guess, that's not possible on the server side. So webapp wouldn't be able to do that.

Maybe just as an emulation in supergroups, where a user can indeed delete their own messages. But I guess it's too narrow utility to spend time on it…

**Comment by zhukov** [comment]
Duplicate #1155.
