### ISSUE TITLE
Sharing with telegram.me/share/url not working on the first time

### ISSUE THREAD

**Issue by arieljannai** [zhukov/webogram#1081]
When sharing with `https://telegram.me/share/url?url=address&text=description` it opens the telegram forward popup to select a chat. On the first click it doe's nothing, and on the second time it inserts the shared text to the text box in the selected chat.

I don't know if it supposed to send the text as forward message or it's fine that it's just adding the content to the text box, that's already a design question and not the bug itself. Just to notice that it's not **"forwarding"**

The opened popup also shows chats that cannot receive messages, like channels. This behaviour doesn't happen on the regular forward

**Comment by ferfarz** [comment]
Giving

**Comment by ttvd94** [comment]
No fixes yet?
