### ISSUE TITLE
Webogram has no "clean history" option for a chat

### ISSUE THREAD

**Issue by thibauld** [zhukov/webogram#1085]
Hi,

Other telegram clients have a "clean history" option (accessible from "parameters") that enables the user to clean the history of his chat without "deleting the chat". It seems that Webogram only has the "delete chat" option but no "clean history" option. It would be nice to have a "clean history" option as well.
Thanks for this great piece of software,

Thibauld

**Comment by dikiaap** [comment]
#1073

**Comment by TitanNano** [comment]
directly above "delete conversation" there is a "clear history" option :)

**Comment by zhukov** [comment]
True, we actually have this option.
