### ISSUE TITLE
Public group visible without account (as a guest - only readable)

### ISSUE THREAD

**Issue by HostFat** [zhukov/webogram#1087]
I think that it can be a good idea to make it possible to see **public groups** on webogram without using/having a Telegram account.

So the user will find the public link somewhere, and by clicking it he will be already able to see all the messages/discussion.

If he will want to partecipate, then he will need to make his new account.

By showing the content, I think that it will give a good incentive to new users on registering their new Telegram account.

**Comment by zhukov** [comment]
Sorry, this is currently not possible.
