### ISSUE TITLE
Support pinned messages

### ISSUE THREAD

**Issue by ingria** [zhukov/webogram#1088]
Update 3.7: https://telegram.org/blog/supergroups5k
Update 4.5: https://telegram.org/blog/albums-saved-messages#pinned-messages-in-channels

**Comment by kiddick** [comment]
Is there support of pinned messages? Seems only notification about message was pinned isn't enough. Is there a quick way to access to this message?

**Comment by stek29** [comment]
@zhukov and why is it closed?

**Comment by yellowblood** [comment]
Hey, any news? It really sucks that you have to switch to the mobile app just to find a pinned message in a subgroup. Thanks!

**Comment by Deses** [comment]
+1 to this. The app and the web version should have the same features.

**Comment by Ryuno-Ki** [comment]
Wasn't that fixed in #1287?

**Comment by stek29** [comment]
@Ryuno-Ki nah, pinned chats and pinned messagages are different

**Comment by stek29** [comment]
@Ryuno-Ki nah, pinned chats and pinned messages in chat are different

**Comment by orschiro** [comment]
How can you even pin a message on Android? I don't see this option.

**Comment by whipermr5** [comment]
It only works in supergroups. Tap the message you wish to pin and select pin.

**Comment by rodneyrod** [comment]
From what I can see, Webogram can see when a message is pinned, since it comes up as a quote in the message feed.
Only problem is that it has no way of displaying it after the fact.
