### ISSUE TITLE
Messages in super groups default to read

### ISSUE THREAD

**Issue by Jargonius** [zhukov/webogram#1090]
When sending a message to a super group it defaults to being seen instead of waiting until someone has seen the message.  This happens on the Android version, the Windows version, and the web version.  I can't seem to find anywhere else to report this.  I tried the official telegram support chat but nobody reads my messages there.  Can somebody here pass the message along?

**Comment by zhukov** [comment]
Sorry, this is API-related question. Please contact telegram support or twitter.com/telegram.
