### ISSUE TITLE
Super group messages not loaded until next reload of browser tab

### ISSUE THREAD

**Issue by fhoshino** [zhukov/webogram#1093]
Messages in super group does not seems to appear until manually reload tab or sending a message in the group.

**Comment by ArsenyYankovsky** [comment]
+1

**Comment by fhoshino** [comment]
Further detail: If supergroup member excided 239 members, new messages could not be fetch until page refresh, supergroup which has members 238 or below and normal groups works fine.

**Comment by zhukov** [comment]
Should be fixed in 0.5.4
