### ISSUE TITLE
Icons search

### ISSUE THREAD

**Issue by UnoSD** [zhukov/webogram#1094]
Please consider implementing a text box to allow search icons by name as other chat like Slack have.

**Comment by zhukov** [comment]
We have one. try to type `:lau` in text field.
![screen shot 2016-04-03 at 10 55 02 pm](https://cloud.githubusercontent.com/assets/775173/14234584/2285cdfa-f9ef-11e5-8fb7-0d05b31da52d.png)

**Comment by UnoSD** [comment]
Ah, thanks! Probably my request should have been a "contains text" search then. If you type :augh, you don't get the laughing suggestion.
