### ISSUE TITLE
Сломалось автообновление чата в веб версии

### ISSUE THREAD

**Issue by PekaFat** [zhukov/webogram#1097]
В конференциях на https://web.telegram.org новые сообщения перестали автоматически подгружаться, приходится обновлять страницу вручную, иначе новых сообщений я не увижу.
В десктоп версии всё ок.
Хром 49.0.2623.110, никаких расширений не стоит, раньше всё было ок, но внезапно началось это.

**Comment by zhukov** [comment]
Duplicate #1093
