### ISSUE TITLE
channels access_hash

### ISSUE THREAD

**Issue by elia07** [zhukov/webogram#1102]
Hi
there is an api for reading channels messages : channels.getImportantHistory#ddb929cb channel:InputChannel offset_id:int add_offset:int limit:int max_id:int min_id:int = messages.Messages;

but it needs inputchannel and inputchannel need access_hash , how to find access_hash for channels ?

**Comment by zhukov** [comment]
Sorry, this is not webogram-related question. Please don't pollute issues.

**Comment by elia07** [comment]
well , we assume that is not webogram-related question, but u know the answer please help me
