### ISSUE TITLE
[REQUEST] Remove left and right white bounds.

### ISSUE THREAD

**Issue by Mistero5050** [zhukov/webogram#1105]
There are useless enormeous borders left and right? Why? Why not using the full page instead like messenger.com?

Explain this to me, please.

Sorry for my bad English.

**Comment by zhukov** [comment]
Sorry we have a designer already. This repo is just for code.

**Comment by eyeofshiva** [comment]
Jeg ved ikke hvad der er sket men tror min konto har gjort noget på din side, og det er ikke mig 😧

Sendt fra min iPhone

Den 7. apr. 2016 kl. 17.06 skrev Igor Zhukov <notifications@github.com>:

Closed #1105.

**Comment by eyeofshiva** [comment]
i dont know what happened. i did not meant to do anything. it wasnt me 🤕

Sendt fra min iPhone

Den 7. apr. 2016 kl. 17.06 skrev Igor Zhukov <notifications@github.com>:

Sorry we have a designer already. This repo is just for code.

**Comment by Mistero5050** [comment]
Ok, but don't you agree with me?
How can we contact the designer?
