### ISSUE TITLE
no download option TelegramWeb

### ISSUE THREAD

**Issue by jusore** [zhukov/webogram#1106]
Into web.telegram.org when you receive an audio that telegram can't recognize like ogg, and you press play on it, the download option disapear and you cannot listen the audio and neither download it, your contact has to resend it to you.

**Comment by zhukov** [comment]
Can you show a screenshot?

**Comment by jusore** [comment]
I could, but I've search for the file that gave that problem and now it shows the "Save" button O.o, I think you maybe have resolve this problem in the last update.
