### ISSUE TITLE
Feature request: automatic new audio message play while screen is on

### ISSUE THREAD

**Issue by keerah** [zhukov/webogram#1107]
It would be pretty convenient if incoming audio messages automatically played for current user in focus while screen is still on. And probably this feature would be controllable.

**Comment by Ryuno-Ki** [comment]
To me, it would be bad UX.

Say, I'm checking my Telegram messages while traveling. I dislike annoying people around just because audio starts playing without my control.

**Comment by keerah** [comment]
That's why it should be switchable. It's good when you have quite constant conversation to someone. Now I have to press play each time I've got a message.

**Comment by Ryuno-Ki** [comment]
Defaulting to "no auto-play"?

**Comment by keerah** [comment]
no matter :)

**Comment by Ryuno-Ki** [comment]
The issue with adding more and more config options can lead to confusion or appear badly designed.

So a careful choice of proper options which are not editable by the user is favorable.

**Comment by keerah** [comment]
But there're ways to optimize it as well. For example continuous dialog can be on while the particular user in focus AND the screen is on, you turn off screen manually and then you got only notification about incoming message. Or even further, while screen is on, the user in focus and the phone is in vertical position (held in hand)

**Comment by magicgoose** [comment]
If you decide to implement it, please keep it turned off by default. Unexpected auto-playing sound is probably the worst a webapp can do.

**Comment by zhukov** [comment]
Sorry I don't think this will be a good UX for web app. And there is no such feature in the mobile native apps afaik.
