### ISSUE TITLE
[Enhancement] Limit webpage description height

### ISSUE THREAD

**Issue by codefuhrer** [zhukov/webogram#1113]
Sometimes it can be too tall (especially for Wikipedia articles):
![shot1](https://cloud.githubusercontent.com/assets/2178368/14659486/80ab0696-06ad-11e6-9784-5e70280f4278.png)

TDesktop (limited to 3 lines):
![shot2](https://cloud.githubusercontent.com/assets/2178368/14659516/bf19847a-06ad-11e6-9018-27f2f82fdd4b.png)

**Comment by Ryuno-Ki** [comment]
Telegram Desktop truncates at 147 chars (+ 3 dots), whereas Webogram used ~1032 chars here.

I agree, it's way too much for a preview.
