### ISSUE TITLE
Unicode support (UTF-8) for contact names

### ISSUE THREAD

**Issue by bladefistx2** [zhukov/webogram#1115]
This works in the telegram phone app, but not in chrome webapp.
![image](https://cloud.githubusercontent.com/assets/4094788/14676949/3c50dbb8-0718-11e6-995a-e58c399fa6bf.png)

I think the image speaks for itself. 
To reproduce, create contacts that have names like: משפחה OR קיבינימט

**Comment by zhukov** [comment]
Duplicate #1136
