### ISSUE TITLE
Cannot view channels content before leaving

### ISSUE THREAD

**Issue by Kondra007** [zhukov/webogram#1118]
Steps to reproduce:  
1) Open channel in Telegram Web. **Result**: You see nothing.  
2) Press "+Join". **Result**: You see nothing.  
3) Open channel info and press "Leave". **Result**: You see channel's content.

Alternative way:
1) Open channel in Telegram Web. **Result**: You see nothing.  
2) Open channel info and press "Join". **Result**: You see channel's content.

Chrome 49.0.2623.112 m  (Same on Chrome 50)
Windows 8.1x64

**Comment by zhukov** [comment]
Can't reproduce. Can you give a channel url, screenshots and check if you see any errors in javascript console

**Comment by Kondra007** [comment]
Any channel (really any), for example, https://telegram.me/sickipedia.
Yes, there's one error: `Error 400 OFFSET_INVALID 2 2`

**Comment by codefuhrer** [comment]
I confirm. Btw, the same error occurs in tg-cli too:

```js
[2.698] Api call updates.getDifference app.js:29:27772
[2.698] Error 400 OFFSET_INVALID 2 2
```
![2016-04-26 19 59 08](https://cloud.githubusercontent.com/assets/2178368/14827102/d7be64a2-0bf1-11e6-88a2-4b0f1dc51523.png)
