### ISSUE TITLE
iframe telegram chat for website

### ISSUE THREAD

**Issue by ZeoNish** [zhukov/webogram#1121]
It would be nice to have the ability to install telegram chat on your site. Now there is a need to create a good chat for your website, telegram is great for implementing a multi-platform chat for the site.

All users will be able to access the chat site clients using the telegram and chat while on the website.

**Comment by codefuhrer** [comment]
Dupe #825, #442, #1040

**Comment by ser37** [comment]
#1155 #1154

**Comment by zhukov** [comment]
Sorry, but I don't have time for that. Feel free to fork and implement this.
