### ISSUE TITLE
Feature request full width mode

### ISSUE THREAD

**Issue by Eduruiz** [zhukov/webogram#1122]
I think will be great if we can have a larger version of telegram web, maybe a option in settings.
something like:
```
.tg_head_split { max-width: 100%;  }
.im_page_wrap { width: 100%; }
.im_message_wrap { max-width: 90%; }
.im_send_panel_wrap { max-width: 95%; }
.im_send_form { max-width: 95%; }
```

this will make telegram web looks more "comfortable", I think.

**Comment by magicgoose** [comment]
Oh yeah. Right now there's a lot of wasted space when using it on a typical wide monitor.

**Comment by zhukov** [comment]
Sorry, we have no plans to change design for now. The chat log has limited width due to improve readability for text messages.

**Comment by fsolatan212** [comment]
is there an easy way to change the width of the left bar with the list of chats?
