### ISSUE TITLE
Feature request—allow to hide conversations list

### ISSUE THREAD

**Issue by magicgoose** [zhukov/webogram#1124]
I'd like to not have conversations list on the screen constantly. (for privacy reasons)  
Please implement a way to hide/restore the list.

**Comment by codefuhrer** [comment]
You can use the mobile layout: https://web.telegram.org/?force_mobile=1

**Comment by magicgoose** [comment]
Oh yeah. Thank you for the tip. However, it has other unintended side-effects, like disabled picture autoloading, and generally different design.

**Comment by zhukov** [comment]
Sorry but mobile layout is the only solution for now.
