### ISSUE TITLE
Can't download .dll sent as documents in telegram web

### ISSUE THREAD

**Issue by notnsane** [zhukov/webogram#1134]
No problems with Mobile Telegram. 

Just send or have sent a dll, the download finishes but I click on "Save file" and nothing happens.

**Comment by zhukov** [comment]
Works fine for  me with some sample dll. What's the browser? Can you record a video? Can you give the file? Can you try with one of these dll http://www.thevbzone.com/d_DLL.htm ?

**Comment by zhukov** [comment]
Closing the issue for now.
