### ISSUE TITLE
Improvement request: inline bots geolocation if location not set in browser

### ISSUE THREAD

**Issue by 8manuel** [zhukov/webogram#1147]
Hi, this is not a bug, is an improvement and not only webogram.

If you create an inline bot with `/setinlinegeo` enabled in Android, even if you don't have the GPS on the Android client sends the `inline_query` message to the bot, of course without the `location`, but this is not a problem because in the bot you can send a message back to the user and remind to enable the GPS on the phone (this is much better than saying nothing because the user sees the communication in progress gif and thinks the bot is working on the query).

But the Webogram if you don't press in the browser the share my location button, never arrives the  the `inline_query` message to the bot.
In iOs is also the same problem, if no GPS enabled no message is received in the bot.

So, my improvement request is that in webogram, even if location is not available to send the `inline_query` message to the bot.
For iOs I have the same request but, I don't know where to request it because the github repository seems outdated.

**Comment by zhukov** [comment]
can you record a video?
I see this:
![screen shot 2016-06-06 at 8 49 54 pm](https://cloud.githubusercontent.com/assets/775173/15831851/454db080-2c28-11e6-81c5-9cfc71750839.png)
When I press either button, the request is being sent and I see some results. I tested with @foursquare bot.
