### ISSUE TITLE
LTR language are overlapping the emoji icon

### ISSUE THREAD

**Issue by Thatkookooguy** [zhukov/webogram#1149]
Here's an emample:
LTR:
![ltr_before](https://cloud.githubusercontent.com/assets/10427304/15448902/76391044-1f77-11e6-9ef2-d9a754825b2f.PNG)

RTL:
![before](https://cloud.githubusercontent.com/assets/10427304/15448904/79d3d554-1f77-11e6-925d-4e7ce03a854a.PNG)

**Comment by zhukov** [comment]
Duplicate #1076

**Comment by Thatkookooguy** [comment]
I think the solution I suggested is better. It means you don't need the javascript condition at all. If I understand correctly, this javascript condition is needed to understand RTL languages.
With my solution, no change is needed for either RTL or LTR

**Comment by stek29** [comment]
@Thatkookooguy your solution isn't related to this issue.

**Comment by Thatkookooguy** [comment]
@stek29 it fixes both. It makes the RTL solution work the same as the LTR solution

It does solve the reported RTL text overlapping the emoji button

**Comment by Thatkookooguy** [comment]
That's why I added extra padding on the right side of the element so text won't be able to overlap with the icon (that's true for both languages)

@stek29 did you try it out? I just checked and it works great (no scrollbar + no text overlapping the emoji)
