### ISSUE TITLE
Linux client does not honor selection buffer

### ISSUE THREAD

**Issue by phaoost** [zhukov/webogram#1152]
Hello,

we have weird bug that changes the default system behavior.
Normally, Linux users do not need to copy/paste with drop-down menu: selecting the text and then pasting it with middle button click of pointing device works, while in telegram it doesn't. Selecting does not put selection in the buffer.
Instead, it should put the selection to the buffer. Only calling drop-down menu and selecting 'Copy selected text' works.

Please fix this bug.

**Comment by migueloop** [comment]
Hello phaoost, 

Could you give us more information? What browser are you using? What linux distribution and version are you using? I can actually copy text in my Ubuntu 14.04 with both browsers Chrome and Firefox...

**Comment by phaoost** [comment]
Hello,

I am trying to select text in linux telegram client, not in browser. Did I use the wrong tracker for reporting the bug?

**Comment by migueloop** [comment]
I think so. Please others correct me but Telegram Linux client's repository is this one https://github.com/telegramdesktop/tdesktop

**Comment by phaoost** [comment]
Thanks. submitted.
