### ISSUE TITLE
[Feature Request]: Add the ability to record an audio message

### ISSUE THREAD

**Issue by cajuntechie** [zhukov/webogram#1153]
All of the non-web versions of the Telegram client support the ability to click a microphone icon near the chat bar to record a short voice message to another user. The web version does not support this feature and makes communications in some contexts very difficult. Please add this feature to the web version.

**Comment by marco-c** [comment]
#840 is adding the feature for Firefox OS, but it should be simple to extend it for desktop browsers.

**Comment by Akronix** [comment]
Duplicated of #190
