### ISSUE TITLE
Error when trying to return to a group

### ISSUE THREAD

**Issue by parhamdoustdar** [zhukov/webogram#1159]
Steps to reproduce:

1. Leave a group you have been invited to.
2. Click on the name of the group at the top of the window, and in the pop-up that appears, choose `Return to group`.

Expected result: you should re-join the group.

Actual result: you receive an error saying `Sorry, you can only send messages to mutual contacts at the moment.`

Here is the technical details:

```
Method: messages.addChatUser
Url: N/A
Result: {"_":"rpc_error","error_code":400,"error_message":"PEER_FLOOD"}
Stack: g@https://web.telegram.org/js/app.js:31:11150
e.returnToGroup@https://web.telegram.org/js/app.js:38:4407
ln.prototype.recurse/<@https://web.telegram.org/js/app.js:17:26437
@https://web.telegram.org/js/app.js:22:1736
fn/this.$get</m.prototype.$eval@https://web.telegram.org/js/app.js:16:3934
fn/this.$get</m.prototype.$apply@https://web.telegram.org/js/app.js:16:4163
@https://web.telegram.org/js/app.js:22:1716
ie.event.dispatch@https://web.telegram.org/js/app.js:5:2735
ie.event.add/f.handle@https://web.telegram.org/js/app.js:4:31540

```

**Comment by zhukov** [comment]
Sorry, your account was limited, you should contact telegram support.
