### ISSUE TITLE
answerCallbackQuery notification message is not properly centered

### ISSUE THREAD

**Issue by lososerg** [zhukov/webogram#1162]
Notification that is sent via https://core.telegram.org/bots/api#answercallbackquery (`show_alert = false`) appears on the bottom of the page, overlapping important UI elements such as bot keyboard. 

See attached screenshot.

![answercallbackquery_webogram](https://cloud.githubusercontent.com/assets/6727329/15892042/3abdf6e4-2d80-11e6-8df2-4e466f104beb.png)

**Comment by zhukov** [comment]
This is an intended design. It looks almost the same on Android app.

**Comment by ihoru** [comment]
@zhukov 
Here is how it looks like in Android:
![photo_2016-06-09_22-12-20](https://cloud.githubusercontent.com/assets/361908/15943005/99cd2776-2e8f-11e6-9eb9-b95ce5c7a268.jpg)


Here is how it looks like in desktop (bubble is lovely centered):
![2016-06-09_22 11 31](https://cloud.githubusercontent.com/assets/361908/15942999/9551a94c-2e8f-11e6-80fa-d4c68cd13815.png)
