### ISSUE TITLE
answerCallbackQuery alert problems: New line symbol is ignored, Emojis are shown without using sprite

### ISSUE THREAD

**Issue by lososerg** [zhukov/webogram#1163]
When sending alert message via https://core.telegram.org/bots/api#answercallbackquery (`show_alert = true`) new line symbols are ignored. Tested in other clients (Android, iOS, Desktop, Mac) - new line symbols are shown correctly there.

Also in same alerts emojis are shown using the OS library, but not webogram's emoji sprite, which breaks  consistency of UX.

See screenshots attached.

_Webogram on Windows in Chrome_
![web_answercallbackquery_alert](https://cloud.githubusercontent.com/assets/6727329/15893190/d9be27a4-2d86-11e6-9f65-a276153bab14.png)
 
_Mac native client_
<img width="250" alt="mac_answercallbackquery_alert" src="https://cloud.githubusercontent.com/assets/6727329/15893260/30f63a16-2d87-11e6-92e1-a068daf9ce55.png">

_Android_
![android_answercallbackquery_alert](https://cloud.githubusercontent.com/assets/6727329/15893297/741797cc-2d87-11e6-8158-98ce17abf8c3.png)

_Desktop client on Mac_
![desktop_answercallbackquery_alert](https://cloud.githubusercontent.com/assets/6727329/15893336/9e464282-2d87-11e6-9aba-d5dbecaa5272.png)

_iOS_
![iphone_answercallbackquery_alert](https://cloud.githubusercontent.com/assets/6727329/15893348/b739d808-2d87-11e6-8c8d-a06b908ca76b.png)

**Comment by ihoru** [comment]
Thanks you! Now it's work great!
![2016-06-09_20 37 52](https://cloud.githubusercontent.com/assets/361908/15939797/0d7044aa-2e82-11e6-849b-adb1f5ce4a16.png)

@zhukov but new line symbols are still being ignored in alert message...
