### ISSUE TITLE
Open links to Telegram contact from text without reloading page

### ISSUE THREAD

**Issue by ihoru** [zhukov/webogram#1166]
1. A bot sends message to with a link (`<a href="https://telegram.me/NAME_BOT">test</a>`) with `parse_mode=HTML` (or even Markdown as well)
2. You are trying to open this link in Webogram

Problems:
1. It shows a confirmation dialog to go through this link.
2. After accepting the confirmation page reloads and dialog with a bot is shown.

How should it be:
1. Do not show confirmation dialog as it is a link to the telegram.
2. Show new dialog in place without reloading.

How to reproduce:
1. Open the link below (the command `/me` will be executed):
https://telegram.me/PokerBot?start=L21l
2. If it necessarily, it will ask you to choose a language -- choose one and hit the link above again.
3. You will see your profile with your level in the top (it's a link), click on it.

![2016-06-16_09 58 16](https://cloud.githubusercontent.com/assets/361908/16108191/73867bc4-33aa-11e6-9ae1-aea41a07c207.png)

**Comment by zhukov** [comment]
1. It shows a confirmation dialog to go through this link.
it is supposed to work like this. Try iOS version.

**Comment by ihoru** [comment]
@zhukov 
1. But there is no confirmation in Android and Desktop client. Two vs One :)

2. What about second point? Is it a bug?
