### ISSUE TITLE
BlackBerry OS 7 Browser fails on "Generating keys"

### ISSUE THREAD

**Issue by nihirash** [zhukov/webogram#1171]
In debugger I've got 2 errors:
![2016-06-24 14-21-15](https://cloud.githubusercontent.com/assets/5459892/16336530/f3aea2aa-3a16-11e6-8f93-45b86d2b9e8f.png)

I tried wait(all evening) but nothing happens at all. 

Device: BlackBerry Bold 9900.

**Comment by nihirash** [comment]
After I add polyfill.js to project I've got "Network error". 
![2016-06-24 20-35-02](https://cloud.githubusercontent.com/assets/5459892/16345580/55f56fbe-3a4b-11e6-8f2a-ca920d1b414f.png)

And request to api - gets 404 error page
![2016-06-24 20-36-40](https://cloud.githubusercontent.com/assets/5459892/16345601/6f6a35d8-3a4b-11e6-9da8-40c34bfdee56.png)

**Comment by zhukov** [comment]
I think, the reason is that we need [xhr2](http://www.html5rocks.com/en/tutorials/file/xhr2/) with binary data send/receive support. Telegram uses MTProto protocol, which is binary.

**Comment by zhukov** [comment]
Yep, http://caniuse.com/#search=arraybuffer shows, that Blackberry 7 doesn't have support for Typed arrays, so it can't be properly supported in XHR, which is required by Webogram to work.
