### ISSUE TITLE
Mesage preview in contact list does not change when message text is edited

### ISSUE THREAD

**Issue by maximal** [zhukov/webogram#1177]
When I edit the message (in another Telegram client) its text changes in the webchat, that’s okay.

But message preview in the contact list stays the same (like in the old, initial message).

**Comment by azzimuth** [comment]
Confirm. One needs to reload the page in order the message preview to be update to correct version.
![webogram_bug](https://cloud.githubusercontent.com/assets/1640148/19852203/41bd43f6-9f62-11e6-9dcc-fcbf0c09a407.png)

**Comment by maximal** [comment]
Preview text in the sidebar stays the same even if the message is edited from inside web client.
