### ISSUE TITLE
[Feature Request] Allow regular groups to have a description

### ISSUE THREAD

**Issue by MSadeghHE** [zhukov/webogram#1179]
It should be nice to allow regular groups to have a description, same as super-groups and channels which both already can have a description.

**Comment by zhukov** [comment]
This is a feature request for Telegram API, not Webogram app.

**Comment by MSadeghHE** [comment]
Thanks for the information, I hope someone tell me where can i report this feature request? I have searched telegram.org website, but I could not found anyway to report this feature request.
