### ISSUE TITLE
Text will be trimmed after pressing ALT

### ISSUE THREAD

**Issue by OsamaAbbas** [zhukov/webogram#1188]
This behavior is annoying if user is typing in two languages. For example: he write `Some English Text `, then he press ALT+SHIFT to change Keyboard layout. Now that sentence is trimmed to `Some English Text`. Even worse, if network connection was weak, that trim action will not preformed immediately, So the user would write some text in the other language (a few charachters maybe), then he will find them got trimmed because of ALT key was pressed.

How to re-produce?

Type some text, put a space at the end of it, now:
Press SHIFT: nothing will happen. (no trim).
Press CTRL: also nothing. (no trim).
Press ALT: Text will be trimmed.

Put another space. Now press ALT and type a few charachters very fast. They will dissappear.

**Comment by zhukov** [comment]
Please refresh the page on web.telegram.org and try again.

**Comment by OsamaAbbas** [comment]
Solved! Thank you.
