### ISSUE TITLE
Weird message box behaviour in Firefox

### ISSUE THREAD

**Issue by codefuhrer** [zhukov/webogram#1189]
Sometimes input text appears in some random place. Looks like the new drafts system doesn't work correctly.

![578beaa43884a163757117](https://cloud.githubusercontent.com/assets/2178368/16902916/989fd02e-4c76-11e6-8c6e-02cc0e34cf93.gif)

App version 0.5.5 (7be7137)
Firefox 47.0

**Comment by zhukov** [comment]
@codefuhrer Punto switcher?
Can you reproduce in chrome? What are the steps to reproduce?

**Comment by codefuhrer** [comment]
Hm, seems like my Webogram was outdated. Works well with the latest commit :+1:
