### ISSUE TITLE
[UI] GitHub project link is not intuitive enough to be found

### ISSUE THREAD

**Issue by Vdragon** [zhukov/webogram#1190]
Recently I'd want to report an issue to this issue tracker and tried to find the GitHub link but I failed, I only made possible to come here by a friend's hint.

Currently (at least in Firefox) one must:
1. Expand the menu
2. Open the about page
3. Manually scroll-down the page to make the "GitHub" link visible
4. Click the "GitHub" link

However the step 3 is non-self-suggestible at all as user will presume that scrolling-down only show more changelogs instead of a link to GitHub.  In my case I frustrated to end myself in the "Telegram Web" Twitter page since it's the only external link I could've found.

Issue reproduction video: [Telegram Web - [UI] GitHub project link is not intuitive enough to be found - reproduction video - YouTube](https://www.youtube.com/watch?v=L98IsGbkSrc)

I would suggest that:
- making the GitHub link as a button same as Twitter
- making the GitHub link visible without user scrolling-down

**Comment by pjoshi235** [comment]
Add these in index.html
<link rel="stylesheet" href="https://web.telegram.org/css/app.css"/>
<link rel="stylesheet" href="vendor/jquery.nanoscroller/nanoscroller.css">

**Comment by pjoshi235** [comment]
Add these lines in index.html
`<link rel="stylesheet" href="css/app.css"/>
 <link rel="stylesheet" href="vendor/jquery.nanoscroller/nanoscroller.css">`
```

**Comment by pjoshi235** [comment]
```
`Add these `lines in index.html
<link` rel="stylesheet" href="https://web.telegram.org/css/app.css"/>
<link rel="stylesheet" href="vendor/jquery.nanoscroller/nanoscroller.css">`
```

**Comment by zhukov** [comment]
I'm sorry but this is an intended design. No plans to change it yet.
