### ISSUE TITLE
URGENT !!! Please delete my this 2 ids : @geetlimo & @Geet11591 

### ISSUE THREAD

**Issue by salonilimo** [zhukov/webogram#1194]
![image](https://cloud.githubusercontent.com/assets/16555713/17133196/c3ea331e-5342-11e6-9af0-e144bf653c46.png) 

Kindly do the needful on urgent basis

**Comment by TitanNano** [comment]
if this is is your user id, remove it form your account. If not, nothing can be done. Also this is not the right place for your request.

**Comment by stek29** [comment]
Looks like this issue isn't related to Webogram **at all**. 
Also, @salonilimo has no public activity or contributions except this issue, so I'm sure (s)he won't close this issue on h(er)(is) own. 
@zhukov I think this issue can be closed ^_^

**Comment by stek29** [comment]
@salonilimo thanks!
You can also use "Ask a question" button in app settings
