### ISSUE TITLE
Icon of webogram/telegram and guide arrows not properly displayed & CSS not included.

### ISSUE THREAD

**Issue by psingl** [zhukov/webogram#1195]
![untitled](https://cloud.githubusercontent.com/assets/13885706/17183589/d43e2028-5445-11e6-85c5-57e05fcb266b.png)
When I loaded latest version of extension in chrome. On launching the app, the window that opened looked weird and unthinkable. On inspecting the code I found that CSS file i.e. CSS folder was missing in app folder of webogram-master. Please look into this matter. Add a css folder of previous version that also works well. Next, the icon of the telegram or webogram was not in place rather its position, height width were all right. This was because filename General.png in img/icons folder is not proper or not properly working on merging img folder of old version and new version it was alright.

**Comment by zhukov** [comment]
Where did you get this version of extension?

**Comment by stek29** [comment]
That icon in taskbar...

**Comment by psingl** [comment]
I downloaded it from github only.

**Comment by stek29** [comment]
@psingl do you have a link?

**Comment by zhukov** [comment]
You should use release version from https://github.com/zhukov/webogram/releases or build release from source you've downloaded (instructions are in README)
