### ISSUE TITLE
"Use Large Fonts" setting not being respected in text input field on Telegram for Mac

### ISSUE THREAD

**Issue by rafaelclaycon** [zhukov/webogram#1197]
After I was upgraded to version 2.18.48804 of Telegram for Mac, the text input field (the one used to type-in messages) doesn't have the same font size as the text of messages displayed in chats. I use the app with the "Use Large Fonts" setting on. Think somebody just forgot to honor the font size for the text input field too.
![captura de tela 2016-07-28 as 21 21 30](https://cloud.githubusercontent.com/assets/5100081/17233790/480d1978-5509-11e6-8f8b-a3dc99d14720.png)

**Comment by stek29** [comment]
Please, report this issue to [Telegram for Mac repo](https://github.com/overtake/telegram). 
This Repo is for web.telegram.org.
@zhukov I think this issue can be closed ^_^

**Comment by rafaelclaycon** [comment]
You are right! Thanks!

**Comment by stek29** [comment]
@rafaelclaycon can you close the issue then?
