### ISSUE TITLE
Can't forward messages between chats

### ISSUE THREAD

**Issue by TitanNano** [zhukov/webogram#1200]
I have some issues forwarding messages across chats on mobile. I had a look at the logs and it looks to me like the message, selected to be forward, is overwritten by the current draft for the chat. Even when I didn't write anything. 

I don't experience this problem on desktop and sometimes I can forward something on mobile but at some point it seams to break and after that I can't forward anything anymore.

**Comment by evgkrsk** [comment]
Same problem on desktop Firefox using web.telegram.org.

**Comment by kiddick** [comment]
same here
from time to time

**Comment by stek29** [comment]
Always: irefox 48.0.2, Arch Linux, web.telegram.org v.0.5.5
