### ISSUE TITLE
camera still working and draining battery after blocking phone

### ISSUE THREAD

**Issue by Reakleases** [zhukov/webogram#1202]
Android app.
When you able to choose your photo for sending image, you also can see preview of photo provided by camera. I guess camera is not handled by lifecycle and continues to work after i switch off screen.
Sorrry for my bad english.

**Comment by stek29** [comment]
Maybe it's for Android app and not for Webogram?

**Comment by Reakleases** [comment]
yes, but its not possible to create issue in android repo. So google saying that people creating issue here even for mobiles.

**Comment by stek29** [comment]
It's possible to use "Ask a question" button in settings.
And it's recommended.
Internal private bug tracker is used for android app, and contacting support is the only way to report bugs.

Btw, google also saying that people jumping even off the roofs. Would you do it too?
