### ISSUE TITLE
Pressing enter to send message after ASCII emoticon does not close pop-up

### ISSUE THREAD

**Issue by polybuildr** [zhukov/webogram#1203]
Recently I've noticed the following bug:

If I use an ASCII emoticon, such as `:P`, as soon as I type the `:`, the pop-up list of emojis appears. When I type `P` after that and hit enter, the message is sent and the pop-up closes, but then reappears an instant later once again. The end state looks like this:

![screenshot](https://cloud.githubusercontent.com/assets/6189009/17556846/92983760-5f32-11e6-88d9-2025501a9e71.png)

**Comment by stek29** [comment]
It became fixed...

**Comment by polybuildr** [comment]
@stek29, did you mean to comment that on #1207? As of 0.5.5 (which is the version I have), this still happens.

**Comment by stek29** [comment]
@polybuildr it fixed itself 6 days ago, but now it happens again...
