### ISSUE TITLE
I can't send messages to supergroups

### ISSUE THREAD

**Issue by mstrey** [zhukov/webogram#1208]
I can't send nothing to a supergroup. The admins group said me they don't banned my user, but the message I receive when try to send something is that:
"One of the params is missing or invalid"
Details:
"Method: messages.sendMessage
Url: N/A
Result: {"_":"rpc_error","error_code":400,"error_message":"USER_BANNED_IN_CHANNEL"}
Stack: Error
    at Object.h [as invokeApi] (https://web.telegram.org/js/app.js:23:25735)
    at Z.l.send (https://web.telegram.org/js/app.js:29:5996)
    at n (https://web.telegram.org/js/app.js:2:17056)"

My username is @mstrey
This supergroup is: https://telegram.me/PokemonRS

What I need to do? How to back this to normal?

**Comment by Dwebble** [comment]
I can't send anything in supergroups (Telegram) too a three days ago. And my friends also have this problema. What should we do? My username is Dwebble, and these supergroups are: https://telegram.me/PokemonRS and https://telegram.me/PokemonSC

**Comment by chuuey** [comment]
I have same problem in almost all of my groups

> Method: messages.sendMessage
> Url: N/A
> Result: {"_":"rpc_error","error_code":400,"error_message":"USER_BANNED_IN_CHANNEL"}
> Stack: h@https://web.telegram.org/js/app.js:23:25735
> Z/l.send@https://web.telegram.org/js/app.js:29:5994
> n@https://web.telegram.org/js/app.js:2:17056

In addition, when i tried to contact group admins i had this

> Method: messages.sendMessage
> Url: N/A
> Result: {"_":"rpc_error","error_code":400,"error_message":"PEER_FLOOD"}
> Stack: h@https://web.telegram.org/js/app.js:23:25735
> Z/l.send@https://web.telegram.org/js/app.js:29:5994
> n@https://web.telegram.org/js/app.js:2:17056

This additional information only shown in web client. Android or desktop clients dont show anything but still can not send messages.

**Comment by stek29** [comment]
Try contacting [@SpamBot](telegram.me/spambot)
Looks like you're blocked.

**Comment by mstrey** [comment]
@stek29 tks for this tip.

I have no ideia why I was reported and who do this. The @SpamBot said me the limitations will be lifted from my account on 19 Aug 20:26 UTC.

I hope who got this prank to me dont do it again.

**Comment by stek29** [comment]
Well, sometimes _sh_it happens :)

**Comment by scqsu** [comment]
this problem was solved？

**Comment by IshakD** [comment]
Method: messages.sendMessage
Result: {"_":"rpc_error","error_code":400,"error_message":"USER_BANNED_IN_CHANNEL"}
