### ISSUE TITLE
Edit Messages

### ISSUE THREAD

**Issue by mrdrogdrog** [zhukov/webogram#1211]
Hi,

Telegram allows editing you messages.
Telegram-Desktop too.
What about Telegram-Web?

**Comment by stek29** [comment]
Please [search for existing issues](https://help.github.com/articles/using-search-to-filter-issues-and-pull-requests/) before creating new ones.
#1155

Wouldn't you be so kind to close this issue? :)

**Comment by auchri** [comment]
@stek29 nice c/p :stuck_out_tongue_winking_eye:

**Comment by stek29** [comment]
@auchri should I give credits next time? :)

**Comment by auchri** [comment]
@stek29 No, it's fine :joy:
