### ISSUE TITLE
Provide permission for labelling GitHub issues for contributors

### ISSUE THREAD

**Issue by Ryuno-Ki** [zhukov/webogram#1212]
In my opinion it's worth thinking about allowing contributors like @stek29 to assign Labels to GitHub issues.

This way the developers can easily scan through open ones and spot questions/bugs/etc.

**Comment by stek29** [comment]
Does github allow it?

**Comment by Ryuno-Ki** [comment]
According to [StackOverflow](https://stackoverflow.com/a/13829505) it's only allowed for contributors.

You can chime in the associated Feature Request at isaacs/github#148.

**Comment by zhukov** [comment]
I can add collaborators to the project, but they will be also able to make pushes to the repo. Not sure about this part for now.

**Comment by stek29** [comment]
@zhukov I think it's not a good idea.

**Comment by zhukov** [comment]
Unfortunately this is not supported by GitHub at the moment.
