### ISSUE TITLE
A group chat vanished from my account, yet people in group still see me inside 

### ISSUE THREAD

**Issue by Simon311** [zhukov/webogram#1215]
So, I've had a group chat I recently entered via an invite link completely vanish from my account. Any attempts to join it back with the invite link from the same account failed, either saying the link has expired or that the chat no longer exists (different clients say differently). However, I've been able to join that same chat with the same invite link from a different account AND from there it looks like my first account is still in there. Also, no record of me being kicked or anything.
I am really confused as to what happened here. 

Here's what web.telegram.org said:

`Method: messages.checkChatInvite
Url: N/A
Result: {"_":"rpc_error","error_code":400,"error_message":"INVITE_HASH_EXPIRED"}
Stack: Error
    at Object.h [as invokeApi] (https://web.telegram.org/js/app.js:23:25735)
    at v (https://web.telegram.org/js/app.js:25:31282)
    at g (https://web.telegram.org/js/app.js:25:28732)
    at m (https://web.telegram.org/js/app.js:25:28121)
    at Object.f [as start] (https://web.telegram.org/js/app.js:25:31073)
    at new <anonymous> (https://web.telegram.org/js/app.js:26:13653)
    at Object.r [as instantiate] (https://web.telegram.org/js/app.js:11:21370)
    at https://web.telegram.org/js/app.js:12:15279
    at Object.link (https://web.telegram.org/js/app.js:16:12334)
    at https://web.telegram.org/js/app.js:11:6148`

But like I said, INVITE_HASH_EXPIRED can't be the case, since everyone else can still join that chat.

**Comment by stek29** [comment]
Does the link work in other apps? 
If not you should try asking support (Settings -> Ask a question in almost every app except Webogram)

**Comment by Simon311** [comment]
@stek29 No, it does not. I am not sure whetever support will respond or do anything about this, since this looks like a bug.

**Comment by ryan-mulrooney** [comment]
I'm experiencing exactly the same. Incredibly annoying.

**Comment by Simon311** [comment]
@ryan-mulrooney Apparently it means that you've been banned.

**Comment by AndrewOwere** [comment]
I cant join a Telegram group with the error below:
Method: messages.checkChatInvite
Result: {"_":"rpc_error","error_code":400,"error_message":"INVITE_HASH_EXPIRED"}

**Comment by iammultiman** [comment]
Ask the admin to check **Removed Users** under **Permissions**. If your username is there, it should be cleared since such users cannot join via an invite link. Or ask the admin to add your username to the **Add Exception** list under **Permissions**.
