### ISSUE TITLE
[suggestions] Pinned Message

### ISSUE THREAD

**Issue by Velliz** [zhukov/webogram#1219]
I think it's a good idea to have an option to pin a message. Like for pinning important message that i would take a look again later after a ton of new messages incomming. Thanks :)

**Comment by stek29** [comment]
I think it's better to call it "Favouriting" or "Staring" becasue pin is used for other thing.
Also, it's an api issue. You can use "Ask a question" button in setting of any official app except webogram or ask on Twitter.

**Comment by zhukov** [comment]
This is a request not for a Web App, but for the Telegram API. Please contact Telegram Support (telegram.org/support or "Ask a Question" in Settings).
