### ISSUE TITLE
Bug reporting

### ISSUE THREAD

**Issue by NeetuGahlot** [zhukov/webogram#1220]
Bug 1: Not showing emoticon 
in my redmi note 3 phone, telegram app is not showing emoticons. instead of them it is showing blank spaces and this problem is being observed after 3 days of installing this app. emoticons are visible in other apps like whatsapp. refer to the screenshot for more info.
![14113867_658288561013761_445216846_o](https://cloud.githubusercontent.com/assets/17921906/18017294/688918e0-6bee-11e6-8a30-b82f9e5ca454.jpg)

Bug 2: self destruct timer is not working
i have set the self destruct timer of my private chat to one day. but it does not deleting the chats of even last three days.

**Comment by zhukov** [comment]
This is not an Android app' repo. Contact Telegram Support in-app instead.
