### ISSUE TITLE
Message draft in channels

### ISSUE THREAD

**Issue by kiddick** [zhukov/webogram#1226]
How to reproduce:
1. Copy some text into clipboard
2. Open channel
3. Press ctrl+v (possibly several times)
4. Wait about 5 sec
5. Refresh

![screen](https://cloud.githubusercontent.com/assets/9250239/18274663/951f089c-7454-11e6-8f5d-6029a4fd5118.png)

**Comment by stek29** [comment]
If you want to clear that draft you can open it in tdesktop or open in iOS App.
And IMO it's server-side issue (feature?) which allows drafts in channels you can't post to.

**Comment by zhukov** [comment]
Should be fixed server-side as well though.
