### ISSUE TITLE
Rejoinig group chat fails with unknown error

### ISSUE THREAD

**Issue by radekvokal** [zhukov/webogram#1227]
Web Telegram 0.5.5

I've left a group chat and I'm trying to rejoin it back. THe group got renamed in the mean time. After finding that group I'm trying to send a message which fails with

`
Method: messages.sendMessage
Url: N/A
Result: {"_":"rpc_error","error_code":400,"error_message":"PEER_ID_INVALID"}
Stack: h@https://web.telegram.org/js/app.js:23:25735
Z/l.send@https://web.telegram.org/js/app.js:29:5994
n@https://web.telegram.org/js/app.js:2:17056
`

**Comment by stek29** [comment]
Wasn't group updated to supergroup? Haven't admin revoke old invite link?
Can't you just contact someone in that  group and ask for invite link?

**Comment by zhukov** [comment]
Yeah, I guess you can't join it, because it was converted to supergroup.
