### ISSUE TITLE
Unable to join public groups

### ISSUE THREAD

**Issue by pcdinh** [zhukov/webogram#1229]
Hi,

I am unable to join public groups: Android, Mac, Windows clients report the same error: User Not Found. When I use web client, I get the following error

>  Not found
> There is no Telegram account with the username you provided. 

`
Method: contacts.resolveUsername
Url: N/A
Result: {"_":"rpc_error","error_code":400,"error_message":"USERNAME_NOT_OCCUPIED"}
Stack: h@https://web.telegram.org/js/app.js:23:25735
d@https://web.telegram.org/js/app.js:24:15237
w@https://web.telegram.org/js/app.js:26:10548
Cn/this.$get</g.prototype.$broadcast@https://web.telegram.org/js/app.js:13:14047
m@https://web.telegram.org/js/app.js:16:9820
Cn/this.$get</g.prototype.$broadcast@https://web.telegram.org/js/app.js:13:14047
l@https://web.telegram.org/js/app.js:12:27570
Jt/this.$get</</<@https://web.telegram.org/js/app.js:12:29172
Cn/this.$get</g.prototype.$eval@https://web.telegram.org/js/app.js:13:12662
Cn/this.$get</g.prototype.$digest@https://web.telegram.org/js/app.js:13:11144
Cn/this.$get</g.prototype.$apply@https://web.telegram.org/js/app.js:13:12947
Jt/this.$get</<@https://web.telegram.org/js/app.js:12:28388
ae.event.dispatch@https://web.telegram.org/js/app.js:4:2735
ae.event.add/f.handle@https://web.telegram.org/js/app.js:3:31539
`
All of groups I tried is fine to others

@BitcoinCore (BTC)
@BitSharesDEX (BTS)
@Counterparty (XCP)
@DashDigitalCash (DASH)
@EtcRussia (ETC Russia)
@EthClassic (ETC Main Group)
@FactomFCT (FCT)
@Litecoin (LTC)
@MaidSafeCoin (MAID)
@MoneroCurrency (XMR)

https://telegram.me/litecoin

However, I asked some of my friends to access those groups (for the first time), they reported the same error.

Ex: I and my friends in Vietnam can not join any group here https://combot.org/telegram/top/chats Same error 

Is it because Vietnam IP addresses are blocked or something?

**Comment by sokomo** [comment]
I have the same issue when trying to access those public groups. I tried to access using Android client, and my IP and phone number are from Vietnam.

**Comment by zhukov** [comment]
I think it's some server-side restriction. You should contact Telegram support, the app itself has nothing to do with it.
