### ISSUE TITLE
Call a function when number of unread is changed

### ISSUE THREAD

**Issue by belaviyo** [zhukov/webogram#1230]
I am working on a greaseMonkey script and in this script I would like to get notified when number of unread messages change.

Is this possible to register a function to get notified for the change?

**Comment by zhukov** [comment]
We have 
```javascript
$rootScope.$broadcast('dialog_unread', {peerID: peerID, count: newUnreadCount})
```

So I guess you could attach a listener for this event.

**Comment by belaviyo** [comment]
I am not sure how to access the `$rootScope` from my GreaseMonkey contexy (`$rootScope` is undefined in the browser console)

**Comment by Ryuno-Ki** [comment]
@belaviyo When on a node `#foo` inside that controller, call this to access the scope:
```js
var scopeOfElement = angular.element("#foo").scope();
```
Due to prototypal inheritance you should be able to access the `$rootScope` this way. Angular events (such as `dialog_unread`) can be registered with
```js
angular.element("#foo").$on('dialog_unread', onDialogUnread)
```
At least this works on my service at work, where we also have jQuery present …

**Comment by belaviyo** [comment]
@Ryuno-Ki to use `angular.element`, first I need to switch to the debugging mode`angular.reloadWithDebugInfo()` which doesn't make sense for a GreaseMonkey script.

**Comment by Ryuno-Ki** [comment]
@belaviyo Could you explain why this is necessary?

**Comment by belaviyo** [comment]
@Ryuno-Ki try to install an `on` listener for web.telegram.org and you will see the the scopes are undefined unless you are switching to the debugging mode.
