### ISSUE TITLE
Push notification not working on Chrome for Android

### ISSUE THREAD

**Issue by k4ml** [zhukov/webogram#1233]
I've allowed the notification when first loading web.telegram.org, and has verified in the settings. I'm using Chrome 52.0.2743.98, Android 5.1.0 on Lenovo A2010-a Build/LMY47D.

I've tried https://storage-cdn.realtime.co/chrome-push/index.html to test their push notification and it seem to work. I closed my Chrome and run their given curl command and managed to get the notification on my mobile.

**Comment by TitanNano** [comment]
@k4ml telegram web does not support WebPush at the moment, only desktop notifications.

**Comment by zhukov** [comment]
Duplicate #981

**Comment by AmirDaliri** [comment]
????
