### ISSUE TITLE
install on windows

### ISSUE THREAD

**Issue by realreef** [zhukov/webogram#1234]
hi all,

i try this code and install on linux based, this is successfully.

but when i install on windows 8.1 i got any error:

C:\Users\arief\Desktop\webogram-master\node_modules\gulp-serviceworker\node_modu
les\oghliner\node_modules\travis-encrypt\node_modules\ursa>if not defined npm_co
nfig_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\
....\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )

Building the projects in this solution one at a time. To enable parallel build,
please add the "/m" switch.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targ
ets(356,5): error MSB6006: "CL.exe" exited with code -1073741515. [C:\Users\ari
ef\Desktop\webogram-master\node_modules\gulp-serviceworker\node_modules\oghline
r\node_modules\travis-encrypt\node_modules\ursa\build\ursaNative.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` fail
ed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\
npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:200:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodej
s\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\arief\Desktop\webogram-master\node_modules\gulp-servicewor
ker\node_modules\oghliner\node_modules\travis-encrypt\node_modules\ursa
gyp ERR! node -v v4.5.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok

> gifsicle@3.0.4 postinstall C:\Users\arief\Desktop\webogram-master\node_modules
> \gulp-imagemin\node_modules\imagemin\node_modules\imagemin-gifsicle\node_modules
> \gifsicle
> node lib/install.js

  √ gifsicle pre-build test passed successfully

> jpegtran-bin@3.1.0 postinstall C:\Users\arief\Desktop\webogram-master\node_mod
> ules\gulp-imagemin\node_modules\imagemin\node_modules\imagemin-jpegtran\node_mod
> ules\jpegtran-bin
> node lib/install.js

  √ jpegtran pre-build test passed successfully

> optipng-bin@3.1.2 postinstall C:\Users\arief\Desktop\webogram-master\node_modu
> les\gulp-imagemin\node_modules\imagemin\node_modules\imagemin-optipng\node_modul
> es\optipng-bin
> node lib/install.js

  √ optipng pre-build test passed successfully
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\
node_modules\npm\bin\npm-cli.js" "install"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9
npm ERR! code ELIFECYCLE

npm ERR! ursa@0.9.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ursa@0.9.4 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the ursa package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ursa
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls ursa
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\arief\Desktop\webogram-master\npm-debug.log

**Comment by JohnMKC** [comment]
Same here.

**Comment by zhukov** [comment]
I don't have Windows available to debug the issue. And for now only OSX and Linux are supported. But I guess the problem should be common, so you can try to google it and find a workaround.

**Comment by azzimuth** [comment]
This is a known issue with `node-gyp`: https://github.com/nodejs/node-v0.x-archive/issues/4047

@zhukov can you upload the precomplied CSS files? Those are the only thing missing required to run Webogram on Windows...

**Comment by zhukov** [comment]
Every release version contains compiled CSS files: https://github.com/zhukov/webogram/releases

**Comment by azzimuth** [comment]
I see. I meant `master` branch but that will work as well.

**Comment by zhukov** [comment]
I finally have windows PC, fix is coming.
