### ISSUE TITLE
When writing right-to-left text, the first letters are hidden by the emoji smiley icon

### ISSUE THREAD

**Issue by mankurt** [zhukov/webogram#1236]

**Comment by stek29** [comment]
@mankurt Can you attach a screenshot please?

**Comment by mankurt** [comment]
![screenshot from 2016-10-29 23-09-23](https://cloud.githubusercontent.com/assets/15964583/19832465/d6fee96a-9e2c-11e6-9dab-d5b5f2849ba5.png)

**Comment by stek29** [comment]
Why won't you close this issue?
