### ISSUE TITLE
my telegram web

### ISSUE THREAD

**Issue by radioburna** [zhukov/webogram#1237]
https://github.com/radioburna/webogram

**Comment by radioburna** [comment]
Hello
I have created a page but the name does not change the icons on my page
You check where is the problem

https://github.com/radioburna/webogram

**Comment by Ryuno-Ki** [comment]
I'm not sure, I understand you correctly, @radioburna.

Do you mean the icons on https://github.com/radioburna/webogram ?

They're defined in the gh-pages branch. Looks Arab to me.

Can you make a screenshot and highlight the icons in question?

**Comment by zhukov** [comment]
Sorry, can't quite understand the problem

**Comment by stek29** [comment]
@zhukov I think he wants you to help him to re-brand his fork (change icons).
