### ISSUE TITLE
can't add phone number to contact

### ISSUE THREAD

**Issue by mob2005** [zhukov/webogram#1239]
i have 1800 contact in my telegram account , when i want add more number it's dhow below massage :
 Not found
Sorry, there is no Telegram account with the phone number you provided. 
Method: N/A
Url: N/A
Result: {"code":404,"type":"USER_NOT_USING_TELEGRAM","detailsShown":true}
Stack: 
but this number is registered in telegram and can add to contact with other account .
how can add more number  ?

**Comment by zhukov** [comment]
I'm afraid, this is a server-side limit. Contact Telegram support if you have any questions about it.
