### ISSUE TITLE
Next release

### ISSUE THREAD

**Issue by mikasoukhov** [zhukov/webogram#1241]
The latest release dated by Feb 10, 16. When will be the next version? Or the Release section now is out of date?

**Comment by azzimuth** [comment]
Zhukov seems to have abandoned this project...

**Comment by mikasoukhov** [comment]
Not sure that the commit related with my question. Do you plan to publish next releases?

**Comment by stek29** [comment]
@mikasoukhov Just keep opening new issues each time app is updated, huh.
