### ISSUE TITLE
Update emojis

### ISSUE THREAD

**Issue by azzimuth** [zhukov/webogram#1244]
Emojis in Telegram have got a new look. Update emojis even in Webogram to have the same look.

**Comment by stek29** [comment]
Please no, I hate new Emoji look.

**Comment by azzimuth** [comment]
Doesn't matter. There are others who like it. I personally would like to see that my messages look the same both in Webogram and on Telegram apps.

**Comment by stek29** [comment]
@azzimuth Either give me a choice or keep the old ones (like TDesktop)

**Comment by azzimuth** [comment]
Why not, option sounds reasonable

**Comment by Ryuno-Ki** [comment]
Too many options can lead to [Analysis paralysis](https://en.wikipedia.org/wiki/Analysis_paralysis)!

**Comment by azzimuth** [comment]
We do not have many options on Webogram. I don't see any risk for analysis paralysis.
![image](https://cloud.githubusercontent.com/assets/1640148/19261260/2fa8b1aa-8f90-11e6-91a7-221cc45bd438.png)

**Comment by Ryuno-Ki** [comment]
Right now, yes. I just want to not add options blindly.

**Comment by azzimuth** [comment]
Just an example. A message looks so in Webogram:
![image](https://cloud.githubusercontent.com/assets/1640148/19342220/2e1387b4-9131-11e6-9700-71ebc60c052d.png)
And the same message in Telegram Android app:
![img_20161013_102953](https://cloud.githubusercontent.com/assets/1640148/19342342/bd54bf88-9131-11e6-85db-6ec82b7f14c7.png)

**Comment by stek29** [comment]
@azzimuth There's also one more issue with it: current implementation doesn't support skin tones, so it's not just "Add new emojis", it's "Rewrote emoji related code and update emojis"

**Comment by andresro14** [comment]
This is important, is not consistent with Telegram in other platforms

**Comment by azzimuth** [comment]
@zhukov Any plans to implement this? I even noticed that many emojis, which are available in the app, cannot be sent from Webogram.

**Comment by Ryuno-Ki** [comment]
After reading up that lengthy article about Emoji and Unicode on SmashingMagazine, I wonder wether this here is an OS issue.

@zhukov Look into the EmojiOne project if you want to implement this.

**Comment by ehsannozari** [comment]
Hi. Please guide me how to bring back old look emojis without going back to old updates of telegram. Is there any way i can bring them back? These new look emojis dont express feelings right. Pleaaaaaaaseeee

**Comment by stek29** [comment]
@ehsannozari Are you sure you're talking about Webogram?

**Comment by stek29** [comment]
Btw, why don't we just use EmojiOne's libraries?

**Comment by Ryuno-Ki** [comment]
@stek29 I can imagine it has to do something with plenty of open tickets and @zhukov working [more or less alone on Webogram](https://github.com/zhukov/webogram/graphs/contributors) …

PRs welcome ;-)

**Comment by stek29** [comment]
@Ryuno-Ki XD
I'd look into it next year unless someone does it before me :)

**Comment by Akronix** [comment]
Just an update: Android app has updated and added new emoji icons: https://telegram.org/blog/unsend-and-usage

**Comment by Akronix** [comment]
Btw, I tried to fix this in the past. But I found it quite hard to know how the emojis are loaded in webogram without any help or docs :confused: Maybe some directions from @zhukov would help.

**Comment by zhukov** [comment]
@Akronix do you have specific questions? All emoji related things are in config.js:Config.Emoji (list of emojis with data), message_composer.js:EmojiTooltip (display emojis in tooltip) and ng_utils.js:wrapRichText (replacing emoji characters with icons).

**Comment by tim-peters** [comment]
I think one important step further to new emojis is to habe css sprites with all the new emojis. The emojis can be downloaded e.g. here http://emojipedia.org/apple/

Unfortunately there are almost 1.4k emojis with random filenames. So it's a lot of work to create all the css sprites. Additionally the sprites should be created with some consistent logic (like the same emoji in different colors should be always in the same col and row of the sprites to minimize programming effort). 

Does anyone have a better source or better idea how to generate the sprites?

**Comment by Akronix** [comment]
I can use DownThemAll! or write a script to download all the emojis, how should I create the sprites afterwards? is there already a gulp command for this?

**Comment by stek29** [comment]
@tim-peters use EmojiOne?
It's not just about the sprites lol, the modifiers are just not supported at all.

**Comment by Akronix** [comment]
Well, I'd start just updating the emojis and see the modifiers thing later...

@stek29 you mean this: https://github.com/Ranks/emojione/tree/master/lib ?

**Comment by stek29** [comment]
@Akronix yup
IMHO it's better to rewrite it to use emojione lib, than update it now and see it working till next unicode release.

**Comment by zhukov** [comment]
Duplicate #760

**Comment by azzimuth** [comment]
Wow great! You could wait another half year for even more discussion and close then...

**Comment by zhukov** [comment]
No offence, just trying to clear open issues.
