### ISSUE TITLE
Image double paste in web.telegram

### ISSUE THREAD

**Issue by leotsarev** [zhukov/webogram#1245]
Steps to reproduce:
Windows 10, Firefox
1. Open Windows snipping tool
2. Create some snippet
3. Press copy
4. Switch to open web.telegram.org
5. Press paste

Actual result:
Offering to paste two files with same name .png and .jpg

Expected result:
offering to paste only one file, automatically preferring .png

**Comment by stek29** [comment]
Do you mean actual File by .jpg file or Photo?

**Comment by leotsarev** [comment]
I mean:
When web.telegram got same image in two formats from clipboard, it offers to past both

**Comment by leotsarev** [comment]
Now (Version 0.5.5) problem doesn't reproduce.
