### ISSUE TITLE
No Push Notification on Android 

### ISSUE THREAD

**Issue by sdelahoza** [zhukov/webogram#1247]
I don't recive push notification on my android device until I open de app, please fix this bug, I really like to use telegram as my principal chat

**Comment by Ryuno-Ki** [comment]
Duplicates #1233

**Comment by sdelahoza** [comment]
It´s not duplicate, my problem is not on chrome, my problem is on de mobile app, when it's closed I don´t recive the notifications of the messages.

**Comment by Ryuno-Ki** [comment]
Read the comment of TitanNano in the linked issue, please.

Webogram is Telegram's web app, i.e. not native.

**Comment by sdelahoza** [comment]
OK, was my mistake, this issue should not be here, thanks
