### ISSUE TITLE
content of message not show

### ISSUE THREAD

**Issue by javansolo** [zhukov/webogram#1248]
hi,
example content of message chanel "@hatef_marefat" not show !!

**Comment by stek29** [comment]
Can you please provide screenshots? 
I can't understand what do you mean by "content not shown", because everything "is shown" for me.

**Comment by javansolo** [comment]
Revision: 0e531b27a961a904a10f19ca99e2cac72345aa98
chanel "@hatef_marefat"
on localhost
![telegram](https://cloud.githubusercontent.com/assets/11363999/19218593/ebca4b78-8e0a-11e6-8ee5-6d86038e05a6.png)

**Comment by azzimuth** [comment]
Works fine here:
![image](https://cloud.githubusercontent.com/assets/1640148/19231494/9c60d4e6-8eda-11e6-941b-3d5c71a583dc.png)
Maybe it's blocked in Iran?

**Comment by javansolo** [comment]
no not blocked!
on chrome on localhost on Revision: cd70b7e65b4772c4979e75b8a5bafe9beaddaa43 show content.
after this Revision not work and other chanel show title only!!!!
content Sometimes show and Sometimes not show!
test in chrome Version 53.0.2785.143 m (64-bit)

**Comment by azzimuth** [comment]
I have now the same issue after I have updated to the latest code:
![image](https://cloud.githubusercontent.com/assets/1640148/19237149/92dddfc4-8efb-11e6-9cbe-44a2deefd2f4.png)
