### ISSUE TITLE
Alt + Shift + # shortcut breaks native keyboard behaviour in OSX

### ISSUE THREAD

**Issue by wicol** [zhukov/webogram#1249]
I know there were discussions about what shortcuts use for this but I'm sorry to say Alt + Shift + # is used in OSX (macOS!?) for special characters. This is with swedish keyboard/input scheme but I'm pretty sure more use the same behaviour. As an example every time I try to write this smiley :}, I end up in conversation number 9. :{ would be 8.. you get the picture. The following characters are no longer available and instead make me jump around conversations: •¡”¥¢‰¶\{}≠¿. I'm sure you'll agree backslash and curly brackets are kinda useful.

Anyways, since it seems to be difficult to find a free shortcut the best approach is probably to make it configurable or at least possible to de-activate them. I know it's possible to configure it by editing a file but I'd like it to work on all devices I use (even new ones) :}

**Comment by Akronix** [comment]
yeah, it happens also with Mac OS X Spanish...

It's definitely hard to find a cross-plattform and cross-browser shortcut for this.

**Comment by Akronix** [comment]
Yeah, it happens also with Mac OS X Spanish...It's definitely hard to find a cross-plattform and cross-browser shortcut for this.

It comes to my mind these approaches:
1. To have different shortcuts for Mac OS X and for Windows / Linux as many apps do. We could use `control + shift + #` for this for example.
2. To add an screen with the different shortcuts and a check to enable/disable them
3. To let the user choose its own keybindings.

The latest requires much more effort than the previous one and it's not clear if it's worth it for just a few bindings. I'm more up for 1 or 2.

**Comment by Akronix** [comment]
@zhukov how can we know if the user is on Mac OS X from webogram code?

**Comment by Ryuno-Ki** [comment]
Maybe via UserAgent sniffing …
