### ISSUE TITLE
Share URL and text , include utf8 characters, have problem with desktop and portable telegram

### ISSUE THREAD

**Issue by clickmeplz** [zhukov/webogram#1250]
I am using a telegram share button at my website for sharing URL and a title text for it.
URL and title text include UTF8 characters like Farsi,Arabic,...
If i use android version of telegram, it seems there is no problem.
But if i use windows desktop or portable version, it convertes UTF8 characters to a string of **?** characters.
This is an example.
Share link: 
https://telegram.me/share/url?url=www.agahichi.com/listings/مالی-اداری/خدمات-اداری/مشاوره-حقوقی/مشاوره-حقوقی-و-وکالت-تخصصی-خانواده-682.html&text=مشاوره حقوقی و وکالت تخصصی خانواده

Result in telegram:
www.agahichi.com/listings/????-?????/?????-?????/??????-?????/??????-?????-?-?????-?????-???????-682.html
?????? ????? ? ????? ????? ???????

Many thanks.

**Comment by stek29** [comment]
Why aren't they escaped?

**Comment by clickmeplz** [comment]
@stek29 ... I just copy/paste the link result here. Actual code is something like this:
`<a href="https://telegram.me/share/url?url={$smarty.server.HTTP_HOST}{$smarty.server.REQUEST_URI}&text={$title_item}"></a>`

**Comment by Ryuno-Ki** [comment]
I wonder, whether that is vulnerable to XSS …

**Comment by clickmeplz** [comment]
I don't know what does @zhukov did. But i checked it a few minutes ago, and surprizingly everything is OK with telegram desktop and portable versions and Yes! the problem was solved.
**Thank you very much @zhukov .**

**Comment by Ryuno-Ki** [comment]
@clickmeplz I'd like to ask you to close this issue then.

**Comment by yasna40** [comment]
THANK
http://takhta.ir/

**Comment by mahbob68** [comment]
Thanks
[تبلیغ رایگان](https://tablighraygan.ir)
