### ISSUE TITLE
Click to view (as opposed to auto display) images

### ISSUE THREAD

**Issue by marcopaganini** [zhukov/webogram#1251]
Unfortunately, some people in large chat groups send messages contain images which are not very... let's say, office friendly. :) It would be nice to have an option to view images on demand only (maybe show a blurred version and on a click, un-blurr the image.)

**Comment by zhukov** [comment]
Duplicate #420.

**Comment by arash2262** [comment]
Hey now, what should we do

**Comment by arash2262** [comment]
Hey now, what should we do error #420
