### ISSUE TITLE
Hide conversation block (feature request)

### ISSUE THREAD

**Issue by fedorvinogradov** [zhukov/webogram#1254]
Good day.
It would be great in terms of privacy to have the ability to hide the conversation screen (i.e. like no convo is chosen) when you finish chatting with somebody. Now there is a blank space only only when you first load the webogram, but if you choose any convo from the convo list you then cannot unchoose it. So the feature is like a stand by mode - with no convos chosen.

**Comment by fedorvinogradov** [comment]
I suggest it this way:
the conversation is shown when you click on a contact or a group and is hidden when you click 'em the second time.

**Comment by zhukov** [comment]
you can hide conversation by pressing esc twice.
