### ISSUE TITLE
Limit on Group Member List

### ISSUE THREAD

**Issue by Alexa69** [zhukov/webogram#1260]
Hi

On Desktop version I am able to see all the members on my group or the groups that I am member of but on the Web version It just show 50 members ( including myself 51 ) is there any solution to see all the members of a group when I click on Group Info ?! instead of 50 members only I would like to see all the members on a group on Web Version of Telegram

Best Regards

**Comment by Alexa69** [comment]
There should be somewhere in code to alter that let you to see more than 50 members on a Super Group .. I wish it was like Desktop version displaying all the users .. I tried but I didn't find out where to modify to remove the display limit on Groups member

**Comment by zhukov** [comment]
Duplicate #1160
