### ISSUE TITLE
Location items show a g.co/staticmaperror/billing error image

### ISSUE THREAD

**Issue by Akronix** [zhukov/webogram#1262]
This is what appears now when you see a location item in webogram:
![screenshot from 2016-11-09 18-45-23](https://cloud.githubusercontent.com/assets/2631430/20148457/03e6a08e-a6ad-11e6-8b65-d486966b3679.png)

Very easy to reproduce: Just send a location with any of the Telegram clients that support it and open that conversation in webogram.

**Comment by zhukov** [comment]
thanks. trying to fix this thing in google console.
