### ISSUE TITLE
Russian localization

### ISSUE THREAD

**Issue by mennya** [zhukov/webogram#1263]
In cd9441e62b8fbe321256eefccabb89648db8b69e commit in app/js/lib/config.js file was added rusian locale to supported but it's commented
```
+  supported: [
 +    "en-us"
 +    ,"es-es"
 +    ,"de-de"
 +    ,"it-it"
 +    // ,"ru-ru"`
```   

Russian localization file is exists app/js/locales/ru-ru.json, so why is it still uncommented? Why we can't pick ru-ru?

**Comment by stek29** [comment]
Because other official clients don't have it?

**Comment by mennya** [comment]
Then why app/js/locales/ru-ru.json file exists and maintained?)

**Comment by stek29** [comment]
Well, Russian translation exists and maintained for Android and iOS (and maybe even for WP, not sure).
TDesktop can't be translated grammatically correctly without changing the code, and it has only unofficial translations by channels like tglive.

**Comment by zhukov** [comment]
Sorry, translations are not maintained by this repo. See https://telegram.org/faq#q-can-i-translate-telegram for more info.
