### ISSUE TITLE
web.tlgrm.ru?

### ISSUE THREAD

**Issue by fedorvinogradov** [zhukov/webogram#1268]
Насколько я понял, это не ваш проект?
Если нет, может вам известно, безопасно ли его использовать?
Использовать хочется, т.к. там есть русский язык.

**Comment by zhukov** [comment]
этот проект не имеет ко мне никакого отношения.

**Comment by stek29** [comment]
@fedorvinogradov tlgrm.ru не имеет никакого отношения к Telegram. 
Если вам нужен русский язык, используйте перевод с Transifex и поднимите свой сервер.
Ну или доверьтесь tlgrm.ru (я бы не советовал)
