### ISSUE TITLE
Bookmark message 

### ISSUE THREAD

**Issue by vanimesh76** [zhukov/webogram#1274]
Bookmark message in group chats

**Comment by zhukov** [comment]
This is a request not for a Web App, but for the Telegram API. Please contact Telegram Support (telegram.org/support or "Ask a Question" in Settings).

**Comment by stek29** [comment]
@vanimesh76 are you talking about pinning?

**Comment by vanimesh76** [comment]
Yes something like that, how can we add such a feature?

**Comment by stek29** [comment]
Then it's duplicate of #1088.
But I have absolutely no idea why is that issue closed.

**Comment by vanimesh76** [comment]
Can't the issue be reopened?
The messages in group chats contain many links, can't visit them all at
once, bookmark will save a lot of scrolling up time.

**Comment by stek29** [comment]
@vanimesh76 ask @zhukov
