### ISSUE TITLE
Webtelegram markdown: dialog flavored text and links

### ISSUE THREAD

**Issue by Akronix** [zhukov/webogram#1283]
Hello. First, I'm happy for the recent addition of built-in markdown in webogram. Good work! :tada:

Second, I'm missing the formatted text in the dialog window on the left hand side. (I mean the `im_dialog_message`). In other words, if I send a flavored text message, it looks well in the message box but it looks unformatted text on the left dialog list. I've been looking and Android and telegram desktop apps behave also like this, so I don't know if this' done on purpose. 

Third, is it possible to support text links as @bold bot can do? It's just the last part of [Telegram markdown](https://core.telegram.org/bots/api#markdown-style).

**Comment by stek29** [comment]
@Akronix About the text links -- server doesn't accept them from users, only from bots.
They were working a month ago, but Telegram decided to disable them.

**Comment by zhukov** [comment]
This behaviour is migrated from mobile apps. The text is so small that there is almost no point in formatting it. But we might change it if it is changed in mobile apps in the future.

**Comment by Akronix** [comment]
Ok... WhatsApp does format the text in mobile apps though.
