### ISSUE TITLE
Add ability to disable text format triggers

### ISSUE THREAD

**Issue by Idran** [zhukov/webogram#1285]
Feature request: some option to disable character-based text format triggers like `*bold*` or `_italic_`, either by a client settings toggle or possibly by the use of an escape character like backslash. Minor issue, but I use asterisks in text chat for purposes other than formatting as it stands, and it's always frustrating in any chat client when this gets implemented with no way to work around it.

**Comment by stek29** [comment]
@Idran escaping may be a good idea indeed.

**Comment by AndrewNeo** [comment]
Please consider making this a toggle. Escaping is a somewhat acceptable solution but I use these characters for emphasis all the time and do not want to use text formatting.

**Comment by Mowsh** [comment]
This shouldn't be the default, I imagine 99% of the time people surround their text in *asterisks* they're intending for them to show up, not make their text bold.  It's used very commonly as a alternative to /me (like IRC)

I suggest the feature should be removed for now until a toggle is available, I don't believe this is good UX for a chat app.

**Comment by gamax92** [comment]
All of the text formatting stuff should probably be changed to double characters as is the way it works on Android. Where you'd need two stars to make text bold.

As it is now I have to use an invisible character before the formatting character to prevent the text formatting happening, or just not use the web client any more.

**Comment by mohammad0016** [comment]
bot zed

**Comment by mohammad0016** [comment]
bot m

**Comment by mohammad0016** [comment]
@bot zed
