### ISSUE TITLE
Introduce karma

### ISSUE THREAD

**Issue by Ryuno-Ki** [zhukov/webogram#1291]
Because #840 I cloned the repo and digged into the code today.

To my surprise I discovered, that you have no testsuite yet, @zhukov O_O

I'd like to setup karma and start writing some tests.

My biggest hindrance could be to get around the register/key generation screen when running the code locally …

Any objections?

**Comment by kskarthik** [comment]
Is it possible to add option to adjust text size ? Default webogram font size adjusts to browser font size. I need big text. I couldn't read small one's.

**Comment by Ryuno-Ki** [comment]
@kskarthik Sounds related to #889. I can't see what it has to do with Karma …

**Comment by kskarthik** [comment]
Just to know the possibilities :)

**Comment by Ryuno-Ki** [comment]
Technically it is possible (I've seen several implementations on German websites). It isn't done, yet.

This issue is about getting Webogram more stable. Karma is a test runner for Jasmine (or other test frameworks). The idea is to prevent regressions, i.e. break things that once work.

As a side effect, @zhukov can onboard new contributors easier since they can look at tests to deduce how parts of the application work with each other.

**Comment by zhukov** [comment]
@Ryuno-Ki hi. thanks for the issue and PR.
I have some concerns about tests in this project. Most of the work is done for UI (which I think should not be covered by tests), other parts are really API-related (just performing requests and storing results, not obvious for me how to test it). There are only couple services that IMO need testing: things like RichTextProcessor (text in, text out), Storage may be.


>My biggest hindrance could be to get around the register/key generation screen when running the code locally …


You can generate auth key once and then store it into `localStorage.dc*_auth_key` for tests. It's not very secure to export these values to repo, though.

**Comment by zhukov** [comment]
@kskarthik please stop spamming issues with unrelated questions. Respect others. Do use search field first.

**Comment by Ryuno-Ki** [comment]
Why should UI not covered by (e2e) tests (done by protractor in a follow-up PR)?

Imagine Telegram Server is changing the API. Wouldn't it be handy to have the tests tell you, where you need to fix the code?

I'll look after getting `nt_utils.js` covered by tests soon. Thanks for prioritising!

> You can generate auth key once and then store it into localStorage.dc*_auth_key for tests. It's not very secure to export these values to repo, though.

I'd advice to store those secrets in a `secrets.json` (or similiar) and read them in. The structure should be documented, but the file not versioned by git. I saw your secrets already versioned.

**Comment by ndpatel221** [comment]
> @kskarthik Sounds related to #889. I can't see what it has to do with Karma …

good but you need related something to #1160 or #891
