### ISSUE TITLE
Error  One of the params is missing or invalid.

### ISSUE THREAD

**Issue by fqdb** [zhukov/webogram#1294]
After login I am getting a popup with: 
**Error**

**One of the params is missing or invalid.**

`Method: account.registerDevice
Url: N/A
Result: {"_":"rpc_error","error_code":400,"error_message":"WEBPUSH_KEY_INVALID"}
Stack: Error
    at Object.h [as invokeApi] (https://zhukov.github.io/webogram/js/app.js:23:30730)
    at D (https://zhukov.github.io/webogram/js/app.js:25:28028)
    at https://zhukov.github.io/webogram/js/app.js:25:29283
    at g.$emit (https://zhukov.github.io/webogram/js/app.js:13:15068)
    at p (https://zhukov.github.io/webogram/js/app.js:22:29233)
    at https://zhukov.github.io/webogram/js/app.js:22:27983`

I'm using it at work, and the Chrome installation has some restrictions, so I am also seeing the following warning:
![capture](https://cloud.githubusercontent.com/assets/2826336/21259018/dbccab44-c37f-11e6-8462-37851fda42d1.PNG)

As far as I can see, the functionality is not compromised by this error

**Comment by zhukov** [comment]
> I'm using it at work, and the Chrome installation has some restrictions, so I am also seeing the following warning:

This is not a problem that causes error.
Can you please find entry like this in your javascript console?

<img width="328" alt="screen shot 2016-12-16 at 13 13 53" src="https://cloud.githubusercontent.com/assets/775173/21259239/950c7b46-c391-11e6-81c9-ee0ce4ae453e.png">


What does it look like? What is the length of 'p256dh' string? how many `=` (if any) are on the end of the string.
This key allows to send you PUSH notifications (together with endpoint URL), so it might be a good idea to leave it private.
Although you could share it here, replacing some characters in the middle with equal number of `$` symbols e.g.

```BHxsWllGYqoJYeRB84HvSx$$$$lu4e8rikEsKKxBxXutd0COKKlAjq5F31wkXoKwUVdkgBhj_rmDDWwS45WbUY=```

**Comment by fqdb** [comment]
I am never seeing the line you mention...
[log.txt](https://github.com/zhukov/webogram/files/657118/log.txt)

**Comment by zhukov** [comment]
@fqdb what is your Chrome version?

**Comment by zhukov** [comment]
I've found the problem. You probably use not up-to-date Chrome, with subscriptionId instead of encryption keys.
https://developer.mozilla.org/en-US/docs/Web/API/PushSubscription/subscriptionId

```
This feature has been removed from the Web standards. Though some browsers may still support it, it is in the process of being dropped. Do not use it in old or new projects. Pages or Web apps using it may break at any time.
```

You will not see the error anymore, but new notifications will not work until you upgrade the browser.
