### ISSUE TITLE
Unused ErrorService in AppWelcomeController

### ISSUE THREAD

**Issue by Ryuno-Ki** [zhukov/webogram#1295]
While preparing tests for #1293 I stumbled upon `ErrorService` in the controller. I couldn't find any usage.

https://github.com/zhukov/webogram/blob/44b4228ca4ece9c38893c37756f72f6b0a941bf2/app/js/controllers.js#L14

**Comment by zhukov** [comment]
Sure, we can delete any unused dependence.
