### ISSUE TITLE
Getting hundreds of notifications when starting the browser

### ISSUE THREAD

**Issue by marco-c** [zhukov/webogram#1298]
I'm getting hundreds of notifications (most of them empty, some with a message) when I start the browser (after a while that I haven't used it).

I've already read all the messages on my phone, so none of those notifications was about a new message.

**Comment by marco-c** [comment]
I've had to disable notifications unfortunately, as this often happens also while the browser is running.

**Comment by zhukov** [comment]
Thanks for the feedback. Are you using Chrome? What version? I created some workarounds because of Chrome's forcing `{userVisibleOnly: true}` in `pushManager.subscribe` method. These empty messages are probably my attempts to show notification and hide it right after that together with other notifications.

Found this document: https://docs.google.com/document/d/13VxFdLJbMwxHrvnpDm8RXnU41W2ZlcP0mdWWe9zXQT8/edit# and currently trying to fix the code accordingly. Hope you can test it once the fix is published.

**Comment by marco-c** [comment]
I'm using Firefox 53.

**Comment by marco-c** [comment]
BTW, why do you need emtpy notifications? Isn't the server sending a notification only when necessary?

**Comment by zhukov** [comment]
@marco-c No, I don't need them of course. This was a part of hack for Chrome. We need to show real notifications there even if we want to hide all the current notifications as a result of Push notification. Hope to remove it

**Comment by marco-c** [comment]
> @marco-c No, I don't need them of course. This was a part of hack for Chrome. We need to show real notifications there even if we want to hide all the current notifications as a result of Push notification. Hope to remove it

It shouldn't be needed then, if you use a tag to replace an old notification when a new one arrives, you can avoid closing, no?

**Comment by zhukov** [comment]
Of course we use tag field for each conversation. But there are some push notifications, which are sent when user reads all the history from another device, so we need to close all current notifications when it is received. We also were not showing notification when Push was received, but user manually closed another notification less than 10 min ago (this logic is removed now) or had recently clicked on "Mute for 24H" button (this settings is exported to API now).

**Comment by zhukov** [comment]
I think I might have fixed the issue here. Can you refresh the app and try again?

**Comment by marco-c** [comment]
> But there are some push notifications, which are sent when user reads all the history from another device, so we need to close all current notifications when it is received.

Ok, this is what I meant by "empty notifications".

BTW, I think this complex logic shouldn't be needed, you should be able to avoid showing notifications from time to time even if `userVisibleOnly` is true.

**Comment by zhukov** [comment]
>BTW, I think this complex logic shouldn't be needed, you should be able to avoid showing notifications from time to time even if userVisibleOnly is true.

Yeah, it allows up to 10 times in a row, but that might easily be not enough. It all started without this logic and I've seen a lot of unneeded 'the app was updated in background' notifications on my Android, so I added the logic with empty notifications.

**Comment by marco-c** [comment]
This (https://github.com/zhukov/webogram/blob/master/app/js/lib/push_worker.js#L68) should be a function call, right?

**Comment by zhukov** [comment]
true, fix is coming

**Comment by marco-c** [comment]
Thanks, I'll test and let you know.

BTW, I think you could clean up the code a bit by removing the unneeded checks (like `if ('waitUntil' in event)`), as they always evaluate to true (IIRC no browser shipped without `waitUntil`).

**Comment by marco-c** [comment]
This particular issue appears to have been fixed, but there are still a few rough edges:

- notifications are often missing the profile picture;
- some notifications are shown twice when a Telegram tab is already open (maybe you're using the Notifications API somewhere else other than push_worker.js?);
- sometimes notifications are shown on desktop for messages that I've already read on an Android device.

**Comment by zhukov** [comment]
>notifications are often missing the profile picture;
That's a feature. We don't have nice REST API for Telegram and we can't have MTProto client running in service worker.

>some notifications are shown twice when a Telegram tab is already open (maybe you're using the Notifications API somewhere else other than push_worker.js?);

Yes, we definitely use `new Notification` etc on the running app. But this code: https://github.com/zhukov/webogram/blob/master/app/js/lib/push_worker.js#L50 should prevent showing duplicate notifications. Although I've already seen that Firefox sometimes returns empty client list for Service worker, when they actually are present.

**Comment by marco-c** [comment]
> Although I've already seen that Firefox sometimes returns empty client list for Service worker, when they actually are present.

Interesting, I've never noticed this. Have you tried removing the `type` parameter?

**Comment by marco-c** [comment]
Oh, I've noticed you're using the global scope there.
With service workers, it isn't reliable to use variables from the global scope in event handlers (see https://developer.mozilla.org/it/docs/Web/API/ServiceWorkerGlobalScope or https://jakearchibald.com/2016/service-worker-meeting-notes/).

**Comment by marco-c** [comment]
(so, lastAliveTime is likely to often evaluate to false here: https://github.com/zhukov/webogram/blob/master/app/js/lib/push_worker.js#L48)

**Comment by marco-c** [comment]
I've filed new issues for the two of the three problems outlined in my previous comment: #1301 and #1302.

**Comment by marco-c** [comment]
And #1303 for the last issue.
