### ISSUE TITLE
[Feature-Request] HashTag Notification

### ISSUE THREAD

**Issue by FranklinWhale** [zhukov/webogram#1299]
A channel user may not be interested in all messages in the channel but only some with specific hashtags. Also, the user may be interested in a hashtag across all channels. Please provide an option for the user to input hashtags so that he/she will be notified when a message with a listed hashtag is received in one or more channels.

See also telegramdesktop/tdesktop#2104

**Comment by MasterGroosha** [comment]
No API for that (AFAIK)

**Comment by FranklinWhale** [comment]
I think it can be a client-side feature, if Telegram does not have an API to do so

**Comment by zhukov** [comment]
There is no point in such client-side features. These 'custom hashtags' should be known to channel admins, there should be a list of them etc.

This is a request not for a Web App, but for the Telegram API. Please contact Telegram Support (telegram.org/support or "Ask a Question" in Settings).

**Comment by FranklinWhale** [comment]
There may not be a prefined list of hashtags, and the user may input any string as hashtag filter. I think it is valuable even if the feature is implemented on client-side only.

**Comment by zhukov** [comment]
Of course it is valuable, like every other implemented client-side feature. But it is less valuable than almost every other open issue here. So until it is supported in the API I'm afraid I will not have time for that.
