### ISSUE TITLE
Use `ng-strict-di`

### ISSUE THREAD

**Issue by Ryuno-Ki** [zhukov/webogram#1304]
Since @zhukov [insists](https://github.com/zhukov/webogram/pull/1293#discussion_r93434222) on implicit dependency declaration, it is highly recommended by Angular to add `ng-strict-di` directive: https://docs.angularjs.org/api/ng/directive/ngApp#usage

**Comment by zhukov** [comment]
Hmm.. I see the docs, but I don't get it. Should we enable it only when opening minified production-ready version? Otherwise if we add this attribute it should not allow us to use implicit dependency annotations.

**Comment by Ryuno-Ki** [comment]
I would not apply it right now.

From what I've read it helps tracking down bugs, where `ngAnnotate` did not worked properly. Because the explicit dependency annotation is done by it.

**Comment by zhukov** [comment]
ngAnnotate seems to work properly and we use it only with minification, when preparing release. So I guess ng-strict-di will not help to track anything if is used production-only.
