### ISSUE TITLE
Emoji Icon's place for Rtl languges is not correct

### ISSUE THREAD

**Issue by reza1615** [zhukov/webogram#1307]
### Steps to reproduce
1. when I want to add a comment the gray Emoji Icon (icon-emoji) covers the first 3 letters of  my Persian comment
2-for example to produce this bug please copy  `الان`  to the comment bar and you will see the below screenshot

### Expected behavior
The Emoji Icon should be left or upper or outside of the comment box see the below screenshot

### Actual behavior
The emoji icon covers 3 first letter of the Rtl texts and shouldn't cover.

### Configuration
**Operating system:**
Windows 10, Chrome 55.0.2883.87 m (64-bit) and Firefox 50.0.2
**Version of Telegram Desktop:**
Telegram web Version 0.5.5
The screenshot at Chrome and firefox
![429918468_17665_5052495002241989504](https://cloud.githubusercontent.com/assets/2202483/21484795/d692c830-cbad-11e6-866c-ff525c5557ec.jpg)

**Comment by arashpt** [comment]
To prevent this bug the Emoji Icon should be at right side of the comment box (under send botton)

**Comment by stek29** [comment]
#851, #1076, #1149 and of course #1150.
