### ISSUE TITLE
Audio (!) bug with @gif bot

### ISSUE THREAD

**Issue by MasterGroosha** [zhukov/webogram#1313]
Steps to reproduce:
1. Open Webogram.
2. Enable sound on your device.
3. Type "@gif nintendo switch" in chat.

Result: A short audio is played repeadetly O_O  
Even if you erase your query and switch to another chat, the sound still plays. Only page refresh helps (as far as I see)

Source: https://www.reddit.com/r/Telegram/comments/5ll6kb/bug_soundfile_in_gif_bot/

**Comment by azzimuth** [comment]
Cannot reproduce. Running the latest Webogram code.

Does it matter where one types "@gif nintendo switch"? I tried on several PMs and chats - no effect.

Windows 10, Chrome 55.0.2883.87, NodeJS 4.4.4

**Comment by MasterGroosha** [comment]
Cannot reproduce now as well. Maybe that "broken" gif is not in query results.
Will close the issue until I find another query which plays sound.
