### ISSUE TITLE
Redownloaded media has diff. sharing options in iOS

### ISSUE THREAD

**Issue by lucmbahmoute** [zhukov/webogram#1314]
iOS 10.2 Telegram v3.15 (Latest as of now)

Steps to reproduce:
1. Settings > Chat settings > Cache settings > Clear Cache
2. Go to any chat with media > info > shared media 
3. For any blurred images, telegram will redownload it. Click share icon > Click share icon again
4. Telegram showing Add to notes, Import, Copy to, etc.. This is diff than photos received on the device. 
Click add to notes.
Result:
![image](https://cloud.githubusercontent.com/assets/24886483/21600090/d0e38780-d1b1-11e6-8872-37694c2016ef.png)

Workaround:
1. On the sharesheet, share to telegram > send to yourself
2. Go to yourself > Click share icon > Click share icon again
This will show the normal share sheet again for media (with icloud photo sharing)
3. Click add to notes,
Result:
![image](https://cloud.githubusercontent.com/assets/24886483/21600094/db2f5052-d1b1-11e6-8ddb-c75805582c10.png)

This is the 2 notes: 
![image](https://cloud.githubusercontent.com/assets/24886483/21600106/0ad0671a-d1b2-11e6-94e3-95a8dcaf5496.png)

Let me know if you have questions. Btw, can you add also a scrub in multiple select and multiple select with share sheet? Thanks

**Comment by stek29** [comment]
Not related to Webogram.
Report iOS app issues using "Ask a Question" button in settings, or on Twitter.

**Comment by lucmbahmoute** [comment]
Thanks! Sorry about that!

**Comment by stek29** [comment]
Please close the issue :)
