### ISSUE TITLE
Error while installing locally

### ISSUE THREAD

**Issue by vahidvdn** [zhukov/webogram#1316]
Hi. I want to install the webogram locally. First when I run `npm install -g gulp` I get these warnings:

`
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher
 to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher
 to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail o
n node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible
. Use 'npm ls graceful-fs' to find it in the tree.
C:\Users\Cebit\AppData\Roaming\npm\gulp -> C:\Users\Cebit\AppData\Roaming\npm\no
de_modules\gulp\bin\gulp.js
C:\Users\Cebit\AppData\Roaming\npm
-- gulp@3.9.1
`

**NOTE:** When I run `npm -v minimatch`, I get this version: **3.10.10**

Then, When I run `npm install`, I get these errors:

`
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.9.4
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! ursa@0.9.4 install: node-gyp rebuild
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ursa@0.9.4 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ursa package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ursa
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ursa
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Cebit\webogram-master3\npm-debug.log
`

Finally, When I run `gulp watch`, I get these errors:

`
Error: Cannot find module 'gulp-serviceworker'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at C:\Users\Cebit\webogram-master3\node_modules\gulp-load-plugins\index.js:4
5:34
    at Array.forEach (native)
    at module.exports (C:\Users\Cebit\webogram-master3\node_modules\gulp-load-pl
ugins\index.js:35:33)
    at Object.<anonymous> (C:\Users\Cebit\webogram-master3\gulpfile.js:3:37)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
`

Any idea?

(**NOTE:** I updated `npm` and `node` to the latest version)

**Comment by azzimuth** [comment]
I haven't succeded to install `gulp` on Windows since a year or so. I remember though times when it was installed without any problem.

This is related to #1234.

**Comment by zhukov** [comment]
Sorry, windows is not currently supported. But PRs are welcome.
