### ISSUE TITLE
Pasting multi-Line text doesn't work

### ISSUE THREAD

**Issue by chrismc92** [zhukov/webogram#1317]
When pasting text containing line breaks into a message in telegram web, only the first line and line break pastes in. If I backspace the line break and paste again, the full text is produced. 

I'm not sure what's causing this bug. Please don't hesitate to ask for clarification on steps to repro!

I'm running Chrome 57.0.2970.0(dev) on Windows 10, and the latest version of webogram

**Comment by zhukov** [comment]
Can't reproduce. Any extensions installed? Can you disable them all if any?
Can you record a video?

**Comment by chrismc92** [comment]
Sure, I'll take a look and see if I can nail down repro steps.

**Comment by zhukov** [comment]
@chrismc92 any updates here?

**Comment by chrismc92** [comment]
For the sake of closure: I haven't been able to reproduce the issue. It must have been a temporary problem with my local system.
