### ISSUE TITLE
Getting Chrome notifications while Webogram is not running

### ISSUE THREAD

**Issue by azzimuth** [zhukov/webogram#1318]
I run Webogram locally via NodeJS. Even if the NodeJS is not running, I still get Chrome notifications. There is no content shown but only "X has sent you a message" or "Y has sent a message to grout Z".

**Comment by stek29** [comment]
And what's the issue?
That's the point of push notifications

**Comment by azzimuth** [comment]
The issue for me is that the Webogram is not running and if I click on the notification I see a 404 page.

I guess that the notifications are designed so. I chose to disable the push notifications.

**Comment by stek29** [comment]
Shouldn't app be cached?

**Comment by azzimuth** [comment]
I can test more if I can reproduce it.

**Comment by zhukov** [comment]
@azzimuth Is your local server running?

**Comment by azzimuth** [comment]
I hade NodeJS running, then I hibernated my laptop. When I started it again and logged in to Windows, I saw that NodeJS process was not running any longer. But I was still getting Chrome notifications.

**Comment by zhukov** [comment]
@azzimuth Don't see any problem then. Service worker is cached in browser, push notifications are sent from server side. If you launch server, click will open chat window.

**Comment by azzimuth** [comment]
I see. Then it's not an issue...
