### ISSUE TITLE
Search works in "starts with" mode

### ISSUE THREAD

**Issue by azzimuth** [zhukov/webogram#1319]
I was trying to find the Guggy Stickers bot. I typed "stickers" in search field but only got bots and users whose nicknames began with "stickers". I'd rather expect it to search in "contains" mode, i.e. find all bots and users whose nicknames contain the keyword.

**Comment by azzimuth** [comment]
This might be a limitation of Telegram API. If so, I would appreciate if someone could send me a link where I can file an issue for Telegram API (if that is possible).

**Comment by zhukov** [comment]
@azzimuth Yes, that's a server side limitation. You can try in-app support.

**Comment by azzimuth** [comment]
I have unfortunately never got any response from in-app support. I will file an issue in iOS app's GitHub project. But I would need someone with iOS app to confirm this behavior (I personally have an Android device).
