### ISSUE TITLE
Move "search in chat" to its own menu entry

### ISSUE THREAD

**Issue by Akronix** [zhukov/webogram#1328]
Currently webogam only supports "global search"; but, since more than a year, [telegram allows to search within a particular chat](https://telegram.org/blog/search-and-media).

I'd find it interesting to have it in webogram too and I offer myself to help with the implementation.

**Comment by stek29** [comment]
@Akronix Media -> Search :)

**Comment by Akronix** [comment]
Humm, Search under media menu? :confused: Shouldn't it have its own menu entry or button?

**Comment by azzimuth** [comment]
Agree! Sounds more logical to have a separate menu item for the search.
