### ISSUE TITLE
Next release

### ISSUE THREAD

**Issue by mikasoukhov** [zhukov/webogram#1329]
When you plan to build a new release?

**Comment by zhukov** [comment]
when it's done.

**Comment by mikasoukhov** [comment]
Hope your project will not die and next release will be available soon or later.

**Comment by stek29** [comment]
It gets updated often, but version number doesn't change.

**Comment by mikasoukhov** [comment]
https://github.com/zhukov/webogram/releases the latest update was 1 year ago.

**Comment by stek29** [comment]
The latest **release** was 1 year ago.

Go to web.telegram.org, open any chat and notice magnifier icon. It was added 2 days ago, see #1328.

**Comment by mikasoukhov** [comment]
But I'm looking the release package to run it on my own local server.

**Comment by Haktrum** [comment]
Have you tried reading [README.md](https://github.com/zhukov/webogram/blob/master/README.md)?

**Comment by stek29** [comment]
@mikasoukhov as @Haktrum said, [RTFM -- here's the link to Readme with an anchor](https://github.com/zhukov/webogram/blob/master/README.md#running-in-production)

**Comment by mikasoukhov** [comment]
I have a windows based platform. There is not glum.

The release packages are out of the box. No need any pre installed software. Was very friendly.

**Comment by Haktrum** [comment]
No idea what glum is but you can ways use gulp.

**Comment by mikasoukhov** [comment]
sorry, updated the comment.

**Comment by Haktrum** [comment]
Ok, I'll bite.

From [README.md](https://github.com/zhukov/webogram/blob/master/README.md):
> Install [node.js](http://nodejs.org/) and run the following commands in the project directory
>
>```
>sudo npm install -g gulp
>npm install
>```
>
>This will install all the needed dependencies.

That gets you gulp.

**Comment by stek29** [comment]
@mikasoukhov [here you go](http://bfy.tw/9c8a)

**Comment by mikasoukhov** [comment]
That why I said the releases are more friendly. No need to install any software, etc.
