### ISSUE TITLE
Automatic emoji menu "sticks" around for next message.

### ISSUE THREAD

**Issue by marcopaganini** [zhukov/webogram#1332]
When composing a message, typing a colon opens a mini-menu with popular emojis. The menu will disappear once the emoji sequence is completed, or if the next character does not belong to any emoji sequence. Under normal circumstances, this does not affect typing, other than the distraction of a menu opening near the cursor.

I've noticed however that in about 40% of the attempts the mini-menu will "stick around" when ENTER is typed right after a valid emoji sequence (very common with emojis at the end of the message). When that happens, we have a new message box with the popular emojis mini-menus obscuring the previous messages.

Alternatively, it would be nice to be able to turn off this "auto emoji" feature (Let me know if a separate feature request is preferred for this request.)

How to reproduce:
- Start a chat
- Type "meh :(<ENTER>" (no quotes)
- In about 40% of the tries, the new message box shows with the mini-menu still there.

**Comment by Ryuno-Ki** [comment]
Yeah, pretty annoying :-/

**Comment by stek29** [comment]
Duplicate reports are even more annoying...
