### ISSUE TITLE
On Firefox, playing voice messages stops in the middle

### ISSUE THREAD

**Issue by SettembreNero** [zhukov/webogram#1336]
Fedora 25, Firefox 50.
When I try to play an audio note (I only tried with audio made from iPhones, maybe it's relevant), web.telegram.org starts to play it but then after some seconds it stops, saying
```
Method: N/A
Url: N/A
Result: {"type":"MEDIA_TYPE_NOT_SUPPORTED","detailsShown":true}
```
Unfortunately googling the error message brings me to the GitHub page where the message is actually coded into. Also I don't think it's a codec error, because it can play the firsts seconds of a note...

**Comment by stek29** [comment]
Can you please set a breakpoint somewhere near [this place](https://github.com/zhukov/webogram/blob/82786e91ceb0f7c1324d9f7667269a9b53db2fa2/app/js/directives.js#L3002) and look what is in `event`?

Should be second result if you search for `type: "MEDIA_TYPE_NOT_SUPPORTED"` in pretty-printed `app.js`.

Here's where it was for me:
![image](https://cloud.githubusercontent.com/assets/11808223/22306400/364feb86-e350-11e6-9d41-49763cfb830a.png)

Or maybe there's some other way to get originalError? @zhukov ?

**Comment by SettembreNero** [comment]
This is the screenshot I took from the Firefox Debugger. I'm sorry, but I have rarely used it before and I didn't manage to get the full content of the variable to copy&paste\screen.

![screenshot from 2017-01-29 19-46-29](https://cloud.githubusercontent.com/assets/6898884/22406872/a637a39a-e65b-11e6-9e4d-9c3cd2808d5e.png)

**Comment by stek29** [comment]
You could try `JSON.stringify(e)` (in console)

**Comment by SettembreNero** [comment]
After Firefox v51, the bug seems gone. Thank you for availability to provide help and sorry for the disturb!
