### ISSUE TITLE
On Telegram macOS 2.30.51442, shows unread messages

### ISSUE THREAD

**Issue by vitaliy-komenda** [zhukov/webogram#1337]
It shows unread messages counter even if there is no unread messages
Steps like this:
1. I post a link
2. It downloads content of the link
3. It expands a link with downloaded content
4. Shows unread counter

Also it is not possible to make counter disappear by just focusing on a chat window like with regular unread counter

**Comment by stek29** [comment]
This repo is for Web version, not for macOS native app.
Check [this](https://github.com/overtake/telegram)

**Comment by vitaliy-komenda** [comment]
Ah okay sorry for that
