### ISSUE TITLE
Offer details on "Waiting for network…" and "Connecting…", including server addresses

### ISSUE THREAD

**Issue by mk-pmb** [zhukov/webogram#1338]
I see both messages "Waiting for network…" and "Connecting…" a lot, so I'd like to have some button to show me
* which servers Webogram tried to contact,
* how good the connection was (might be as simple as "unable to connect" or "connection duration: …"),
* which servers it is going to try next (firewall wishlist).

For the meantime, this is the command I used to guess destinations, I assume those are Telegram messenger server addresses:

```bash
$ grep -oPe '\{[^{}]*host"?\s*:\s*["0-9][^{}]*\}' **/*.js | tr -s '",:' '\t'
js/app.js       {id     1       host    149.154.175.10  port    80}
js/app.js       {id     2       host    149.154.167.40  port    80}
js/app.js       {id     3       host    174.140.142.5   port    80}
js/app.js       {id     1       host    149.154.175.50  port    80}
js/app.js       {id     2       host    149.154.167.51  port    80}
js/app.js       {id     3       host    149.154.175.100 port    80}
js/app.js       {id     4       host    149.154.167.91  port    80}
js/app.js       {id     5       host    149.154.171.5   port    80}
```

Note that the `id` numbering restarts. Parts of the source near them look like the first set might be test servers and the 2nd set might be the live servers.

**Comment by zhukov** [comment]
You can see all the info in browser network console. Don't think it's a good idea for general usage messenger app.

**Comment by mk-pmb** [comment]
> Don't think it's a good idea for general usage messenger app.

Any reason for this? Are there drawbacks?
I can only see advantages in having an option to display details about what a program is trying to do, especially in cases where it takes a long time.

> You can see all the info in browser network console.

I wish it were that easy. My console log [looks like this](https://abload.de/img/tg-console-log2xspy.jpeg), above and below are just the same messages repeating over and over, I can't see hostnames or IPs. With prior knowledge of what IP I'm looking for, I can find it [in the network tab](https://abload.de/img/tg-console-networkutsfp.jpeg), and can guess that "apiw1" is the magic keyword to look for if you don't know the IPs. With this additional info, your suggestion becomes feasible for readers of this thread, but it's still not quite easy.

In addition, you can't always rely on the browser. The screenshots are from my old Ubuntu 12.04.5 precise machine, using Gnome Web v3.4.1.
("Powered by WebKit 1.8.3", navigator.userAgent = "Mozilla/5.0 (X11; Linux i686) AppleWebKit/535.22+ (KHTML, like Gecko) Chromium/17.0.963.56 Chrome/17.0.963.56 Safari/535.22+ Ubuntu/12.04 (3.4.1-0ubuntu1) Epiphany/3.4.1")

When I try the same on my more recent Ubuntu 14.04.5 trusty machines (Web v3.10.3, "Powered by WebKit 2.4.10"), trying to open the browser console yields just [this error message](https://abload.de/img/tg-console-faili9j8v.jpeg).

Gnome Web might be a niche browser but I like it for Telegram because it has the web app mode, and it is light-weight enouth to run it on my weak netbook even while VLC is playing video.
