### ISSUE TITLE
Emoji autocompletion highlight ist barely visible

### ISSUE THREAD

**Issue by cypressious** [zhukov/webogram#1339]
When typing an emoji `:something...` an autocompletion list appears. You can select an entry by using the arrow keys. The currently selected entry is highlighted with a light blue color. However this highlight is so light that you can barely notice it. I attached a screenshot that demonstrates it:

![grafik](https://cloud.githubusercontent.com/assets/1191816/22462246/d3586b0a-e7ac-11e6-8be7-0baa2d7b9f6c.png)

Could you make the color a bit darker so that it's better visible?

**Comment by zhukov** [comment]
Duplicate #721 #723 
I didn't merge the PR since we use the same highlight styles in the whole app like this:
<img width="327" alt="screen shot 2017-02-08 at 13 54 32" src="https://cloud.githubusercontent.com/assets/775173/22734289/285d3b3a-ee06-11e6-84e3-59f64e2537a0.png">
