### ISSUE TITLE
Implement "unsend" feature

### ISSUE THREAD

**Issue by azzimuth** [zhukov/webogram#1340]
I tested the delete functionality in Webogram and cannot see that it supports "Unsend" or "Delete for" functionality introduced in [Telegram app version 3.16](https://telegram.org/blog/unsend-and-usage).

**Comment by stek29** [comment]
It's called revoke btw :)

**Comment by azzimuth** [comment]
@stek29 Telegram themselves call it ["unsend"](https://telegram.org/blog/unsend-and-usage)

**Comment by stek29** [comment]
@azzimuth [Well...](https://tjhorner.com/tl-schema/method/messages.deleteMessages)

**Comment by azzimuth** [comment]
@stek29 well I see 😝 You could say that the parameter is called revoke.

Anyways, my idea is to implement unsend functionality by making use of revoke parameter 😄

**Comment by azzimuth** [comment]
Wow! Great!
