### ISSUE TITLE
How secure are regular chats?

### ISSUE THREAD

**Issue by armensg** [zhukov/webogram#1341]
I am having a hard time identifying how secure chats are on the telegram web app. For example, If my network traffic is being monitored would it it be possible read the contents of regular chats or are they encrypted?

**Comment by stek29** [comment]
Short answer: There're no evidences that someone except you, other side and Telegram can read your messages, even if they monitor your connection.

**Comment by armensg** [comment]
Thanks - on what basis do you think that's the case though?

On 2 Feb 2017, at 13:22, Viktor Oreshkin <notifications@github.com<mailto:notifications@github.com>> wrote:


Short answer: There're no evidences that someone except you, other side and Telegram can read your messages, even if they monitor your connection.

-

**Comment by stek29** [comment]
@armensg Telegram FAQ, source code, Telegram's tweets, Telegram Support answers, MTProto documentation and other public sources.

**Comment by armensg** [comment]
Oh okay thanks - I thought perhaps the telegram-web app made communications to the telegram servers that were not encrypted (I haven't investigated the telegram-web code).

**Comment by trap40** [comment]
Help mee , my idea 💡. Very important for people

**Comment by zhukov** [comment]
Correct. On top of that all the communications of Telegram Web are  additionally encrypted with SSL (since the site is hosted on https).
