### ISSUE TITLE
occasionally fail to get message history update

### ISSUE THREAD

**Issue by daflin** [zhukov/webogram#1342]
My program calls [`AppMessagesManager.getHistory()`](https://github.com/zhukov/webogram/blob/v0.5.3/app/js/messages_manager.js#L571) to poll for new messages in the conversation history every 2-3 seconds, but sometimes it would stop returning new messages for at least a minute even though new messages come up in the official Telegram app. Sometimes there are FLOOD_WAIT errors in browser console after a while, but usually there is no error message in the console.

Would anyone know if it's a proper use of the APIs, or should I use other function calls for getting new message update? If I should still use `AppMessagesManager.getHistory()`, what would be the proper interval to call it if 2-3 seconds is too short? Thanks for help.

**Comment by zhukov** [comment]
You should handle new message updates, don't poll getHistory method.

**Comment by daflin** [comment]
@zhukov, thank you for making this great web app. I guess I should focus on `AppMessagesManager`, within which the function [handleNewMessages()](https://github.com/zhukov/webogram/blob/v0.5.3/app/js/messages_manager.js#L2607),  [handleNewDialogs()](https://github.com/zhukov/webogram/blob/v0.5.3/app/js/messages_manager.js#L2614) or [$on('apiUpdate')](https://github.com/zhukov/webogram/blob/v0.5.3/app/js/messages_manager.js#L2649) seem likely to handle new message updates, but when I try to run in debug mode, I can't get new messages from them. Would you provide more hints on how I should handle new message updates, or if there is some documentation about the system design of this web app I can refer to? Thanks for your help.

**Comment by zhukov** [comment]
@daflin you should handle `history_multiappend` event on `$rootScope`.

**Comment by daflin** [comment]
Great, thanks for your advice!
