### ISSUE TITLE
security issue: hint is auto-generated from first and last symbol of password

### ISSUE THREAD

**Issue by vladon** [zhukov/webogram#1344]
https://github.com/zhukov/webogram/blob/master/app/js/controllers.js#L4573

```
if (!len) {
        $scope.passwordSettings.hint = ''
      }
      else if (len <= 3) {
        $scope.passwordSettings.hint = '***'
      }else {
        $scope.passwordSettings.hint = newValue.charAt(0) + (new Array(len - 1)).join('*') + newValue.charAt(len - 1)
      }
```

I think it is very bad for passwords of length 4.

**Comment by stek29** [comment]
Why would you ever have a password of length 4 and use auto-generated hint if you worry about security?

**Comment by vladon** [comment]
@stek29 This way 4-letter password turns into 2-letter password.

**Comment by zhukov** [comment]
4-letter password is bad anyway. The hint field is editable, so one can change the value.
I would change this behaviour so it's the same as on mobile, but as I see iOS app shows `X*X` value even for 3-letter passwords.
