### ISSUE TITLE
blank username in invite notification

### ISSUE THREAD

**Issue by Ryuno-Ki** [zhukov/webogram#1348]
![tmp_14350-screenshot_2017-02-23-19-54-00-90839088](https://cloud.githubusercontent.com/assets/3097194/23274268/56d443ac-fa02-11e6-993e-050c914f4711.png)

I experienced attached situation in Mozillians telegram group.
The English UI shows the username.
I'm using v0.5.5 on web.telegram.org

**Comment by pollti** [comment]
![screenshot 34](https://cloud.githubusercontent.com/assets/5623575/23277741/4986d4be-fa0f-11e6-9a12-7c2117788aa2.png)
The German and English mobile websites seem to be affected by this.

**Comment by Ryuno-Ki** [comment]
Fellow Mozillians reported that they would see the username with their English locale. Thanks for the PR!
