### ISSUE TITLE
Null reference when opening a link to a chat

### ISSUE THREAD

**Issue by JuliaVikulina** [zhukov/webogram#1350]
Steps to recreate:

1. Open some link to a telegram chat in browser. For example, go to https://combot.org/telegram/top/chats and open the first one.
2. In the page https://telegram.me/WerewolfArena click 'Open Channel' button
3. You get this message with 'null' instead of the chat name:
<img width="1240" alt="screen shot 2017-02-24 at 12 08 19 pm" src="https://cloud.githubusercontent.com/assets/7235702/23297594/2b680d96-fa8b-11e6-9339-1125002a524d.png">

---
OS X El Capitan 10.11.6
Safari Version 10.0.3 (11602.4.8.0.1)

**Comment by stek29** [comment]
This is not related to Telegram Web.
It looks like your system doesn't know what app to use to open "tg://" links.
But Webogram can't register handler for custom protocol unless it starts with "web+". 
You can easily find issue reports related to it.

**Comment by zhukov** [comment]
https://www.tekrevue.com/tip/rebuild-launchservices-fix-duplicate-entries-os-xs-open-menu/

```/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -kill -r -domain local -domain system -domain user```
helped me with the same issue. Not a webogram related thing.
