### ISSUE TITLE
Web client closed and receiveing messages

### ISSUE THREAD

**Issue by cemsbr** [zhukov/webogram#1351]
Is there a way to stop receiving notifications after closing the web client? Probably logging out works, but it's not convenient to log in/out every time.

**Comment by zhukov** [comment]
@cemsbr If you mean background notifications, you can disable them in App Settings.

**Comment by cemsbr** [comment]
There's desktop and background notifications. It seems that background notification is what I was looking for and couldn't find in any doc/FAQ. Thanks
