### ISSUE TITLE
Fix parsing of formatting

### ISSUE THREAD

**Issue by akaleeroy** [zhukov/webogram#1352]
Steps to reproduce: Type a message with more than 1 bold / italic formatting:

    Me: This __is__ a **test** of the __emergency broadcast system.__

Expected result: This _is_ a **test** of the _emergency broadcast system._  
Frustratingly fucked result: This _is_ a te**st o**f the emergency broadcast system.

So starting with the 2nd instance of formatting in a message the parser shifts, eats up and otherwise bungles formatting in what can only be described as a **formatting haywire mayhem apocalypse.** :boom: :fire: :scream: :scream_cat: 

Make kitty un-sad!

**Comment by stek29** [comment]
#1333 fixed this

**Comment by akaleeroy** [comment]
@stek29 Thanks for the fix! Sorry, I only looked at issues and I missed it. Any idea when it will roll out?

**Comment by stek29** [comment]
@akaleeroy Only @zhukov knows.
