### ISSUE TITLE
Exit in the drop-down box About

### ISSUE THREAD

**Issue by yarik-vv** [zhukov/webogram#1357]
On the page https://web.telegram.org/#/login, when you click on the "Learn more" link, the shows "About" box and page scrolling to the down. This makes inaccessible input form for small screens.

I suggest added a button or a link "back" in the drop-down box "About" with ng-click = "about.shown = true".

P.S: sorry for my very bad English :(

**Comment by zhukov** [comment]
Can you show a screenshot? Don't understand the problem.
// Можно по-русски, если так проще.

**Comment by Stapelpanda** [comment]
I think the following is meant (marked in yellow):
![image](https://cloud.githubusercontent.com/assets/5207258/23907779/6e921ad0-08d2-11e7-9f53-1333d6f5ceb4.png)

I've added one line of code to the partial (desktop and mobile), can create a PR if the styling is ok :)

**Comment by zhukov** [comment]
Ah.. I see. Then I think it's better to add it right next to About header, inside `<small>` tag.
@Stapelpanda will you provide PR?
