### ISSUE TITLE
Some words become annoying  link

### ISSUE THREAD

**Issue by ruv** [zhukov/webogram#1358]
Why does any occurrence of `/me` word in a message becomes active link in a group chat? The URL of the link is `tg://bot_command?command=me`.  By left click on the link a message contained just "/me" is immediately sent to the group. The worse thing — by right click such message is sent too.

It seems that the issue affects any word that starts with slash.

If something looks like link, it must have idempotent behavior. It should never send a message by click.

**Comment by zhukov** [comment]
This links are called bot commands: https://core.telegram.org/bots#commands

**Comment by ruv** [comment]
Thanks,  I see. 

> Telegram apps will: [...] Highlight /commands in messages. When the user taps a highlighted command, the command is sent at once.

At least for group chats, sending at once seems to be a very bad design choice: users usually don't expect that tapping on a link causes sending some message to the group chat (i.e. to other people in the chat). But let's leave it on the author's conscience.

What is the reason to highlight such words if no any bot in the group?  Or several bots? Since in the case of several bots a command should also contain a bot's name.

**Comment by zhukov** [comment]
This is a technical difficulty. Highlighting the command inside text might occur, when there is no info on whether any bots are present in group.

**Comment by ruv** [comment]
I don't see in the code any checks for presence bots in the group. It seems that a message is parsed on the client side (for [bot commands](https://github.com/zhukov/webogram/blob/94a94b864dc1d7453cf82d456deb0d932681633d/app/js/lib/ng_utils.js#L1384) and other entities) and then bot commands are represented [as special link](https://github.com/zhukov/webogram/blob/94a94b864dc1d7453cf82d456deb0d932681633d/app/js/lib/ng_utils.js#L1705) in any group (`AppPeersManager.isAnyGroup(toPeerID)`) [regardless of bots presence](https://github.com/zhukov/webogram/blob/181921d7d3736b2bd78ce5422f3072e9f82d19cd/app/js/messages_manager.js#L2366). This special link [is handled](https://github.com/zhukov/webogram/blob/94a94b864dc1d7453cf82d456deb0d932681633d/app/js/services.js#L4546) regardless bots presence too, [just on click](https://github.com/zhukov/webogram/blob/94a94b864dc1d7453cf82d456deb0d932681633d/app/js/services.js#L4628).

At the first, right click should not cause navigation or sending a message. Could you filter in only left click in this place?

At the second. Perhaps there is a sense to check if any bot presents in the group. But it can be too expensive for big groups and just partial solution.
My suggestion is to highlight (and treat) commands in the messages from or to bots only. I suppose it is enough to remove `AppPeersManager.isAnyGroup(toPeerID)` option in the `withBot` variable of [`wrapMessageText` function](https://github.com/zhukov/webogram/blob/181921d7d3736b2bd78ce5422f3072e9f82d19cd/app/js/messages_manager.js#L2366):

```
var withBot = (
        fromBot ||
        AppPeersManager.isBot(toPeerID)
)

```

**Comment by stek29** [comment]
Android and iOS apps check if there are any bots in chat (but don't check message author) afaik -- they're doing it by using `bot_info`, I suppose.
