### ISSUE TITLE
Google static map key error

### ISSUE THREAD

**Issue by alanbirtles** [zhukov/webogram#1364]
Sometimes when a location is posted the following image is displayed
![](https://cloud.githubusercontent.com/assets/8985104/23832022/d284b962-0724-11e7-8729-d6249bd37126.png)

**Comment by hazowskey** [comment]
Issue still exists.

![image](https://cloud.githubusercontent.com/assets/6570775/25111996/13cd898c-23f7-11e7-8446-e16a89fbfda0.png)

**Comment by alanbirtles** [comment]
the fix hasn't been released yet
