### ISSUE TITLE
Preview of message is not updated after editing the message

### ISSUE THREAD

**Issue by YanaSavchenko** [zhukov/webogram#1367]
![capture](https://cloud.githubusercontent.com/assets/10143921/24259284/701b6daa-0fbe-11e7-8687-b0b5cb8aff18.PNG)

1. Send message
2. Update it
3. Check left preview

**Comment by stek29** [comment]
#1177

**Comment by whipermr5** [comment]
Fixing this in #1378

**Comment by zhukov** [comment]
Duplicate
