### ISSUE TITLE
Text in message text box is under commands button

### ISSUE THREAD

**Issue by Newlifer** [zhukov/webogram#1373]
![](http://pastexen.com/i/oXcyqZeCu9.png)

_Browser:_ Google Chrome 57.0.2987.110, Windows 7 x64

**Comment by ruollah051** [comment]
244659223:AAHNbWilbgk8Sxk7kbum2ZLol3FbxciTHPU

**Comment by ruollah051** [comment]
yon.ir/sHX4c

**Comment by stek29** [comment]
Hm, maybe something like #1150 should be done.
