### ISSUE TITLE
Implement voice calls

### ISSUE THREAD

**Issue by azzimuth** [zhukov/webogram#1376]
Telegram [has announced](https://telegram.org/blog/calls) voice calls today. Would be nice to have this feature in Webogram as well.

**Comment by stek29** [comment]
@azzimuth It's technically impossible: Calls require raw socket access, which obviously can't be done in Browser.
Even if Telegram makes some kind of WebSocket <=> TCP relays, (de)cyphering, (ed|de)coding opus, tracking packets, syncing the sound can't be done in browser.

**Comment by azzimuth** [comment]
Impossible? Say that to Facebook whose Messenger has both video and voice calls in browser.

I can believe that it's not possible right now but once Telegram API includes methods for voice calls, it should not be a big problem to implement this.

**Comment by marco-c** [comment]
> @azzimuth It's technically impossible: Calls require raw socket access, which obviously can't be done in Browser.
Even if Telegram makes some kind of WebSocket <=> TCP relays, (de)cyphering, (ed|de)coding opus, tracking packets, syncing the sound can't be done in browser.

https://developer.mozilla.org/en-US/docs/Web/API/WebRTC_API

**Comment by stek29** [comment]
@marco-c Isn't WebRTC a Working Draft? Anyways, I'm not so confident, and I'm happy if I'm wrong and WebRTC API allows sending raw UDP packets. 

@azzimuth Telegram API already includes methods for voice calls. There's even public [documentation](https://core.telegram.org/api/end-to-end/voice-calls) for them, and you could also check [libtgvoip](https://github.com/grishka/libtgvoip).

**Comment by marco-c** [comment]
> @marco-c Isn't WebRTC a Working Draft? Anyways, I'm not so confident, and I'm happy if I'm wrong and WebRTC API allows sending raw UDP packets.

WebRTC is used by a lot of popular web sites (skype, facebook, hangout), it's a proven technology.
If you are not confident, you can do a quick online search or you can look at the documentation that I sent you.

**Comment by stek29** [comment]
@marco-c but have you looked on how telegram calls are implemented? They have their own protocol, which doesn't seem to be compatible with WebRTC. Correct me if I'm wrong -- make a PR.

**Comment by marco-c** [comment]
> @marco-c but have you looked on how telegram calls are implemented? They have their own protocol, which doesn't seem to be compatible with WebRTC. Correct me if I'm wrong -- make a PR.

I've never said it's feasible with the current protocol for calls (I don't know anything about it), I've simply said that browsers can support voice calls.
If Telegram wants to support them, they might need to modify their protocol slightly (like they've done to support Web Push), but it is definitely feasible.

**Comment by grishka** [comment]
@marco-c it is technically impossible to implement this using the current web technologies alone. It is likely possible, however, with the use NPAPI/PPAPI plugins or, maybe, in a packaged Chrome app. I do know what WebRTC is and that it's a "proven technology", but the problem here is that it isn't in any way compatible with what Telegram uses at least in terms of packet format and cryptography. There's currently no way to gain low-level access to networking that my implementation requires, even if we rewrite the entire thing in JS. WebRTC [doesn't allow one to simply open a raw UDP socket](http://stackoverflow.com/questions/13811854/can-i-use-webrtc-to-open-a-udp-connection) but requires to use a bunch of pre-existing protocols. A WebSockets-compatible TCP relay might be an option but TCP isn't really suited for real-time communication because of its retransmissions and (the wrong kind of) congestion control. But,
 [Chrome has UDP sockets](https://developer.chrome.com/apps/sockets_udp) for apps & extensions, and there's also [a W3C draft](https://www.w3.org/TR/raw-sockets/) for an API that is supposed to allow websites to use raw sockets.

So, it might be possible in the future, but not right now.

**Comment by zhukov** [comment]
Don't see any point in implementing support for just Chrome App since it's deprecated by Google and is limited to just ChromeOS: https://blog.chromium.org/2016/08/from-chrome-apps-to-web.html.

**Comment by azzimuth** [comment]
What about WebAssembly?

**Comment by grishka** [comment]
@azzimuth WebAssembly may come in handy to reuse the existing C++ code, but it still doesn't do anything about the lack of any usable low-level networking API.

**Comment by marco-c** [comment]
> @marco-c it is technically impossible to implement this using the current web technologies alone. It is likely possible, however, with the use NPAPI/PPAPI plugins or, maybe, in a packaged Chrome app. I do know what WebRTC is and that it's a "proven technology", but the problem here is that it isn't in any way compatible with what Telegram uses at least in terms of packet format and cryptography.

Yes, I'm not saying that you can blindly use WebRTC with the current protocol and get it to work, I'm just saying that implementing voice calls in general in browsers is feasible.
You could modify your protocol to use the networking protocol WebRTC uses (RTP, if I recall correctly), but clearly it depends on your priorities.

> A WebSockets-compatible TCP relay might be an option but TCP isn't really suited for real-time communication because of its retransmissions and (the wrong kind of) congestion control.

Why would you use TCP? If you want to build a relay, you can build a WebRTC based one (e.g. https://github.com/meetecho/janus-gateway).

**Comment by grishka** [comment]
> You could modify your protocol to use the networking protocol WebRTC uses (RTP, if I recall correctly), but clearly it depends on your priorities.

WebRTC doesn't give me the necessary freedom. It handles too many things all by itself. Also, RTP completely lacks some of the features that we rely on, like packet acknowledgements or, again, proper cryptography. So that's my reason why using any standard protocol is not an option.

**Comment by lifehome** [comment]
What about take a look at Discord's implementation?


https://discordapp.com/developers/docs/topics/voice-connections

**Comment by azzimuth** [comment]
I object that commit [e6395fa](https://github.com/zhukov/webogram/commit/e6395fac8359455ce4fe3bca2bc4b3dac1032e52) solves this and this issue can be closed. We did not implement the calls rather added an error message.

**Comment by zhukov** [comment]
Unfortunately that's all we can do for now. We can reopen the issue if the state of Telegram Calls protocol changes, but for now that's not an issue for Web App.

**Comment by azzimuth** [comment]
OK, I agree. Can you somehow label this issue?

**Comment by zhukov** [comment]
Done

**Comment by Kreijstal** [comment]
is there a project that just proxies the voice calls? I would like to call over the browser, even if I need to self-host

**Comment by grishka** [comment]
The new calls implementation supposedly uses WebRTC, so might be possible to do it directly this time. Don't know much about the implementation details tho.
