### ISSUE TITLE
Support for Pin to top?

### ISSUE THREAD

**Issue by orschiro** [zhukov/webogram#1377]
Dear all, 

On my Android app, I pinned a number of conversations to the top. 

However, this is not reflected in the web version.

Could we add support to display pinned conversations?

Yours,

Robert

**Comment by Ryuno-Ki** [comment]
See #1088 and #1287.

**Comment by orschiro** [comment]
Dear @Ryuno-Ki,

Thank you for your follow-up in #1287!

Yours,

Robert

**Comment by stek29** [comment]
Dear @orschiro,

You can now close this issue. Thanks.

Yours,
Viktor Oreshkin aka Doge Lord

**Comment by guf228** [comment]
хочу новый телеграмм
