### ISSUE TITLE
Acquire channel owner privileges

### ISSUE THREAD

**Issue by AndySky21** [zhukov/webogram#1381]
When a channel creator leaves the channel or the platform altogether, their privileges do not pass to any of the channel administrators.
Note that channels can be related to entities, communities and so on. It's natural for such communities to have changes in the staff, so it's absurd that noone can acquire it when a creator leaves.
Discard the channel itself and create another one is really a poor option, but it's the only possible way now.
Please fix this situation.

**Comment by Ryuno-Ki** [comment]
I don't think that tgis issue is related to webogram, but to Telegram in general.

Have you tried getting in contact with Telegram support?

**Comment by AndySky21** [comment]
Not yet. I reached this project by clicking on the "Github" link on (web) Telegram.

**Comment by Ryuno-Ki** [comment]
https://telegram.org/faq#telegram-support is the channel you should try.
