### ISSUE TITLE
irc:// and ircs:// URLs are misinterpreted

### ISSUE THREAD

**Issue by grahamperrin** [zhukov/webogram#1383]
In this example, irc:// is misinterpreted as http://

![telegram web](https://cloud.githubusercontent.com/assets/192271/24590014/b704e73e-17dc-11e7-87f0-7be5f23a93cd.png)

**Comment by stek29** [comment]
@grahamperrin Unfortunately, it's a server side issue: It seems to have protocol whitelist, and irc isn't in it.
But it tries to parse links with no [valid] protocol, and assumes them to have http. 
I'd suggest you to contact support or report this to telegram on Twitter

**Comment by zhukov** [comment]
Yep, @stek29 is right here.
