### ISSUE TITLE
"3: Incorrect/incomplete header." alert box

### ISSUE THREAD

**Issue by mbasaglia** [zhukov/webogram#1384]
Very often when looking through stickers, an alert shows up with that text.
It was already reported in #805 and supposedly fixed but it still happens very often.

**Comment by zhukov** [comment]
What is the website you are using app from? Did you try to clear cache / use another computer? Can you find the exact sticker pack and sticker, which causes problems?

**Comment by stek29** [comment]
Also looking for errors in the console may help

**Comment by mbasaglia** [comment]
I'm accessing it from https://web.telegram.org/, I'm not sure how to check which sticker causes it, it happens by moving the mouse when the sticker selector is open. It seems to happen regardless of cache and on different computers (though with the same configuration).

The console shows a few messages, a couple of which seem to be errors:
```
Error: [$rootScope:inprog] $digest already in progress
http://errors.angularjs.org/1.5.7/$rootScope/inprog?p0=%24digest
```

It happens after opening the sticker selector for the first time since loading the page and then every few hours.

**Comment by zhukov** [comment]
To locate the problem you might first to learn, which stickerset is causing problems.
You can send every stickerset URL to some chat (click Stickerset title in stickers selector, then SHARE button in bottom left). Then reload page and click URLs in chat one by one. The first stickerset which will cause the error is a problem one. You might just share problem URL here and it will help.

**Comment by codefuhrer** [comment]
Example set:
https://telegram.me/addstickers/Ultimateyoba

Console out:
[webpjs] decoding failed TypeError: this.Yc is not a function Object { xd: 0, yd: 1, vd: 2, ud: 3, Ad: 4, zd: 5, Bd: 6, wd: 7 }

Occurs only in browsers that doesn't support webp.
