### ISSUE TITLE
 api_id_invalid  in new update telegram

### ISSUE THREAD

**Issue by behroozmaghsodi** [zhukov/webogram#1390]
hi dear 
new api_id in https://my.telegram.org/auth  is 6 digit when set in project 
error is   
Method: auth.sendCode
Url: N/A
Result: {"_":"rpc_error","error_code":400,"error_message":"API_ID_INVALID"}
but old api_id (5 digit and low ) is ok and not problem  
plz help me to set new api_id?!!
for example this hash and id 
33dcb8a2f5081aa3515dc59753ddbabb
152072

**Comment by behroozmaghsodi** [comment]
for example this hash and id 
33dcb8a2f5081aa3515dc59753ddbabb
152072

**Comment by zhukov** [comment]
this was recently fixed from server-side. thanks for the report
