### ISSUE TITLE
Launching webogram without needing gulp watch

### ISSUE THREAD

**Issue by davidniki02** [zhukov/webogram#1394]
I need to deploy webogram to my heroku installation but the gulp dependency causes major problems. Is there a way to bypass that and run webogram directly?

**Comment by zhukov** [comment]
@davidniki02 Yep, just use prebuilt version in releases section.

**Comment by davidniki02** [comment]
Thanks, but how do I run it? there is no package.json file and "node index.js" also fails. Can you tell me the command I should execute to run it?

**Comment by stek29** [comment]
@davidniki02 you just deploy it to any web server (don't forget about `X-Frame-Options SAMEORIGIN`)

**Comment by davidniki02** [comment]
For anyone else that lands here, especially as I mentioned heroku; webogram functions somehow like a static website. It is not a web app so you should not expect it to execute like a node app. And heroku will reject the app since it cannot recognize the app type.
Workaround: add an index.php with a redirection code like below:
`<?php header( 'Location: /index.html' ) ;  ?>`
It will make heroku think of your webogram as a static website and run it! (we are effectively tricking heroku to think that this is a php website - the closest I could find)
