### ISSUE TITLE
New day begins from 12:00 AM in telegram web 

### ISSUE THREAD

**Issue by shotacat** [zhukov/webogram#1395]
After 11:59 PM starting a new day from 12:00 AM onstead of 00:00 AM
![12am](https://cloud.githubusercontent.com/assets/6895744/25354294/a4f96614-295c-11e7-88ec-e8f63844e90d.PNG)

**Comment by bartist** [comment]
Is that really wrong? The [12-hour notation](https://docs.angularjs.org/api/ng/filter/date) used by AngularJS just goes from 1 to 12, so it would be hacky to even want 00:00 AM instead of 12:00 AM

**Comment by shotacat** [comment]
it`s correct. 
Too much coffee at night, sorry (◎-◎)
