### ISSUE TITLE
Media type not supported in Mac OS Safari

### ISSUE THREAD

**Issue by misamplus** [zhukov/webogram#1396]
When I play an audio, I get this error!
`Method: N/A`
`Url: N/A`
`Result: {"type":"MEDIA_TYPE_NOT_SUPPORTED","detailsShown":true}`

**Comment by zhukov** [comment]
Yes, unfortunately Safari doesn't support opus which is used to encode voice messages in Telegram.

**Comment by misamplus** [comment]
but I can't even downloading the file and opening it in a standalone player...
Please solve this problem for downloading the file easily.

**Comment by misamplus** [comment]
@zhukov
