### ISSUE TITLE
Size of an image increase when copied and sent within Windows desktop client app.

### ISSUE THREAD

**Issue by trialsid** [zhukov/webogram#1398]
My friend sent me an uncompressed image as a file from iOS app to my Windows desktop client app of Telegram. I copied the image within the app and pasted in another friend's message thread to send it to him. I did this to avoid the "forwarded by so-so" that appears when we forward an image to other person. The image I received had some 'x'MB of size and when I sent it to the other friend via the procedure I mentioned, it came out to be 2.5xMB or 3xMB. ( not exact figures but I'm trying to say that it gets oversampled? opposite to compression)

ORIGINAL IMAGE:
![image](https://cloud.githubusercontent.com/assets/6409449/25477641/d2b5616a-2b5b-11e7-8505-90a9fe5ae47b.png)

COPIED AND SENT IMAGE:
![image](https://cloud.githubusercontent.com/assets/6409449/25477680/f821c312-2b5b-11e7-9d2d-aaab3b381831.png)

Hope you understand what I'm trying to report here. Would help the community if you resolve this.
Thank you. Love Telegram.

**Comment by stek29** [comment]
But how is this related to Webogram?

**Comment by trialsid** [comment]
Sorry. I didn't know that. So where should I post this issue?

**Comment by stek29** [comment]
https://github.com/telegramdesktop/tdesktop

**Comment by bartist** [comment]
@trialsid
If this does not relate to webogram, could you close this issue? :)
