### ISSUE TITLE
Unable to silence link warnings for inline links on individual chats or globally

### ISSUE THREAD

**Issue by TheSteppe** [zhukov/webogram#1402]
Inline links currently always require a warning prompt to be clicked through, which also entirely breaks opening the links in a new tab/window through use of middle-click, Ctrl+left-click, or right-click/context menu options. There should be an option to silence this warning for individual chats and an option to silence it globally.

**Comment by stek29** [comment]
Seems an API issue for me

**Comment by zhukov** [comment]
Sorry, this is consistent across all Telegram platforms. Confirm windows are shown when user can't see the URL before clicking.
