### ISSUE TITLE
[ChromeOS] Update color of ChromeOS App window to be Telegram blue

### ISSUE THREAD

**Issue by vcantu** [zhukov/webogram#1403]
Currently the top of the window of the Chrome OS app looks like this
![screenshot 2017-05-04 at 1 32 58 am](https://cloud.githubusercontent.com/assets/13156162/25691580/674002dc-306a-11e7-85f7-d817eec8aba8.png)

However it would be nice if it looked like this
![screenshot 2017-05-04 at 1 32 42 am](https://cloud.githubusercontent.com/assets/13156162/25691589/8106103a-306a-11e7-88cc-5aa27a78bdbf.png)

It's an easy one line fix, just needs `app/background.js` to include `frame: { color: "#5682a3" }`

I could create a PR or someone else could if approved.

**Comment by zhukov** [comment]
Sure, go ahead, I'll merge it.

**Comment by vcantu** [comment]
@zhukov done thanks!
