### ISSUE TITLE
"Unsupported action messageActionPhoneCall" in chat after voice call on mobile app

### ISSUE THREAD

**Issue by azzimuth** [zhukov/webogram#1404]
I get this message in chat in Webogram after I talk to someone via mobile app:
![image](https://cloud.githubusercontent.com/assets/1640148/25705294/1691bfb0-30dd-11e7-84e8-52ebecbee350.png)
Would be nice to see more "friendly" message, something like "You were in phone call with X (not supported in Webogram yet)".

**Comment by azzimuth** [comment]
IIRC, when the voice calls were just introduced, I saw "You were in phone call with X" in the chat. After some update that disappeared and now I see this not-so-friendly message.

**Comment by stek29** [comment]
@azzimuth That's not possible. I guess Webogram didn't even know about existence of messageActionPhoneCall action, and haven't showed any error.

IMO this is a variation of #1376

**Comment by azzimuth** [comment]
@stek29 you really like to say "impossible" and "not possible" :) Remember the motto - "impossible is nothing" ;)

Anyways, while this is related to #1376, this issue is about show more user-friendly message while we still are waiting for implementation of voice calls.

**Comment by bartist** [comment]
A simple search reveals that the message "unsupported action messageActionPhoneCall" originates from the [locales json files](https://github.com/zhukov/webogram/search?l=JSON&q=unsupported+action&type=&utf8=%E2%9C%93). This is set via [Transifex](https://www.transifex.com/telegram/telegram-web/), thus it needs to be consistence with the Telegram app. 

I also checked all commits from the day you issued 1376, there have been no changes to the code containing "phone call", thus I think it is very unlikely that the message "You were in phone call with X" was generated by Webogram.

**Comment by stek29** [comment]
@bartist iirc that message is generated for any action which exists in schema but isn't handled by app. Due to way MTProto works it wouldn't be possible to show "unsupported action X" if X wasn't known -- you can't reverse CRC32 :)
So the message likely started showing up after @whipermr5's commits -- when layer 62 was pulled in

It shouldn't be hard to fix this issue: just add new action to message_service.html partial.

**Comment by bartist** [comment]
Aah, that would explain it

**Comment by azzimuth** [comment]
Unfortunately, it seems that Telegram hasn't updated the documentation for API. I cannot find `messageActionPhoneCall` [here](https://core.telegram.org/type/MessageAction). Anyone can suggest a way to list the properties of the `messageActionPhoneCall` type?

**Comment by stek29** [comment]
@azzimuth https://tjhorner.com/tl-schema

**Comment by azzimuth** [comment]
Thanks, @stek29. 

I'm almost done with this but need some method to convert the duration to some readable format. Is there any method present in the application for that? The duration is in seconds and, as far as I can see in the app, is converted to the number of minutes (possibly to hours:minutes but I have no such long call in my history to test with).
