### ISSUE TITLE
Cannot forward messages sent to a group to the same group

### ISSUE THREAD

**Issue by azzimuth** [zhukov/webogram#1405]
Steps to reproduce:
1. Write some message in a group;
2. Select that message;
3. Click on Forward and select the same group in the Forward dialog.
Result: Nothing happens.
Expected result: the message is possible to forward to the same group (verified on the Android app).

**Comment by bartist** [comment]
Although I currently don't have the time to fix this, the code in question is in:
File: webogram/app/js/messages_manager.js
Function: [forwardMessages](https://github.com/zhukov/webogram/blob/master/app/js/messages_manager.js#L1948)

**Comment by azzimuth** [comment]
When I set a breakpoint in that function and try to reproduce the bug, the breakpoint is never hit. I guess something happens before the function `forwardMessages` is called.

**Comment by azzimuth** [comment]
After some investigation, I found out that it has to do with the condition in line 458 in [controller.js](https://github.com/zhukov/webogram/blob/master/app/js/controllers.js#L458). Anyone knows why do we need the condition `peerData.peerString == $scope.curDialog.peer` there?

**Comment by stek29** [comment]
@azzimuth It was [introduced in](https://github.com/zhukov/webogram/commit/d9447f62245b6686b94d18d93ae6075a7ae68886#diff-40084eb42a8e52b0a5ff0264ef426c94R128) d9447f62245b6686b94d18d93ae6075a7ae68886, maybe it can help you

**Comment by azzimuth** [comment]
Ok, I guess @zhukov will have to look at it. I don't get what `history_focus` is and why it is called when I click on a chat/contact in the dialog.

**Comment by stek29** [comment]
@azzimuth [use the force](https://github.com/zhukov/webogram/search?q=history_focus&type=Code&utf8=%E2%9C%93)
