### ISSUE TITLE
Emoji window stays open after using shortcut

### ISSUE THREAD

**Issue by Alber70g** [zhukov/webogram#1409]
I'm experiencing an issue when sending emoticons using `:` shortcuts. 
I'm using the Chrome app: https://chrome.google.com/webstore/detail/telegram/gjmanaihpgjcijokbimnamcdndkffigp

Steps to reproduce:
1. Type message with emoji, e.g.: `This is a test :blush:`
2. Press `<enter>`

Expected: Message is sent, the emoji window closes
Actual: Message is sent, the emoji window stays open

**Comment by stek29** [comment]
Duplicate
Iirc Chrome app is deprecated

**Comment by Alber70g** [comment]
I'm sorry to hear that. For me it was very useful since I login on Chrome and I've got all my aps. Is there no way to keep the Chrome app updated?

**Comment by stek29** [comment]
@Alber70g Why won't you just use web.telegram.org?

**Comment by Alber70g** [comment]
@stek29 I like to have it in a separate window. And able to start without full Chrome

**Comment by stek29** [comment]
@Alber70g there are extensions which let you to open websites in separate Windows.
Anyways, it would be better to ask @zhukov
