### ISSUE TITLE
Pressing Ctrl+Shift defocuses input field

### ISSUE THREAD

**Issue by golergka** [zhukov/webogram#1414]
Steps to reproduce:

1. Open chat
2. Focus on the input field, while it's still empty
3. Press Ctrl-Shift to switch input language

Expected result:

I can type the message right away

Actual result:

Focus on input field is lost, I have to focus on the input field again

Operating system: Windows 10 14939.1066
Browser: Chrome 58.0.3029.110 (64-bit)

**Comment by zhukov** [comment]
Can't reproduce this. Tried with both Ctrl+Shift / Alt+Shift. And I see no reason for this in code. Can you try again with all the extensions disabled / on different PC?
