### ISSUE TITLE
Google static map billing error

### ISSUE THREAD

**Issue by alanbirtles** [zhukov/webogram#1415]
#1364 is fixed but I guess telegram web is now reaching the limits on the number of map loads:
![staticmap](https://cloud.githubusercontent.com/assets/8985104/26170069/f96f46ea-3b37-11e7-96f3-d2cf4d8551b1.png)

**Comment by MasterGroosha** [comment]
Clicking on the "Yandex" map opens Google Maps. Is it okay?
