### ISSUE TITLE
Support video messages/Telescope

### ISSUE THREAD

**Issue by azzimuth** [zhukov/webogram#1416]
Telegram [has introduced](https://telegram.org/blog/video-messages-and-telescope#meet-telescope) new feature - video messages. Right now we are displaying following for such messages:
![image](https://cloud.githubusercontent.com/assets/1640148/26245310/cc6f5862-3c93-11e7-9a2a-bb87daa85dea.png)
Add support for display of video messages (at least) and recording and sending such messages (preferably).

**Comment by azzimuth** [comment]
The API already includes methods: [sendMessageRecordVideoAction](https://tjhorner.com/tl-schema/constructor/sendMessageRecordVideoAction) and [sendMessageUploadVideoAction](https://tjhorner.com/tl-schema/constructor/sendMessageUploadVideoAction).

**Comment by Ryuno-Ki** [comment]
Maybe related to #1376?

**Comment by stek29** [comment]
@Ryuno-Ki Completely unrelated, except both of these issues are missing in Webogram.

**Comment by Ryuno-Ki** [comment]
My assumption was, that the underlying protocol can't be implemented in Webogram.

**Comment by stek29** [comment]
@Ryuno-Ki No, Video messages are just an update to MTProto, while Voice Calls are using completely different protocol.

**Comment by azzimuth** [comment]
@zhukov you're the best! 👍

**Comment by azzimuth** [comment]
@zhukov Is it possible to add a filter for video messages? Or include them in Videos filter.

**Comment by stek29** [comment]
@azzimuth it is possible, but I'd create a separate issue for that

**Comment by azzimuth** [comment]
Done, #1440.
