### ISSUE TITLE
Private Channel - Error code 400

### ISSUE THREAD

**Issue by ajsb85** [zhukov/webogram#1417]
Hi, @zhukov 

When I delete a channel from other client, I got this error:

```
Method: messages.getPeerDialogs
Result: {"_":"rpc_error","error_code":400,"error_message":"CHANNEL_PRIVATE"}
```

![image](https://cloud.githubusercontent.com/assets/663460/26372107/0b52cb7e-3ffd-11e7-8f1a-a6c364766d68.png)

**Comment by zhukov** [comment]
Do you leave it or remove completely?

**Comment by chagai95** [comment]
same error
