### ISSUE TITLE
Telegram Web not sending SMS, "too fast"!

### ISSUE THREAD

**Issue by Yoshimaster96** [zhukov/webogram#1419]
I tried several times to log in to Telegram Web, but I didn't receive the SMS message. I was confident the phone number is correct. Why is it doing this?

Second, after several tries, it says I was "too fast" and I should try later. Well excuse me for not being able to log in! How long do I have to wait? Is it possible for you to remove this flag from my account?

**Comment by stek29** [comment]
Ask tg support

**Comment by biagio91** [comment]
What are the error details? If you're getting 420 FLOOD_WAIT_X, that means you'll have to wait X seconds before trying again to log in to Telegram

**Comment by azzimuth** [comment]
@stek29 does it exist? I have asked so many times inside the app but never got any response...

**Comment by stek29** [comment]
@azzimuth It does :D
