### ISSUE TITLE
How use getFile while file using different DC?

### ISSUE THREAD

**Issue by Johnw12** [zhukov/webogram#1420]
Hello friends, 
Sorry if my question is unrelated, but I was getting it while analysing webogram codes and telegram API. I was reading and trying telegram API for developing to start developing, but yet I can't understand all about the API.

While I was trying to get pictures of a profile, I notice some of the pictures/files are on different datacenter, my current DC number is 1 but the picture is on DC 4. I take look at the [schema file](https://github.com/zhukov/webogram/blob/master/app/js/lib/schema.tl.txt) and tried these methods.

First I try to get a picture.  `(upload.getFile (inputFileLocation volume_id:0000000 local_id:00000 secret:000000000000000000) 0 4545)` (with real id and size), but I've get this error. 
```
ANSWER 83
{"error": "RPC_CALL_FAIL 303: FILE_MIGRATE_1", "result": "FAIL", "error_code": 71}
 ```
which means I've requested to [wrong DC](https//core.telegram.org/api/datacenter). After that I find the new method `fileLocation` and used it this way `(upload.getFile (fileLocation 1 000000 00000 secret:0000000000000000) 0 4545)` this time I didn't get anything (returned 0 bytes!) and I think I'm using it wrong.

I glad if someone can help me on this. Thank you.

**Comment by stek29** [comment]
You have to connect to another DC. Try looking through the code to see how you do it.

**Comment by Johnw12** [comment]
Hello @stek29 , Thanks for your response, 
should I use this API?
```
dcOption#2ec2a43c id:int hostname:string ip_address:string port:int = DcOption;
config#232d5905 date:int test_mode:Bool this_dc:int dc_options:Vector<DcOption> chat_size_max:int = Config;
```
Am I using it truly? `(config 1496143262 (boolFalse) 1 (dcOption 1 "" "149.154.175.50" 80) 200)` I used config (IP and Port) same as `/app/js/lib/mtproto.js` file (I didn't findout about `hostname`)

**Comment by zhukov** [comment]
yes, you should connect to another DC via another IP. Please see mtproto_wrapper.js code. 
Also this docs might help https://core.telegram.org/api/datacenter, they are a bit outdated though.
