### ISSUE TITLE
audio file cant re play untin reload page

### ISSUE THREAD

**Issue by mohammad6006** [zhukov/webogram#1421]
audio file can play one time and you cant re play it again until you reload page

**Comment by zhukov** [comment]
As far as I see it's either broken OGG files or Chrome bug (works OK in Firefox for me).

Example file.
[t_voice5089462711624925272.zip](https://github.com/zhukov/webogram/files/1109996/t_voice5089462711624925272.zip)

MP3 works fine for me everywhere.

**Comment by zhukov** [comment]
I've learned that the problem is with iOS app, notified its developer.
