### ISSUE TITLE
[Feature Request] Custom overlay images for contact thumbnail

### ISSUE THREAD

**Issue by mk-pmb** [zhukov/webogram#1426]
Would be nice if I could configure user thumbnail overlay image URLs for each contact. With "thumbnail" I mean their initials, their user photo or [my override text circle](https://github.com/zhukov/webogram/issues/1425). Webogram shall display each overlay image URL as an image tag over the contact's thumbnail and hide or remove the ones that failed to render as an image. This option will make it trivial to override NSFW user pictures with SFW ones, and at the same time offers a low-effort hook for custom indicators. Examples include:

* Refresh your contact list in a network where your telephony server is reachable and you see little phone symbols added in some contacts' entries.
* Refresh your contact list in a network where your spy drone server is reachable and you see live M-JPEG streams instead of their static photo.
* If file:// URLs are supported, or you fire up a minimalist webserver on localhost, get different user photos according to which computer you use for telegram.
* (more ideas + your ideas)

As long as you manage the layer ordering correctly, you can mix and match any of the above.

In case the effect is easy but the settings UI is too much effort, I can provide the settings by adding some file (text, JSON, …) to the webogram directory on my webserver.

**Comment by zhukov** [comment]
This is a request not for a Web App, but for the Telegram API. Please contact Telegram Support (telegram.org/support or "Ask a Question" in Settings).

**Comment by mk-pmb** [comment]
> This is a request not for a Web App, but for the Telegram API.

Not sure how you came to that conclusion. I'm still convinced an app can implement all the behavior I requested, even with the existing TG API.
Note that my request did not include synchronization of settings between clients. If someone wants the settings to be sent to the TG servers, they can request that as an additional feature. I for one would prefer to configure the overlays on each client, ideally via the webspace where I host it.
