### ISSUE TITLE
[Feature Request] Collapse media based on hash tags in message

### ISSUE THREAD

**Issue by mk-pmb** [zhukov/webogram#1427]
An extension of @Antiarchitect's [request to collapse NSFW media](https://github.com/zhukov/webogram/issues/1145).

In order to support more languages and more reasons, let's allow users to configure a list of hash tags, each with an ugliness danger score as a number (positive or negative), and an ugliness danger limit number. For all hashtags in the message that are also on the list, sum the scores, compare to limit, and if the limit is reached, set initial display state to collapsed.

Detail problems:
* Case sensitivity. (I suggest: ignore case)
* Partial sum limit rules for multiple occurrence of same hash tag. (I suggest: maybe later)
* Partial sum limit rules for multiple hash tags with same meaning. (I suggest: maybe later)
* Adapt scores based on message author, since people use hash tags differently. (I suggest: maybe later)

Feature creep:
* Add ugliness danger score for URLs, using [match patterns](https://developer.chrome.com/extensions/match_patterns).
* Support regexps.
* Support custom additional scoring functions, given as list of ECMAScript module identifiers.

**Comment by zhukov** [comment]
Duplicate #1145

**Comment by mk-pmb** [comment]
Nope, this is a distinct alternative to #1145. The difference why I split it out is that the approach requested here gives users control over what to collapse, independent of whether it's (N)SFW.
