### ISSUE TITLE
Suport telegram Voice Calls in webogram

### ISSUE THREAD

**Issue by aurium** [zhukov/webogram#1429]
The [Voice Calls](https://core.telegram.org/api/end-to-end/voice-calls) support is compatible to WebRTC? If it is not, what technologies should be implemented on the client side?

This feature depends on issue #126 as it uses _"the Diffie-Hellman key exchange, as well as the whole protocol used to create a new voice call, is quite similar to the one used for Secret Chats"_.

**Comment by stek29** [comment]
#1376
