### ISSUE TITLE
Old twitter links.

### ISSUE THREAD

**Issue by DAlperin** [zhukov/webogram#1430]
In the files:
```
app/partials/desktop/footer.html
app/partials/mobile/settings_modal.html
app/partials/mobile/changelog_modal.html
app/partials/desktop/changelog_modal.html
```
there are links to the twitter account [telegram_web](https://twitter.com/telegram_web). This account seems to have stopped being used in favor of [telegram](https://twitter.com/telegram). I don't know if this is intentional or not, but I thought I would bring it up. Should these references be switched to the new account ([telegram](https://twitter.com/telegram)), or not?

**Comment by stek29** [comment]
@DAlperin Telegram account is, well, for Telegram, and not just for Telegram Web. And telegram_web is Webogram's account, which is just inactive. So no, they're different.

**Comment by DAlperin** [comment]
Ok thanks!
