### ISSUE TITLE
[Feature Request] Use emoji.codes 

### ISSUE THREAD

**Issue by stormyqq** [zhukov/webogram#1431]
I am wondering if you can add https://emoji.codes/ instead of the existing emoji set with at least 48x48px size (on desktop), if it's not possible, can you at  least allow us to add our own emojis like stickers? thanks.

**Comment by stek29** [comment]
emoji.codes is emojione, and they've changed their license -- Webogram won't be able to use it.
Also, Webogram is part of Telegram "solution", and it has to use same emoji set as other apps.

Oh, and #571 #760

**Comment by zhukov** [comment]
Duplicate #571
