### ISSUE TITLE
Audio not working at all when inserting headphone jack during a call

### ISSUE THREAD

**Issue by maicasajusta** [zhukov/webogram#1432]
Hi, I've found a bug on my Xiaomi Mi5 global version 8.2.2.0 (android 7.0) while using telegram. 

During a call, if I plug in some headphones or earbuds (I've tried many of them) the audio on my smartphone completely crashes. That means that not only I can't hear the person I was talkin' (and viceversa), but means that audio is not working at all till the next reboot. I can't listen music, send voice message or make a phone call. And things not fix up if I unplug the earbuds, I just need to reboot in order to have audio working again.

Everything is fine if I connect my earbuds before the telegram audio call starts.

Everything is fine with audio call or some other instant messaging app, even if I connect earbuds while the conversation is already started.

**Comment by stek29** [comment]
> xiaomi
> call
> webogram

What?

**Comment by maicasajusta** [comment]
You're right stek29, I found a reddit post with a link pointing here to report telegram bugs, but now   I've realized it's not the right place. Sorry.

**Comment by stek29** [comment]
@maicasajusta The right place is Telegram in-app support or twitter.
