### ISSUE TITLE
Handle FRESH_RESET_AUTHORISATION_FORBIDDEN

### ISSUE THREAD

**Issue by wodim** [zhukov/webogram#1436]
When you've just logged in with a client (webogram in this case) and you try to terminate another session, you get this error from the server:

    Method: account.resetAuthorization
    Result: {"_":"rpc_error","error_code":400,"error_message":"FRESH_RESET_AUTHORISATION_FORBIDDEN"}

This error is not correctly handled by webogram so it just shows like this... there should be a nicer message.

**Comment by zhukov** [comment]
What do other apps show in this case?

**Comment by stek29** [comment]
@zhukov "For security reasons, you can't terminate older sessions from a device that you've just connected. Please use an earlier connection or wait for a few hours"
