### ISSUE TITLE
Can we create Electron version from webogram?

### ISSUE THREAD

**Issue by stgolem** [zhukov/webogram#1438]
Telegram native desktop client have one big issue with DPI scaling telegramdesktop/tdesktop/issues/1121 which is not the case in web version ofc.
My request is to create an Electron desktop wrapper around webogram with some little enchancements.
Any ideas? Votes? Suggestions?

I do not see this will be hard to implement, but still will take some time to learn Electron itself.

**Comment by codefuhrer** [comment]
You can create a "desktop bookmark" for web.telegram.org in Google Chrome, to make it behave like separate desktop app.

**Comment by stgolem** [comment]
Yes i can. But then we miss some important "messenger" features with that:

- Hide to tray
- Pin code protection
- Themes ;)
- Work offline (sometimes this is critical to search in history)

Others can be mentioned, this is my own list only.

**Comment by stgolem** [comment]
Oh, and also i noticed, that every Chrome "app" share the same keyboard locale.
This is really annoing, as i prefer separate locale per application.

**Comment by stek29** [comment]
@stgolem all features you listed don't exist in Webogram and they won't magically appear in Electron version.
Even more -- some features like spell checking would have to be manually handled.

**Comment by stgolem** [comment]
This is totally understandable. My point is that Electron version have it's benefits.
And i totally agree that this would be a separate project from webogram.
I just want your support with this one, as i'm planning to create a wrapper project, that will totally reuse your code.

**Comment by orschiro** [comment]
Maybe related?

https://github.com/telegramdesktop/tdesktop/issues/2410

**Comment by stgolem** [comment]
Not mine, but yes i've seen this.
Telegram Desktop team is of little help here.
We have to do our own product, and i see webogram as the main part of it.

**Comment by stek29** [comment]
So what do you want exactly? 
I mean, what's the point of this issue? Are you asking for somebody to make an electron version? Or maybe you're having some issues in webogram which are not allowing you to make an electron version?

**Comment by zhukov** [comment]
@stgolem you are more than welcome with this feature, as soon as it doesn't violate project GPL license.
I might also help with specific questions about implementation, when possible.
