### ISSUE TITLE
Upload audio from URL

### ISSUE THREAD

**Issue by orschiro** [zhukov/webogram#1441]
Instead of having to download an audio file and re-upload it to Telegram Web, I suggest a feature to directly upload/import audio from an URL.

What do others think?

**Comment by zhukov** [comment]
This is a request not for a Web App, but for the Telegram API. Please contact Telegram Support (telegram.org/support or "Ask a Question" in Settings).

Telegram API has already this feature, for some file types, e.g. OGG:
![telegram ogg from web](https://user-images.githubusercontent.com/775173/27769784-6fa8fccc-5f3a-11e7-9df0-e85f529e93fb.jpg)

**Comment by orschiro** [comment]
Just done so, thank you.

**Comment by stek29** [comment]
@zhukov Well, you can upload file from url manually using methods used by botapi.
messages.sendMedia with media: {_: 'inputMediaDocumentExternal', url: 'link-to-mp3'} works.
But I'm not sure if it's a sane thing to reveal this to UI.

```
inputMediaGifExternal#4843b0fd url:string q:string = InputMedia;
inputMediaPhotoExternal#b55f4f18 url:string caption:string = InputMedia;
inputMediaDocumentExternal#e5e9607c url:string caption:string = InputMedia;
```

**Comment by orschiro** [comment]
> But I'm not sure if it's a sane thing to reveal this to UI.

Why?

**Comment by stek29** [comment]
@orschiro Because it's not used in any app and isn't documented -- and it's behaviour can be changed at any moment.

**Comment by orschiro** [comment]
I understand. Thus it needs to become official part of the API first.

**Comment by stek29** [comment]
@orschiro it is official part of API. 
Actually, you either say "official API" haven't been updated for years, or you say that whatever is available in wild (in apps sources) is official.
The problem isn't in "official"ness, it's about this method not being used by anybody except botapi backend -- just like importBotAuthorization.

**Comment by orschiro** [comment]
> it's about this method not being used by anybody except botapi backend -- just like importBotAuthorization.

What do you suggest as a next step to implement this feature?

**Comment by stek29** [comment]
@orschiro I suggest to wait for @zhukov and his opinion about this.
