### ISSUE TITLE
Video messages not supported in web version

### ISSUE THREAD

**Issue by miticocampo** [zhukov/webogram#1442]
Hello devs,
unfortunately I have tried to force the update of the web version but I got stacked with this message for video message that I can download from my smartphone.

![image](https://user-images.githubusercontent.com/16059281/27766075-f09e631a-5ec4-11e7-86e8-4c0f1de4a3b5.png)

**Comment by zhukov** [comment]
Was fixed in #1416. To be released soon. For now you can use https://zhukov.github.io/webogram/#/im
