### ISSUE TITLE
User highlighting broken

### ISSUE THREAD

**Issue by emilfihlman** [zhukov/webogram#1443]
### Steps to reproduce
1.In group, enter @ and select user in group
2. @123456789 (Name) appears

### Expected behaviour
Like on mobile, the user should be link highlighted and not expanded to a number

### Actual behaviour
@123456789 (Name) appears

### Configuration
**Operating system:**
Windows 10 Pro x64, using Google Chrome Version 59.0.3071.115
**Version of Telegram Web:**
Version 0.5.6

**Comment by orschiro** [comment]
I am not able to reproduce your problem on Linux with Chrome 59 and version 0.5.6. It expands into the user's name and not a number.

**Comment by emilfihlman** [comment]
https://www.youtube.com/watch?v=mI4PBeDAKTA

Here's a video about it. First I try to highlight two other people in the group and they are expanded as @numbersequence (name). Then I highlight myself and it's expanded as @nick.

**Comment by emilfihlman** [comment]
It seems that only writing the message is broken, it seems to expand properly into a user highlighted link when sent.

**Comment by stek29** [comment]
It's a feature -- that's how webogram formats mentions for users with no username.

**Comment by azzimuth** [comment]
I can confirm this - as @stek29 said, for the users with no nicknames, the mention expands to a number.

**Comment by emilfihlman** [comment]
Imho it should work as it does on mobile: expand to the name of the user.

**Comment by stek29** [comment]
@emilfihlman PR is welcome, I guess. Good luck with handling formatting in text area.

**Comment by zhukov** [comment]
This is intended behavior. And yes, PRs are welcome.
