### ISSUE TITLE
Location opens in Google Maps in 0.5.7

### ISSUE THREAD

**Issue by andremacareno** [zhukov/webogram#1447]
I don't know whether it was intentionally or not, but clicking on messages with location, which now are being provided by Yandex, still opening in Google Maps.

**Comment by MasterGroosha** [comment]
I think that's intended behaviour, since Yandex is used only for static maps as shown [here](https://github.com/zhukov/webogram/commit/8bd4651f7c635951b75734f36b114846082e6744)

**Comment by zhukov** [comment]
Yep, it's intended for now.
