### ISSUE TITLE
Emoji pop-up :: not convenient way

### ISSUE THREAD

**Issue by fedorvinogradov** [zhukov/webogram#1449]
As said in the subject the way Emoji-panel pops-up is not convenient - I don't use 'em too much, but this panel is always in the way when I accidentally hover the mouse over the Emoji icon.

**Comment by zhukov** [comment]
Sorry, but:
1. This is not constructive
2. It works the same way as on TDesktop
3. Design is not handled by this repository

**Comment by fedorvinogradov** [comment]
OK
Is there a place to discuss the program design?
