### ISSUE TITLE
ask feature: Selective alerting for every msg...

### ISSUE THREAD

**Issue by gorec2005** [zhukov/webogram#1451]
Can you add this feature? (selective alerting in incoming msg from bot)
for example:
when bot send msg with option:nosound - don't play any sound
when option:sound=tada play tada
when option:sound=tutum play tutum

**Comment by orschiro** [comment]
Does Telegram Desktop or Android support this? If not, you need to suggest this feature to the Telegram.org/support team first.

**Comment by zhukov** [comment]
This is a request not for a Web App, but for the Telegram API. Please contact Telegram Support (telegram.org/support or "Ask a Question" in Settings).
