### ISSUE TITLE
Setting for disabling window-manager-override

### ISSUE THREAD

**Issue by JodliDev** [zhukov/webogram#1452]
Can you please remove the custom window again (or add a setting to disable it)? Not all window-managers have the window-menu-buttons in the typical windows-configuration or on the right side...

It may look fancy now, but it is really unpracticable if you are not on windows (or have a similar UI) :/

**Comment by zhukov** [comment]
@JodliDev hm.. I didn't remember doing anything specific for what you are describing. Can I have a screenshot?

**Comment by Peque** [comment]
![](http://i.imgur.com/bbCCIKX.png)

That is how it looks now (just like Windows, but my OS is not Windows). :blush:

**Comment by zhukov** [comment]
@Peque and what did it look before? do those buttons work?

**Comment by Peque** [comment]
@zhukov yeah, they do work.

Before they looked like this ([GNOME Shell](https://en.wikipedia.org/wiki/GNOME_Shell) style):

![](http://i.imgur.com/pwvwLMU.png)

I looks like the window header is no longer created by the window manager.

**Comment by orschiro** [comment]
How do you create the window as such? For me Telegram Web is just a tab inside Chrome that uses my native window manager borders.

![image](https://user-images.githubusercontent.com/170947/27895140-dd534e98-6210-11e7-843b-1e0cd10266e3.png)

**Comment by AndreyNikitin** [comment]
Also right mouse button menu not working (in KDE).

**Comment by Peque** [comment]
@orschiro You can install it as an extension. Go to `chrome://extensions/` (or find "Extensions" in the menu) and click on "Load unpacked extension". Then select your local `webogram/app/` folder.

If everything went well you should now be able to launch Telegram as a separate application/program in its own window. :wink:

PS: alternatively you can install it from the [Chrome web store](https://chrome.google.com/webstore/detail/telegram/clhhggbfdinjmjhajaheehoeibfljjno) if you would rather forget about source code.

**Comment by orschiro** [comment]
Thank you, Miguel.

What is the advantage of your described approach over just opening Telegram
Web in a web browser tab?

Yours,

Robert

**Comment by Peque** [comment]
@orschiro It simply opens as a separate application/window. Meaning it has its own launcher and its own distinguishable icon. So maybe it is easier for you to work with it within your window manager/desktop.

I guess it is a matter of personal preference. :blush:

**Comment by zhukov** [comment]
I couldn't find anything related to window in Chrome app apart from this change:
https://github.com/zhukov/webogram/commit/d6d84bc835ccdc34dca9bd4b479b099eeba60799#diff-58c224c849582e7f9465c40fbd361c3d
But it's just deleting fields, that are not included in docs: https://developer.chrome.com/extensions/manifest.
@Peque can you try reverting this change and see if it helps?

**Comment by Peque** [comment]
@zhukov Git bisect tells me d2cb9273b063611bdf8c4e8cae1700f58c172fbc is the first bad commit.

**Comment by JodliDev** [comment]
Thanks for your efforts! Changing that line back worked for me

Before:
![telegram2](https://user-images.githubusercontent.com/19917795/27925791-4c7b7898-6286-11e7-8df2-85e1919fb1d7.png)

After:
![telegram1](https://user-images.githubusercontent.com/19917795/27925778-43373da8-6286-11e7-9ba7-5720d57943cd.png)

**Comment by zhukov** [comment]
can someone show how it looks on windows before / after?

**Comment by Peque** [comment]
@zhukov I guess it would simply look gray instead of blue (https://github.com/zhukov/webogram/pull/1410).
