### ISSUE TITLE
Changelog received as a message disappeared after I closed the tab

### ISSUE THREAD

**Issue by anewuser** [zhukov/webogram#1453]
The Telegram bot appeared as a contact with the changelog for v0.5.7, but after I close the tab (before reading it carefully) and reopened Telegram, it was gone. 

If this is the intended behavior, please consider to make it stay in the contacts list until the user decides to remove it.

Firefox 54.0.1
Windows 10

**Comment by zhukov** [comment]
It's intended behaviour on desktop, yes. If you need to review changelog, there is link in Menu - About.

**Comment by stek29** [comment]
@zhukov But don't other Telegram apps keep it?
