### ISSUE TITLE
Warning: Unrecognized manifest key 'gcm_sender_id'

### ISSUE THREAD

**Issue by Peque** [zhukov/webogram#1454]
Since 3a283f5494ff7d6b54e3bfc2ea2c3824a2f70ba1 there is a warning when loading the extension in Chrome.

![](http://i.imgur.com/04xKU2k.png)

**Comment by Vest** [comment]
Can you please update Google Chrome to the latest version? Internet says ([StackOverflow](https://stackoverflow.com/questions/38783357/google-push-notifications-domexception-registration-failed-permission-denie) and [Chromium](https://bugs.chromium.org/p/chromium/issues/detail?id=463113)) that your browser probably doesn't support PushAPI.

What is the version of OS and the browser you are using? My Chrome (Version 60.0.3112.78 (Official Build) (64-bit), Windows 10) doesn't show this warning.

**Comment by Peque** [comment]
Google Chrome 60.0.3112.78 (Official Build) (64-bit)

Fedora 25 (GNU/Linux), fully updated.

Extension is loaded from a local path (from source, as an unpacked extension).

**Comment by adel-aa1401742** [comment]
Hello sir, i have the same issue with my chrome extension ,[here](https://stackoverflow.com/questions/49285791/unrecognized-manifest-key-gcm-sender-id-chrome-extension-linked-to-fcm) .
did you fix the problem ?

**Comment by Peque** [comment]
@adel-aa1401742 Stopped using Webogram. Telegram-desktop is what I use now. :wink:

**Comment by baeby** [comment]
Help
