### ISSUE TITLE
iOS app 4.1 - Error while trying to add a file from Google drive 

### ISSUE THREAD

**Issue by eanurag** [zhukov/webogram#1455]
![img_0027](https://user-images.githubusercontent.com/1189946/27970121-3f339c3e-636b-11e7-8684-3386dc8512f5.PNG)
![img_0028](https://user-images.githubusercontent.com/1189946/27970120-3f2f01b0-636b-11e7-9040-b242727f934a.PNG)
![img_0029](https://user-images.githubusercontent.com/1189946/27970119-3f2e4004-636b-11e7-8f10-e2d6c5a24fc1.PNG)
![img_0030](https://user-images.githubusercontent.com/1189946/27970122-3f805d58-636b-11e7-8e34-7e369bf0ac3f.PNG)

**Comment by eanurag** [comment]
More info - Testing it on iPhone 7 plus - 128 GB - iOS 10.3.2

**Comment by stek29** [comment]
@eanurag this is a wrong place for iOS app issues, please report them on Twitter or via inapp support next time
This particular issue is known btw
