### ISSUE TITLE
Audio messages playback issue

### ISSUE THREAD

**Issue by mel6nuk** [zhukov/webogram#1459]
Once the audio message is opened it cuts off 2 seconds before its ending time. No matter what is the duration of the message, it always ends 2 seconds short. 
macOS Sierra ver. 10.12.5
Chrome browser
Telegram Web Version 0.5.7

**Comment by stek29** [comment]
Would be nice if you posted your system info (browser, os, etc) and webogram version.

**Comment by mel6nuk** [comment]
Yes, sorry about that.
macOS Sierra ver. 10.12.5
Chrome browser
Telegram Web Version 0.5.7

**Comment by mel6nuk** [comment]
hey! It works!

**Comment by orschiro** [comment]
Cannot confirm on Linux, Chrome 59, TW 0.5.7.

**Comment by stek29** [comment]
Can't reproduce on latest macOS Sierra with latest stable version of Chrome

**Comment by mel6nuk** [comment]
Guess then the desktop version is the only solution for this so far.

**Comment by stek29** [comment]
Does it work in any browser (ff maybe?)
Or even Safari...

**Comment by zhukov** [comment]
Duplicate #1421

**Comment by w3lifer** [comment]
Linux Mint 18.1 Serena MATE 64-bit
Google Chrome 60.0.3112.90
Telegram Web 0.5.7

After reloading the page also.

**Comment by zhukov** [comment]
It should work on latest beta: https://zhukov.github.io/webogram/
We use javascript decoder now.
