### ISSUE TITLE
npm modules don't install

### ISSUE THREAD

**Issue by feklee** [zhukov/webogram#1460]
instead, I get:

    npm WARN Invalid version: "0.5.7.1"
    npm WARN webogram No description
    npm WARN webogram No repository field.
    npm WARN webogram No README data
    npm WARN webogram No license field.

**Comment by feklee** [comment]
Workaround: Changed the version in `package.json` from `0.5.7.1` to `0.5.7`.

I'm on:

    npm 5.2.0
    node v6.11.1

**Comment by Peque** [comment]
Yeah, I think maybe `0.5.7.1` should be bumped to `0.5.8` instead.

**Comment by feklee** [comment]
But it’s not yet `0.5.8`. Suggestion from [Semantic Versioning Specification 2.0.0][1], section 9:

“A pre-release version MAY be denoted by appending a hyphen and a series of dot separated identifiers immediately following the patch version. Identifiers MUST comprise only ASCII alphanumerics and hyphen [0-9A-Za-z-]. Identifiers MUST NOT be empty. Numeric identifiers MUST NOT include leading zeroes. Pre-release versions have a lower precedence than the associated normal version. A pre-release version indicates that the version is unstable and might not satisfy the intended compatibility requirements as denoted by its associated normal version. Examples: 1.0.0-alpha, 1.0.0-alpha.1, 1.0.0-0.3.7, 1.0.0-x.7.z.92.”

[1]: http://semver.org/spec/v2.0.0.html#spec-item-9

**Comment by GsHeri** [comment]
why does an invalid semver stop ALL dependencies from being installed??? :/
