### ISSUE TITLE
Dockerfile: Gulp not installed correctly

### ISSUE THREAD

**Issue by just-ole** [zhukov/webogram#1462]
# First attempt
## Steps taken
`git clone https://github.com/zhukov/webogram.git`
`cd webogram`
`docker build -t webogram .`
`docker run -p 8000:8000 webogram`
## Resulting output
`[18:37:17] Local gulp not found in /opt/webogram`
`[18:37:17] Try running: npm install gulp`
exit

# Second attempt
## Steps taken
`git clone https://github.com/zhukov/webogram.git`
`cd webogram`
`echo 'RUN npm install gulp' >> Dockerfile`
`docker build -t webogram .`
`docker run -p 8000:8000 webogram`
## Resulting output
`module.js:487`
`    throw err;`
`    ^`

`Error: Cannot find module 'gulp-load-plugins'`
`    at Function.Module._resolveFilename (module.js:485:15)`
`    at Function.Module._load (module.js:437:25)`
`    at Module.require (module.js:513:17)`
`    at require (internal/module.js:11:18)`
`    at Object.<anonymous> (/opt/webogram/gulpfile.js:3:9)`
`    at Module._compile (module.js:569:30)`
`    at Object.Module._extensions..js (module.js:580:10)`
`    at Module.load (module.js:503:32)`
`    at tryModuleLoad (module.js:466:12)`
`    at Function.Module._load (module.js:458:3)`

# 
I won't investigate this any further. Feel free to fix. Or not. As soon as it got into module management of webhipster-technology(tm) I lost all interest in having it running on localhost.

**Comment by GsHeri** [comment]
oh i ran into this too yesterday. had to install everything one by one.
really annoying

**Comment by guy-cohen** [comment]
Running 'npm install' should resolve the Error: Cannot find module 'gulp-load-plugins'
