### ISSUE TITLE
Allow direct replay of *.ogg and *.opus files without downloading

### ISSUE THREAD

**Issue by KopfKrieg** [zhukov/webogram#1465]
It would be nice if both audio file types could replayed within the browser, without the need to download them first and play them via external application (Similar to the ability to directly play *.mp3 files)

**Comment by orschiro** [comment]
I agree with you. MP3 files allows this up to a certain file size, correct?

**Comment by KopfKrieg** [comment]
I don't know if there's a file size limit, but yes, *.mp3 files can be replayed within the browser.

Modern browsers are capable of replaying many audio file types, so support for – at least –*.ogg shouldn't be too hard to implement.

**Comment by zhukov** [comment]
Duplicate #1421
