### ISSUE TITLE
can't mix italics and bold format in telegram

### ISSUE THREAD

**Issue by orestescm76** [zhukov/webogram#1468]
if i try to mix italics and bold it doesn't work. it should output __*test*__ but it outputs 
![image](https://user-images.githubusercontent.com/21990645/28525750-8f75841a-7085-11e7-9742-a4b26be1b7ab.png)

**Comment by stek29** [comment]
1) That screenshot is from TDesktop
2) It's an API issue, telegram doesn't allow nested formatting.
