### ISSUE TITLE
[Feature Request] Individual Emojis/Stickers list

### ISSUE THREAD

**Issue by LedZeck** [zhukov/webogram#1469]
I was wondering if could be interesting have emojis / stickers lists based on each chat usage.

Something like:

- To Mary I used to send stickers 'a', 'b' and 'c';
- To Joseph I eventually send emojis 'd', 'e' and 'f'

The idea is to use some filters to show the most used emojis / stickers with each contact.

**Comment by zhukov** [comment]
This is a request not for a Web App, but for the Telegram API. Please contact Telegram Support (telegram.org/support or "Ask a Question" in Settings).
