### ISSUE TITLE
Add markdown formatting, mainly for code

### ISSUE THREAD

**Issue by alexladerman** [zhukov/webogram#147]
Add the ability to markdown text, or at least just specify that you want certain code text to be displayed as monospace. Nicer would be to have full markdown and other rich formatting. Language detection and syntax highlighting would be super cool.

**Comment by PerfectCarl** [comment]
I would use this, also.

**Comment by profilink** [comment]
If possible, Igor, please drop a link to download is not off. Russian version Telegram for Android, 2.3.5 and 4+ versions. I would be very grateful, because I would like to use but many times in the application interface are not clear not only to me unfortunately.

Если возможно, Игорь, бросьте пожалуйста ссылку для загрузки не офф. русифицированной версии Telegram для Android, 2.3.5 и 4+ версий. Буду искренне благодарен, т.к. хотел бы пользоваться но многие моменты в интерфейсе приложения, не ясны не только мне к сожалению.

**Comment by NamPNQ** [comment]
+1

**Comment by alexgarbarev** [comment]
+1. Right now, telegram is useless for developers chats. We using Slack instead

**Comment by bb010g** [comment]
If you want to see Markdown in Telegram clients across the board, message Telegram Support. They can pass it on to the core dev team.

**Comment by PerfectCarl** [comment]
Markdown is a text based readable formatting syntax. It means that people reading your markdown on non markdown compatible telegram clients will understand your message without problem.

Heck, I even forked webogram to add this feature. 
And I didn't know angular.
My point here is that, if the webogram team wants to implement it, it's quite easy.
 And there is no need to update the telegram protocol.

**Comment by zhukov** [comment]
@alexgarbarev what code are you sharing in IM? Do you use text snippets from Slack?

**Comment by bb010g** [comment]
[**@PerfectCarl**](https://github.com/PerfectCarl) commented on [May 19, 2015, 7:25 AM PDT](https://github.com/zhukov/webogram/issues/147#issuecomment-103520708 "2015-05-19T14:25:59Z - Replied by Github Comment Enhancer"):
> Markdown is a text based readable formatting syntax. It means that people reading your markdown on non markdown compatible telegram clients will understand your message without problem.
> 
> Heck, I even forked webogram to add this feature.   
> 
> And I didn't know angular.  
> 
> My point here is that, if the webogram team wants to implement it, it's quite easy.  
> 
>  And there is no need to update the telegram protocol.

I'm not saying that the protocol needs to be updated—just that the core team should be notified so the addition can be coordinated over all the main apps.

**Comment by alexgarbarev** [comment]
@zhukov Usually we share application log text (like server responses etc) while coordinate between front-end and back-end teams. Just monospace text inside block is much better than nothing for that

**Comment by bk322** [comment]
+1. Also some subset of LaTeX math will be a great and unique feature.

**Comment by NamPNQ** [comment]
+1, This is great idea

**Comment by DenisIzmaylov** [comment]
+1

**Comment by benjamin-weiss** [comment]
+1

**Comment by lynxbyorion** [comment]
+1

**Comment by NamPNQ** [comment]
:+1:

**Comment by samarulrajt** [comment]
https://assets-cdn.github.com/images/icons/emoji/unicode/1f44d.png

**Comment by samarulrajt** [comment]
+1

**Comment by themsaid** [comment]
+1

**Comment by Ismael-VC** [comment]
+1

**Comment by antonKalinin** [comment]
+1

**Comment by bb010g** [comment]
Everyone, you can stop +1'ing. Look at the above commit. He added basic markdown formatting.

**Comment by Phisherman** [comment]
How do I use it?

**Comment by infacq** [comment]
yeah... just follow gittem.im

**Comment by eserozvataf** [comment]
+1

**Comment by Ismael-VC** [comment]
I've just tested with the web interface it works, both inline `foo(x) = :x` and block syntax

```
function foo(x)
    :x
end
```

Without syntax highlighting: 

![foo](https://cloud.githubusercontent.com/assets/4594825/10619095/65ec69b6-7739-11e5-98f8-02b17b19e064.PNG)

**Comment by Phisherman** [comment]
Doesn't work for me with your code. Do I need to activate it manually?

**Comment by Ismael-VC** [comment]
@Phisherman I haven't activated anything, it's the first time I use the web interface, just use normal markdown syntax for code snippets there.

![foo1](https://cloud.githubusercontent.com/assets/4594825/10619283/6f25c396-773a-11e5-9eea-f3693b1bfe41.PNG)

That produces the last example output.

**Comment by Phisherman** [comment]
@Ismael-VC  Now it works. I forgot the tick marks. Thanks!

**Comment by Ismael-VC** [comment]
I just tested with my android and it doesn't work.

**Comment by Walkman100** [comment]
Works for me (on https://web.telegram.org)

**Comment by Ismael-VC** [comment]
I just installed the windows client and it doesn't work either, I can't test in other platforms now.

**Comment by Walkman100** [comment]
It works only on https://web.telegram.org/...

**Comment by bb010g** [comment]
@Ismael-VC See @zhukov's original response:

[**@zhukov**](https://github.com/zhukov) commented on [Mar 12, 2014, 3:11 PM PDT](https://github.com/zhukov/webogram/issues/147#issuecomment-37475544 "2014-03-12T22:11:46Z - Replied by Github Comment Enhancer"):
> In my opinion code should be shared with services like Pastebin, Pastie, Gist etc. Syntax highlighting is not supported by other Telegram clients, not needed by most users and will make app slower.  
> 
> I think, that's a task for browser extension, not for Webogram itself.

He added this in as an extra feature due to so many requests. If you want it in Telegram apps proper, ask Telegram support.

**Comment by zhukov** [comment]
For now this is an experimental feature, supported in Web app. Other clients are not guaranteed to support it. If you like it and want to be supported in other apps, contact corresponding apps' developers (not me).

**Comment by NamPNQ** [comment]
Not support simple markdown like `*Hello*`, only support code?

**Comment by zhukov** [comment]
Yep. Just `inline code` and

```
block code
```

**Comment by Walkman100** [comment]
`inline code`
    
    ```
    block code
    ```

**Comment by zekefast** [comment]
+1

**Comment by bb010g** [comment]
@zekefast Already implemented; please read the thread.

**Comment by zekefast** [comment]
@bb010g Thanks!
