### ISSUE TITLE
Cannot read property 'out' of undefined

### ISSUE THREAD

**Issue by javansolo** [zhukov/webogram#1470]
error: show error on console "Cannot read property 'out' of undefined" when message is equal {deleted: true}
app/js/messages_manager.js on line 195

**Comment by Vest** [comment]
Can you please tell us how to reproduce the issue? The browser you are using, maybe something else?

**Comment by Stanley8** [comment]
I'm only senggel my status..help my I'd apple order SMS verfikasion gmail

**Comment by zhukov** [comment]
@javansolo ping

**Comment by javansolo** [comment]
I'm update and this problem has been resolved on commit bfd333648508598e466e40a06d65aff56936e13e

**Comment by sanyhamid** [comment]
Hi;
Unsubscribe me please
I could'nt do it by use the site

         THANKS

**Comment by Ryuno-Ki** [comment]
@sanyhamid Have you tried it [via the unsubscribe button](https://help.github.com/articles/unsubscribing-from-conversations/)?
