### ISSUE TITLE
Click links with middle mouse button in Chrome app crashes Chrome

### ISSUE THREAD

**Issue by excyruss** [zhukov/webogram#1471]
As title. Using the web Chrome app if you click on links with your middle mouse button this crashes the web app and Chrome completely.

Version details:
Windows 10 (1703, 15063.483), Chrome Version 59.0.3071.115 (Official Build) (64-bit), Telegram Web 0.5.7.1

**Comment by zhukov** [comment]
What is the expected behaviour? AFAIK, chrome app doesn't support opening in new tab.

**Comment by excyruss** [comment]
I think by habit I click the middle button to open in a new tab, but I know this is irrelevant from the chrome app but it's just habit from using tab based messaging apps.  What I would expect is it to do the same as a left click, or nothing, but at the very least not crash everything.

**Comment by Vest** [comment]
I apologize for my curiosity, I have looked through the commit, but I didn't understand why the previous version crashed the browser?

Is it Chrome's bug?

**Comment by zhukov** [comment]
@Vest Yep, it's a chrome bug. The app crashes when clicking on any <a href="..." target="_blank" rel="noopener noreferrer">..</a>

**Comment by Vest** [comment]
Thank you. My Chrome has v60, but I couldn't reproduce the issue with a small sample. Maybe there are other conditions that I should meet.

I haven't found any bug report in the Chromium project. Maybe [this](https://code.google.com/archive/p/chromiumembedded/issues/1057) one, but it is very old.

Nevertheless, I appreciate your reply to my question. Thanks, you are back again.
