### ISSUE TITLE
Can't connect to telegram web

### ISSUE THREAD

**Issue by borntoshoot600d** [zhukov/webogram#1473]
Hi there,

Can't connect telegram (on ipad) with telegram web (chrome, win 10)
When I click "Next" after typing my nr it doesn't send me the code.
Does anyone have an idea why?

Thanks!!

**Comment by stek29** [comment]
Do other apps work? What is your iOS version?

**Comment by borntoshoot600d** [comment]
Hi,

Yes, 
10.3.2

**Comment by borntoshoot600d** [comment]
Hi @zhukov, I'm using Telegram on iPad Pro, and I want to connect it to [telegram web](https://web.telegram.org/#/login)  on my computer (windows 10) with chrom (not the chrom app)
Until last month it worked well. 
actually I'm not getting anything after submitting , it's the same screen.

**Comment by zhukov** [comment]
So it's already working ok on iPad? And the problem is only with Chrome on Win 10?

Can you open javascript console and take a screenshot of it right after you submit the form?

**Comment by borntoshoot600d** [comment]
Yep, works on ipad
here:
![jt](https://user-images.githubusercontent.com/10392639/28787091-eaaa44e4-7623-11e7-9dc3-6473dd882505.JPG)

**Comment by zhukov** [comment]
@borntoshoot600d Can you open the URL https://venus.web.telegram.org/apiw1 and share a screenshot here?

**Comment by borntoshoot600d** [comment]
Hmm can't access to this page because of my internet protection...

**Comment by zhukov** [comment]
@borntoshoot600d That's the reason it's not working.

**Comment by borntoshoot600d** [comment]
Yep  I'll try to open it.
Thanks for your help!

**Comment by asgharali130** [comment]
Hi there,
Can't connect telegram on web (chrome, windows 7)
When I click "Next" after typing my no it doesn't send me the code.
Does anyone have an idea why?

Thanks!!
