### ISSUE TITLE
Error 400 APP_PUSH_APIKEY_MISSING

### ISSUE THREAD

**Issue by ProjectSky** [zhukov/webogram#1474]
* can't get any notification, i get APP_PUSH_APIKEY_MISSING error message.

* what is PUSH APIKEY?

###### log
```
Error 400 APP_PUSH_APIKEY_MISSING 5 5
Push subscribe Object {endpoint: "https://android.googleapis.com/gcm/send/e5nur_o_16…OobUzhbSv3QRNf5WJS6f_QyQxTyRMXUkxWelmTsxcQeAAonPX", keys: Object}endpoint: "https://android.googleapis.com/gcm/send/e5nur_o_16Q:APA91bFONUPu2oJxPsQuEEbEAdxFAVGn65r0HcGik-VyAKjDG4KVBSD246wi-7_wbZD008Bf3SanNeLVbRvj7V2tlL7OobUzhbSv3QRNf5WJS6f_QyQxTyRMXUkxWelmTsxcQeAAonPX"keys: Object__proto__: Object
Api call account.registerDevice
Rpc error Object {code: 400, type: "APP_PUSH_APIKEY_MISSING", description: "CODE#400 APP_PUSH_APIKEY_MISSING", originalError: Object}
```
###### image
![snipaste_20170802_184443](https://user-images.githubusercontent.com/16351827/28870410-beb71cb4-77b2-11e7-9cd6-87dcdd5601df.png)

**Comment by mazi5769** [comment]
Method: auth.sendCode
Result: {"_":"rpc_error","error_code":420,"error_message":"FLOOD_WAIT_52915"}

**Comment by mazi5769** [comment]
Result: {"_":"rpc_error","error_code":420,"error_message":"FLOOD_WAIT_52915"}

**Comment by mazi5769** [comment]
can't get any notification, i get APP_PUSH_APIKEY_MISSING error message.

    what is PUSH APIKEY?

log

Error 400 APP_PUSH_APIKEY_MISSING 5 5
Push subscribe Object {endpoint: "https://android.googleapis.com/gcm/send/e5nur_o_16…OobUzhbSv3QRNf5WJS6f_QyQxTyRMXUkxWelmTsxcQeAAonPX", keys: Object}endpoint: "https://android.googleapis.com/gcm/send/e5nur_o_16Q:APA91bFONUPu2oJxPsQuEEbEAdxFAVGn65r0HcGik-VyAKjDG4KVBSD246wi-7_wbZD008Bf3SanNeLVbRvj7V2tlL7OobUzhbSv3QRNf5WJS6f_QyQxTyRMXUkxWelmTsxcQeAAonPX"keys: Object__proto__: Object
Api call account.registerDevice
Rpc error Object {code: 400, type: "APP_PUSH_APIKEY_MISSING", description: "CODE#400 APP_PUSH

**Comment by zhukov** [comment]
Web PUSH is currently supported only for official web app (api_id = 2496).
