### ISSUE TITLE
we need more chat name symbols =)

### ISSUE THREAD

**Issue by andrewshevtsov** [zhukov/webogram#1475]
If possible, please do so that you can see the maximum of the chat name symbols (if it is long) so that you can identify the chat without going into its description.
Sorry if the request is incorrectly framed.
Thank you)
![web1](https://user-images.githubusercontent.com/22729696/28970959-fa9ec9a8-7932-11e7-8390-51729c0115e3.JPG)
![web2](https://user-images.githubusercontent.com/22729696/28970960-faa36b7a-7932-11e7-9d8c-85f2ad91ed70.JPG)

**Comment by zhukov** [comment]
Hi. How does it look on mobile / different desktop apps?

**Comment by andrewshevtsov** [comment]
@zhukov Hi, the screenshot was created from the web version on the desktop. I'm not talking about the mobile version, as there is not enough free space. Thanks for the feedback.

**Comment by stek29** [comment]
@andrewshevtsov he asked for comparison to know how it may look

**Comment by zhukov** [comment]
Anyway I don't see any flexibility in current design.
