### ISSUE TITLE
[Chrome] Text is blurred when chat panel has borders.

### ISSUE THREAD

**Issue by cherrot** [zhukov/webogram#1476]
Browser:  Google Chrome 62.0.3178.0-dev 64bit
OS: Mac OS X EI Capitan 10.11.6 (15G1510) 
( I added blockquotes before my screenshots for a clear look)

When the chat panel has no border, it looks all right. However if I **enlarge my browser size until telegram having borders around**, all text in the chat panel looks blurred (like a scaled screenshot):

> ![image](https://user-images.githubusercontent.com/964629/29123942-f8a67648-7cdc-11e7-85cb-1bf4a014334b.png)

looks fine when **it has no border, or has one side border** (There are left & right borders in 2nd screenshot):
> ![image](https://user-images.githubusercontent.com/964629/29123749-6612dc7c-7cdc-11e7-958f-3e4f435a5ffb.png)

> ![image](https://user-images.githubusercontent.com/964629/29123826-a610ebfc-7cdc-11e7-826a-3ddceb424e62.png)

When this happens, **text on menus, input area and popup toasts looks fine**:
> ![image](https://user-images.githubusercontent.com/964629/29124030-45f60b16-7cdd-11e7-92b3-1b4095b8c9a4.png)

There is no zooming on my browser or my desktop, FYI. And I suspect it is a browser related issue because this happened after I upgraded my Chrome.

**Comment by shkhkh** [comment]
...

**Comment by shkhkh** [comment]
این چیه اصلا

**Comment by cherrot** [comment]
Is there anybody who could give me some clue about this?

**Comment by zhukov** [comment]
I can't reproduce this on my mac.
And I also think it's a browser issue.

**Comment by Vest** [comment]
@zhukov, that guy is correct. If you simply download the Google Canary (Version 62.0.3185.0 (Official Build) canary (64-bit)) and go to web.telegram.org, you will see this behavior.
It disappears when the window has width less than 1010px and height less than 600px.

I see that the chat window looks fine when the following media is active:
```css
@media (max-height: 600px), (max-width: 1010px) {
```
It is up to you to decide whether it is worth fixing the nightly build of Chrome.

**Comment by cherrot** [comment]
Fixed by Google in Version 63.0.3213.3-dev (64 bit), close this issue.
