### ISSUE TITLE
possible overflow in unread messages count

### ISSUE THREAD

**Issue by sgitkene** [zhukov/webogram#1477]
![grafik](https://user-images.githubusercontent.com/11799843/29133241-21328326-7d33-11e7-9745-ba5e73a3a6ee.png)

telegram me if you need help resolving this, or need to know chats where this is ocurring. it's not easily reproduced and only happens sometimes.

right now I can only tell with certainty that this has happened before and it's in a supergroup with at least some unread messages.

**Comment by stek29** [comment]
Is that unread count shown on webogram only?

**Comment by zhukov** [comment]
@sgitkene yep, it's a known server-side issue. it happens in supergroups with more than 1M messages. Nothing webogram can do here, unfortunately.
