### ISSUE TITLE
"One of the params is missing or invalid." - recipient's display name contains special characters 

### ISSUE THREAD

**Issue by Titokhan** [zhukov/webogram#1480]
One of my contact's display name is "ᴍᶦᵈo" (without the quotes). I'm often facing the following error while messaging him via Telegram Web app:
```
Error

One of the params is missing or invalid.

Method: messages.sendMessage
Result: {"_":"rpc_error","error_code":400,"error_message":"PEER_ID_INVALID"}
```
- It started since he changes the display name.
- I can, however, contact him via the mobile client (Android) without any issue. After using the mobile client, the web app may (or may not) get pass the error.
- Using Google Chrome 60.0.3112.101 x64 Stable on Windows 10 Pro 15063.

[Screenshot is here](http://i.imgur.com/qzTqgNU.png).

**Comment by stek29** [comment]
Does this still occur?

**Comment by Titokhan** [comment]
I need to text him again from the web client to reproduce it - allow me some time.

**Comment by stek29** [comment]
@Titokhan Open console and enter `Config.Modes.debug = true`.
Wait for error, then look up API that call in console, it's parameters should be printed. Post them here.

Also, is that person in your contacts (do you have his number)?

**Comment by Titokhan** [comment]
Thanks, I'll give it a go.

No, I've added him via his Telegram username.

**Comment by zhukov** [comment]
any news here? did you reproduce and collect the log?

**Comment by Titokhan** [comment]
Thanks for getting back :)

Unfortunately I can't reproduce it yet, but I'll definitely post it whenever I'll catch it again.

**Comment by stek29** [comment]
Let's reopen the issue when (if?) you catch it

**Comment by Titokhan** [comment]
```
[235575.452] Api call account.updateStatus {offline: true} 6511517536402819388 17639 {noErrorBox: true, resultType: "Bool"}
app.js:60 [235585.483] Api call account.updateStatus {offline: false} 6511517579419770972 17645 {noErrorBox: true, resultType: "Bool"}
app.js:60 [235610.560] Api call account.updateStatus {offline: true} 6511517686955282164 17653 {noErrorBox: true, resultType: "Bool"}
app.js:60 [235610.908] Api call updates.getChannelDifference {channel: {…}, filter: {…}, pts: 131473, limit: 30} 6511517687682942356 17657 {timeout: 2147483647, resultType: "updates.ChannelDifference"}
app.js:60 [235611.696] Api call channels.getParticipants {channel: {…}, filter: {…}, offset: 0, limit: 200, hash: 1548611529} 6511517691535568564 17665 {resultType: "channels.ChannelParticipants"}
```
Screenshot: https://i.imgur.com/NVNE9aB.png

**Comment by zhukov** [comment]
I don't see error in your screenshot. Can you find it in the log? It should be a line with red text. Also it should appear in the bottom every time you try to send message.

**Comment by Titokhan** [comment]
Well, it disappears again. It's getting really hard to catch it up.

Looking at the screenshot, can you please comment  if I'm doing it properly or not?

**Comment by zhukov** [comment]
After entering `Config.Modes.debug = true` in console did you reproduce the problem and the same error message PEER_ID_INVALID appeared?
