### ISSUE TITLE
No reply keyboard

### ISSUE THREAD

**Issue by irudoy** [zhukov/webogram#1482]
There no reply keyboard in dialogs with bots.

**Comment by irudoy** [comment]
@zhukov it's at web.telegram.org now!

**Comment by zhukov** [comment]
@irudoy Please provide a screenshot.

**Comment by irudoy** [comment]
@zhukov dm

**Comment by Sovigod** [comment]
@zhukov I have same problem at web.telegram.org now
No reply keyboard in dialogs with bots
