### ISSUE TITLE
Chat shows message "User is typing..." while he is playing a game, not typing

### ISSUE THREAD

**Issue by aangairbender** [zhukov/webogram#1483]
Chat shows message "User is typing..." while he is playing a game, not typing.
From the mobile app it's displayed correctly.(Like "User plays a game")

**Comment by stek29** [comment]
#1008

**Comment by allesmi** [comment]
Is this still the case? I could neither reproduce a 'User is typing...' nor a 'User is playing a game...' message when someone played a game.

**Comment by yansovanareak** [comment]
tel:*111%23
