### ISSUE TITLE
Can't reproduce voice messages on Ubuntu Phone (Ubuntu Touch)

### ISSUE THREAD

**Issue by raistlinmaestre** [zhukov/webogram#1485]
I recently upgraded to version 0.6.0 and while I can record voice messages, I can't reproduce them anymore (I could before). I can download them but if I try to play them, nothing happens.

My phone is a bq Aquaris E5 Ubuntu Edition with Ubuntu 15.04 OTA-15.

**Comment by zhukov** [comment]
Can you check js error console when playing?
