### ISSUE TITLE
[Chrome] Text is blurry when scrolling up or down

### ISSUE THREAD

**Issue by Mizaroth** [zhukov/webogram#1486]
# [Chrome] Text is blurry when scrolling up or down

**Issue description**:
Telegram Web chat content text becomes blurry when scrolling 1 mousewheel tick up or down. This happens only if the number of rows to skip during vertical scroll is set to a value that is not a multiple of 3.
Please refer to the attached screenshots for more information.

![6](https://user-images.githubusercontent.com/24280982/30001863-dd672720-909a-11e7-9be6-e7fc34a56afa.png)
_The text is not blurry, even after scrolling up and down a few times._

![7](https://user-images.githubusercontent.com/24280982/30001862-dd66d982-909a-11e7-8fca-37f3317fb5a5.png)
_The text becomes blurry just after 1 mousewheel tick up/down._

**Environment**:
Windows 10 64-bit
Google Chrome 60.0.3112.113 64-bit

**Comment by AlexByte** [comment]
I confirm, the text is clear only with the screen with the `Pg Up` and `Pg Down`.

**Comment by zhukov** [comment]
I have no idea why this happens, PRs are welcome.
