### ISSUE TITLE
No send button?!

### ISSUE THREAD

**Issue by mhm233** [zhukov/webogram#1487]
The send button has been disappeared after the voice update.

**Comment by stek29** [comment]
Type something

**Comment by mhm233** [comment]
Found it! the problem was caused by the browser zoom. sounds webogram ain't zoom-responsive!

**Comment by zhukov** [comment]
Can you show screenshot?

**Comment by mhm233** [comment]
![1](https://user-images.githubusercontent.com/4971331/30028087-e4beec66-9198-11e7-8226-220126097542.jpg)
![2](https://user-images.githubusercontent.com/4971331/30028093-edcd1b52-9198-11e7-87f1-87ed926685e8.jpg)

**Comment by jvschiavo** [comment]
How can I get the permission to assign labels to issues? I'd like to help if that is useful.

**Comment by stek29** [comment]
@jvschiavo you can't unless you have push access.

**Comment by jvschiavo** [comment]
Can I have that push access then? I just want to help as much as I can.

**Comment by stek29** [comment]
@jvschiavo ask @zhukov (on tg?..)

**Comment by zhukov** [comment]
@mhm233 it's a feature. You don't need send button, until you type something in text field. like on mobile and TDesktop.
