### ISSUE TITLE
Recently updated the Terms of Service

### ISSUE THREAD

**Issue by F7D** [zhukov/webogram#1489]
![12345](https://user-images.githubusercontent.com/10187863/30063976-a5c29846-9265-11e7-90cc-e83f579e7900.jpg)

Hey guys . 
i have some question About that new [message from Telegram](https://t.me/durov/58)
[screenshot](https://www.dropbox.com/s/riqzaphoz6lzl2m/12345.jpg?dl=0)
i want know  need **Editing Webogram template ?!** ....or No its Okay ? :)

And Second:
 from last week i do understand can not join to some channel.. and telegram say this channel blocked... its okay. but after 2-3 hours i do understand so much channel are block but just for my country phone Number And we can very easy visit them just with all phone number for every where barring my country !!! 
    **So its not filter or block with IP its with Country Code !!!**
[Mr Pavel Durov](https://t.me/durov)  always talks about Freedom of speech And Universal Declaration of Human Rights . So why not follow? :(

**Comment by stek29** [comment]
Ask Mr Durov, please.

I didn't understand the issue -- how do updated ToS affect Webogram?

**Comment by F7D** [comment]
About my issue? or Telegram message!? 😯
maybe my english isn't well 😀or You too confused about new telegram terms like me 😀!?

**Comment by stek29** [comment]
What's wrong with official web app calling itself official?

**Comment by F7D** [comment]
i mean when we make a app id and using from webogram like = [https://T-7.ir](http://T-7.ir) 

Now must change official web to UNofficial web???

**Comment by stek29** [comment]
@F7D lol of course. Saying your app is official was never allowed, even before ToS update.

**Comment by F7D** [comment]
@stek29 😂🙌 Really!??? wtf 🤦🏻‍♂️ for me ? or for all? 😄 i have android and ios App with api id 7Chat 😀 Also web..
and telegram say no problem just need my logo change with 7Chat and from description explain about telegram 😄

**Comment by stek29** [comment]
How is this related to Webogram?
