### ISSUE TITLE
Why do ban IP address from China?

### ISSUE THREAD

**Issue by 123ysys** [zhukov/webogram#1490]
Why do ban IP address from China?

**Comment by F7D** [comment]
ip !? Ban ? where!? when ? who? China?! its order or just a idea?please let's me know more about that.. if u can explain please.. 🙂

**Comment by 123ysys** [comment]
We can change hosts to access telegram official website and many websites blocked by GFW in China such as Facebook or Google. But we can not open the web of telegram by changing hosts. We guess the telegram team decided to ban IP from China.
So I ask is it true? We can't know the truth. Thank you for help.

**Comment by zhukov** [comment]
Telegram doesn't ban anything from China. What do you mean by changing hosts? Can you show screenshot of how it looks?

**Comment by 123ysys** [comment]
@zhukov Hi.
There are some ways if we want to access blocked website in China. One of these ways is changing hosts files on PC to avoid from the dns pollution or to cross Great Fire Wall.
Here are some screenshots that may be useful to you.
![default](https://user-images.githubusercontent.com/27964272/30507371-7ce461e4-9ab6-11e7-9691-fb1b57d08911.PNG)
I can use this way to access the Telegram official website and Wikipedia. But can't still access web. Telegram,org， the official chat web.

**Comment by F7D** [comment]
@zhukov  but so why we can not join to someone channel with iran phone number (+98)... but i can join and not problems with others country phone number like +49 or +1.
its my ask... 
If my government has created this ban, ...
1- How ? i m sure Not via ip
2-and if my government can do it ban why just ban someone channel like music , photo or p-o-r-n ?
----Or if its from telegram... why all time say we dont block nothing ?
thanks for Your explan and help about that

**Comment by zhukov** [comment]
@123ysys I guess it's because requests to *.web.telegram.org are additionally encrypted (unlike FB etc) and it's detected by GFW. Anyway Telegram itself doesn't block anybody, no point here.
