### ISSUE TITLE
Implement multi-forward functionality

### ISSUE THREAD

**Issue by azzimuth** [zhukov/webogram#1492]
In Telegram one can forward a message to multiple contacts/chats by long tap and then selecting those. Implement similar multi-forward functionality in Webogram.

**Comment by zhukov** [comment]
We also have multi-forward for quick forward (click on date in channels)

**Comment by azzimuth** [comment]
I don't really understand how does it work. I tried clicking on the date but then I reply on the message, instead of forwarding it.

Could you record a demo? I guess I'm doing it wrong.

I would also like to be able to mutli-forward when I forward messages using the Forward button. Is that implemented?

**Comment by stek29** [comment]
@azzimuth It's available when clicking on date in channels

**Comment by azzimuth** [comment]
No no! I don't mean that! I app, when I want to forward to several contacts, I can long-tap on one and then I will be able to select several contacts. That works with any type of messages and conversations (peer, group or channel).

I would like to have the same functionality in Webogram.

**Comment by azzimuth** [comment]
Here is a demo https://youtu.be/H5dqtayfsEM

**Comment by zhukov** [comment]
@azzimuth I see your point. IMO will be kinda easter egg in Web version (I never discovered it in Android app until your issue). Like if you select conversation with Shift/Cmd/Ctrl button pressed, we allow multi selection, it's should be easy with current controller. Or just add a button to toggle multi selection. If you select multiple coversations, we don't jump to the chat to add comment, but will just send message right away. If you want, you can take a try with this.

**Comment by azzimuth** [comment]
@zhukov it can be implemented without a hotkey. My idea is to add checkboxes to the contacts list in the popup, just like in the message list.

**Comment by azzimuth** [comment]
@stek29 Please reopen this issue as the desired functionality not implemented.

**Comment by azzimuth** [comment]
Please review my PR for the implementation for desktop. The "Forward" popup in initial state looks as follows:
![image](https://user-images.githubusercontent.com/1640148/34567104-3439b14a-f161-11e7-8b70-b0391fbf0718.png)

Clicking on some of the contacts will start forwarding directly just like it used to work. Сlicking on some of the ticks will switch the list to multi-select mode:
![image](https://user-images.githubusercontent.com/1640148/34567239-b780fd56-f161-11e7-8092-f2274cc17811.png)

Once in multi-select mode and there is only one contact selected, clicking on that contact's tick will deselect that contact and switch the list to initial state.

**Comment by azzimuth** [comment]
@zhukov, as far as I can see the current multi-forward functionality does not work in mobile mode. Should I also skip for mobile mode?
