### ISSUE TITLE
Changelog of 0.6.0 is missing

### ISSUE THREAD

**Issue by jvschiavo** [zhukov/webogram#1493]
Changelog is missing here:
https://github.com/zhukov/webogram/blob/master/CHANGELOG.md

Since "Changelog is now received as a message" is this intended?

**Comment by blueburningcoder** [comment]
I was wondering, but I cant find any changelog between v0.5.7 and (current) v0.6.1. They simply appear to be missing, even though presumably changes have been made. @zhukov can you tell us some more about it? There seem to have happened quite massive changes just looking in the commit history.
