### ISSUE TITLE
HTML tags in input field

### ISSUE THREAD

**Issue by qttc** [zhukov/webogram#1496]
I can change view of my message using shortcuts like as Ctrl+B Ctrl+U Cltr+I

![img-2017-09-12-14-24-51](https://user-images.githubusercontent.com/12008449/30323514-288659c4-97c6-11e7-8af2-744c50b3e100.png)

**Comment by zhukov** [comment]
No you can't. But you can use simple markdown like here on GitHub. E.g.
```
**bold**
__italics__
`code`
```block of code```
```
