### ISSUE TITLE
Suggestion: allow messages and conversations to be pinned/unpinned

### ISSUE THREAD

**Issue by shentino** [zhukov/webogram#1497]
I noticed that the web version of telegram doesn't seem to support pinned messages

* No way to pin/unpin a conversation from the list on the left
* No way to pin/unpin a message in a conversation
* Pinned messages are not highlighted in the conversation

The third one has caused some consternation when using just the web version left me ignorant about a channels' rules/policies and so on.

Suggestion:

Update the web version so that pinned messages show up as pinned.  Presently I'm using the web client via Google Chrome on Gentoo Linux

Allow  messages to be pinned/unpinned in the web client

Allow conversations to be pinned/unpinned in the web client

**Comment by stek29** [comment]
#1088, #1287
