### ISSUE TITLE
GUI: separate channels and chats

### ISSUE THREAD

**Issue by ksn135** [zhukov/webogram#1498]
Now it's very easy to lost important message from someone in general list of chats and channels, because recently updated channels moves up in the list and stay on top after pinned items.
Proposal: separate channels and other chats in GUI and make it configurable in settings.

**Comment by zhukov** [comment]
This is a feature request for Telegram Platform, not for Telegram Web app. Please contact in-app support  on mobile apps (Settings - Ask a question) for this kind of requests.
