### ISSUE TITLE
Using api's TCP tunnel to receive instantly

### ISSUE THREAD

**Issue by JackPoteYes** [zhukov/webogram#1499]
The Telegram API can be used in TCP.
This way you don't need to send a request in order to update the messages.
The whole session is open through a TCP tunnel, this way any new message is sent to you instantly.

How to enable it with Webogram ?

**Comment by stek29** [comment]
Do browsers really support raw TCP tunnels not for extensions?
And why do you even need that?

**Comment by JackPoteYes** [comment]
I heard that chrome's extensions support it for a couple of years now.
I need to receive a message asap in a known time interval, where every milisecond has value.

Otherwise, what is the original method calling the update trigger ? I can't find it in the code. 
I could run it intensively in a setInterval, but I might be flood-blocked by telegram...

Thank you

**Comment by stek29** [comment]
@JackPoteYes use something more suitable for this:

Python - https://github.com/LonamiWebs/Telethon
Rust - https://github.com/JuanPotato/Vail
Rust - https://github.com/Connicpu/mtproto-rs
PHP - https://github.com/danog/MadelineProto
Kotlin - https://github.com/badoualy/kotlogram
JavaScript - https://github.com/zerobias/telegram-mtproto
C - https://github.com/vysheng/tg
C - https://bitbucket.org/vysheng/tdcli
Elixir - https://github.com/Fnux/telegram-mt-elixir
GoLang - https://github.com/shelomentsevd/mtproto

**Comment by JackPoteYes** [comment]
@stek29  Thanks v much, telegram-mtproto seems to be indeed great for that.
