### ISSUE TITLE
Error: [ngRepeat:dupes] Duplicates in a repeater are not allowed

### ISSUE THREAD

**Issue by devbazilio** [zhukov/webogram#1501]
Error: [ngRepeat:dupes] Duplicates in a repeater are not allowed. Use 'track by' expression to specify unique keys. Repeater: dialogMessage in dialogs track by dialogMessage.peerID, Duplicate key: 778899915, Duplicate value: 

` {"_":"message","pFlags":{"out":false,"unread":false},"flags":256,"id":6860,"from_id":778899915,"to_id":{"_":"peerUser","user_id":778899915},"date":1505290316,"message":"коробка","mid":6860,"peerID":778899915,"fromID":778899915,"totalEntities":[],"canBeEdited":true,"peerData":{"_":"user","pFlags":{"self":true},"flags":1147,"id":778899915,"access_hash":"67657568978978798112","first_name":"Someuser","username":"someuser","phone":"380000000000","photo":{"_":"userProfilePhoto","photo_id":"1234567890012345679","photo_small":{"_":"fileLocation","dc_id":2,"volume_id":"223032492","local_id":839247,"secret":"1111111112222222222"},"photo_big":{"_":"fileLocation","dc_id":2,"volume_id":"223032492","local_id":839249,"secret":"145680948609844227802780"}},"status":{"_":"userStatusOnline","expires":1505469905},"rPhone":"+380000000000","num":4,"rFirstName":{},"rFullName":"...","sortName":"someuser","initials":"al","sortStatus":1505469905},"peerString":"u778899915_67657568978978798112","unreadCount":0,"index":91050006149380,"pinned":false,"richMessage":{},"dateText":"Wed","draft":false}`

I replaced some private data in json

**Comment by zhukov** [comment]
Already fixed from server side.
