### ISSUE TITLE
Hyperlinks ending in a full stop don't work properly

### ISSUE THREAD

**Issue by Jeffrey-Remien** [zhukov/webogram#1504]
This is probably not trivial to solve but the app seems to interpret full stops at the end of a sentence as not being part of a hyperlink. 
While this is a wanted behavior in most cases as it would break many hyperlinks that are placed at the end of a sentence followed by a full stop, it therefore breaks those hyperlinks that do end in a full stop. This might not be an extremely common case. But maybe a fix for most occasions for a pasted hyperlink would be to include the full stop if it was part of the pasted hyperlink and not typed in afterwards

**Comment by zhukov** [comment]
@Jeffrey-Remien Can you provide an example?

**Comment by Jeffrey-Remien** [comment]
of course.
If I copy paste this hyperlink -> https://de.wikipedia.org/wiki/R.U.R. 
into the web app the described error occurs

**Comment by Jeffrey-Remien** [comment]
Haha and seemingly github does the same thing
so here is the link for you https://de.wikipedia.org/wiki/R.U.R..

**Comment by zhukov** [comment]
As I see it doesn't work properly in GitHub as well. I think it will create more problems to change the bahavior to the opposite. This way users will open `google.com/.` instead of `google.com/`. Or do you know any bulletproof solution to determine if we should include the dot into URL?

**Comment by Jeffrey-Remien** [comment]
I have an Idea that would fix most cases while maintaining those links that
are at the end of a sentence.
I think most hyperlinks are copy pasted into the message and only rarely
typed in manually.
Therefore I'd say we check text that is pasted for a hyperlink. If it
contains one and it happens to end in a full stop then we can assume the
full stop is part of the hyperlink. Only if someone manually types a full
stop after a hyperlink we shouldn't include it as we can be pretty sure it
will mark the end of the sentence.
This way we would never break a hyperlink by including a full stop that was
not intended as part of the hyperlink while being able to include it in the
case of pasted hyperlinks.

I know hyperlinks ending in full stops don't occur too often but whenever
this issue arises it is extremely hard to troubleshoot, especially for
users with no IT knowledge.
Another option would of course be to just ask the user. E.g.: Having a
flash message pop up whenever the user pasted or typed a hyperlink ending
in a full stop asking him whether the full stop belongs to the hyperlink.
This might seem weird but would at least cover all possible cases.

2017-12-04 17:33 GMT+01:00 Igor Zhukov <notifications@github.com>:

**Comment by stek29** [comment]
But links are (re)parsed on server side, and it has no info about what was pasted and what was typed.
Probably apps can override that behavior by making links with custom text (it can be done via bold for now).

**Comment by Jeffrey-Remien** [comment]
So only pure text is sent to the server? No additional data? Then I'd say
making it bold is a good Idea for now.

2017-12-04 20:21 GMT+01:00 Viktor Oreshkin <notifications@github.com>:

**Comment by stek29** [comment]
@Jeffrey-Remien even if client does send links server should just ignore them iirc

**Comment by zhukov** [comment]
I think Telegram web version should not be the first app to change current behaviour with URLs pasted. Might change this behaviour after mobile / tdesktop apps, but personally me see no point here.  It should be either changed server-side (which is tricky) or not touched at all. Btw, Twitter, FB, WA, Github don't support dots in the end.
