### ISSUE TITLE
Empty notifications

### ISSUE THREAD

**Issue by PFight** [zhukov/webogram#1505]
I receiving a lot of empty notifications like this

![image](https://user-images.githubusercontent.com/198847/30557259-5ef0baaa-9cb6-11e7-9dcc-1cbe48ec460e.png)

Steps to reproduce:
1) Work with telegram web on home computer - all notification is ok
2) Susped home computer, go to work, open telegram web on work computer
3) Work with telegram on work computer
4) Return to home, wake up home computer - got a lot of empty notifications.
5) Return to work computer - got a lot of empty notifications again

This flow of empty notifications continues for several minutes breaking access to bottom-right part of the screen. When I close them, new ones occur, so I cant interact with web content in this part of the screen.

I want to receive meaningfull notifications about new messages, but this empty stuff, wich meets me every day is very frustrating.

**Comment by stek29** [comment]
#1458

**Comment by JasonRammoray** [comment]
@stek29, please, assign #1458 to me.
I would like to investigate and fix that issue.

**Comment by stek29** [comment]
@JasonRammoray I can't do that lol, ask @zhukov :)

**Comment by JasonRammoray** [comment]
@zhukov, please, assign #1458 to me.

**Comment by stek29** [comment]
@JasonRammoray Can't you work on issue without it being assigned to you? :)

**Comment by JasonRammoray** [comment]
@stek29, I can, but it would be nice, if one person is responsible for it so that we can make sure, that two persons are not working on the same thing without knowing that.

**Comment by stek29** [comment]
@JasonRammoray So in result no persons were working on that thing :)

**Comment by JasonRammoray** [comment]
@stek29, I haven't forgot about it.
Last time, when I was working on it I had several failed unit tests even when I've launched them on clean master branch.
If you don't mind, keep this issue attached to me, because last month I can't say I had enough spare time.
