### ISSUE TITLE
Chat text is blured after scroll

### ISSUE THREAD

**Issue by kabantejay** [zhukov/webogram#1506]
text in chat is blured after i scroll, it shown on the screen in attach
 i use the latest chrome browser
![default](https://user-images.githubusercontent.com/9472648/30667960-e315f5dc-9e61-11e7-8362-904781899321.png)

**Comment by miiichael** [comment]
Isn't this a duplicate of #1486?

**Comment by AlexByte** [comment]
@miiichael yes

**Comment by zhukov** [comment]
Duplicate of #1486
