### ISSUE TITLE
How to get name of channel

### ISSUE THREAD

**Issue by damms005** [zhukov/webogram#1508]
As I do not do angularJS, I am having a real though time understanding the app. I simply want to hook to new messages, so that I can parse it to get message string and also full normal displayed name of the sender. So far, what I do is create a method in `notifyAboutMessage` of `messages_manager.js` and do `AppUsersManager.getUser(peerID)`. This works for normal users, but for channels and groups, the message object does not have these strings set.

How do I achieve the same for groups and channels (both my public and private channels)?

Thanks.

**Comment by stek29** [comment]
@damms005 why do you even use webogram in first place?

Python - https://github.com/LonamiWebs/Telethon
Rust - https://github.com/JuanPotato/Vail
Rust - https://github.com/Connicpu/mtproto-rs
PHP - https://github.com/danog/MadelineProto
Kotlin - https://github.com/badoualy/kotlogram
JavaScript - https://github.com/zerobias/telegram-mtproto
C - https://github.com/vysheng/tg, https://bitbucket.org/vysheng/tdcli
Elixir - https://gitlab.com/snippets/1664390
Elixir — https://github.com/Fnux/telegram-mt-elixir
