### ISSUE TITLE
Notification when active mute

### ISSUE THREAD

**Issue by ArtemDolor** [zhukov/webogram#1509]
Hello! I have many channels and communities and all of them on mute, but for some reason it does not work for messages that are attached, notifications still come. It seems to me that this is a bug.

**Comment by stek29** [comment]
Notifications for pinned messages are managed by whoever pins them -- they have option to just pin and pin+notify.

**Comment by zhukov** [comment]
Yes, it's a Telegram API feature

**Comment by phistuck** [comment]
Then give the user an option to notify about pinned messages. I asked for silence from that group. :|
