### ISSUE TITLE
Empty notifications in Chrome?

### ISSUE THREAD

**Issue by ThinkPadNL** [zhukov/webogram#1511]
Since a while i sometimes get empty notifications in the bottom right corner of my Chrome browser.
I have Telegram Web opened on my work PC, when i go home and open my own laptop, these notifications appear. It seems to be for messages that i received during the day.

Is there a way to stop this? Quite annoying
![image](https://user-images.githubusercontent.com/12446338/30871132-19a93dc4-a2e6-11e7-920f-0c6383350d79.png)

**Comment by JasonRammoray** [comment]
@ThinkPadNL, I guess this is closely related to #1458.
I am currently working on it.

**Comment by ThinkPadNL** [comment]
Seems identical. I will close this issue and follow that one. 
Thanks.
