### ISSUE TITLE
Update chrome webapp

### ISSUE THREAD

**Issue by figuretti** [zhukov/webogram#1513]
Hi Zhukov... I've found something strange on the Chrome Extension... for some reason, the voice recording sended from some friends with Iphone, stops exactly 2 sec before finishing... all the other audio my friends send from Android phones can be reproduced without inconvenience... just the ones sended from Iphones suffer this problem...
I've tested the hosted versions of webogram, and it works without problem... the Chrome Extension it's the one I tested and found the strange behavior... I don't know about the one for Firefox

**Comment by ewnd9** [comment]
Fixed in beta according to https://github.com/zhukov/webogram/issues/1459#issuecomment-323279819

**Comment by kudrevatykh** [comment]
@zhukov any news on this? may be you need some help to update app in chrome store?

**Comment by stek29** [comment]
I believe that Chrome WebApp is deprecated.

**Comment by YorikSar** [comment]
@stek29 Could you please elaborate? Is it official? Will Chrome App receive any updates, or will it be deleted from Store?

**Comment by Ryuno-Ki** [comment]
@stek29 IIRC, https://github.com/zhukov/webogram/issues/1376#issuecomment-291208034 was the first mention of deprecation of Chrome Apps.
