### ISSUE TITLE
Send image from clipboard no longer works in Chrome

### ISSUE THREAD

**Issue by janipewter** [zhukov/webogram#1514]
Previously, if you hit CTRL+V or right click and paste in the chat box when there was an image in the clipboard, a dialog box would pop up asking if you wished to send the image.

This no longer works, I think it stopped a month or two ago. Now, nothing happens when you hit CTRL+V or paste. It still works fine in Firefox. Haven't tested other browsers. I have attached a screenshot to show what I am talking about. I would REALLY like this functionality back in Chrome!

![tele](https://user-images.githubusercontent.com/18750515/31038568-7b15ff44-a56f-11e7-9019-b43e6eb2e3cd.png)

**Comment by azzimuth** [comment]
Works fine for me. Windows 10 x64, Chrome 61.0.3163.100 (Official Build) (64-bit) (cohort: Stable)

**Comment by janipewter** [comment]
No worries, turned out to be the Chrome extension **Don't Fuck With Paste**. Removed it and all is working again

**Comment by rodneyrod** [comment]
@janipewter Could you close the issue?
