### ISSUE TITLE
Make extentions for other web browsers also

### ISSUE THREAD

**Issue by afarsi** [zhukov/webogram#1515]
Hi.
You have a chrome app. Why you don't want to make extentions for other browsers also?
Especially, open source browsers like Firefox?
Maybe one person want to use other browsers, not chrome!

**Comment by azzimuth** [comment]
Extension? Webogram can be used on all browsers as it's an webapp.

**Comment by tulir** [comment]
Chrome apps are just websites disguised as apps. Firefox doesn't have such an app system, but you can just use the non-packaged version (read: [README.md](https://github.com/zhukov/webogram/blob/master/README.md#maintained-locations)). Also, there is a [packaged version for Firefox OS](https://marketplace.firefox.com/app/telegram/)

**Comment by afarsi** [comment]
I think making brower extentions will be usefull for those persons who are using web browsers in most cases and they are web surfecrs in most times.

**Comment by stek29** [comment]
Doesn't "open source browser" chromium support extensions?
Firefox extensions are painful, at least from what I remember.
Also, Telegram for Chrome isn't an ""extension"", it's an app, and as @tulir has pointed out, Firefox doesn't have such app system.

**Comment by zhukov** [comment]
I see no point in browser extensions for Telegram. Current Chrome App will be replaced with better support for PWA in Chrome and Chrome Apps will be deprecated.
