### ISSUE TITLE
Desktop message notifications not work.

### ISSUE THREAD

**Issue by bpGusar** [zhukov/webogram#1520]
Desktop message notifications not work. I enable notifications in settings but not work.

**Comment by stek29** [comment]
Are you talking about https://web.telegram.org?

**Comment by bpGusar** [comment]
yes

**Comment by stek29** [comment]
What exactly doesn't work? Do they work while page is open? Did you allow webogram to send notifications? Do they work for other sites?

**Comment by zhukov** [comment]
@bpGusar please answer the questions. Also try checking error console and capture a video.
