### ISSUE TITLE
Can not print "("

### ISSUE THREAD

**Issue by Sett** [zhukov/webogram#1522]
Sometimes if I tried to print left bracket "(", whole tg tab (Chrome 61) suspends. 
As a result no bracket is printing, recovering after some period - from few seconds to few minutes, emoji popup is showing. 

Can not reproduce it when I want to, but it repeated periodically, suspending is increased after last tg update.

Usual the aim is to print "(:"

**Comment by azzimuth** [comment]
Does it work with ":)"?

**Comment by Sett** [comment]
No, but "%" also breake Tg. Other special characters work normal.

**Comment by zhukov** [comment]
can't reproduce with any of my browser.. is it still actual with latest chrome (63)?
