### ISSUE TITLE
Cannot click on contact name (to display a conversation)

### ISSUE THREAD

**Issue by raphael0202** [zhukov/webogram#1524]
On web.telegram.org, with Firefox Nightly (58.0a1), a click on the contact name to display a conversation has no effect.
Some TypeError are present in the console (see the screeshot attached).

![screenshot](https://user-images.githubusercontent.com/9609923/31573982-6b330eea-b0b5-11e7-88b0-eac097e10e03.png)

**Comment by stek29** [comment]
Is this still relevant?

**Comment by glogiotatidis** [comment]
I don't see the errors anymore and clicking on the contacts works as expected.

**Comment by raphael0202** [comment]
The problem is fixed for me too.
