### ISSUE TITLE
Telegram allows deleting seen messages

### ISSUE THREAD

**Issue by woj-tek** [zhukov/webogram#1531]
### Steps to reproduce
1. Receive a message from userA
2. *open* and *view* a message from userA
3. userA removes the message indicating that it should be removed for me as well

### Expected behaviour
userA must not be able to delete a message that has already been seen (I'm ok with removal of the messages before I've seen them)

### Actual behaviour
The message is completely removed! This causes quite a concern and is mind-boggling when you would think that you have seen the massage and look through recent ones yet you can't find it!

### Configuration
**Operating system: macOS HighSierra 10.13**

I think this is an issue with telegram itself as it happens also in all tested telegram clients, see: 
* https://github.com/telegramdesktop/tdesktop/issues/4019
* https://github.com/zhukov/webogram/issues/1531
* https://github.com/overtake/TelegramSwift/issues/26

**Comment by rodneyrod** [comment]
This is expected behaviour from Telegram, it's a design choice by them and it can't really be changed clientside.
