### ISSUE TITLE
Safari wrong file names

### ISSUE THREAD

**Issue by ArtemBernatskyy** [zhukov/webogram#1536]
When downloading file web.telegram saves it under the wrong name.

Examples:
- trying to save file with "Введение в CANVAS.pdf" saves under "Unknown.pdf"
- "lab.odt" saves under 'Unknown.zip'

Steps to reproduce:
- upload some doc to web.telegram
- trying to save it

Mac OS Sierra 102.12.6

**Comment by ArtemBernatskyy** [comment]
Shit, is this repo alive ? It seems to me that nobody watches issues (

**Comment by zhukov** [comment]
It's a known issue. Unfortunately it's all we can do, Safari doesn't allow proper file naming when downloading from blob/base64.

**Comment by ArtemBernatskyy** [comment]
Can we at least use proper filename extension ? Any workaround ?

**Comment by ArtemBernatskyy** [comment]
Yeeeee, thanks guys , @zhukov u r superb )
