### ISSUE TITLE
Don't display message as forwarded if it was forwarded from private channel

### ISSUE THREAD

**Issue by zaplachinsky** [zhukov/webogram#1537]
In Telegram client for iOS, if you forward message from a private chat or channel, it is not displaying as forwarded, and nobody can see from where it is:

![img_0550](https://user-images.githubusercontent.com/20682149/32175172-c2ffc06c-bd8c-11e7-8110-a7afac50a836.PNG)
 
In webogram it is displaying as forwarded:

![fireshot capture 391 - telegram web - https___web telegram org_ _im_p nationalgeographicch](https://user-images.githubusercontent.com/20682149/32175237-0285b58e-bd8d-11e7-8e01-dd844e2d4ba7.png)

And we get an error on click to this channel's name:

![fireshot capture 389 - telegram web - https___web telegram org_ _im_p nationalgeographicch](https://user-images.githubusercontent.com/20682149/32175256-12378c8c-bd8d-11e7-9d63-27a3d2452ee7.png)

**Comment by stek29** [comment]
That's Telegram for iOS bug, since message is actually forwarded.

**Comment by zaplachinsky** [comment]
@stek29 Yes, you're 100% right.
