### ISSUE TITLE
Error: Constructor not found

### ISSUE THREAD

**Issue by irudoy** [zhukov/webogram#1543]
```
app.js:13 Error: Constructor not found: 3504867164 328784060 1992907048
    at TLDeserialization.fetchObject (app.js:57)
    at app.js:58
    at o (app.js:14)
    at app.js:14
    at m.$eval (app.js:14)
    at m.$digest (app.js:14)
    at m.$apply (app.js:14)
    at l (app.js:13)
    at b (app.js:13)
    at XMLHttpRequest.M.onload (app.js:13)
```

Can't login at all. Just freezing at `Generating keys...`.

**Comment by stek29** [comment]
Are you using https://web.telegram.org?
This is really weird, since constructor 3504867164 (aka d0e8075c) was never used by tg.
So it's likely read something wrong right before that.
I'm unable to reproduce it.
If it still happens, please set a breakpoint on that throw, and look at local variables. One of them would contain full "path" to field currently being read.

**Comment by irudoy** [comment]
Yes, I'm using web.telegram.org

```
deserializer.fetchObject("Server_DH_Params", "RESPONSE");
...
var constructor = this.readInt(field ("RESPONSE") + '[id]');
constructor === 3504867164
```

**Comment by l1bbcsg** [comment]
I am having this issue for a couple of days as well, but only on current Chrome Canary (`64.0.3262.0` at the time of writing) on Mac OS. I'm having no problems on Chrome 61.

I had telegram tab open for pretty much forever and suddenly it just stopped working - it rendered a blank template with no chats/messages. Reload did not help and I tried clearing application data (cookies, local storage, dbs, etc...) which brought me to login page and now I'm experiencing exactly the same problem as described.

Here's the console output right after page load (note that numbers are different from @irudoy's, mine are: `3504867164 1309788097 3259107725`)
![image](https://user-images.githubusercontent.com/1044684/32592652-4e363388-c557-11e7-9e5f-4a054ae5a576.png)

**Comment by l1bbcsg** [comment]
>If it still happens, please set a breakpoint on that throw, and look at local variables. One of them would contain full "path" to field currently being read.

@stek29 The code is minimized, it's not exactly clear which one is the `path` you're looking for. This is what local variables look like when this exception is thrown:

![image](https://user-images.githubusercontent.com/1044684/32593088-225b5d04-c559-11e7-8cb9-956c2ef5dd58.png)

**Comment by irudoy** [comment]
My Chrome version is `64.0.3260.2 dev (macOS 10.13.1)`.
I understand that this is unstable build, but I believe that we need to understand the cause of the problem before the stable channel is updated to 64.

**Comment by ZxBing0066** [comment]
I also got this in google chrome canary(64.0.3262.0 Mac), but in my chrome(62.0.3202.89 ), it's OK, maybe this is an issue due to chrome canary?

**Comment by jekader** [comment]
I also see this on several machines running Chrome dev 64.0.3260.2 on Linux. Maybe worth testing against latest chromium and reporting it as a regression if that's the only browser that doesn't work.

**Comment by stek29** [comment]
I can confirm it's some really weird bug in chrome, I'd call it "Schrodinger's typed array" lol
I'm investigating it :|)

**Comment by mbc07** [comment]
AFAICT it started in Chrome 63. I'm using releases from the dev channel (currently at 64.0.3269.3) and experiencing the same issue...

**Comment by ZxBing0066** [comment]
I have update my chrome canary to  64.0.3271.0 and this problem was resolved

**Comment by stek29** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=784835 :)
