### ISSUE TITLE
Зависает при попытке посмотреть канал @nopaywall

### ISSUE THREAD

**Issue by zmkdsh** [zhukov/webogram#1544]
При попытке зайти на канал @nopaywall вкладка зависает.

Chrome Версия 62.0.3202.75 (Официальная сборка), (32 бит), windows 10

**Comment by stek29** [comment]
В консоли что?

**Comment by zmkdsh** [comment]
[55.585] Api call channels.getFullChannel
[Violation] Forced reflow while executing JavaScript took 47ms
app.js:58 [55.769] Api call messages.getHistory
app.js:58 [55.787] Api call upload.getFile
app.js:59 [56.079] Rpc response upload.file
app.js:58 [56.130] Api call upload.getFile
app.js:59 [56.211] Rpc response messages.chatFull
app.js:59 [56.284] Rpc response messages.channelMessages

**Comment by zmkdsh** [comment]
Так же зависает в Firefox

**Comment by zhukov** [comment]
Can't reproduce. Can you try different network / account? And may be record a video.
