### ISSUE TITLE
google chrome web app - nacl helper 84.1 GB virtual memory

### ISSUE THREAD

**Issue by dumanlipars** [zhukov/webogram#1545]
hello, 

i'm using telegram chrome web application and while telegram web application is open, then google chrome's nacl helper module uses 84.1 gb virtual memory (i dont know what it means or how it's possible btw )

please check the red text in the screenshot
![screenshot from 2017-11-10 16-41-02](https://user-images.githubusercontent.com/33411869/32660957-0d31a248-c636-11e7-99a2-f54c3f0d0865.png)

**reproduce:**
install telegram for chrome web application,
run it,
install htop in ubuntu if you don't have,
run htop to check active process with their details,
then you will see this detail.

it's not only for me. after some lags, i checked on internet this issue. here is the same problem for another person:
https://bugs.chromium.org/p/chromium/issues/detail?id=544608#c26

**Comment by tptrixtop** [comment]
Hello,

As i know virtual memory that is not real memory, that is just what application wants to allocate for future usage

**Comment by zhukov** [comment]
@dumanlipars  From the link you provided I suppose the problem is not unique to Telegram Web, so I think it's related to NaCl itself. The code we are using in the library is pretty straightforward, taken from OpenSSL:
https://github.com/zhukov/webogram/tree/master/app/nacl
