### ISSUE TITLE
Unsuccessfully inserts a link

### ISSUE THREAD

**Issue by splincode** [zhukov/webogram#1546]
I inserted this text:

```
Овчинников Павел Евгеньевич:
https://github.com/stankin
Сейчас этот ресурс - просто моя личная инициатива.

.... (more text)

Ограничивать в правах доступа студента, шлифующего как раз навыки Руководителя, выглядит как-то не совсем логично. Другое дело, что все наши репозитории имеют смысл "песочницы" и любое их разрушение в общем-то не будет критичным.
```

As a result, the text was cut, and it was not correctly inserted

![image](https://user-images.githubusercontent.com/12021443/32770835-feb05dfa-c931-11e7-843c-8a392b2765df.png)

**Comment by stek29** [comment]
That's likely because of message length limit and has nothing to do with links.
