### ISSUE TITLE
Rename own chat to "Saved Messages"

### ISSUE THREAD

**Issue by azzimuth** [zhukov/webogram#1548]
In version 4.5 the own chat (the one that used to be initiated on the mobile app by tapping on the cloud icon) has been renamed to "Saved Messages".

Rename own chat to "Saved Messages" in Webogram to align with the changes in the mobile app.

**Comment by mohamaamin** [comment]
Hi recovery chat 2month ago  tnks

**Comment by azzimuth** [comment]
@zhukov who has the original versions of icon files General.png and General_2x.png? I need to add an icon for saved messages.

**Comment by zhukov** [comment]
@azzimuth Original is in the repo. Just these PNG versions.

**Comment by azzimuth** [comment]
OK. I will try to add it myself.

**Comment by zhukov** [comment]
@azzimuth thanks for the effort, unlucky that we did job twice. Next time please let me know here if you are implementing some of features.

**Comment by azzimuth** [comment]
@zhukov no problem! I liked working on this :) 
Actually I thought that you would understand that I was working on this because I asked about the PNG files.

**Comment by azzimuth** [comment]
@zhukov could you even add new option to menu for Saved Messages (both desktop and mobile) as I did in my PR?

**Comment by zhukov** [comment]
@azzimuth Yeah, I will, waiting for icons

**Comment by azzimuth** [comment]
👍

**Comment by azzimuth** [comment]
@zhukov any progress on this?
