### ISSUE TITLE
Problems with fonts while scrolling in chromium-based browsers

### ISSUE THREAD

**Issue by dtitbd** [zhukov/webogram#1549]
При скроллинге мылятся шрифты.
![19438354](https://user-images.githubusercontent.com/17032471/32942612-5c8e3bce-cbab-11e7-860b-8f73143946ca.gif)
Cent Browser Версия 3.0.4.27 (Официальная сборка), (32 бит) (Chromium 62.0.3202.89)
Google Chrome Версия 62.0.3202.94 (Официальная сборка), (64 бит)
Хром сносил полностью вместе с данными, перезагружал ПК, устанавливал, сразу после запуска заходил в Телеграм (не подключая акк, не меняя ничего), проблема все равно есть.
Вероятно, проблема из-за этого:
![screenshot_2](https://user-images.githubusercontent.com/17032471/32942795-e3908e06-cbab-11e7-848e-299d18993eb5.png)

**Comment by zhukov** [comment]
Duplicate of #1486
