### ISSUE TITLE
links with custom InstantView template not opened

### ISSUE THREAD

**Issue by AlexMercier** [zhukov/webogram#1553]
I have own custom tamplate for instant view on my channel, and **webogram** got error while trying to open this link
example:
`https://t.me/iv?rhash=1fba7926fbe4db&url=https://chrdk.ru/sci/Unusual_Brains`
source post `https://t.me/cherdaq/504`
error when click to link:
```
Method: contacts.resolveUsername
Result: {"_":"rpc_error","error_code":400,"error_message":"USERNAME_INVALID"}
```

only clicking on preview title open this link.

webogram version: Version 0.6.0

**Comment by alexbagirov** [comment]
+1. I'm facing the same issue.
