### ISSUE TITLE
Can't send voice messages

### ISSUE THREAD

**Issue by Discostu36** [zhukov/webogram#1555]
I can't send voice messages with Telegram Web on https://web.telegram.org/ . If I click  or click and hold the microphone button, nothing happens at all. 

Firefox 57.0 (64-Bit)
Microsoft Windows 10 Home Build 15063

**Comment by zhukov** [comment]
What do you see in javascript error console? Can you check site settings, if you have declined record permission for web.telegram.org domain?

**Comment by Discostu36** [comment]
Can't reproduce the problem right now. I will close this issue. If it happens again, I will reopen and provide more information.
