### ISSUE TITLE
Stucked in "Generating Key"

### ISSUE THREAD

**Issue by JeremiahHsu** [zhukov/webogram#1558]
Occured in about 2 weeks ago since I wipe out all cookie from my Chromebook.
Implemented a Powerwash changed nothing.
Currently on Build 64.0.3270.0 dev ChromeOS.

**Comment by irudoy** [comment]
Possibly duplicate of #1543

**Comment by zhukov** [comment]
What do you see in Javascript error console?

**Comment by stek29** [comment]
This version of Chrome is affected by bug causing #1543.
Feel free to report here again if the issue still occurs on latest version of Chrome.
