### ISSUE TITLE
not all resources are properly cached

### ISSUE THREAD

**Issue by TitanNano** [zhukov/webogram#1560]
![screen shot 2017-12-04 at 21 06 39](https://user-images.githubusercontent.com/4500858/33573885-8697a646-d937-11e7-83fd-b53e14e0209d.png)

Mainly the `app.js` file appears not to be properly cached.
Also, anything with a hash, like `https://web.telegram/#/im` is not handled by the service worker cache.

**Comment by zhukov** [comment]
<img width="596" alt="screen shot 2017-12-05 at 15 10 54" src="https://user-images.githubusercontent.com/775173/33604311-e7716ef6-d9ce-11e7-9417-502cfdece588.png">
Can't reproduce in Chrome. Can reproduce in Firefox though. Any known way to fix?

**Comment by TitanNano** [comment]
It doesn't work in chrome either:
![screen shot 2017-12-05 at 21 36 13](https://user-images.githubusercontent.com/4500858/33629469-6f14a5aa-da04-11e7-9878-587c18829eeb.png)

`from disk cache` is not the same as `from ServiceWorker`.
![screen shot 2017-12-05 at 21 37 35](https://user-images.githubusercontent.com/4500858/33629515-a13cf9ba-da04-11e7-9cd9-d797d21e1147.png)

**Comment by TitanNano** [comment]
what's the sw-precache config?

**Comment by TitanNano** [comment]
output when I run `gulp generate-service-worker`:

```
[21:48:18] Skipping static resource "./dist/js/app.js" (2.57 MB) - max size is 2.1 MB
```

**Comment by TitanNano** [comment]
Acording to the sw-precache README max cache size can be set.
It would be also better to set a `navigateFallback`.

```JS
{
    "maximumFileSizeToCacheInBytes": "3004152" // about 3MB, default is "2097152" 2MB,
    "navigateFallback": "./dist/index.html"
}
```

**Comment by zhukov** [comment]
Would you provide PR here?

**Comment by TitanNano** [comment]
PR is #1562
