### ISSUE TITLE
Convert link to downloadable format?

### ISSUE THREAD

**Issue by orschiro** [zhukov/webogram#1563]
Dear all, 

I am wondering whether in the web interface we can convert paste URLs (e.g. .mp3) into a downloadable button. 

See below example:

![image](https://user-images.githubusercontent.com/170947/33793610-7f9ba97e-dcba-11e7-9704-6ac7a0f2c4ef.png)

**Comment by stek29** [comment]
It's done by server and afaik there's no way to do that (except using bot methods  or sending link and hoping to see a preview)
