### ISSUE TITLE
Unused variables or property

### ISSUE THREAD

**Issue by javansolo** [zhukov/webogram#1564]
1. app/js/lib/mtproto.js on line 675
           this.iii = iii++
2. app/js/lib/mtproto.js on line 679
          this.authKeyBuffer = convertToArrayBuffer(authKey)
3. app/js/lib/mtproto.js on line 690
          this.currentRequests = 0
4. app/js/lib/mtproto.js on line 694
          this.clientMessages = []
5. app/js/lib/mtproto.js on line 701
          this.pendingTimeouts = []
please remove!

**Comment by zhukov** [comment]
Easy thing, why don't you just provide PR if you already are diving into the code?

**Comment by javansolo** [comment]
and
`var iii = 0`
app/js/lib/mtproto.js on line 656

**Comment by stek29** [comment]
._.
