### ISSUE TITLE
 Lost focus in the conversation text field

### ISSUE THREAD

**Issue by ZiTAL** [zhukov/webogram#1566]
The mouse focus is in the text field, but I can't write in, changing focus and restoring it solves the problem, but it's not comfortable.

Navigator: Firefox 59.0a1 (2017-12-10) (64-bit)

**Comment by zhukov** [comment]
Do you know a way to reproduce?

**Comment by ZiTAL** [comment]
Don't worry, I think is due to experimental Firefox

**Comment by cbarnesc** [comment]
I am somehow subscribed to this thread.

It might be through an email address (or wildcard one) that forwards to this one.

Is there any way to figure out why I’m receiving these?

I’d like to be removed from the distro.

Dan

**Comment by ZiTAL** [comment]
In the right side you have the "Unsubscribe" button

**Comment by ZiTAL** [comment]
![ezgif-3-6d4b787685](https://user-images.githubusercontent.com/2283548/33929077-745fca8c-dfe8-11e7-820c-5935c6c72d8c.gif)

Can't write in the field, change the conversation, come back to the original conversation and still can't write

**Comment by zhukov** [comment]
Can you reproduce in stable Fx version? Did you try to disable all extensions?

**Comment by ZiTAL** [comment]
No, I will try it

**Comment by zhukov** [comment]
Any news here?

**Comment by ZiTAL** [comment]
Still not working but now I'm using the desktop app.

**Comment by ZiTAL** [comment]
![pantaila-argazkia - or 2018 eko urtren 05a - 19 06 23](https://user-images.githubusercontent.com/2283548/34622012-abd96eb2-f24b-11e7-844a-2d3ca01548ac.png)

The icon goes to this place instead of chat WTF

**Comment by zhukov** [comment]
I asked to reproduce in stable version, without extensions etc, that's what I'm asking.

**Comment by ZiTAL** [comment]
No problem in debian gnu/linux FF ESR 52.5.2

**Comment by ZiTAL** [comment]
No problem in debian gnu/linux FF 57.0.4 (Latest stable version) closing issue

**Comment by nikita2206** [comment]
Filed a bug report in FF: https://bugzilla.mozilla.org/show_bug.cgi?id=1432132
I'm still not sure if this is entirely FF's fault, though it's a fact that it behaves differently than all other browsers or older versions of Firefox.
