### ISSUE TITLE
Better quotes

### ISSUE THREAD

**Issue by BanterFace** [zhukov/webogram#1567]
There is some suggestions for quotes-settings, that, I think, would be useful. These paragraphs are valid for desktop version too. 
1.  Full\one-string\n-string quote appearance. 
     Sometimes (always, actually) one string isn't enough, so you'll have to move to this message by link in quote just for a few words.
2. Less differences between 'forward' and 'reply'.
     I think, reply — it's just a forward to this dialog. Styles should be same, reply should support multiple selection, replys should be sendable without message text.

**Comment by zhukov** [comment]
Thanks for the suggestions, but replies are currently consistent across all the platforms and web version is just supporting the same format. You can forward your suggestions to "Help - Ask a question" in mobile apps or in Twitter twitter.com/telegram
