### ISSUE TITLE
Обойти блокировку на работе

### ISSUE THREAD

**Issue by slonnik** [zhukov/webogram#1571]
Я поднял инстанс на EC2 http://ec2-18-217-229-235.us-east-2.compute.amazonaws.com/app/index.html#/login  на работе я могу увидеть страницу входа, но когда пытаюсь зарегистрировать номер у меня не генирриуется ключ. Очевидно из-за блокировки, это как-то можно разрешить ?

**Comment by zhukov** [comment]
Что отобржается в консоли ошибок Javascript в момент с проблемами?

**Comment by stek29** [comment]
Попробуйте вот это еще поднять 
https://github.com/zhukov/webogram/blob/74da08df7bd741d6e0d68b081a6ff975ba92d1f2/app/js/lib/mtproto.js#L11
