### ISSUE TITLE
Pinning a conversation in a mobile app does not trigger an update in Webogram

### ISSUE THREAD

**Issue by azzimuth** [zhukov/webogram#1580]
Steps to reproduce:
1. Open the mobile app and Webogram (with the same account);
2. Pin a conversation in the mobile app;
3. The conversation **is not** pinned in Webogram;
4. Refresh Weborgram. Now the conversation **is** pinned.

Interesting that the unpinning works as intended.

**Comment by stek29** [comment]
I guess a proper "pinned" update handling is needed. Closing in favor of #1287.
