### ISSUE TITLE
Autocomplete of Usernames stopped working on chrome

### ISSUE THREAD

**Issue by doktormerlin** [zhukov/webogram#1584]
With the newest update, the username autocompletion stopped working. Entering @ results in nothing popping up

![image](https://user-images.githubusercontent.com/18120083/34467983-02ad8a52-eeff-11e7-974d-377620dcefbf.png)

**Comment by reza39** [comment]
مشکل کجاست

در تاریخ ۱ ژانویهٔ ۲۰۱۸ ۱۶:۵۱، "Merlin Dienst" <notifications@github.com>
نوشت:

**Comment by azzimuth** [comment]
@reza39 please write on English so that everyone understands you.

**Comment by azzimuth** [comment]
@doktormerlin I tried just now and it is working. Chrome version 63.0.3239.84 @Windows 10 x64.

Please let us know the browser and its version you're using.

**Comment by doktormerlin** [comment]
@azzimuth I am also in Chrome on Windows 10 x64, can't tell you the version sadly since I'm not at home anymore.

However I just tried it on my mobile phone and there is no autocomplete working there as well. Android v8.0.0 in Chrome 63.0.3239.111

**Comment by doktormerlin** [comment]
Tried Firefox 57.0.1 on my phone and the issue exists there aswell

**Comment by doktormerlin** [comment]
Back at home, Google Chrome has Version 63.0.3239.84, so the same one as tested by you.

I tried it on four different browser, on three devices with two Accounts so far, it is not working on any of these.

Autocomplete for Botcommands works
