### ISSUE TITLE
Up arrow (edit message) should be optimistic

### ISSUE THREAD

**Issue by jjant** [zhukov/webogram#1586]
When I send a message, and I immediately press the up arrow, to edit that message I just , I get whatever message I sent before.

This is likely because the message I'm trying to edit was not yet sent, but in this case, it is best UI to be optimistic and treat it as sent (letting the user edit it).

**Comment by stek29** [comment]
Sadly other apps don't support this too :(

**Comment by stek29** [comment]
@zhukov It might be put to queue, and once message gets an ID it editMessage can be called on it

**Comment by jjant** [comment]
@stek29 Exactly, this can be managed entirely in the frontend, let the user edit whatever he wants, just delay the request until you have the message id.
