### ISSUE TITLE
Autocomplete doesn't work.

### ISSUE THREAD

**Issue by MiNGRotten** [zhukov/webogram#1587]
Autocomplete (@ blahblah) in chats not works.

**Comment by MiNGRotten** [comment]
![image](https://user-images.githubusercontent.com/10127549/34525194-d33cca0c-f0e9-11e7-874f-6e375cc0f7cb.png)

**Comment by azzimuth** [comment]
Works fine by me. Make sure that you're running the latest code. There was a recent fix for #1584.
