### ISSUE TITLE
Webogram closing in IE in some cases [Windows RT]

### ISSUE THREAD

**Issue by hooddy** [zhukov/webogram#1589]
Не могу воспроизвести и понять причину, но вылетает вебограм на ИЕ. Все обновления стоят. Другой браузер не вариант, ибо на ВинРТ. Как скинуть лог?
![01 2](https://user-images.githubusercontent.com/6899176/34649611-a597e870-f3aa-11e7-8537-f6943bbf9f16.png)

**Comment by hooddy** [comment]
Кстати, вебограм завернутый в метро клиент LightTelegram не сыпется. Хотя производительность не очень, подвисает. Но выбора на ВинРТ вообще нет.

**Comment by sbr50** [comment]
Hi

**Comment by havaljaan** [comment]
Hello
در تاریخ ۷ ژانویهٔ ۲۰۱۸ ۲۲:۰۰، "sbr50" <notifications@github.com> نوشت:

**Comment by hooddy** [comment]
Жесть какая-то... Вылетет постоянно. Добавьте в настройки отключение стикеров и всей это трехомундии. Чтобы смайлики отображались, а стикеры не гурзились или хотя бы заменялись ими. Тоже хочется в настройках и для медиа - на десткопе и в мобильном есть опции, здесь нет. Чтобы контент не грузился без нажатия на него. Смею предполагать это избавит от кучи лагов.

**Comment by zhukov** [comment]
А если на том же железе, но с нормального браузера?

**Comment by stek29** [comment]
@zhukov А на RE нет нормальных браузеров :)

**Comment by hooddy** [comment]
Так и есть - на ВинРТ только ИЕ. Не понимаю причину лагов и вылетов. ЛайтТелеграм тоже глючит. Альтернативы нет. Хотелось бы облегченный вебограм с опциями для отключения аатозагрузки всего - стикеров, контента и т.п. Просто текст, смайлики и ссылки.

**Comment by hooddy** [comment]
При открытии чата просто с легкой перепиской все вроде нормально. Но стоит выбрать канал с контентом - все. ИЕ валится, лайьелеграм также.

**Comment by azzimuth** [comment]
Добавьте в название тикета, что вылетает на Windows RT. А то получается что вылетает на любом IE.

**Comment by hooddy** [comment]
Либо что-то изменилось - прилетело обновление - либо что-то я в настройках ИЕ поменял (хотя на первый взгляд ничего такого). Поковырялся в канала - тормозит, но не вылетает. Я не знаю, завести новый тикет с просьой на облегченную версию или тут оставить? Я про настройки в клиенте для отключения предзагрузки контента и стикеров.

**Comment by zhukov** [comment]
Нужно максимально упростить тест-кейс, от чего валится. очистить диалог (например saved messages), увидеть, что ничего не валится. затем методом перебора отправлять с другого клиента в этот диалог разные стикеры и дождаться того сообщения, из-за которого падает клиент (после этого хорошо бы еще раз почистить диалог и снова отправить уже только одно это сообщение, чтобы быть уверенным, что дело точно в нем). это сообщение переслать мне на t.me/izhukov. тогда смогу оперативно поправить.

**Comment by hooddy** [comment]
Я пока не могу привести стабильный кейс. Валится при различных вариантах. То валится, то нет в таком же случае. Что необходимо обязательно для работы? Джава скрипты я уже понял. Что-то еще? Я пытаюсь в ИЕ поотключать всякие ненужные опции типа анимации гифок, проигрывания медиа... Кстати, о проигрывании медиа.... Надо проверить.

Мне бы хотелось ультра лайт телеграм без блекджека и шлюх, да, т.е. как я уже не раз написал, без предзагрузки вообще всего. И без вских фич типа "набирает текст". Ладно, я на тухлом ноуте это мучаю, но как это на мобильном работает, насколько адекватно в плане быстродействия, я не уверен. Думаю, на том же Тизене удобнее лайт версия. Но я понимаю, что это уже совсем не приоритет.

**Comment by Ryuno-Ki** [comment]
And non-Russian users have no idea what that was all about …

**Comment by azzimuth** [comment]
@Ryuno-Ki https://translate.googleusercontent.com/translate_c?depth=1&hl=en&ie=UTF8&prev=_t&rurl=translate.google.com&sl=auto&sp=nmt4&tl=en&u=https://github.com/zhukov/webogram/issues/1589&usg=ALkJrhh53IJDor_lqzWmuJiDy6qKbGViJw

**Comment by stek29** [comment]
@Ryuno-Ki tl;dr: Windows RT is shit, IE sucks, it can't handle webogram so maybe lighter version would help.
