### ISSUE TITLE
Not updated preview

### ISSUE THREAD

**Issue by splincode** [zhukov/webogram#1590]
When I use the link
https://github.com/Angular-RU/

![image](https://user-images.githubusercontent.com/12021443/34677251-90b3cad6-f4a0-11e7-9483-7c3614758982.png)

However, for a long time already changed the community logo, is it a cache problem?

**Comment by stek29** [comment]
@splincode caching is server-side. use https://t.me/webpagebot

**Comment by splincode** [comment]
the link is the same

![image](https://user-images.githubusercontent.com/12021443/34682618-7f9b8e72-f4b0-11e7-98b8-56facfa90e76.png)
