### ISSUE TITLE
"This site has been updated in the background" notification accompanies every PUSH notification in Chrome

### ISSUE THREAD

**Issue by foxmajik** [zhukov/webogram#1593]
Every time I get a notificaition in Chrome from Webogram there's a secondary notification:

> This site has been updated in the background.

Based on my research, typically this is because of one of three bugs:

1. You're not showing a notification in response to the push message. Every time you receive a push message on the device, when you finish handling the event a notification must be left visible on the device. This is due to subscribing with the userVisibleOnly:
true option (although note this is not optional, and not setting it will cause the subscription to fail.

2. You're not calling event.waitUntil() in response to handling the event. A promise should be passed into this function to indicate to the browser that it should wait for the promise to resolve before checking whether a notification is left showing.

3. For some reason you're resolving the promise passed to event.waitUntil before a notification has been shown. Note that self.registration.showNotification is a promise and async so you should be sure it has resolved before the promise passed to event.waitUntil resolves.

**Comment by zhukov** [comment]
Well, we do our best to comply with all 3. Does it reproduce easily for you? Can you record a good quality video demo with a shot of console in the end? Lines with `[SW] push`and around them  are the most interesting ones.

**Comment by zhukov** [comment]
In case you can only reproduce it without any tab open, please open `chrome://serviceworker-internals/` URL in separate tab and click "Inspect" near web.telegram.org

**Comment by zhukov** [comment]
I think I was able to reproduce this at last, needed to swtich from banners to alert notifications on macOS. Possibly fix is coming.

**Comment by foxmajik** [comment]
I'm afraid recording a video of it would be a violation of my privacy and that would defeat the purpose of using Telegram.

Thanks for looking into it and going the extra mile to reproduce it.

**Comment by mjbnz** [comment]
This is occuring for me too. The following looked promising:

[https://stackoverflow.com/questions/31108699/chrome-push-notification-this-site-has-been-updated-in-the-background](https://stackoverflow.com/questions/31108699/chrome-push-notification-this-site-has-been-updated-in-the-background)
