### ISSUE TITLE
[Bots] Plain text is returned instead of entity when an inline query result that returns a command is pressed

### ISSUE THREAD

**Issue by zagkk** [zhukov/webogram#1596]
Could be good if an inline query result is pressed and if result of pressed result starts with "/", the app detects it as a command only if the inline query is performed in a private chat with the bot.

Right now when we try to perform this action, this "command" is returned as plain text instead of entities.

**Comment by zhukov** [comment]
I didn't get it. Please provide a screenshot and one of another app (android e.g.), where it works correctly.

**Comment by zagkk** [comment]
When you try an inline query in Telegram Web:

![web-1](https://user-images.githubusercontent.com/35106755/34803276-cd88a1bc-f648-11e7-8d0d-9e4e1358ee3e.png)

When you press a result, I should get an object with entities property because the result is a command instead of plain text (it starts with slash):

![web-2](https://user-images.githubusercontent.com/35106755/34803316-08c44092-f649-11e7-9401-b1bef1db8471.png)

But in Android:

![android-1](https://user-images.githubusercontent.com/35106755/34803341-20d41c8e-f649-11e7-8bbf-0ce8c6f1c707.jpg)

I get it right: entities property in object.

**Comment by zhukov** [comment]
Was fixed from server-side.
