### ISSUE TITLE
[Unrelated to webogram] Does the source of @githubbot available?

### ISSUE THREAD

**Issue by arieljannai** [zhukov/webogram#1597]
**_Sorry for the offtopic_**

I was looking for the [GitHubBot](https://t.me/GitHubBot) and couldn't find it.
Does its code available somewhere publicly?
I wanted to deploy it to a private GitHub site.

Thanks :)

**Comment by stek29** [comment]
Let's close it, but wait for Igor's answer.

**Comment by arieljannai** [comment]
Ok, thanks :)
