### ISSUE TITLE
Нет возможности выбрать Русский язык

### ISSUE THREAD

**Issue by KDASOFT** [zhukov/webogram#1598]
Добрый день! В приложении нет возможности выбрать Русский язык. Версия 0.7. Пробовал по адресам https://web.telegram.org/ и https://zhukov.github.io/webogram
В списке доступны для выбора только следующие языки:

![image](https://user-images.githubusercontent.com/35321858/34808256-b08874f4-f6c8-11e7-80ec-32f27f6c16bf.png)

**Comment by zhukov** [comment]
All the translations are done through the Transifex, please don't create issues for them.

**Comment by KDASOFT** [comment]
В программе в исходниках имеется файл русского языка, но в программе нет возможности выбрать Русский webogram/app/js/locales/ru-ru.json

**Comment by KDASOFT** [comment]
webogram/app/js/lib/config.js

Русский язык отключен

![image](https://user-images.githubusercontent.com/35321858/34813000-26439b00-f6e3-11e7-8d03-8ac7e303272a.png)
