### ISSUE TITLE
Timeline in Telegram Messenger 

### ISSUE THREAD

**Issue by alish123456** [zhukov/webogram#1600]
Hello to all friends...

I used before [Messenger Line](https://line.me/en/)

There is a feature in this messenger called Timeline
This feature can post (all types of media) and share with friends Or everyone.
send comments and likes are availabl (for post). like facebook.

To better understand it, install the line Messenger and use this feature
I'm sure you'll love this timeline too will

If this feature is added to the telegram messenger, it will be added to the popularity of the telegram.
It will also be very attractive

what do you think?
If it's good us to share it with the telegram managers (pavel duro)

**Comment by zhukov** [comment]
This is a feature request for Telegram Platform, not for Telegram Web app. Please contact in-app support  on mobile apps (Settings - Ask a question) for this kind of requests.

**Comment by alish123456** [comment]
@zhukov 
I know
I wanted to share this idea with you before sending a request to the telegram :|
