### ISSUE TITLE
[Feature Request] Implement Customer Chat Control

### ISSUE THREAD

**Issue by Ma3yTa** [zhukov/webogram#1601]
Please implement something like Facebook made for Customer Chat Plugin https://developers.facebook.com/docs/messenger-platform/discovery/customer-chat-plugin or Microsoft made for WebControl https://dev.skype.com/webcontrol to chat directly with bot/person. Thanks.

**Comment by zhukov** [comment]
This is a feature request for Telegram Platform, not for Telegram Web app. Please contact in-app support  on mobile apps (Settings - Ask a question) for this kind of requests.
