### ISSUE TITLE
Question about TmpfsFileStorage

### ISSUE THREAD

**Issue by mhdizade** [zhukov/webogram#1606]
in this commit **[#de16c0c](https://github.com/zhukov/webogram/commit/94a94b864dc1d7453cf82d456deb0d932681633d)** you disabled chrome temps, and i used chrome temps for my app, i have question why did you do that?
what is problem about chrome temps?

**Comment by azzimuth** [comment]
As far as I can see, you can still use tempfs if you set `Config.allow_tmpfs` variable to `true`.

**Comment by zhukov** [comment]
@mhdizade we had some security concerns, its behaviour is not very compatible with our use case. I filed bug report to Chromium: https://bugs.chromium.org/p/chromium/issues/detail?id=688390. Was not fixed, so we disabled the feature in favour of IndexedDB, which doesn't introduce this security issue.
