### ISSUE TITLE
Telegram: Waiting for Network... Retry

### ISSUE THREAD

**Issue by TheAdidam** [zhukov/webogram#1608]
Hello, It used to work 2-3 months back very well but these days, It just disconnects again and again and shows error "Waiting for network... Retry"

Could you please fix this issue?

Yes, I face this most on the web.telegram.org and https://zhukov.github.io/webogram/

I'm using the latest version of Telegram.

My internet is stable and fine. I use it for many other stuff and it doesn't show such issues with any other web app.

If you need any kind of details from my side or logs let me know? I'll have them for you.

Screenshot: https://image.prntscr.com/image/2X4UeQQBSYq5C-wY7F5v0g.png

Thanks.

**Comment by stek29** [comment]
Can you open 149.154.175.50 and https://venus.web.telegram.org?

**Comment by TheAdidam** [comment]
149.154.175.50 ---->  http://prntscr.com/i5sbba

https://venus.web.telegram.org/ ---->  http://prntscr.com/i5sbi7

**Comment by TheAdidam** [comment]
Any update?

**Comment by stek29** [comment]
Any errors in console?

**Comment by TheAdidam** [comment]
Console Screenshot for venus.web.telegram.org: http://prntscr.com/i6myx8

Console Screenshot for 149.154.175.50 http://prntscr.com/i6mz2q

**Comment by stek29** [comment]
No, I mean for Web.telegram.org

**Comment by zhukov** [comment]
@TheAdidam can you take a screenshot of javascript errors console at the moment when it happens? look for lines with red text about network errors.

**Comment by tonycai** [comment]
I have the same problem. How to resolve it? Thank you so much!

**Comment by tonycai** [comment]
I had resolved.
git clone https://github.com/alexbers/mtprotoproxy.git
then:
nohup python3 mtprotoproxy.py &
refer: https://github.com/p1ratrulezzz/mtproxy-server-linux

**Comment by chrone81** [comment]
I frequently experience this "Waiting for network.. Retry" issue on web.telegram.org. Tested on several ISPs, PCs, and browsers, still produced same results.

One of the error displayed on Chrome Devs Tool when this occurred was:
> Failed to load https://flora.web.telegram.org/apiw1: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://web.telegram.org' is therefore not allowed access. The response had HTTP status code 502.
