### ISSUE TITLE
Telegram blocked me for inviting people on channel

### ISSUE THREAD

**Issue by Cappadonna** [zhukov/webogram#1609]
Telegram just blocked me for using a function that they allowed.
I have participated on an ICO Bounty, I had to invite members in their channel, telegram banned me for that.
I tried to contact @SpamBot and I am banned too, I can't write to @SpamBot.

![image](https://user-images.githubusercontent.com/35773849/35376481-06f4bd0c-01b4-11e8-92b4-91521df10590.png)

**Comment by zhukov** [comment]
@Cappadonna Error message says that it’s you who blocked user, just unblock him

**Comment by Cappadonna** [comment]
I have not blocked anyone.

**Comment by zhukov** [comment]
Trust me, you blocked the user you were trying to send message in the first screenshot. Open his profile and select "unblock".
Anyway that's not a Web app problem, closing the issue. Feel free to contact support.

**Comment by Cappadonna** [comment]
Man the "user i was trying to send message" is Telegram Bot, and no I have not blocked him.Trust me!

**Comment by zhukov** [comment]
then send the same screen for him
<img width="487" alt="screen shot 2018-01-25 at 12 29 34" src="https://user-images.githubusercontent.com/775173/35378225-42006ee6-01dc-11e8-8068-6aedad7030a7.png">

**Comment by Cappadonna** [comment]
![image](https://user-images.githubusercontent.com/35773849/35378397-513742f2-01bb-11e8-8a88-d746340e2a42.png)

**Comment by zhukov** [comment]
nope, I mean for @spambot. it's a different one.

**Comment by Cappadonna** [comment]
![image](https://user-images.githubusercontent.com/35773849/35378889-08f1718c-01bd-11e8-9237-eb4d91189d63.png)

**Comment by zhukov** [comment]
what's your telegram username?

**Comment by toshirou28** [comment]
I have the same issue but I able to chat with the spam bot info. I found out that somebody reported me as annoying. Well I didn't know why am I become Annoying never posted any bad things and here is what I've got . 
![image](https://user-images.githubusercontent.com/31353928/37558927-f23d6622-2a56-11e8-9d99-5a7fdcc3dc94.png)

Hope this helps. buddy.

**Comment by PapuPutta** [comment]
hello,
  I am getting this message when trying to post in telegram..pls help me..
One of the params is missing or invalid.
Method: messages.sendMessage
Result: {"_":"rpc_error","error_code":400,"error_message":"USER_BANNED_IN_CHANNEL"}
