### ISSUE TITLE
Experiments with service-worker.js

### ISSUE THREAD

**Issue by isopen** [zhukov/webogram#1610]
What was done :)

> Opened two tabs
> Stop/start service-worker.js (with an interval of 1s). Worker restarts itself. It's very good

As a result:

> The picture with the fox did not come (resonce 404)
> After each reboot of the tab, this plate appears on the next tab
> I click ok. Appears in the next tab
> It's all in a loop
![image](https://user-images.githubusercontent.com/7373292/35382580-4ae0cf36-01f2-11e8-9471-ad51f105d0f9.png)

**Comment by zhukov** [comment]
@isopen How do you restart service worker? And why?

**Comment by isopen** [comment]
1. Via Console Google Chrome
2. I was just scared https://goo.gl/jh4xLj. I don't want to be mined.

**Comment by isopen** [comment]
Visually behaves like this
https://youtu.be/GIsy-bG2mEw
404 fox on this video is not, but it's also not so difficult to cause. Try it yourself.
