### ISSUE TITLE
Try to pin more than 5 Channel... the program quit [Mac book pro from Appstore]

### ISSUE THREAD

**Issue by FallHouse** [zhukov/webogram#1614]
Process:               Telegram [32819]
Path:                  /Applications/Telegram.app/Contents/MacOS/Telegram
Identifier:            ru.keepcoder.Telegram
Version:               3.7.5 (115423)
App Item ID:           747648890
App External ID:       825716515
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Telegram [32819]
User ID:               501

Date/Time:             2018-01-30 21:28:00.655 +0100
OS Version:            Mac OS X 10.13.2 (17C205)
Report Version:        12
Anonymous UUID:        7CF137FE-25DD-6CDF-41F2-CA4CB126182C

Sleep/Wake UUID:       729E6940-912A-4C72-A2A6-73C3E7BD2365

Time Awake Since Boot: 130000 seconds
Time Since Wake:       1900 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_INSTRUCTION (SIGILL)
Exception Codes:       0x0000000000000001, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Illegal instruction: 4
Termination Reason:    Namespace SIGNAL, Code 0x4
Terminating Process:   exc handler [0]

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   ru.keepcoder.Telegram         	0x000000010b756fc2 0x10b51d000 + 2334658
1   ru.keepcoder.Telegram         	0x000000010baf1346 0x10b51d000 + 6112070
2   ru.keepcoder.Telegram         	0x000000010baf148c 0x10b51d000 + 6112396
3   org.telegram.Telegram.SwiftSignalKitMac	0x000000010c460b91 0x10c438000 + 166801
4   org.telegram.Telegram.SwiftSignalKitMac	0x000000010c43d8b6 0x10c438000 + 22710
5   org.telegram.Telegram.SwiftSignalKitMac	0x000000010c43f996 0x10c438000 + 31126
6   org.telegram.Telegram.SwiftSignalKitMac	0x000000010c43f950 0x10c438000 + 31056
7   org.telegram.Telegram.SwiftSignalKitMac	0x000000010c4450b0 0x10c438000 + 53424
8   libdispatch.dylib             	0x00007fff7535a591 _dispatch_call_block_and_release + 12
9   libdispatch.dylib             	0x00007fff75352d50 _dispatch_client_callout + 8
10  libdispatch.dylib             	0x00007fff7535e32d _dispatch_main_queue_callback_4CF + 1148
11  com.apple.CoreFoundation      	0x00007fff4dac97a9 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
12  com.apple.CoreFoundation      	0x00007fff4da8b9ca __CFRunLoopRun + 2586
13  com.apple.CoreFoundation      	0x00007fff4da8ad23 CFRunLoopRunSpecific + 483
14  com.apple.HIToolbox           	0x00007fff4cda2e26 RunCurrentEventLoopInMode + 286
15  com.apple.HIToolbox           	0x00007fff4cda2a9f ReceiveNextEventCommon + 366
16  com.apple.HIToolbox           	0x00007fff4cda2914 _BlockUntilNextEventMatchingListInModeWithFilter + 64
17  com.apple.AppKit              	0x00007fff4b06df5f _DPSNextEvent + 2085
18  com.apple.AppKit              	0x00007fff4b803b4c -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 3044
19  com.apple.AppKit              	0x00007fff4b062d6d -[NSApplication run] + 764
20  com.apple.AppKit              	0x00007fff4b031f1a NSApplicationMain + 804
21  ru.keepcoder.Telegram         	0x000000010b563319 0x10b51d000 + 287513
22  libdyld.dylib                 	0x00007fff7538c115 start + 1

Thread 1:: com.apple.NSEventThread
0   libsystem_kernel.dylib        	0x00007fff754d27c2 mach_msg_trap + 10
1   libsystem_kernel.dylib        	0x00007fff754d1cdc mach_msg + 60
2   com.apple.CoreFoundation      	0x00007fff4da8c355 __CFRunLoopServiceMachPort + 341
3   com.apple.CoreFoundation      	0x00007fff4da8b6a7 __CFRunLoopRun + 1783
4   com.apple.CoreFoundation      	0x00007fff4da8ad23 CFRunLoopRunSpecific + 483
5   com.apple.AppKit              	0x00007fff4b1ab3c8 _NSEventThread + 184
6   libsystem_pthread.dylib       	0x00007fff756176c1 _pthread_body + 340
7   libsystem_pthread.dylib       	0x00007fff7561756d _pthread_start + 377
8   libsystem_pthread.dylib       	0x00007fff75616c5d thread_start + 13

Thread 2:
0   libsystem_kernel.dylib        	0x00007fff754dbcee __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff75618662 _pthread_cond_wait + 732
2   org.telegram.Telegram.SwiftSignalKitMac	0x000000010c44412b 0x10c438000 + 49451
3   org.telegram.Telegram.SwiftSignalKitMac	0x000000010c440129 0x10c438000 + 33065
4   com.apple.Foundation          	0x00007fff4fb78e48 __NSThread__start__ + 1197
5   libsystem_pthread.dylib       	0x00007fff756176c1 _pthread_body + 340
6   libsystem_pthread.dylib       	0x00007fff7561756d _pthread_start + 377
7   libsystem_pthread.dylib       	0x00007fff75616c5d thread_start + 13

Thread 3:
0   libsystem_kernel.dylib        	0x00007fff754dbcee __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff75618662 _pthread_cond_wait + 732
2   org.telegram.Telegram.SwiftSignalKitMac	0x000000010c44412b 0x10c438000 + 49451
3   org.telegram.Telegram.SwiftSignalKitMac	0x000000010c440129 0x10c438000 + 33065
4   com.apple.Foundation          	0x00007fff4fb78e48 __NSThread__start__ + 1197
5   libsystem_pthread.dylib       	0x00007fff756176c1 _pthread_body + 340
6   libsystem_pthread.dylib       	0x00007fff7561756d _pthread_start + 377
7   libsystem_pthread.dylib       	0x00007fff75616c5d thread_start + 13

Thread 4:
0   libsystem_kernel.dylib        	0x00007fff754dbcee __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff75618662 _pthread_cond_wait + 732
2   org.telegram.Telegram.SwiftSignalKitMac	0x000000010c44412b 0x10c438000 + 49451
3   org.telegram.Telegram.SwiftSignalKitMac	0x000000010c440129 0x10c438000 + 33065
4   com.apple.Foundation          	0x00007fff4fb78e48 __NSThread__start__ + 1197
5   libsystem_pthread.dylib       	0x00007fff756176c1 _pthread_body + 340
6   libsystem_pthread.dylib       	0x00007fff7561756d _pthread_start + 377
7   libsystem_pthread.dylib       	0x00007fff75616c5d thread_start + 13

Thread 5:
0   libsystem_kernel.dylib        	0x00007fff754dc562 __workq_kernreturn + 10
1   libsystem_pthread.dylib       	0x00007fff7561726f _pthread_wqthread + 1552
2   libsystem_pthread.dylib       	0x00007fff75616c4d start_wqthread + 13

Thread 6:
0   libsystem_kernel.dylib        	0x00007fff754dc562 __workq_kernreturn + 10
1   libsystem_pthread.dylib       	0x00007fff7561706a _pthread_wqthread + 1035
2   libsystem_pthread.dylib       	0x00007fff75616c4d start_wqthread + 13

Thread 7:
0   libsystem_pthread.dylib       	0x00007fff75616c40 start_wqthread + 0
1   ???                           	0x0000000000000001 0 + 1

Thread 8:
0   libsystem_kernel.dylib        	0x00007fff754dc562 __workq_kernreturn + 10
1   libsystem_pthread.dylib       	0x00007fff7561706a _pthread_wqthread + 1035
2   libsystem_pthread.dylib       	0x00007fff75616c4d start_wqthread + 13

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x00006080000eaa00  rbx: 0x0000000000000000  rcx: 0x00000000ff000000  rdx: 0x00006080000eaa08
  rdi: 0x0000000500000790  rsi: 0x0000000000000000  rbp: 0x00007ffee46e1180  rsp: 0x00007ffee46e0f10
   r8: 0x00007fffa7e15750   r9: 0x00007ffee46e0dc7  r10: 0x00007fffa7e0b550  r11: 0x00007fd28e8944a0
  r12: 0x00006080000eaa18  r13: 0x000000010dacfd08  r14: 0xc000000000000030  r15: 0x0000000000000001
  rip: 0x000000010b756fc2  rfl: 0x0000000000010246  cr2: 0x000000011451c000
  
Logical CPU:     4
Error Code:      0x00000000
Trap Number:     6

...

**Comment by stek29** [comment]
Report to t.me/macswift.
