### ISSUE TITLE
Media Player unable to reproduce audio 

### ISSUE THREAD

**Issue by nkz0g** [zhukov/webogram#1623]
The Media Player unable to reproduce audio of 10mb or more. in my example I've use Paranoid Android of RH. This mp3 have a duration of 6:23 and the size is 15mb.

How to reproduce:
- Create a public or private channel
- Add a mp3 of 10mb or more
- You see that the media just have the option of download the file

Hardware & Software:
- Fedora 27 x64
- Codecs multimedia installed
- Tested in Firefox 57 & Chrome 62+

**Comment by stek29** [comment]
#1624
