### ISSUE TITLE
Time showed incorrectly

### ISSUE THREAD

**Issue by BANOnotIT** [zhukov/webogram#1631]
Messages which sent in 0:01, 0:10, etc. in 24h format are showed like 12:01 AM, 12:10 AM

**Comment by stek29** [comment]
Actually it should be 12 AM. Pisses me off too. See Wikipedia:

> Each period consists of 12 hours numbered: 12 (acting as zero),[3] 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, and 11.

**Comment by khan1310** [comment]
Error
One of the params is missing or invalid.
Click for technical details
