### ISSUE TITLE
Link only opens new Window

### ISSUE THREAD

**Issue by olivermpl** [zhukov/webogram#1637]
Whenever I click on a link it opens just a new empty Window instead of the link (using Chrome).
Telegram Version:  3.7.5.115423 
OS Version: macOS High Sierra (10.13.3 )
Chrome Version: 64.0.3282.167

**Comment by stek29** [comment]
That's Chrome bug. Restart it.

Also, report macOS app issues to https://t.me/macswift, not to webogram repo.
