### ISSUE TITLE
Unable to send Voice Message with a porxy API

### ISSUE THREAD

**Issue by mashirozx** [zhukov/webogram#1640]
It shows like this...
![image](https://user-images.githubusercontent.com/16148054/37081633-0cb9bb48-2225-11e8-888f-e9f9f3fbc9c0.png)

This one works with the Telegram API proxy: <https://tel.shino.cc/>

And this one works with the original API: <https://wtf.shino.cc/>

Using this release: <https://github.com/zhukov/webogram/releases/download/v0.5.7/webogram_v0.5.7.zip>

Nginx conf:

```

    charset utf-8;

    access_log  /var/log/nginx/$host.access.log;

    client_max_body_size 20M;

    root   /var/www/telegram;
    index  index.html index.htm index.php;

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }

    location / {
        if ($scheme = http) {
            return 302 https://$http_host$request_uri;
        }
    }

    location ~* .(jpg|jpeg|png|gif|ico|css|js)$ {
        expires 365d;
    }

```

**Comment by stek29** [comment]
Does it work on web.telegram.org?

**Comment by mashirozx** [comment]
@stek29 Yes, web.telegram.org works fine here
![image](https://user-images.githubusercontent.com/16148054/37085063-18cc1fac-222f-11e8-8fe1-bc7cd0d2fa73.png)

**Comment by mashirozx** [comment]
I've added some configuration details in question.

**Comment by mashirozx** [comment]
Find another problem:
![image](https://user-images.githubusercontent.com/16148054/37085457-0b307f54-2230-11e8-891d-fbec350161c5.png)

**Comment by mashirozx** [comment]
problem solved
