### ISSUE TITLE
one of the params is missing or invalid

### ISSUE THREAD

**Issue by aanandkummar** [zhukov/webogram#1641]
Hi, my telegram user name is aanandkummar,
When I send a msg then show that one of the params is missing or invalid, please check & resolve my problem

**Comment by stek29** [comment]
Click on more info and post full error code.

**Comment by whythatdo** [comment]
I had the same problem guy. One of the params is missing or invalid.
Detail is: Method: messages.sendMessage
Result: {"_":"rpc_error","error_code":400,"error_message":"USER_BANNED_IN_CHANNEL"} Please help me. when i send a message, I always get that thing

**Comment by stek29** [comment]
> USER_BANNED_IN_CHANNEL

obviously you've been banned.

**Comment by stek29** [comment]
@aanandkummar closing since you haven't provided more info.

**Comment by tung0608** [comment]
please,i have the same proplem,how can i slove this problem? please

**Comment by Ryuno-Ki** [comment]
Talk to support (we have several issues with USER_BANNED_IN_CHANNEL opened already with instructions on how to get in touch with support).

**Comment by endergun** [comment]
i'm getting the ''Method: channels.joinChannel
Result: {"_":"rpc_error","error_code":400,"error_message":"CHANNELS_TOO_MUCH"}'' mesage

**Comment by endergun** [comment]
what is the limit for channels

**Comment by Digital21** [comment]
I'm looking for support to solve this issue.

**Comment by endergun** [comment]
there is a limit for channels...

2018-07-18 6:12 GMT+03:00 Digital21 <notifications@github.com>:

**Comment by PapuPutta** [comment]
'One of the param is missing or invalid..'Please solve this problem.Thanks.

**Comment by PapuPutta** [comment]
Method: channels.joinChannel
Result: {"_":"rpc_error","error_code":400,"error_message":"CHANNELS_TOO_MUCH"}

**Comment by arifhosen** [comment]
i have same isuue plz help

**Comment by sewasingh** [comment]
![telegram issue](https://user-images.githubusercontent.com/41656991/48311241-e13baa00-e5c2-11e8-85dd-2fa1632babb9.png)
pl resolve issue,help plz

**Comment by PapuPutta** [comment]
You need to delete few channels or contacts to keep telegram open for new entries..if your telegram contacts are full(that meets maximum number)you will get that message.So please delete few contacts in telegram then you can add new entreis.This is what the system is in telegram.Hope that helps.
    On Sunday, 11 November, 2018, 3:04:09 PM IST, sewasingh <notifications@github.com> wrote:  
 
 

pl resolve issue,help plz

**Comment by skamchani** [comment]
Same Issue how to resolve ?

**Comment by farasteh** [comment]
`Method: channels.inviteToChannel
Result: {"_":"rpc_error","error_code":400,"error_message":"USER_BOT"}`

my error code differs
