### ISSUE TITLE
Using Telegram Web with selenium for automated tests

### ISSUE THREAD

**Issue by alelunardi98** [zhukov/webogram#1647]
Hi, im doing automated tests with selenium on telegram web, but every time i close webdriver i have to re-do login, and that stress me because i must put every time the verification code. So i tried to save cookies and load it when the webdriver start, but cookies was empty! 
How can i save my session for all tests? How? I also tried with different websites and they gave me cookies.

**Comment by stek29** [comment]
1) Webogram stores auth data in localstorage
2) There are test accounts for that, see https://core.telegram.org/api/datacenter#testing-redirects. To switch to test backend add "?test=1" to Telegram url

**Comment by Hossein-Gholami** [comment]
Hi there,
Have you tried Firefox Profile? (in case you're using Firefox)

**Comment by ahmedyasserays** [comment]
I'm facing the same problem , did you find a solution ?
