### ISSUE TITLE
Cannot read property 'photo' of undefined

### ISSUE THREAD

**Issue by javansolo** [zhukov/webogram#1648]
Cannot read property 'photo' of undefined when message is deleted:
previous line : var message = AppMessagesManager.getMessage(messageID) = {
        _: 'messageEmpty',
        deleted: true,
        pFlags: {out: false, unread: false}
      }
https://github.com/zhukov/webogram/blob/32f67b18bbbf9c27e527071c2435498e702b4797/app/js/controllers.js#L3224

**Comment by niccord** [comment]
This issue seems no longer there
