### ISSUE TITLE
Dockerfile does not work (Only shows Not Found page)

### ISSUE THREAD

**Issue by 0xFEEDC0DE64** [zhukov/webogram#1651]
I just tried building a docker image using 
`docker build -t webogram https://github.com/zhukov/webogram.git`

Building succeeds but when I run the container, all I get in the webbrowser is a "Not Found" line without any fancy styling or anything.

![image](https://user-images.githubusercontent.com/10342708/37837828-970ecdc2-2eb6-11e8-9dac-bb89554f0408.png)

The same also happens when I try the image provided from docker hub:
https://hub.docker.com/r/tazjin/webogram/

Is there anything wrong with the Dockerfile?

**Comment by stek29** [comment]
What about localhost:8000/app/index.html?

**Comment by 0xFEEDC0DE64** [comment]
Yep, that was right.
