### ISSUE TITLE
Transparent Background PNGs Displayed as Black Background when Uploaded

### ISSUE THREAD

**Issue by Vdragon** [zhukov/webogram#1655]
Upload the following following image:  

![ubuntu circle of friends white and orange hex taiwan svg](https://user-images.githubusercontent.com/1192163/38175583-48146e2c-3611-11e8-9dfc-9c2493de1434.png)

results in:

![default](https://user-images.githubusercontent.com/1192163/38175555-dd406e16-3610-11e8-9bdb-b91398aae9f2.png)

**Comment by 1ser1gey5** [comment]
https://chart.googleapis.com/chart?chs=200x200&chld=M|0&cht=qr&chl=otpauth%3A%2F%2Ftotp%2FFriendz%2520ICO%2520-%2520Steward%3Aalekszergtuuliulubademjn%2540gmail.com%3Fsecret%3DW4MT5JD33KIRMCRH%26issuer%3DFriendz%2520ICO%2520-%2520Steward

**Comment by stek29** [comment]
Transparent background isn't supported in profile pictures
