### ISSUE TITLE
Login without phone access?

### ISSUE THREAD

**Issue by CarlosEsco** [zhukov/webogram#1657]
Is there anyway to login without phone access? like verification code sent to an email or something?

**Comment by Digital21** [comment]
Brilliances

**Comment by thecyberd3m0n** [comment]
many people don't want to provider their phone number to something that declares 'anonimity' :) I support that feature.

**Comment by stek29** [comment]
API issue

**Comment by baeby** [comment]
Help me

**Comment by Digital21** [comment]
great user-friendly
