### ISSUE TITLE
problem 

### ISSUE THREAD

**Issue by mistoo88** [zhukov/webogram#1658]
![default](https://user-images.githubusercontent.com/37774093/38298480-2392843a-3800-11e8-9bed-6178eb32fcff.JPG)
![default](https://user-images.githubusercontent.com/37774093/38298500-2e74ac5c-3800-11e8-9186-00f3858f4b77.JPG)

**Comment by mistoo88** [comment]
I can not log in via my laptop

**Comment by stek29** [comment]
It literally says what to do, and has nothing to do with the app itself
