### ISSUE TITLE
не приходят смс 

### ISSUE THREAD

**Issue by iMaciaveller** [zhukov/webogram#1672]
Не приходят смс сообщения для аутентификации.

**Comment by hooddy** [comment]
Вот это уже интересно. Вполне логично запретить опсосам пропускать все, что относится к телеграму, включая смс и войс. Интересно, интересно...

**Comment by zhukov** [comment]
Воспроизведите пожалуйста проблему еще раз и скиньте в поддержку номер телефона и время. Если нету доступа в Т, можно в telegram.org/support

**Comment by manylov** [comment]
Билайн 965 не приходит. МТС 911 приходит
