### ISSUE TITLE
Pressing ESC moves the focus to the Search box instead of canceling the current mode

### ISSUE THREAD

**Issue by mindrones** [zhukov/webogram#1675]
Hi, I'm not sure if this is intended but here are some annoyances I get with ESC.

1) Exiting from "select an action" mode

- click on a message offers some actions (forward, delete, reply, edit, cancel);
- press ESC: the focus moves to the Search box;
- expected result: exiting from "Choose action mode" (same as we get by pressing Cancel);

2) Exiting from reply mode

- Clicking on the message and then on "REPLY"
- press ESC: the focus moves to the Search box;
- expected result: exiting from "Reply mode" (same as clicking on the cross on the top-right corner of the Reply form).

3) Exiting from edit mode

- edit a message (by clicking on the message and then on "EDIT" or press arrow up to edit the last message);
- press ESC: the focus moves to the Search box;
- expected result: exiting from "Edit mode" (same as clicking on the cross on the top-right corner of the Edit form).

For example, if we press ESC after clicking on Forward, the forward mode cancels correctly by closing the modal.

I'm using `Firefox 59.0.2 (64-bit)`.

Thanks!

**Comment by Aokromes** [comment]
https://github.com/zhukov/webogram/issues/1628
