### ISSUE TITLE
telegram group joining problem

### ISSUE THREAD

**Issue by rumancox79** [zhukov/webogram#1684]
One of the params is missing or invalid. Click for technical details 
 
{"_":"rpc_error","error_code":400,"error_message":"CHANNELS_TOO_ MUCH

**Comment by rumancox79** [comment]
how can i solve this ? give me any solution

**Comment by stek29** [comment]
What group are you trying to join? Does it happen for all channels/groups or only one particular group?

Please stop opening new issues.

**Comment by ingria** [comment]
@rumancox79 the maximum count of public groups or channels that you can join is 500. Then you'll start getting the CHANNELS_TOO_MUCH error. There's no way to fix this.
