### ISSUE TITLE
Telegram Account hacked 

### ISSUE THREAD

**Issue by Nady69** [zhukov/webogram#1695]
Hi,

My No and Telegram account has been stolen and someone texting my all contact for money to be sent to his account in IRAN. Unfortunately, some of the friends have to do it. also, he disabled my App store access.
The belove massage come up while trying to activate my Telegram.

Method: auth.sendCode
Result: {"_":"rpc_error","error_code":420,"error_message":"FLOOD_WAIT_75444"}

**Comment by stek29** [comment]
You’d have to wait for 75444 seconds to log in. Set up 2fa if you have old session somewhere and kick hacker out from active sessions.

Also, has nothing to do with webogram.
