### ISSUE TITLE
Add an opt-in toggle for NSFW content

### ISSUE THREAD

**Issue by elliot-wood** [zhukov/webogram#1698]
I am suggesting an opt-in toggle for NSFW content. When this is turned off, groups reported as being used for distributing NSFW content will not be accessible, not unlike what is currently mandatory on the Telegram applications distributed on the Apple App Stores.

### Background
On the iOS Telegram clients, groups that post "NSFW" content are blocked, as a cheap workaround for the App Store content policy.

However, the policy actually allows NSFW content to be shown, with the caveat that the user has to consent (opt-in) to this. Secondly, the policy also states that this toggle needs to be on the service's website.

Putting this toggle on the web.telegram.org Telegram client would make it possible for Telegram to allow NSFW content on Apple platforms without risk of being pulled from the App Stores (there are plenty of examples of applications that currently do this without any trouble from Apple). It would also lay the groundwork for bringing this feature to all clients, so that all Telegram users can be in control of what content they want to be able to see.

**Comment by stek29** [comment]
It's not that easy -- Apple loves to pick on some apps while ignoring others.
Anyway, it'd make more sense to put the check on my.telegram.org IMO, even if we add such a check.

> there are plenty of examples of applications that currently do this without any trouble from Apple

Exactly -- some apps can get away with nsfw stuff and some just can't even when they try to comply with guidelines.

**Comment by elliot-wood** [comment]
Those applications use that workaround, though. The problem that Telegram is facing is that an opt-in has yet to be tried, only all or nothing approaches.

The iOS version of Telegram X on the App Store has currently beeen pulled because it completely lacks the NSFW censorship. At present, I don’t believe Apple is targeting Telegram more than anyone else. If we were to implement an opt-in as per the guidelines and Apple still pulled the Telegram application, then I would certainly agree with you there.

**Comment by elliot-wood** [comment]
> They've sent completely safe for work pics complaining that they are not matching age restrictions, but somehow apps like reddit/instagram/twitter get away with definitely NOT safe for work stuff

I can't speak for Instagram since I don't use it, but Reddit and Twitter both implement an opt-in, and this is, according to Apple's guidelines, how they get away with it.

If one went into their Twitter/Reddit/Tumblr account and turned back on the safe/no-NSFW modes for your account, the respective iOS apps will no longer show NSFW content when logged into your account. Any content that does get through would be due to moderation not having caught up to that content on the service.

At this point, I still don't believe Apple are targeting Telegram in particular over any other service. If Telegram was to implement what I am suggesting, and Apple still had problems with Telegram, then I'd believe you one-hundred percent.

**Comment by igor9silva** [comment]
Section `1.2 User Generated Content` from [App Store Review Guidelines](https://developer.apple.com/app-store/review/guidelines/) says, and I quote:

> If your app includes user-generated content from a web-based service, it may display incidental mature “NSFW” content, provided that the content is hidden by default and only displayed when the user turns it on via your website.

Even though it does leave space for interpretation, I'd say that it is clear enough for the suggested approach (reddit or twitter style). 

Telegram is not, and does not intend to be driven by pornographic content.
