### ISSUE TITLE
Allow to send later a message

### ISSUE THREAD

**Issue by rianby64** [zhukov/webogram#1699]
This looks like a feature that has an small value.
Let's imagine that you want to send a message, but not in this right moment, just a bit later.
Sounds interesting? E.g. "have a nice day" next day at 9 morning or something else that you don't want to send right now.

**Comment by zhukov** [comment]
This is a request not for a Web App, but for the Telegram API. Please contact Telegram Support (telegram.org/support or "Ask a Question" in Settings).
