### ISSUE TITLE
Add captcha test to web.telegram.org

### ISSUE THREAD

**Issue by esfahanoog** [zhukov/webogram#1701]
When using the Tor project to access web.telegram.org, it prevents login task with this message "You are performing too many actions. Please try again later."
Method: auth.sendCode
Result: {"_":"rpc_error","error_code":420,"error_message":"FLOOD_WAIT_86400"}

Please add a Captcha test to prevent robots from multiple login attempts, instead of putting an IP  limitation.

**Comment by stek29** [comment]
It’s limit on server side, webogram can’t do much about it

**Comment by esfahanoog** [comment]
How we can ask telegram core team to consider that?
As you know telegram has been banned in Iran and Russia , Tor Browser is a good choice to connect to Telegram Web platform.
