### ISSUE TITLE
no link to "Photo 1 of 2"

### ISSUE THREAD

**Issue by jidanni** [zhukov/webogram#1702]
Clicking on the picture on
https://web.telegram.org/#/im?p=@Momo411
has "Photo 2 of 2" but no link to
"Photo 1 of 2".

**Comment by stek29** [comment]
You can use arrows on keyboard, or click areas with arrows on left and right sides (on desktop -- sadly there's nothing for multiple profile pics on mobile layout)

**Comment by stek29** [comment]
I am not able to reproduce it.
Show a screenshot

**Comment by jidanni** [comment]
Clicking anywhere does not work.
There are no <  > arrows to click on either.
The only thing that works is the arrow keyboard keys, but the user has to guess that.
![ckd1](https://user-images.githubusercontent.com/1230959/41112068-8374716e-6ab0-11e8-985f-f1d9b4672ec2.jpg)

**Comment by stek29** [comment]
Hm, you have a pretty narrow screen, that might be causing the issue indeed.

**Comment by jidanni** [comment]
1024x742.

**Comment by stek29** [comment]
Yup, that's the problem, see:

https://github.com/zhukov/webogram/blob/81448595bb2ec17fc7d217bd16aa7782671047a4/app/less/desktop.less#L2227-L2233

Sadly, showing them on narrower screens might interfere with picture itself, and that's why they are hidden.

Maybe on narrow screens it should be shown only on hover.

**Comment by jidanni** [comment]
All I know is the picture has two big white borders on either side.
Why not put an < and > in each border respectively, and make them
clickable.

Anyway, just do as Facebook does.

With Facebook one always knows how to see the next picture.

Or do as mbasic.facebook.com does: English words Previous and Next.

**Comment by stek29** [comment]
> as facebook does

I don't use facebook. Do you have a screenshot?

**Comment by jidanni** [comment]
![d1](https://user-images.githubusercontent.com/1230959/41118188-cc1423fe-6ac1-11e8-9d28-076eb55d954a.jpg)
