### ISSUE TITLE
Unable to create group

### ISSUE THREAD

**Issue by jamincollins** [zhukov/webogram#1705]
Every time I try to create a new group on either the Android app or web client.  I get the following error.
```
Access denied
You are not allowed for this action.
```
On the web client, I have an option `Click for technical details` which gives the following information:
```
Method: messages.createChat
Result: {"_":"rpc_error","error_code":403,"error_message":"USER_RESTRICTED"}
```

**Comment by stek29** [comment]
well, you are restricted. contact in-app support via android app / spambot.
