### ISSUE TITLE
One of the params is missing or invalid

### ISSUE THREAD

**Issue by toyovoke** [zhukov/webogram#1707]
Method: messages.sendMessage
Result: {"_":"rpc_error","error_code":400,"error_message":"USER_BANNED_IN_CHANNEL"}

What does this mean?

**Comment by Ryuno-Ki** [comment]
You are banned.

Contact SpamBot.

**Comment by toyovoke** [comment]
Please assist. How do i contact SpamBot?

**Comment by toyovoke** [comment]
Reached now. Thanks

**Comment by Ryuno-Ki** [comment]
Like you would any user.
See https://github.com/zhukov/webogram/issues/1609#issuecomment-360399717 for example.
Start a conversation with him.

If that does not work, contact in-app support:
telegram.org/support or "Ask a Question" in Settings

**Comment by stek29** [comment]
You might also be banned/limited in supergroup/channel you're trying to write to

**Comment by Nemusha69** [comment]
Method: messages.sendMessage

Result: {"_":"rpc_error","error_code":400,"error_message":"USER_BANNED_IN_CHANNEL"}

What is meant by it???

**Comment by ba31150** [comment]
Hi. First I just orangeed the background color of Google, then the system
crashed. Then my nerves got messy ... I'm sorry if you had a problem.

‫‪Nemusha69‬‏ <‪notifications@github.com‬‏> در تاریخ جمعه ۱۰ آوریل ۲۰۲۰
ساعت ۲۱:۰۳ نوشت:‬
