### ISSUE TITLE
What's your solution for downloading?

### ISSUE THREAD

**Issue by hosseinGanjyar** [zhukov/webogram#1714]
I want to download data stream from server.
What is your solution for streaming download?
Whats do you do for telegram web download?
Thanks

**Comment by stek29** [comment]
What data stream? Export your data?

**Comment by hosseinGanjyar** [comment]
@stek29 I've a table with paging server (24000 pages). So, user would to export all pages in one time. I get data 42000 times from server and I want to download these data.
How do I to do?
My data are same stream data.

**Comment by stek29** [comment]
How is that related to webogram?

**Comment by hosseinGanjyar** [comment]
@stek29 In **webogram** using this sulotion for download media & file.
Download streaming in web and save from begining on disk.

**Comment by stek29** [comment]
https://stackoverflow.com/questions/42614880/download-large-data-stream-1gb-using-javascript
https://developer.mozilla.org/en-US/docs/Web/API/Streams_API
http://danml.com/download.html
https://webapps.stackexchange.com/questions/41068/how-exactly-does-megas-download-work
https://stackoverflow.com/questions/18425823/how-mega-downloads-a-file
https://stackoverflow.com/questions/15994554/download-files-like-mega-co-nz
