### ISSUE TITLE
Suggestion to make unread favicon more distinguishable from the read favicon

### ISSUE THREAD

**Issue by orschiro** [zhukov/webogram#1718]
Dear all, 

I would like to suggest to make the unread favicon more distuingishable from the read favicon. 

This [video](https://drive.google.com/file/d/1dz4YKdKwYDsaH3D685oxYqu4sa0VUkqF/view) demonstrates the current state. 

I find it hard to disginguish because both are blue and occassionally the blinking letter freezes, making it not sufficiently evident that unread messages exist. 

Could we indicate the number of unread messages in the favicon, similar to the Gmail favicon that shows the number of unread emails?

Thank you!

Further resources:

Read favicon
![image](https://user-images.githubusercontent.com/170947/43724443-4118754a-999a-11e8-92c1-c64f86612053.png)

Unread favicon
![image](https://user-images.githubusercontent.com/170947/43724451-47bf43a6-999a-11e8-823d-1e48a9d0237b.png)

Gmail favicon count
![image](https://user-images.githubusercontent.com/170947/43897250-b78390a0-9bdb-11e8-8b63-04c2f3f3c6c4.png)

**Comment by stek29** [comment]
#1585
