### ISSUE TITLE
I can't change mu phone number in Telegram web. 

### ISSUE THREAD

**Issue by ahmadasemoni** [zhukov/webogram#1721]
Hi
I can't change mu phone number in Telegram web. In FAQ mentioned that we can change the phone number just with tap on it. But I can't. As my old number already expired and I just access to my telegram with Telegram web how I can change my number?

**Comment by stek29** [comment]
Log into your account via different app, code would be sent to webogram. Then wait for some time until session is trusted, and change the number.
See https://github.com/zhukov/webogram/issues/1439#issuecomment-314529035.

Btw, #1439 duplicate.
