### ISSUE TITLE
Clearing history from app does not clear the chat history from Telegram App

### ISSUE THREAD

**Issue by chaisme** [zhukov/webogram#1728]
Telegram web stores copies of chats locally wherever logged in. This is a huge security flaw. 
Clearing chat history does not reflect immediately on Telegram web.

**Comment by stek29** [comment]
Define "immediately".
How is it supposed to remove messages before getting an update from server saying that messages should be removed?

**Comment by chaisme** [comment]
You are right. I should have been more specific. History wasn't being cleared even after multiple refreshes within a time span of a day. The issue is resolved after the latest app update.
