### ISSUE TITLE
Emoji in the channel name

### ISSUE THREAD

**Issue by ThePlenkov** [zhukov/webogram#1738]
Hi - if there is emoji in the channel title - it's not shown properly in the web:

![image](https://user-images.githubusercontent.com/6381507/44977900-a76a7980-af69-11e8-9b71-700cbd517f98.png)
![chrome_2018-09-03_11-06-18](https://user-images.githubusercontent.com/6381507/44977918-afc2b480-af69-11e8-9dc6-dc32c8cc7c93.png)

**Comment by kworr** [comment]
I guess this is `font-weight: 700;` or something like that in app.css. Flags are still font symbols yet they can't be "bold".

**Comment by ThePlenkov** [comment]
is there a chance to replace it with png files? like emojione do?

**Comment by kworr** [comment]
Heh, you are missing the point. I did use EmojiOne and currently I do use TwEmoji. Nothing changes for that as after applying font-weight that's a totally different glyph. Are you proposing extra bunch of code just for the sake of parsing *boldified* stuff to exempt some symbols from it?

**Comment by Aokromes** [comment]
generic bug
