### ISSUE TITLE
Dark Mode on Telegram Web Version Extention on Chrome Browser.

### ISSUE THREAD

**Issue by gvanosch12** [zhukov/webogram#1740]
Hi,

Could it be an idea to implement a darkmode settings on the Telegram Web Version Extention on the Google Chrome browser as the same as the "Cliënt for Telegram"app on Windows 10 desktop version

Geert Van Osch

**Comment by melyreturns** [comment]
I would like to participate, I was looking for the night mode on the extension.

**Comment by Aokromes** [comment]
https://github.com/zhukov/webogram/issues/1100

**Comment by atok71** [comment]
Unsubscribed pls
