### ISSUE TITLE
Emoji turns message into link

### ISSUE THREAD

**Issue by jonathandturner** [zhukov/webogram#1745]
If you tag someone at the beginning of a message and then end the message with an emoji, it turns the whole message into a clickable link that goes nowhere. I think the expected behavior would be that the tagged name is the only clickable link and the emoji has no effect on what becomes clickable.

**Comment by stek29** [comment]
I am unable to reproduce it. Could you please post an example of such message?

**Comment by jonathandturner** [comment]
This may have been fixed since I filed the issue. If I can discover the additional repro tests, I'll open a new issue.
