### ISSUE TITLE
Clock format broken

### ISSUE THREAD

**Issue by SammoLove** [zhukov/webogram#1747]
Hi. Message time is unreadable now, for example "4:03:15 PM". how to decode it? Is it 4 of night or 16? I know, with google. But it is very uncomfortable. Can you please make setting/preference to restore normal international time format?

**Comment by optyler** [comment]
If we follow [this website](https://www.timeanddate.com/time/am-and-pm.html), `4:03:15 PM` means `16:03:15`

Am I missing something?

**Comment by stek29** [comment]
@optyler I guess @SammoLove just wants 24h format, not 12h.

**Comment by Aokromes** [comment]
https://github.com/zhukov/webogram/issues/579
