### ISSUE TITLE
"Telegram Desktop" and "Telegram Web" emoji differ 

### ISSUE THREAD

**Issue by ArmeF97** [zhukov/webogram#1760]
See this issue
https://github.com/telegramdesktop/tdesktop/issues/5234

**Comment by akaleeroy** [comment]
This is a very old situation with no fix in sight, see [these reddit threads](https://www.reddit.com/r/Telegram/search?q=emoji+author%3Aakaleeroy&restrict_sr=on&sort=relevance&t=all)

### Workaround

Install a userscript manager such as @violentmonkey and [Telegram Web Emojione Userscript](https://greasyfork.org/en/scripts/38330-telegram-web-emojione)

**Comment by ArmeF97** [comment]
You are supposing I'm browsing the web version with a customizable browser, which I'm not

**Comment by stek29** [comment]
#760
