### ISSUE TITLE
Clicking the Chrome Notification opens a new Webogram tab every time

### ISSUE THREAD

**Issue by akaleeroy** [zhukov/webogram#1761]
Latest Chrome on Windows: clicking the notification takes you to **a new Telegram Web tab every time.**
Expected behavior: notification takes you to the existing Webogram tab.

Considering the age of the rest of the issues this is probably futile, but even if this repo is effectively abandoned at least the issue's out there for others to see. :roll_eyes:

**Comment by TLuigi003** [comment]
A workaround is Using Chrome's Notification Own System instead of Windows10 notification system.
This can be toogled in chrome://flags/#enable-native-notifications
Setting that flag to "disabled" tells Chrome to use its own system, which works fine with Webogram.

**Comment by stek29** [comment]
that sounds like chrome bug

**Comment by TLuigi003** [comment]
WhatsApp Web does redirect properly to the conversation(most of the times at least) so maybe API is not being used properly

**Comment by akaleeroy** [comment]
I haven't noticed this issue anymore, it seems to have resolved in Chrome 70.0.3538.110
Leaving this open for a few more days to be sure.

**Comment by TLuigi003** [comment]
Closed issue, just for history reasons, it was indeed a chrome bug: https://bugs.chromium.org/p/chromium/issues/detail?id=898486

**Comment by akaleeroy** [comment]
Seeing this bug again, won't reopen because it's not a Webogram bug.

**Comment by akaleeroy** [comment]
Seeing this bug again. And again, WhatsApp notifications are unaffected.

So it's probably a Webogram bug.

**Comment by TLuigi003** [comment]
As far as I have tested WhatsApp notifications seem affected but not always.
I'm not clear about how to reproduce the bug in WaWeb but I can confirm it's happening so I won't be that sure that it's a Webogram problem

**Comment by akaleeroy** [comment]
Well this isn't happening anymore, closing this issue. Whatever it was the browser was at fault.
