### ISSUE TITLE
Changing my display name only changes it for me

### ISSUE THREAD

**Issue by jlei523** [zhukov/webogram#1782]
On my Mac Telegram client, I changed my first name and removed my last name. However, this change only worked for my own client. I see the changes in my client. However, when someone else views my messages, they still see my full name.

This means whoever changes their name is under the impression that it has changed for everyone without a way of knowing that it only changed for their own client.

This seems like a huge privacy issue.

**Comment by jvschiavo** [comment]
This is probably because that person has you added in their contacts. Then, no matter what name you put, they will always see the name they've added on their contacts list. You can verify that by asking other people to see if your name has changed.

**Comment by stek29** [comment]
how is this related to webogram?
