### ISSUE TITLE
[FirefoxOS] "Generating Keys" is pretty damn slow 

### ISSUE THREAD

**Issue by willyaranda** [zhukov/webogram#18]
At least 4 minutes. "PQ factorization start" takes most of the time. I have log without timestamps, but with the full flow.

**Comment by DiogoConstantino** [comment]
I've the same problem with Firefox (fennec, and desktop versions)

**Comment by zhukov** [comment]
@DiogoConstantino what is the hardware? Did you try the same in different browser? Safari / Chrome / Opera ? Can you collect debug info from console?
