### ISSUE TITLE
Firefox web notifications after tab close

### ISSUE THREAD

**Issue by raisedfist** [zhukov/webogram#1801]
Getting web notifications from telegram even after closing the tab used for http://web.telegram.org. This is on linux:

Fedora 29
Linux hostname 4.19.15-300.fc29.x86_64 #1 SMP Mon Jan 14 16:32:35 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

Firefox 64.0.2 (64-bit)

**Comment by stek29** [comment]
that's a feature.
