### ISSUE TITLE
Play video after lock screen.

### ISSUE THREAD

**Issue by gaitan2** [zhukov/webogram#1812]
STR:
1. Open telegramm.
2. Open chat.
3. Tap on video.
4. Lock phone.

Actual result: video still planing.
Expect result : video must be stopped.

**Comment by gaitan2** [comment]
Android 7.1.2
Phone Xiaomi Redmi 4X

**Comment by stek29** [comment]
Are you talking about webogram?

**Comment by gaitan2** [comment]
Hi. Not about webogram. I'm talking about Telegram on phone (Xiaomi Redmi 4x)

**Comment by stek29** [comment]
then go report it somewhere else.

**Comment by stek29** [comment]
(on Twitter or via in-app support)

also, I believe it's a feature.
