### ISSUE TITLE
Can't log in after "generating keys"

### ISSUE THREAD

**Issue by MrSogris** [zhukov/webogram#1822]
Hi!
I installed the Chrome app, but could not log in. App starts without problems, generates keys, shows notification that I should open the app to log in. But in the app I still see start screen, with my telephone number. If I click "Next" it will generate keys again.. What's wrong?

**Comment by cyaniventer** [comment]
are you able to `ping telegram.org` and `ping web.telegram.org`? I had the same issue, it was my ISP blocking telegram web.

**Comment by MrSogris** [comment]
No, I'm sure I can't ping telegram official addresses, because of blocking. But in the same network, I can use  mobile and desktop clients without any problem. I thought Webogram works like any other client...

**Comment by cyaniventer** [comment]
If you can't ping telegram.org then the web version wouldn't work, apps still work for me too. Maybe they don't rely on connecting to telegram.org, idk. For now you should probably use the app or use some sort of proxy to connect to web.telegram.org

I am myself using Tor to access Telegram web.

**Comment by zhukov** [comment]
Telegram Web can't work without access to web.telegram.org.
