### ISSUE TITLE
Text is super blurry

### ISSUE THREAD

**Issue by Avamander** [zhukov/webogram#1827]
After the latest update the channel list text has become super blurry and disturbing to read. The picture displays exactly how blurry it is on my screen.

I'm using Chromium 72.0 on Ubuntu 18

![image](https://user-images.githubusercontent.com/5392141/53993096-17cf9e80-4137-11e9-8131-5cc9e1fb0e20.png)

**Comment by qWici** [comment]
@Avamander what about Firefox? Also try in incognito mode

I tested Chromium 72.0 on Ubuntu 18.04 and everything works fine.
![image](https://user-images.githubusercontent.com/11472929/54235983-365cdd80-451b-11e9-937f-7eb1553ae68f.png)

**Comment by Avamander** [comment]
I don't have Firefox installed because I have no use for it.

I have enabled GPU acceleration though to have smooth video playback, maybe that affects the rendering in Telegram? If I remove any CSS height or padding attribute the text unblurs.

**Comment by qWici** [comment]
@Avamander I have enabled GPU acceleration too. This problem also appears in Incognito mode?

**Comment by Aokromes** [comment]
https://github.com/zhukov/webogram/issues/1819
