### ISSUE TITLE
Web Sign-In Page

### ISSUE THREAD

**Issue by Jach67** [zhukov/webogram#1828]
1:
When using the Web log-in page, the user only has the phone option for receiving code activation which is wrong.
Imagine if the user doesn't have access to his/her phone at the moment and they want to have access to the app, they'll stuck!
The solution would be to add the email as an option to receive the code as well.
<img width="1357" alt="Screen Shot 2019-03-10 at 1 20 04 PM" src="https://user-images.githubusercontent.com/48414677/54088918-68aee500-4339-11e9-94fe-4a4380f322f3.png">

2:
When clicking on the learn more option on the same page, there's no way to scroll back up unless refresh the page. (using chrome on mac)
<img width="1359" alt="Screen Shot 2019-03-10 at 1 19 54 PM" src="https://user-images.githubusercontent.com/48414677/54088921-6cdb0280-4339-11e9-967e-6e98c5dfdd13.png">

**Comment by zhukov** [comment]
This is a feature request for Telegram Platform, not for Telegram Web app. Please contact in-app support  on mobile apps (Settings - Ask a question) for this kind of requests.
