### ISSUE TITLE
Make "<3" transform into a heart emoji

### ISSUE THREAD

**Issue by Kerooker** [zhukov/webogram#1833]
Similarly to #297, but not exactly.

In WhatsApp (quoting Whatsapp as it's the biggest competitor to Telegram), when one type "<3" in the web application (web.whatsapp.com), it turns into a red heart emoji.

This is a common behavior for people that use Whatsapp Web, and it would be great for Telegram Web to include this too.

This is not exactly #297 because not all typed emojis would be converted, just the heart. For example, in Whatsapp, ":D" is not converted to an emoji.

If this issue makes sense, I'd be glad to implement this change

**Comment by zhukov** [comment]
Thanks for the suggestions, but replies are currently consistent across all the platforms and web version is just supporting the same format. You can forward your suggestions to "Help - Ask a question" in mobile apps or in Twitter twitter.com/telegram
