### ISSUE TITLE
Can't log in from multiple machines/connections

### ISSUE THREAD

**Issue by AlessandroFumi** [zhukov/webogram#1839]
![reportbug](https://user-images.githubusercontent.com/23718625/56249015-711ddc80-60aa-11e9-828f-48e3d7ca1baa.png)

Hello guys!

For some days I've been unable to connect to web.telegram.org.
I've used it extensively for the last years without any issue, but this time I could not find any solution. I tried logging in from two different machines (Windows 8.1, Linux 16.04), different internet connections (home, work, both in Germany and Switzerland) and different browsers (Chrome, Brave and Franz for Linux)

My Telegram for Android v5.5.0 (1545) is working perfectly fine.

Thank you in advance for every suggestion.

**Comment by matextrem** [comment]
Same here.

**Comment by AlessandroFumi** [comment]
Now it works, it was probably a problem of the servers

**Comment by zhukov** [comment]
Was fixed from server-side.
