### ISSUE TITLE
My Hdd fulldisk - How to delete save files?

### ISSUE THREAD

**Issue by ZhLongDuo** [zhukov/webogram#1845]
When I save files on Group, I was removed to other Folder, but My HDD (on Mac) notice full. I want to delete temp files, but I don't find files store folder. Please help. I'm using Telegram on Chrome with Mac OS.
Thanks

**Comment by phongphong09** [comment]
Khi tôi lưu tệp trên Nhóm, tôi đã bị xóa sang Thư mục khác, nhưng Ổ cứng của tôi (trên máy Mac) thông báo đầy đủ. Tôi muốn xóa các tập tin tạm thời, nhưng tôi không tìm thấy thư mục lưu trữ tập tin. Hãy giúp tôi. Tôi đang sử dụng Telegram trên Chrome với Mac OS.

**Comment by zhukov** [comment]
Duplicate of #1691
