### ISSUE TITLE
Feature Request: Dark theme mode option for website version. White is painful for eyes in Night and even in day.

### ISSUE THREAD

**Issue by PranavBhattarai** [zhukov/webogram#1861]

**Comment by Aokromes** [comment]
https://github.com/zhukov/webogram/issues/1100

**Comment by atok71** [comment]
Stop it bastard

**Comment by PranavBhattarai** [comment]
> Stop it bastard
> […](#)
> Sent from my iPhone
> On 20 Feb 2020, at 2:07 AM, Aokromes ***@***.***> wrote: Closed #1861. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

But its really a nice option to have. We have that option in Telegram mobile app, why not also in the web version!
