### ISSUE TITLE
Translation to German

### ISSUE THREAD

**Issue by TechnikTim** [zhukov/webogram#1862]
If a new person uses Telegram, it will not be translated.
Instead of **"Name" benutzt jetzt Telegram** there is only **"Name" joined Telegram** like on the Picture.
It´s not a huge problem but I think it´s easy to fix

![InkedUnbenannt_LI](https://user-images.githubusercontent.com/47526678/59280016-34630180-8c65-11e9-8e12-16c955b04adf.jpg)

**Comment by Ryuno-Ki** [comment]
Translations are maintained on Transifex. See https://github.com/zhukov/webogram/blob/master/CONTRIBUTING.md#localization

**Comment by Cyber1000** [comment]
@Ryuno-Ki I don't see any hint to Transifex if I click your link, is this still up-to-date?
There is also a link to "Telegram Translations Manual" which doesn't work, I think it should rather be something like https://translations.telegram.org/

To fix this special issue, I think this should fix it, shouldn't it?https://translations.telegram.org/de/search?query=joined%20telegram

So is this request on the offical telegram-page sufficient to get this translation in "webogram" on the next release?

**Comment by TechnikTim** [comment]
The issue is fixed long ago 👍
