### ISSUE TITLE
INPUT_REQUEST_TOO_LONG 4 4

### ISSUE THREAD

**Issue by cpanels** [zhukov/webogram#1867]
i cant edit media message via message.editMessage

```
MtpApiManager.invokeApi('messages.editMessage', {
        flags: (1 << 14),
        peer: AppPeersManager.getInputPeerByID(peerID),
        id: AppMessagesIDsManager.getMessageLocalID(messageID),
        message: text,
	media: inputMedia,
        entities: getInputEntities(entities)
      })
```

he said error

`Rpc error {code: 400, type: "INPUT_REQUEST_TOO_LONG", description: "CODE#400 INPUT_REQUEST_TOO_LONG", originalError: {…}}`

**Comment by zhukov** [comment]
There is problem with TL serialization on your side.
