### ISSUE TITLE
Frozen "Generating keys" - how to proxy requests of Angular?

### ISSUE THREAD

**Issue by nsuvorov83** [zhukov/webogram#1871]
It's not a duplicate #277. There is an error in Chrome Console:
angular.js:9683 POST https://venus.web.telegram.org/apiw1 net::ERR_TIMED_OUT

So how to handle it? May be this request can be proxied through same server where webogram installed (using nginx for ex.)? Anyone did it?

**Comment by stek29** [comment]
https://gist.github.com/stek29/47a4a02c4fb82d79dbe52d4f36efe163
