### ISSUE TITLE
How can I enable new design?

### ISSUE THREAD

**Issue by Neurotoxin001** [zhukov/webogram#1873]
I see new design on screens here:
https://github.com/zhukov/webogram

But on web.telegram.org I have old version 0.7.0.

**Comment by Bartwillemsen** [comment]
It's actually the other way around: the screenshots are really old and that's the old design :stuck_out_tongue: there is no newer design than the one used now as far as I know.

**Comment by AdelStoreInc** [comment]
You can create one by yourself

**Comment by AdelStoreInc** [comment]
edit the .css files
