### ISSUE TITLE
Cant login - TOO FAST message

### ISSUE THREAD

**Issue by AlexDolinin** [zhukov/webogram#1875]
Just tryng to login on new PC, choose country (+7) and enter my phone number.
When clicking next - i get message Too fast with details:
Method: auth.sendCode
Result: {"_":"rpc_error","error_code":420,"error_message":"FLOOD_WAIT_86400"}

![111](https://user-images.githubusercontent.com/52735974/60948515-be04fe00-a2fb-11e9-96c4-f45fe8b9049d.png)

I am not ready to wait 60 days...

**Comment by gism4rc0s** [comment]
I am. Im ready to waiy 3 more years.

**Comment by 09029516849** [comment]
099232599iì

**Comment by avastar** [comment]
I believe this is an intentional crash. The collaborators here and telegram itself have collaborated to sabotage the program when anyone tries to use TOR to create an account. Instead, just go to any random library and create the account with the fake phone number.

**Comment by zhukov** [comment]
This is a bug report for Telegram Platform, not for Telegram Web app. Please contact in-app support  on mobile apps (Settings - Ask a question) for this kind of requests.
