### ISSUE TITLE
Don't show codes for new devices on lock screen (android app)

### ISSUE THREAD

**Issue by avl42** [zhukov/webogram#1879]
I'm aware that I could disable showing messages on the lock screen altogether, but I really only want to inhibit getting the codes for a new device on the lock screen.

As it is, someone who knows my phone number and has temporary physical control over my locked phone can easily connect his phone by entering my phone number and reading the code from my lock screen.  I'll see it eventually, but that might be too late.

One idea to solve it:
there should be a way to tag sent messages as "somewhat confidential" which would mean that it should not be readable on lock screen of a phone, nor in a notification popup on web or desktop clients.  this "somewhat confidential" would still be less confidential than a secret chat.)  Codes for connecting new devices should then be sent with such a tag.

Another idea: send codes over a "secret chat" - someone adding a new device can be assumed to be online on at least one of the already connected devices.

**Comment by avl42** [comment]
Btw., imagine you showing person "A" some pictures on your phone, and suddenly telegram pops up and person "B" writes you something that "A" shouldn't know (e.g. a planned b-day party)...    I really like this idea of "somewhat confidential" messages, that only become readable once I switch to telegram app.

**Comment by tarres** [comment]
That is an issue of the Android App, not this web client. This is the wrong place for this issue.

**Comment by avl42** [comment]
I apologize, I missed that this is specifically for the web client.

Since the web client can also pop up notifications (unless disabled by the browser),  this "issue" also indirectly affects the web client, but the actual decision for such a feature surely happens somewhere else. (umm, where? - I'd appreciate a hint as I only found twitter links so far as ways of contact)
