### ISSUE TITLE
Flags are not displayed in username

### ISSUE THREAD

**Issue by andyrozman** [zhukov/webogram#1880]
When I am using Telegram through web interface, flags beside someones username are not displayed. When I look at usernames in Android app I can clearly see the flag(s), here its just letters in the box (see attached picture).

![image](https://user-images.githubusercontent.com/5500133/61945014-e39a3480-af96-11e9-9953-147cf9a14ba4.png)

There should be 3 flags displayed here: Polish, Irish and EU one.

**Comment by Aokromes** [comment]
generic bug #996
