### ISSUE TITLE
cannot receive SMS code when login with numbers through webclient

### ISSUE THREAD

**Issue by shi-xiaopeng** [zhukov/webogram#1884]
Located in Mainland China, I found I cannot receive SMS code any more，maybe SMS code send from you is blocked by our  telecom carriers. Hope that u can provide register and login through email.

**Comment by Trangphieu2** [comment]
Method: auth.sendCode
Result: {"_":"rpc_error","error_code":420,"error_message":"FLOOD_WAIT_65183"}

**Comment by Steve126-sudo** [comment]
hi i cannot receive sms code, in kenya

**Comment by zhukov** [comment]
This is a bug report for Telegram Platform, not for Telegram Web app. Please contact in-app support  on mobile apps (Settings - Ask a question) for this kind of requests.
