### ISSUE TITLE
Can't login from local server

### ISSUE THREAD

**Issue by k1tzu** [zhukov/webogram#1886]
It says "We've sent an SMS with an activation code to your phone." and nothing - I've got no SMS.
The same time web.telegram.org is working and instead saying "We've sent the code to the Telegram app on your other device."

Is it supposed to work locally? I want to give not IT users the ability to easily talk to my Telegram bot from my website. Without teaching them how to add a bot contact, find it somewhere, enter it somehow, etc.

**Comment by zhukov** [comment]
You should use your own api_id.
