### ISSUE TITLE
Reverse any group member to phone number with phone contacts

### ISSUE THREAD

**Issue by walterF** [zhukov/webogram#1888]
When I add phone number and use the number as contact name. (For example, a amount of phone number added by program)
![image](https://user-images.githubusercontent.com/5158696/63640235-54388c00-c6d0-11e9-9541-6b48a432f9e5.png)

Telegram is able show with contact name (their phone number) and their icon (if turned on)
![image](https://user-images.githubusercontent.com/5158696/63640250-7b8f5900-c6d0-11e9-92aa-6de2d5f56e9f.png)

Now if we have any public/private common group, I can check their number and conversation (even user tried to hide their phone number)
![image](https://user-images.githubusercontent.com/5158696/63640219-310ddc80-c6d0-11e9-841e-1ab06d560ecf.png)

It is a huge security leakage issue. Please help to hide user data and allow user to not show their name, even on phone contacts.

**Comment by zhukov** [comment]
Was already implemented in mobile apps:
https://telegram.org/blog/scheduled-reminders-themes#new-privacy-settings
