### ISSUE TITLE
The message is not supported on your version of Telegram Web. Update the app to view: web.telegram.org

### ISSUE THREAD

**Issue by coari** [zhukov/webogram#1895]
The message is not supported on your version of Telegram Web. Update the app to view: web.telegram.org.

All the time see this! How to solve?

**Comment by ogghi** [comment]
Yeah, it is when animated stickers come in...is this on the future list to be supported?

**Comment by sirtoobii** [comment]
Duplicate of
#1850

**Comment by Aokromes** [comment]
well, without link to the exact message we cannot know what's the afected feature.

**Comment by mschumacher69** [comment]
I guess this is for animated stickers.

**Comment by Aokromes** [comment]
well, if it's animated stickers
https://github.com/zhukov/webogram/issues/1874
