### ISSUE TITLE
Doubt configuration or possible feature to implement

### ISSUE THREAD

**Issue by tghelere** [zhukov/webogram#1896]
Hey guys, how are you?
I would like to know if it is possible, in the telegram app or web, to order conversations so that chats with single contacts (one person) would be ahead of all group conversations.

* For me who are (actively or passively) part of many groups, I have difficulty identifying answers in personal chats.

Thank you very much

**Comment by zhukov** [comment]
This is a feature request for Telegram Platform, not for Telegram Web app. Please contact in-app support  on mobile apps (Settings - Ask a question) for this kind of requests.

**Comment by tghelere** [comment]
Sorry, I don't know if I understand.
I use telegram web daily, I'm using it right now and I use very little telegram app (desktop or mobile)

I need to pin certain contacts on top to see if they have sent me messages. However I can not fix all contacts and there is a limitation of being able to fix a maximum of 5 contacts.

![Telegram Web](https://user-images.githubusercontent.com/5022782/71183247-68436300-2256-11ea-9135-9336765c9490.png)
