### ISSUE TITLE
Record and send audio message

### ISSUE THREAD

**Issue by staltz** [zhukov/webogram#190]
Android and iOS clients [recently got](https://twitter.com/telegram/status/447092910261948416) support for recording, sending, and playing audio (voice) messages.

Webogram already supports playing those audio messages, and that's great. The small little bit remaining is to allow recording and sending on the web client.

**Comment by TitanNano** [comment]
I sent a audio (ogg file) to someone and telegram displayed it as a video.... would it at least be possible to treat audio files like voice messages? I also received a voice message and it was a ogg file too, but it got some nice voice message UI.

Anyway, I'd like to implement this, but I'd need some assistance for the UX and where to place the code.

**Comment by TitanNano** [comment]
@zhukov I'd be happy to polish my PR, if you are interested to merge it :D Are you interested to land this feature? Chrome also supports this technology now.

**Comment by zhukov** [comment]
@TitanNano Yes, I'm interested for sure!
We need to make it work in Chrome/Fx/Safari on desktop as well and to have some backward compatibility in UI for browsers without proper support. Also the audio file should be compatible with other Telegram clients (they should be able to play it).

**Comment by TitanNano** [comment]
@zhukov okay I will work on it! 
1. Firefox Chrome support should work fine, they both support all the required apis. 
2. For backwards compatibility, is it okay to just not show the recording button? We should make the feature progressive. Only offer it if the platform supports it.
3. Safari support is impossible, they don't support userMedia or MediaRecorder APIs.

**Comment by zhukov** [comment]
2. On desktop - yes, but I'm not sure about mobile. We could change UI if we have mic record button, to be more like iOS / Android. In this case we should show disabled 'Send' button when there is no support for audio capture.

**Comment by TitanNano** [comment]
@zhukov can you give me UI examples from iOS  and android? (screenshots)

**Comment by zhukov** [comment]
@TitanNano 
![1111](https://cloud.githubusercontent.com/assets/775173/21052539/937fb9b0-be36-11e6-8d42-e314e5494723.jpg)
![2222222](https://cloud.githubusercontent.com/assets/775173/21052540/93b99d38-be36-11e6-8ba8-1718c1db55b4.jpg)

I could only get iOS ones. But the UX is almost the same on Android.

**Comment by Akronix** [comment]
Hi @TitanNano .

Here it is the Android one. As @zhukov already said, it's almost the same than the iOS one:
![photo44377049962490681](https://cloud.githubusercontent.com/assets/2631430/21118715/60e1ca1c-c0bf-11e6-85ba-609eefcf616f.jpg)

**Comment by TitanNano** [comment]
Thank you very much :) I'll try to recreate this UX. I'm going to try to re implement this feature, based on my previous implementation, in January!

**Comment by Ryuno-Ki** [comment]
@TitanNano Ping me if you struggle on the design. Do you already have a PR open for your previous implementation?

**Comment by TitanNano** [comment]
@Ryuno-Ki yes #840

**Comment by wehlutyk** [comment]
Awesome to see this come back to life!

**Comment by orschiro** [comment]
Hello everyone,

Is there any chance this gets implemented in the future?

Yours,

Robert

**Comment by Ryuno-Ki** [comment]
I've pinged @TitanNano.

**Comment by zhukov** [comment]
The feature was implemented and rolled out to beta:
https://zhukov.github.io/webogram/

**Comment by orschiro** [comment]
Amazing!

How can I test it?

Opened your link but don't see any option.
