### ISSUE TITLE
[QUESTION] Is the Webogram Project Officially Dead

### ISSUE THREAD

**Issue by LulzRose** [zhukov/webogram#1900]
Is the webogram project officially dead? There have been no updates in months and no word from the dev.

**Comment by gelav** [comment]
[Here's the alternative Telegram React](https://github.com/evgeny-nadymov/telegram-react)

**Comment by sirtoobii** [comment]
@zhukov Would it be possible to get an "official" statement from you?

**Comment by ShockwaveNN** [comment]
@sirtoobii I've asked Pavel Durov that question and never received any answer
https://twitter.com/ShockwaveNN/status/1174348519118909440

**Comment by sirtoobii** [comment]
@ShockwaveNN Thank you for bringing this up. I created a support ticket asking about the future of web.telegram.org. I will post an update if I get a reply.

**Comment by RainerZufahl** [comment]
> 
> 
> @sirtoobii I've asked Pavel Durov that question, and asked is `webogram` official telegram web client or developed by third party developers and never received any answer
> https://twitter.com/ShockwaveNN/status/1174348519118909440

web.telegram.org is developed by a third party and not by Telegram themselves, but they do support it enough to host it on their own web server. 
Still they've recently held a contest for a new web-app, so expect a new (fully official) service to come more or less soon.

**Comment by Aokromes** [comment]
it updates slowly, but still alive.
