### ISSUE TITLE
Abandoned project?

### ISSUE THREAD

**Issue by roukmoute** [zhukov/webogram#1906]
You have many pull requests and the latest updated is several months old.

**Comment by MartinX3** [comment]
Yes, that's a good question.
There can be many "contributors" but if there is none who merges the code the project is "dead".
Especially since a fork is not likely to run on the official https://web.telegram.org address.

**Comment by Ryuno-Ki** [comment]
I am into Frontend Development professionally.
I found it hard to get into TypeScript. And RxJS (Observables, Subjects etc).
But sure, go ahead and raise the bar to contribution, because Google says it's great …

**Comment by azzimuth** [comment]
Yes, this project is dead

**Comment by ShockwaveNN** [comment]
@azzimuth Are you official representative of this project?

**Comment by elky** [comment]
Looks like Telegram is going to create new web version. They launched appropriate [Javascript contest](https://t.me/contest/118) recently.

**Comment by azzimuth** [comment]
> @azzimuth Are you official representative of this project?

No

**Comment by Otto-AA** [comment]
[Telegram React](https://github.com/evgeny-nadymov/telegram-react) is also an official web client for Telegram. It is currently more active than webogram.

**Comment by azzimuth** [comment]
> [Telegram React](https://github.com/evgeny-nadymov/telegram-react) is also an official web client for Telegram. It is currently more active than webogram.

Thanks for the hint. Looks promising. Though it lacks a lot of functionality... So I'll stick to Webogram for a while.

**Comment by omfgnuts** [comment]
> > [Telegram React](https://github.com/evgeny-nadymov/telegram-react) is also an official web client for Telegram. It is currently more active than webogram.
> 
> Thanks for the hint. Looks promising. Though it lacks a lot of functionality... So I'll stick to Webogram for a while.

React version is much more advanced, maybe you haven't looked enough?

**Comment by azzimuth** [comment]
> > > [Telegram React](https://github.com/evgeny-nadymov/telegram-react) is also an official web client for Telegram. It is currently more active than webogram.
> > 
> > 
> > Thanks for the hint. Looks promising. Though it lacks a lot of functionality... So I'll stick to Webogram for a while.
> 
> React version is much more advanced, maybe you haven't looked enough?

I have used it couple of days but that didn't go that well. Couple of things I actively use and which work in Webogram but don't work in Telegram React:
* mentions
* GIF bot (@gif)
* No support for voice messages

Plus I don't like that the Forward, Edit, Delete etc. buttons appear at the top of the page when I select messages (in Webogram they appear in the bottom).

**Comment by tj-ux** [comment]
Hello. Tell me, is it possible to open web telegrams on a simple push-button telephone? this site: www.web-telegram.ru does not open. Only Facebook opens.

The phone has a built-in browser Java ME · SEMC Browser. Third-party Java applications do not support the phone

**Comment by Aokromes** [comment]
it's slowly being updated.

**Comment by azzimuth** [comment]
Yeah, Zhukov has finally woken up

**Comment by azzimuth** [comment]
But now I think that it's dead again...
