### ISSUE TITLE
Don't connect in Russia

### ISSUE THREAD

**Issue by plyaskin** [zhukov/webogram#1910]
Webogram in Opera don't connect in Russia, could you solve this?

**Comment by xaozai** [comment]
This is probably because access to telegram is blocked in Russia. Use a proxy or VPN.
This app is just a client.

**Comment by plyaskin** [comment]
That's right but the official client is work without any proxy and VPN.

**Comment by Tobishua** [comment]
@plyaskin desktop and mobile clients have advanced features for get available IPv4 & IPv6 addresses but web client doesn't have, and web.telegram.org (*.telegram.org) blocked by roskomnadzor.
