### ISSUE TITLE
Feature Suggestion: Search for Emoticons

### ISSUE THREAD

**Issue by MarcMil** [zhukov/webogram#1927]
Rather than browsing through hundreds of emoticons, I often search for a specific emoticon (e.g. party hat). On my phone, I can simply search for an emoticon using a dedicated search bar on the emoticon selection widget.
I'd wish this was the case in the web version as well, since typing is (for me at least) much faster than navigating through many pages manually.

Thank you very much in advance :)

**Comment by Carighan** [comment]
You can already do that (in fact in most chat clients, not just telegram) by typing a colon, then starting to type the name of an emoji. It worked even in this comment window here. 😁

**Comment by MarcMil** [comment]
Oops, you're right :D I somehow thought that this should be in the emoticon widget itself, but this is even more convenient since no mouse is necessary. Thanks!
