### ISSUE TITLE
Telegram: Connecting.... Waiting for Network.... Retry...

### ISSUE THREAD

**Issue by agamerj** [zhukov/webogram#1942]
Hello, I am trying to access Telegram but it's not connecting properly and continuously shows error: Waiting for Network....Retry.

![sx-22-February-20-3062](https://user-images.githubusercontent.com/9323342/75061419-b438af80-5506-11ea-8b79-1ac485158e6c.png)

I have attached the console error for this.

![sx-22-February-20-3063](https://user-images.githubusercontent.com/9323342/75061501-ddf1d680-5506-11ea-9e5a-497430aa4727.png)

How can we fix this?

Thanks.

**Comment by juliogonzalez** [comment]
Are you in a country that blocks telegram? Maybe on a company that blocks websites or even all HTTPS traffice? Or your ISP? Does the Android app works if you connect a phone to the same network where this is happening?

There are a lot of reasons that could cause your problems, but what you see is most probably a network problem/restriction between you and the telegram API.

Try with other browser to load http://vesta1-web.telegram.org/apiw1 it should redirect you to https://core.telegram.org/

If you are on a country blocking Telegram, I think it is time to add this information to the README, to have information about this problem, so not that many issues about the same problem are created :-)

**Comment by Aokromes** [comment]
@agamerj i suggest you to try frigate vpn and add *.telegram.org to the list of domains using the proxy to see if it works for you, if it does, your country is blocking telegram.
https://fri-gate.org/

**Comment by agamerj** [comment]
> Are you in a country that blocks telegram? Maybe on a company that blocks websites or even all HTTPS traffice? Or your ISP? Does the Android app works if you connect a phone to the same network where this is happening?
> 
> There are a lot of reasons that could cause your problems, but what you see is most probably a network problem/restriction between you and the telegram API.
> 
> Try with other browser to load http://vesta1-web.telegram.org/apiw1 it should redirect you to https://core.telegram.org/
> 
> If you are on a country blocking Telegram, I think it is time to add this information to the README, to have information about this problem, so not that many issues about the same problem are created :-)

It is ISP which is blocking this because one of my friend who lives in different city can access it because the ISP is different. So it's a ISP level block. I don't have any other ISP in my area. Yes, they are using "CONNECTION RESET" kind of way to block the Telegram. So it will be blocked on both HTTP and HTTPS.

Something like this: https://i.imgur.com/9hFCqzf.png (Screenshot)

**Now coming to the Solution:**

Could you please tell me how can I replace or remove the blocked URLs and use the working one?

For example, vesta.web.telegram.org is not working but pluto.web.telegram.org loads and it's not blocked.

How can I make use of it?

Appeal: There is no point talking to the ISP or Government because they are stupid enough to block Telegram at the first place. So if you guys could help me?

**I don't wish to use VPN/Proxy because of the delay and latency issue. I use Telegram for work.**

Yes, If I use VPN, I can use Telegram properly (to just tell that VPN can make it work) but it adds a lot of latency.

Looking for more help from you guys @juliogonzalez @Aokromes and anyone else. :)

**Comment by Aokromes** [comment]
it's not telegram (web) issue then, we cannot help you if you don't want to use vpn.

**Comment by agamerj** [comment]
That is what I'm saying, it's not Telegram's issue but I want to use Telegram properly. I have explained above that only some API URL of Telegram are blocked not all of them.

For example, vesta.web.telegram.org is not working but pluto.web.telegram.org loads and it's not blocked.

If you could tell me how can I change the source code and use the working URL for myself?

**Comment by agamerj** [comment]
Telegram App on Mobile: Working 100% Fine.

web.telegram.org: some of the API URL is blocked. Like, vesta is blocked. But pluto is not blocked.
