### ISSUE TITLE
Remove css rules with browser prefixes

### ISSUE THREAD

**Issue by fleksl** [zhukov/webogram#1943]
Nowadays, all browsers support such css properties as 'transform, box-shadow, transition...' without prefixes. Need remove the prefixes for the supported properties.

Exceptions are two properties: 'font-smoothing, appearance'. View the list of properties on the official website: https://caniuse.com

**Comment by KovalenkoStas** [comment]
autoprefixer can take care about prefixes automatically per browserlist/browserconfig setup
