### ISSUE TITLE
Waiting for network.... Retry

### ISSUE THREAD

**Issue by rahulserver** [zhukov/webogram#1947]
From past few days I am getting the "Waiting for network... Retry" error on telegram web.
Here is what I see in console log:

![image](https://user-images.githubusercontent.com/5101740/75946898-70f61d80-5ec4-11ea-9077-b63cddfedca8.png)

Telegram version I am using is 0.7.0, browser: Chrome (Version 80.0.3987.122 (Official Build) (64-bit)) on windows 10

**Comment by Aokromes** [comment]
maybe your country banned telegram web, try opera enable vpn and  check if works.

**Comment by rahulserver** [comment]
@Aokromes no its not the case. Telegram web works on my system, but just the connectivity is discontinuous.
And this probably has happened since the latest update(or something that has happened recently).

**Comment by jace** [comment]
Same here with intermittent connection failures. The problem goes away with a VPN, so it appears to be faulty ISP censorship.
