### ISSUE TITLE
[Idea] Alternative login methods to 

### ISSUE THREAD

**Issue by thisIsTheFoxe** [zhukov/webogram#1948]
Hi,
First of all, I just wanna say how awesome Telegram is to even have an OS repo here, thanx u guyys!! <3

2nd, I got an idea:

related: #1657, I haven't looked too deep into the API & this repo, it might also entirely depend on the API...

_One thing that bothers me (in general, but especially right now) is that one has to have an active phone number to log into TG-web (from a PC), right..? Cuz, I don't always have that handy, and sometimes I just want to quickly check my msg. online._
SO: How about using **alternative login** methods e.g. Username & password, or (better, probably?): If the user has also an email **send the verification code to a linked email acc.**, or on e could use a 2FA authenticator app..
Obviously there is also the whole security thing.. but I really think it's worth considering...

Btw, notice that I say 'login', not 'registration'! I get that a phone nr is needed for initial verification. However, once I'm logged in, iirc I can also provide an email address, can't that be used to send the code?

**Comment by saeedjsanei** [comment]
فارسی بگید

در تاریخ جمعه ۱۳ مارس ۲۰۲۰،‏ ۳:۲۶ Henry <notifications@github.com> نوشت:

**Comment by Aokromes** [comment]
i doub telegram will ever allow non-phone number based accounts

**Comment by thisIsTheFoxe** [comment]
@Aokromes having a non-phone login doesn't mean that it has to be a non-phone acct, tho....
