### ISSUE TITLE
Adopt my Night Mode / Dark mode switch for the evening time.

### ISSUE THREAD

**Issue by Dorson** [zhukov/webogram#1966]
Would be nice, if the https://web.telegram.org had color settings for the night, evening time.

Recently I coded a flexible color mode switch with groups of CSS color variables and simple JS functions. jQuery has similar JS functions available too, in case you already use jQuery. No server-side coding needed :-)

Works with CSS color variables in one file, one JS color switch function in the settings, and one JS event call function to remember the user color preference.

Try it on the GitHub demo page:

https://dorson.github.io/CSS-Dark-Mode-and-color-switch/

Feel free to copy, fork, adopt, re-use, etc... +1

Have fun ! :+1:

**Comment by Aokromes** [comment]
https://github.com/zhukov/webogram/issues/1100
