### ISSUE TITLE
Implement multiple accounts

### ISSUE THREAD

**Issue by lehazyo** [zhukov/webogram#1984]
Hi, in mobile app there is an option to have multiple telegram accounts in one application.

Below is a screenshot of how switching accounts is implemented in mobile app.

![image](https://user-images.githubusercontent.com/4438321/85107520-c3aad980-b216-11ea-83f6-89986c7491fa.png)

Could you please implement it in web version?

**Comment by Aokromes** [comment]
https://github.com/zhukov/webogram/issues/1583
