### ISSUE TITLE
can't get code when regestering by the web

### ISSUE THREAD

**Issue by ilyapashuk** [zhukov/webogram#2014]
if I try to create new account in the web version, I don't getting sms or call code.
When i'm registering through the app or using web version to login to existing account, all works fine.

**Comment by ilyapashuk** [comment]
and also if I type number which I don't used for telegram before, I'm getting "code is sent to telegram app on your other device" message but I have no any other devs on this number.

**Comment by spbsi** [comment]
i have the same problem like you

**Comment by YosefSinger** [comment]
Same! 😀

**Comment by Aokromes** [comment]
i don't think this bug is on telegram side instead your country blocking the sms coming from telegram.

**Comment by mohsen121314** [comment]
hi wat

در تاریخ سه‌شنبه ۲۰ اکتبر ۲۰۲۰،‏ ۰۳:۰۱ Aokromes <notifications@github.com>
نوشت:

**Comment by YosefSinger** [comment]
That's what it would seem. Except that I tried many times from many devices, browsers and cities in the U.S.

Also using virtual phone numbers that aren't based on location but purchased from a cloud-service company (Google Voice, twilio, Clickatell).

**Comment by mohsen121314** [comment]
Hello, I am Iranian, tell me what to do, the cartoon gave me an account
with a legal name

در تاریخ دوشنبه ۱۹ اکتبر ۲۰۲۰،‏ ۱۷:۴۳ ilyapashuk <notifications@github.com>
نوشت:

**Comment by YosefSinger** [comment]
For documentation, I made a screen recording of the entire bug. https://drive.google.com/file/d/1bVegQNiiemXR7uiXgN1jjMSfWtPQdqGh/view?usp=drivesdk

(The video shows me entering a Google Voice number that **never** had a Telegram account before. Still, it says "sent to the Telegram app on your other device"! Then, when requesting an sms instead - no sms arrives in my Google Drive app. Then, when requesting a phone call instead - doesn't arrive as well).
Thank you!!

**Comment by Aokromes** [comment]
Try to contact http://twitter.com/smstelegram

**Comment by Aokromes** [comment]
https://github.com/zhukov/webogram/issues/2013
