### ISSUE TITLE
Bug : day-night icon in app

### ISSUE THREAD

**Issue by Alphasaurs** [zhukov/webogram#2015]
When click once this icon then icon change and toggle another mode but after clicking again this only toggle effect but doesn't change icon.
I am using telegram version 7.1.3 in android.
![IMG_20201022_095958](https://user-images.githubusercontent.com/50196057/96824930-a3ea2300-144d-11eb-9410-1f67fe59a71b.jpg)

**Comment by Aokromes** [comment]
this is telegram web, not telegram android repo. report it at https://t.me/tgbetachat read pinned message before.
