### ISSUE TITLE
Missing group in chats tab

### ISSUE THREAD

**Issue by pechavarriaa** [zhukov/webogram#2021]
Group randomly disappears from the chats tab.
When sending a message from the mobile app would make the chat come back, but after some inactivity the chat will disappear from the chats tab after refreshing the browser.

**Comment by crosspacific** [comment]
I also have this situation on my web telegram. Groups disappears from the chats tab.

**Comment by pechavarriaa** [comment]
This issue is no longer occuring on verzion /z so I am closing this issue
