### ISSUE TITLE
Can't upload files

### ISSUE THREAD

**Issue by emilio** [zhukov/webogram#2023]
Hi, I'm using Telegram Web and somehow I can't upload files (they just get stuck in "0 of Xkb", never finish).

I've tried with the following browsers:

 * Firefox Nightly
 * Firefox 82
 * Chromium Stable 85.0.4183.121
 * Chrome Dev Edition 88.0.4315.5

All of them with the same result.

There are no errors in the console, just some logs like:

```
[2711.811] Api call upload.saveFilePart app.js:60:3033
[2711.814] Api call upload.saveFilePart app.js:60:3033
[2711.816] Api call upload.saveFilePart app.js:60:3033
[2712.807] Api call account.updateStatus app.js:60:3033
```

Do you know how can I diagnose more?

**Comment by ayasystems** [comment]
I have the same problem.....

**Comment by gabrielsantossilva** [comment]
via na pa pasta do projeto estellar 
la tem o conteudo completo

**Comment by ayasystems** [comment]
Fails again 

![Screenshot_1](https://user-images.githubusercontent.com/7864168/99805180-65bf4c80-2b3c-11eb-82a2-75b657ab5d94.jpg)

**Comment by emilio** [comment]
Seems to be working for me now.
