### ISSUE TITLE
Saya minta Kode verifikasi di kirim melalui email

### ISSUE THREAD

**Issue by syahrialardi** [zhukov/webogram#2031]
Saya minta Kode verifikasi di kirim melalui email

**Comment by Aokromes** [comment]
english plz.

**Comment by syahrialardi** [comment]
I asked for the verification code to be sent via email

Pada tanggal 12 Des 2020 1.57 AM, "Aokromes" <notifications@github.com>
menulis:

**Comment by Aokromes** [comment]
that doesn't belongs here.
