### ISSUE TITLE
Please enable sensitive content

### ISSUE THREAD

**Issue by yusufmalikul** [zhukov/webogram#2034]
I am unable to join a group because it's marked as sensitive content. Please add an option to enable/disable this.

Thank you

![image](https://user-images.githubusercontent.com/15918537/102455394-1f450b00-4072-11eb-854a-67bc00ed00b1.png)

![image](https://user-images.githubusercontent.com/15918537/102455613-7814a380-4072-11eb-9a04-61cf76334a35.png)

**Comment by sfilmak** [comment]
Hi. This option should be available in settings:

![](https://habrastorage.org/webt/gt/s5/qi/gts5qikleqou5z3dteu--ghvwqi.png )

**Comment by yusufmalikul** [comment]
I don't have that option. Did telegram do sensitive content blocking for certain countries?

![image](https://user-images.githubusercontent.com/15918537/103500840-e339e480-4e7e-11eb-8df9-abb2ae5a642e.png)

**Comment by Aokromes** [comment]
afaik it depends on witch country you are.

**Comment by yusufmalikul** [comment]
> afaik it depends on witch country you are.

Right, I think it depends on the phone number. I use VPN but no luck.
I will close this because it doesn't relate to this project.
