### ISSUE TITLE
my wife sees my contacts and updates on her telegram

### ISSUE THREAD

**Issue by JeiPie** [zhukov/webogram#2081]
I,
whenever i add a contact to the telegram or one of my contacts joins the telegram, my wife sees my contacts and updates along with hers on her telegram.
It seems to me a serious problem of security and data privacy.

**Comment by Aokromes** [comment]
> I,
> whenever i add a contact to the telegram or one of my contacts joins the telegram, my wife sees my contacts and updates along with hers on her telegram.
> It seems to me a serious problem of security and data privacy.

not a bug, for sure you used your sim on the phone of your wife and it was added to telegram servers. delete sync contacts on the phone of your wife to delete your contacts.

**Comment by JeiPie** [comment]
I never used my sim on her cell phone.  this is very strange.
--
Enviado da aplicação myMail para Android quinta-feira, 25 março 2021, 05:04da tarde +00:00 de Aokromes  ***@***.*** :
