### ISSUE TITLE
Embarcados los cubanos que usábamos Telegram web a través de proxy en centros de trabajo sin necesidad de tener un móvil android

### ISSUE THREAD

**Issue by Vlader7508** [zhukov/webogram#2090]
Hasta hace bien poco tiempo estuve usando el Telegram web de https://zhukov.github.io/webogram y me enviaban el código de login vía SMS el cual recibía en mi viejo teléfono de teclas. Pero parece que actualizaron el sitio y ya estamos Embarcados los cubanos que usábamos Telegram web a través de proxy en centros de trabajo sin necesidad de tener un móvil android, ya que la app de Windows está bloqueada a través del proxy y solo los navegadores Chrome y Firefox pueden pasar a través del proxy. Yo sé que en la actualidad ya casi todo el mundo tiene un móvil Android con datos móvile, pero todavía quedamos algunos como yo de bajo perfil económico que aunque tengo un trabajo estatal de salario medio en Cuba, no he alcanzado a comprarme un nuevo teléfono Android luego de que el que antes tuve se me rompió y me vi obligado a volver a mi antiguo Samsung de teclas y creo que así estaré durante largo tiempo, ya que con el nuevo sistema económico aplicado en este país el salario no alcanza ni para comer a modo supervivencia. Sé que talvez no sea de su interés que todo el mundo sin excepción pueda usar Telegra, pero talvez si les guste poder alcanzar todos los rincones de la tierra.  Yo les estaría muy agradecido de que implementaran la opción de verificación por SMS al menos en un sitio como era el caso de este https://github.com/zhukov/webogram. Y no que tenga que ser a través de la app instalada en el teléfono Android como era con la app de imo y otras que hace algún tiempo ya, que no he podido usarlas más. Solo podía usar Telegram vía web y ya no podre usarla más a menos que pueda verificar vía SMS. Incluso les recomendaría para que sea mucho más perfecto aun, que se pudiera crear cuentas vía web con cualquier teléfono antiguo que soporte SMS, para que llegue a ser de tan fácil acceso como Messenger que en ningún momento te obliga a recibir ningún código en tu app Android para poder ingresar vía web. Mis Saludos y mi respeto. Tengo cuenta hace años mi número es el +5353125406. Pueden localizarme para lo que deseen. Muchas gracias de antemano.

**Comment by Aokromes** [comment]
https://bugs.telegram.org/c/4239
