### ISSUE TITLE
Unresponsive Support service.

### ISSUE THREAD

**Issue by OmegaXavier** [zhukov/webogram#2104]
This is, evidently, not a software issue.

You see, admitedly your tool is better than Whatsapp's, honest here.

But you would be SO MUCH better and liked if you just heard to users' needs.

I had such a personally urgent subject that i sent the request in two langueges....... never got a response, and then it was evident you won't even care for supporting on your Support link....... four support requests and none have been ever addresses, let alone fixed.

Believe it or not, these factors add to user experience and desire to keep using you.... me.... you may consider a former user because i now know you'll never move a finger to help.

**Comment by Aokromes** [comment]
sorry, bug this is a bug tracker, we cannot help you here.
