### ISSUE TITLE
Bug in web.telegram.org

### ISSUE THREAD

**Issue by xk** [zhukov/webogram#2110]
Hello Telegram, something is wrong with the web.telegram.org version, everytime I close the tab and come back later I have to log in again. It started happening a few days/a week or so ago. Cheers.

**Comment by xk** [comment]
Hi!

Yes, Z, K and "old", https://web.telegram.org/?legacy=1#/im all are giving me the same trouble. I'm using Brave "Version 1.29.79 Chromium: 93.0.4577.63 (Official Build) (x86_64)" on MacOS HighSierra (10.13.6). Cheers.

**Comment by Aokromes** [comment]
then maybe it's server bug or browser bug.

**Comment by xk** [comment]
Got a Brave update this morning and it's working fine again... so yeah, it must have been a browser bug. Oh my. Sorry for the noise. Closing.
