### ISSUE TITLE
No possible to Insert / write letters with accent (spanish language) => áéíóú

### ISSUE THREAD

**Issue by Akronix** [zhukov/webogram#218]
Hello!

Thank you very much for the webapp. I'm using it since short time ago.

I'm not able to write letters with accent, which we use in spanish: áéíóú. The normal (no accent) is displayed instead. Same if I try to paste from the clipboard.
Same problem with this other symbols: ü, àèìòù.
Neither in uppercase letters.

But Good to get working: ñ,Ñ.

Keep improving!

**Comment by Ecron** [comment]
Well, it happened to me again, I couldn't write accented letters with the combination "Accent Key" + "Vowel Key" (first one, then the other) using Spanish keyboard. I found out that it may be related with the YouTube preview, these are the steps to reproduce it (under openSUSE 13.1, GNOME 12, Chrome app using Chromium browser and Shockwave Flash 11.2 r999):

1. Open Telegram app and go to a chat with a YouTube preview (don't play the video).
2. Go to a different window (let's say a web browser or a file explorer) and make sure that the window covers the Telegram's textbox (the white square where you type your messages).
3. Go back to Telegram and try to write any accented vowel (áéíóúàèìòù) using the "Accent Key" + "Vowel Key" combination.

If you do it OK, you won't be able to write any character (when you press first `Accent Key` and then `Vowel Key`, nothing happens, but it should insert an accented vowel). To solve this, you must change the chat clicking to other conversation in chat list, but **not using the Alt+UpArrow or Alt+DownArrow key combination**, it has to be clicking with the mouse.

That's all I've found. Any more details or information would be very appreciated :wink:

**Comment by Akronix** [comment]
Hello.

I've followed your steps on Ubuntu 14.04 using Firefox 35.0.1, but I have not experienced this issue.
In fact, I haven't experienced this issue very often lastly. I only remember one time in the last 3 months, and I use webogram everyday in the same configuration,...

**Comment by ocsjwolf** [comment]
I have a same problem. pt-Br

**Comment by zhukov** [comment]
Yay! I've reproduced this on my Firefox! But my steps were different. I opened web.telegram.org, conversation with Youtube video, clicked on it, so it started playing. Then I pressed "Download" some file in the same chat. It downloaded and opened "Save as" popup. I canceled it, and the accented letters stopped working in text field.

Will try to reproduce locally and get into the actual problem.

**Comment by zhukov** [comment]
I narrowed the steps to following:

- open any conversation with some file to download
- download the file, press cancel when asked about "Save as"
- try to select all text in the field with Ctrl + A (Cmd + A on Mac)

You don't even need Spanish keyboard layout  and Youtube video.

**Comment by zhukov** [comment]
So the one here is obviously a Firefox bug. I can easily reproduce it in any other page. Here is the fiddle: http://jsfiddle.net/o79ppagk/3/

I file a bug to Mozilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1129372
