### ISSUE TITLE
Customizable link-enchancers for different platforms

### ISSUE THREAD

**Issue by stefan-niedermann** [zhukov/webogram#240]
Would it be possible to add link-enhancers like youtube for other platforms?
As a user i'd like to see videos from chilloutzone.net in an embedded iframe, too.

**Comment by zhukov** [comment]
@stefan-niedermann after supporting vimeo, instagram, vine, twitter, facebook and couple others, I think, I'm not going to implement this. 
The xpath thing is for server-side software, with php etc. But with javascript you can't just fetch foreign website page.
If you want, you can implement this by yourself and we'll consider merging into the master repo. But I think, that it's better to support the most popular ones (which will cover 95% of users' needs) out of the box and ignore the others. More settings = more fragmentation.

**Comment by stefan-niedermann** [comment]
@zhukov thank you, i agree with you in all points. this issue is solved for me.
