### ISSUE TITLE
Frozen on Generating keys...

### ISSUE THREAD

**Issue by carlsut** [zhukov/webogram#277]
After selecting my country and entering my mobile telephone number nothing happens. Now over 20 minutes. Tried reinstalling with same result.

**Comment by lzw429** [comment]
It seems it is happening again...

**Comment by 0cool-f** [comment]
got this problem, it's like a month that i noticed that, i supposed that was temporary, but it seems not...that's what my Chrome inspector says:
__
Error: Constructor not found: 3504867164 1009246814 4047310522
    at TLDeserialization.fetchObject (app.js:57)
    at app.js:58
    at o (app.js:14)
    at app.js:14
    at m.$eval (app.js:14)
    at m.$digest (app.js:14)
    at m.$apply (app.js:14)
    at l (app.js:13)
    at b (app.js:13)
    at XMLHttpRequest.M.onload (app.js:13)
__
Application Cache Error event: Resource fetch failed (2) https://web.telegram.org/js/app.js
