### ISSUE TITLE
Typing apostrophe ' brings up quick search

### ISSUE THREAD

**Issue by bluezed** [zhukov/webogram#283]
Since this morning whenever I write an apostrophe in the message box the Quick search at the bottom pops up.

That means I can no longer write things like: isn't, can't, won't and so on...

Using Firefox 29.0.1 on Win 7 64bit. In case it's important I use a German keyboard.

EDIT: Just restarted the browser and logged in again and now it works correctly again. Weird!

**Comment by zhukov** [comment]
4 month passed, closing the issue.
