### ISSUE TITLE
ReferenceError: server is not defined

### ISSUE THREAD

**Issue by JuXReal** [zhukov/webogram#318]
Hello i try to install this script on my Raspberry Pi.

Node JS works. If i try to start the server,js i get this error.

> server.js
> ReferenceError: server is not defined
>     at repl:1:2
>     at REPLServer.self.eval (repl.js:110:21)
>     at Interface.<anonymous> (repl.js:239:12)
>     at Interface.EventEmitter.emit (events.js:95:17)
>     at Interface._onLine (readline.js:202:10)
>     at Interface._line (readline.js:531:8)
>     at Interface._ttyWrite (readline.js:754:14)
>     at ReadStream.onkeypress (readline.js:99:10)
>     at ReadStream.EventEmitter.emit (events.js:98:17)
>     at emitKey (readline.js:1089:12)

How i can fix it?

**Comment by tushki** [comment]
npm ERR! install Couldn't read dependencies
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs
\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! path C:\Program Files\nodejs\package.json
npm ERR! code ENOPACKAGEJSON
npm ERR! errno -4058

npm ERR! package.json ENOENT, open 'C:\Program Files\nodejs\package.json'
npm ERR! package.json This is most likely not a problem with npm itself.
npm ERR! package.json npm can't find a package.json file in your current directo
ry.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs
\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4

npm ERR! Uncaught, unspecified "error" event.
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Program Files\nodejs\npm-debug.log

C:\Program Files\nodejs>

**Comment by Md-Abul-Hasan** [comment]
Server.listen(5050);
^

ReferenceError: Server is not defined
    at Object.<anonymous> (C:\Users\User\Desktop\NodeJs\main.js:10:1)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47
PS C:\Users\User\Desktop\NodeJs>
