### ISSUE TITLE
What about bigger emoji images to make them easier to find at a glance?

### ISSUE THREAD

**Issue by midimarcus** [zhukov/webogram#321]
This is just a request more than an issue.
I find quite difficult to recognize emoji images at a glance since images are very small.

Is it possibile to make them a bit larger?

Thank you.

**Comment by zhukov** [comment]
Fixed in 0.4.9. Will be published soon, currently in beta: https://zhukov.github.io/webogram

<img width="313" alt="screen shot 2015-10-13 at 11 30 21 pm" src="https://cloud.githubusercontent.com/assets/775173/10468962/675f3bca-7202-11e5-973d-962ba4f2ad07.png">
