### ISSUE TITLE
Enhance "forwarded message" and "shared contact" view

### ISSUE THREAD

**Issue by Ecron** [zhukov/webogram#340]
Hi again, guys. I've seen that the improvement made in "forwarded message" and "shared contact" layout, but although I think it's way better, it may look a little messy with embeded messages, user's pictures, names and so.

So I propose to enhance a little bit the layout by adding some background to the forwarded message (and the shared contact too, both keeps the same layout). I attach a mockup I made, I tried playing with the CSS but I couldn't get what I wanted...

![captura](https://cloud.githubusercontent.com/assets/488803/3349176/4a6bd134-f956-11e3-81d6-ec8aa096e5b7.png)

I think it clears up the view and lets you see at first sight what is forwarded.

What do you think, guys?

**Comment by zhukov** [comment]
I guess, since the Material update we're not going to change the design, especially using colored background.
These app aspects (about design) are maintained by Toberg.
