### ISSUE TITLE
delete conversation... on left side

### ISSUE THREAD

**Issue by IT-Lueg** [zhukov/webogram#343]
Hello, (my english is not the best)
i know that i can delete a chat if i open it... on the right side

but can you please add a function to easily delete chats in the div on the left side.

maybee just as easy as on my photo...
and then a delete button next to the chats
![webogram](https://cloud.githubusercontent.com/assets/4661044/3370134/73d890f2-fb8b-11e3-811e-16f2b7042cb8.png)

**Comment by bluezed** [comment]
+1

**Comment by PatrickWinkler** [comment]
+1

**Comment by Ryuno-Ki** [comment]
Keep in mind, that there are RTL languages! Should the position be mirrored in this case?
