### ISSUE TITLE
TCP sockets support

### ISSUE THREAD

**Issue by zhukov** [zhukov/webogram#357]
Telegram API has tcp transport: https://core.telegram.org/mtproto#tcp-transport

We could support it in order to perform requests faster. Currently TCP raw sockets are supported by:
* Chrome Packaged App - https://developer.chrome.com/apps/sockets_tcp
* Firefox OS - https://developer.mozilla.org/en-US/docs/Web/API/TCPSocket

**Comment by zhukov** [comment]
Not actual for now with Native Client encryption and other improvements.
May be return here later.

**Comment by JackPoteYes** [comment]
How about now ?
I need to use TCP to receive msgs instantly.
The delay before receiving one avoid me to do what I need
