### ISSUE TITLE
unable to login

### ISSUE THREAD

**Issue by sherlynx** [zhukov/webogram#389]
Hi, I have been stuck at "Generating Keys" stage at sign in page while trying to login. It used to work well until recently. Apart from that, launching the app via Chrome does not help too, it is stuck at "Waiting for Network...Retry" error message. Is it a firewall/network problem?

Thanks!

**Comment by zhkulov** [comment]
How does webogram stores the messages and all the data on the server?
While studying mtproto.js I didn't find anything related to this. Can you tell me?
