### ISSUE TITLE
Suggestion: offline chat history

### ISSUE THREAD

**Issue by bobcanthelpyou** [zhukov/webogram#399]
It would be nice if i could access the chat history offline, too. At the moment i am always forced to go online to access the chat history.

**Comment by marco-c** [comment]
> But I'm not sure whether there is a cross-client storage backend which provides sufficient space to hold a bigger amount of chat history especially when including media?

IndexedDB or the Cache API.

**Comment by zhukov** [comment]
We have no plans to implement this for now.
Feel free to fork the project and implement yourself.
