### ISSUE TITLE
Notification problem with emoji icon

### ISSUE THREAD

**Issue by rubenlagus** [zhukov/webogram#451]
When I receive a message that contains a emoji icon (I didn't test with all of them), the notification is shown wrong:

**Message received:**

![Message](http://i.imgur.com/SdOj5MF.png)

**Notification content:**
![Notification](http://i.imgur.com/ItDdE5P.png)

I'm using Chrome Browser (version 35.0.1916.114) in an Arch Linux instalation

**Comment by zhukov** [comment]
Is this still actual?
