### ISSUE TITLE
Link conversion from pasted URL forgets trailing character

### ISSUE THREAD

**Issue by ludoo** [zhukov/webogram#457]
When Telegram converts a pasted URL like

http://it.wikipedia.org/wiki/Linea_M4_(metropolitana_di_Milano)

to a link, it leaves the trailing parenthesis out and produces this

http://it.wikipedia.org/wiki/Linea_M4_(metropolitana_di_Milano

Thus making the link invalid.

**Comment by ArtemFitiskin** [comment]
I checked existing regex and it works pretty well, but not every time. Also, this behavior differs from the desktop version. I changed it in my Pull Request. I’ve chosen another one on this page: [In search of the perfect URL validation regex](https://mathiasbynens.be/demo/url-regex) (by @diegoperini). You can also chose any other, for example the one used in desktop version.

P. S: There are few more changes in email parsing. “Mailto:” won’t be removed from the string, but instead it will be added to href attribute, if such doesn’t exist.

**Comment by ArtemFitiskin** [comment]
Also, now short addresses are supported.

Master:
![2015-02-07 23 52 46](https://cloud.githubusercontent.com/assets/5507542/6093932/64a23a9a-af25-11e4-9c6f-05bca130677e.png)

PR:
![2015-02-07 23 52 59](https://cloud.githubusercontent.com/assets/5507542/6093933/67d31978-af25-11e4-8215-45cf4519a1d2.png)

**Comment by arguapacha** [comment]
Is this closed? I am still having the same issue with webogram 

Example:
![screen shot 2015-02-19 at 19 59 29](https://cloud.githubusercontent.com/assets/1663486/6274999/a5ffea8a-b873-11e4-9221-8784dfdc0703.png)

Version:
![screen shot 2015-02-19 at 20 13 13](https://cloud.githubusercontent.com/assets/1663486/6275010/c58a3d10-b873-11e4-88d3-074a97b4533a.png)
