### ISSUE TITLE
[Enhancement] Add Favorite conversations.

### ISSUE THREAD

**Issue by FabianPastor** [zhukov/webogram#514]
The idea is to add a section at the top of the contact list with the favorite chat contacts or groups.
Something similar as in the linux version of skype (not sure if it will also be on windows).
![Skype contact chat](https://cloud.githubusercontent.com/assets/4536090/4542093/e94188d2-4e1d-11e4-8bbb-9143b8b1ccc0.png)

Sorry for my English.
Un saludo!

**Comment by zhukov** [comment]
Sorry, we have no plans to implement this, unless it will arrive to core API and mobile clients.

**Comment by FabianPastor** [comment]
I guess now, 2 years later, we can see this coming true.

The next step is to add some kind of division between different type chats...

Well.... it's something xD
