### ISSUE TITLE
Error One of the params is missing or invalid.

### ISSUE THREAD

**Issue by Marm0t** [zhukov/webogram#519]
Hello.

Sometimes when I try to send moticon it happens that I see the error messate "One of the params is missing or invalid."
After resending message everything works fine.

The error is seen on Mozilla Firefox 32.0.3, Windows 7. Never seen this problem using google chrome. Webogram version 0.3.1.

details:
Method: messages.sendMessage
Result: {"_":"rpc_error","error_code":400,"error_message":"MESSAGE_EMPTY"}
Stack: c/u@http://zhukov.github.io/webogram/js/app.js:13:17496
c/</<@http://zhukov.github.io/webogram/js/app.js:13:18550
c@http://zhukov.github.io/webogram/js/app.js:7:14499
l/<@http://zhukov.github.io/webogram/js/app.js:7:14686
On/this.$get</u.prototype.$eval@http://zhukov.github.io/webogram/js/app.js:7:21861
On/this.$get</u.prototype.$digest@http://zhukov.github.io/webogram/js/app.js:7:20360
On/this.$get</u.prototype.$apply@http://zhukov.github.io/webogram/js/app.js:7:22126
o/l<@http://zhukov.github.io/webogram/js/app.js:7:29438
r@http://zhukov.github.io/webogram/js/app.js:6:9979
Ht/l.defer/n<@http://zhukov.github.io/webogram/js/app.js:6:11749

This lilne adds to the chat history after the error:
![image](https://cloud.githubusercontent.com/assets/4036891/4578840/b065ae0c-4fc7-11e4-87a9-77addc40512a.png)

I dn't know if it's already fixed or not...

**Comment by nima1363azad** [comment]
One of the params is missing or invalid.
Technical details here
