### ISSUE TITLE
Keys need to be created every time I start the browser

### ISSUE THREAD

**Issue by Mosrite** [zhukov/webogram#552]
Hello,
I'm running the Tor browser bundle (based on Firefox ESR portable) on Windows 7. Cookies, Scripts and Flash are enabled for web.telegram.org, I don't use private mode. Cookies, website preferences and offline data will not be deleted if the browser closes.
I can login and use the webapp without any problems.
However, everytime I restart the browser I'm logged out of webogram and have to recreate the keys again, which of course is a bit annoying. What can I do to make webogram remember my keys?
Thanks in andvance!

**Comment by TT44bb** [comment]
I have the same problem on Firefox 45.3.0 (from Debian Jessie), on multiple computers.

I didn't change anything about my setup when suddenly it started doing this a couple of weeks ago (don't know when exactly). So it must have been either a Firefox update or a Telegram update introducing this problem.

Using the above test, it seems Firefox is deleting localstorage on restart, but I didn't (want to) configure it to do this. In Safemode, it happens too (plus in a fresh instance with just all my add-ons installed I can't reproduce it). I started putting my settings into the new instance, but the new instance still works although the settings now seem to be identical (as far as a preference seems to have any connection with this, the Privacy and Security tabs and the Advanced/Network tabs for example are all the same).

Any ideas?

**Comment by stek29** [comment]
I think you should report this to firefox, and ask this question on their forums.
