### ISSUE TITLE
Telegram export conversations option 

### ISSUE THREAD

**Issue by sojan-official** [zhukov/webogram#569]
i think currently telegram doesn't have an export conversations option like send archive of your conversation to email .

would be a nice feature if one could export the chat into a txt / xml file, if they want to keep copy of conversation elsewhere than telegram .

**Comment by zhukov** [comment]
Duplicate #316

**Comment by zippl** [comment]
(I just copy my words from a similar request in hope to get it more attention...)

Having almost a full year or daily personal conversations and over thousand pictures shared in single conversations i am stunned this feature is still scarcely discussed at all...
But instead, regularly sticker updates... to make it feel someone is working on the app.

I would love to recommend telegram to others, but the lack of this essential feature as well as the (for me) unsatisfying way it is treated (even at all...) from official side has severe impact on their self-claimed image of transparency and responsibility in general.

I am still full of hope though, as the app is quiet young. In any case i would like to see at least a discussion about this feature by official side and (!) in their own FAQ-list...

And yes, i would even pay for this feature.. (and then, after saving my own property, deleting the app until they offer this feature by default.)

**Comment by psamim** [comment]
For backup, you can use this script, it saves conversations as a CSV file into a sqlite database.
https://github.com/psamim/telegram-cli-backup

**Comment by sab2020** [comment]
واقعا چرا چنین امکانی نداره ؟؟

**Comment by thebigsmileXD** [comment]
@psamim i think plenty people don't use linux, any windows solutions?

**Comment by psamim** [comment]
@thebigsmileXD I suppose `telegram-cli` can be run on Windows too. It is written in C, so at least in theory, it should. I do not know any other solution.

**Comment by thebigsmileXD** [comment]
For now i used TinyTask with click + leftkey, took about 7 hours but was worth it. Ty anyways :)

**Comment by stek29** [comment]
@thebigsmileXD @psamim telegram cli is really old, weird and outdated.

You can use Telethon, Madeline Proto, zerobias' telegram-mtproto or just script Webogram
