### ISSUE TITLE
Support "Hiding Last Seen" - Privacy Options

### ISSUE THREAD

**Issue by eyenx** [zhukov/webogram#581]
Today I read on the [telegram blog](https://telegram.org/blog/privacy-revolution) about this new feature. I think the privacy options feature would be very welcome by webogram users.

**Comment by stek29** [comment]
@zhukov Should settings be in different modal?

**Comment by zhukov** [comment]
I guess so. However, I would give smaller priority to features missing even in TDesktop app.

**Comment by stek29** [comment]
@zhukov This feature isn't missing in tdesktop anymore btw

**Comment by eyenx** [comment]
Closed.

**Comment by pcworld** [comment]
Why closed?

**Comment by stek29** [comment]
@pcworld #1278

**Comment by yugiid** [comment]
Hi, I want to just disable online status and message seen status to this app, where can I edit the line code?
