### ISSUE TITLE
Switching back to desktop view is broken on firefox

### ISSUE THREAD

**Issue by fhoshino** [zhukov/webogram#589]
The dialog just throws "!��../desktop/confirm_modal.html" without displaying it correctly.
![2014-11-29_13-49-17](https://cloud.githubusercontent.com/assets/771955/5233659/b6152024-77ce-11e4-833f-b18a83ae43fe.png)

**Comment by zhkulov** [comment]
I am using the latest source code of webogram to study. While studying, I found that the confirm_modal.html file in app/partials/desktop/ folder is working very fine. But the confirm_modal.html file in app/partials/mobile folder is not working. Actually the html code for confirm_modal.html file in mobile folder is not provided. I am attatching the file here.
![image](https://cloud.githubusercontent.com/assets/10897758/6143209/d1da0382-b1ea-11e4-924c-9ac458fcbc71.png)
The image shown above is the source of the file confirm_modal.html file in app/partials/mobile folder and the one shown below is the view of the same file.
![image](https://cloud.githubusercontent.com/assets/10897758/6143212/e101d074-b1ea-11e4-8683-71c65678a6c2.png)

**Comment by zhukov** [comment]
Windows platform doesn't support symbolic links, I guess..

**Comment by Burdu** [comment]
actually, it does: https://msdn.microsoft.com/en-us/library/windows/desktop/aa365680%28v=vs.85%29.aspx

**Comment by Jzarecta** [comment]
Have the same issue at web.telegram.org on Firefox 39.0
I cant find a way to switch back.
