### ISSUE TITLE
[Enhancement] Switch to different scroller plugin

### ISSUE THREAD

**Issue by achimk1704** [zhukov/webogram#591]
Hi,

https://github.com/leoselig/jsFancyScroll is a nice scroll plugin which uses the same technique as facebook. Replacing the current scroll plugin with that one might speed up the app and simplify code.

But yes, it's not really necessary :smile:

**Comment by zhukov** [comment]
There is no license in the repo and I see that the plugin is buggy.
I'm using OSX with latest Chrome.

![screen shot 2015-02-05 at 11 15 43 pm](https://cloud.githubusercontent.com/assets/775173/6068445/2cf00de6-ad8d-11e4-8292-35f94430e9ca.png)
![screen shot 2015-02-05 at 11 15 52 pm](https://cloud.githubusercontent.com/assets/775173/6068446/2cf57614-ad8d-11e4-97e7-eccc438c8a82.png)

This is even already reported https://github.com/leoselig/jsFancyScroll/issues/2 more than a month ago, but still not fixed.

**Comment by EvanBurbidge** [comment]
Was this issue resolved?

**Comment by zhukov** [comment]
@EvanBurbidge No point in switching to another buggy library.
