### ISSUE TITLE
I cannot see my profile image nor many images since the last update

### ISSUE THREAD

**Issue by Yajo** [zhukov/webogram#597]
I use the Firefox app from the marketplace.

Since the last update, I cannot see my own profile picture, and when I open any other picture it shows a blank square. Also, I cannot see many thumbnails too.

I wanted to test with web.telegram.org, but I got https://github.com/zhukov/webogram/issues/596 so I did not.

**Comment by zhukov** [comment]
Don't know, how to debug firefox app from marketplace. Firefox WebIDE allows to install custom packaged app only for Firefox OS.

**Comment by BadBone2k** [comment]
Ok, but what about selfhosting? Am I the only one who runs webogram on his own server and uses Firefox? Do you need more information from me?

**Comment by zhukov** [comment]
I can't understand difference between your self-hosted version and my development one on localhost and the one on github.io.
Can you check errors console? What is the URL, btw?

**Comment by BadBone2k** [comment]
First of all, Firefox webapp from the Marketplace (wich runs Version 0.3.6) works fine now, just tested that. So I figured, the problem had to be on my end.

After playing around a bit, i realised that I was still using a test domain wich has an Umlaut ( ü ) in it. A few weeks ago this was not a problem, but now something broke compability with punycode URLs. After reverting to a Umlaut-free domain, everything works as intended.

So, from my perspective, this is an issue of how much you want to support Internationalized domain names in the future.

**Comment by zhukov** [comment]
Then I guess, that's not Webogram but a Firefox one. We have no difference about domain name, but it can be for IndexedDB or Blob urls etc on Firefox side.

**Comment by Yajo** [comment]
> Don't know, how to debug firefox app from marketplace. Firefox WebIDE allows to install custom packaged app only for Firefox OS.

@zhukov I found this: https://www.youtube.com/watch?v=IqpMW5C2QSw

**Comment by zhukov** [comment]
I have only OS X. Also, it allows you to debug existing app. And how am I supposed to test an upcoming update?

**Comment by Yajo** [comment]
> I have only OS X.

I have only Linux and the tutorial worked. Just find the executable (in my case it was `~/.telegram-6b3c6d017754f745c6740365d29de1ba/webapprt-stub`) and execute it with `--debug 6000`, and connect from there.

> Also, it allows you to debug existing app. And how am I supposed to test an upcoming update?

Hard to tell, as I never developed js packaged apps, but seems like newest versions of FF-developer-edition come with a "local runtime", according to http://stackoverflow.com/a/26764871/1468388
