### ISSUE TITLE
Feature Request: Backup (export) chat history

### ISSUE THREAD

**Issue by omarzd** [zhukov/webogram#611]
Give the user the ability to save the chat history of a certain contact or group in a text file, secret chats excluded.

**Comment by zippl** [comment]
(I just copy my words from a similar request in hope to get it more attention...)

Having almost a full year or daily personal conversations and over thousand pictures shared in single conversations i am stunned this feature is still scarcely discussed at all...
But instead, regularly sticker updates... to make it feel someone is working on the app.

I would love to recommend telegram to others, but the lack of this essential feature as well as the (for me) unsatisfying way it is treated (even at all...) from official side has severe impact on their self-claimed image of transparency and responsibility in general.

I am still full of hope though, as the app is quiet young. In any case i would like to see at least a discussion about this feature by official side and (!) in their own FAQ-list...

And yes, i would even pay for this feature.. (and then, after saving my own property, deleting the app until they offer this feature by default.)
