### ISSUE TITLE
Disable mobile version on web

### ISSUE THREAD

**Issue by JoseLSegura** [zhukov/webogram#619]
I accepted the change to mobile version in the web interface. I don't like it in the browser and I want to go back to the normal web version. How can I change between both versions? I didn't see anything in settings.

Best regards

**Comment by zhukov** [comment]
Is this problem still actual with the most recent version of app?

**Comment by AndreaGiardini** [comment]
The view is completely messed up with the latest update. Literally impossible to use.

**Comment by zhukov** [comment]
@AndreaGiardini this is completely useless comment without any additional information. What do you expect to see and what do you see instead? Also OS, browser, version, screenshot (!).

**Comment by AndreaGiardini** [comment]
Calm down. We were talking about Iceweasel on Debian, so the issue i reported regards Iceweasel on Debian. Not version 34 but version 31.3 in my case. Here is the screenshot
![telegram](https://cloud.githubusercontent.com/assets/3543138/5702416/3ab4692c-9a5a-11e4-88b8-7903d3740be2.png)

**Comment by AndreaGiardini** [comment]
Upgraded to version 34, the page is now displayed correctly

**Comment by zhukov** [comment]
Any errors in browser console?

**Comment by Nhoya** [comment]
I use debian and iceweasel too but i don't have this  trouble..

**Comment by manuti** [comment]
Same problem here with Chrome in Win7 64 bits.
And Ctrl + F or B doesn't do anything
Chrome version 40.0.2214.111 m
Windows 7 Professional service pack 1

**Comment by manuti** [comment]
[Solved] Just pulling the edge of the window instead of maximizing --> then the message to switch appears

**Comment by noahleigh** [comment]
Could this functionality be changed to work like the Windows app, where below a certain window width, the UI automatically hides the contacts sidebar without prompting?
