### ISSUE TITLE
После редизайна криво отображается в Firefox

### ISSUE THREAD

**Issue by SeibelStan** [zhukov/webogram#628]
![2015-01-01 06 45 29](https://cloud.githubusercontent.com/assets/3998458/5591373/4628502e-9182-11e4-8db4-e14927cc777d.png)

Что съехало - это видно. Плюс расстояние от сообщений до поля ввода кажется слишком большим. И как обычно: где русский? Все изнылись уже. Хороший на трансифексе лежит ведь.

**Comment by SeibelStan** [comment]
![2015-01-01 06 51 17](https://cloud.githubusercontent.com/assets/3998458/5591396/99b039f0-9182-11e4-8412-acbb8dd9883f.png)

И само поле тоже слишком высокое. Оно же всё-равно масштабируется по строкам, зачем сразу в две строки?

**Comment by SeibelStan** [comment]
![2015-01-01 06 54 45](https://cloud.githubusercontent.com/assets/3998458/5591402/1a57fe94-9183-11e4-96db-abe17b8b27b6.png)

От иконок надписи не далековато? Кстати, как раз это меню основной контейнер и сдвинуло.

**Comment by SeibelStan** [comment]
![2015-01-01 07 13 24](https://cloud.githubusercontent.com/assets/3998458/5591443/b4474300-9185-11e4-943c-626f8f48b5cb.png)

Это же не Материал.

**Comment by SeibelStan** [comment]
![2015-01-01 07 14 58](https://cloud.githubusercontent.com/assets/3998458/5591448/0debab26-9186-11e4-9fc5-5f5939e938b9.png)

Серый фон инпутов.

**Comment by zhukov** [comment]
Не могу воспроизвести съехавшую страницу. Какая версия браузера? Какая ОС?
В последней версии на OS X и на Win 7 у меня все в порядке.
Есть ли возможность попробовать разобраться в чем проблема в Firebug?

**Comment by SeibelStan** [comment]
Linux Mint 17.1
Firefox 34.0

Блок tg_head_logo_dropdown dropdown двигает, но
Если удалить tg_head_btn dropdown-toggle (саму ссылку), то всё встанет на место. Если  у tg_head_logo_dropdown dropdown ссылку удалить, но добавить open, то меню выпадет из угла не смещая контейнер.

![2015-01-01 13 20 58](https://cloud.githubusercontent.com/assets/3998458/5591820/09912b40-91b9-11e4-947c-8ae8d98dc8c9.png)

Если навести на этот блок, то направляющие указывают до самого низу страницы, т.е. он занимает всю колонку.

И ещё, я сам не пойму, как такое возможно, но

![2015-01-01 13 22 48](https://cloud.githubusercontent.com/assets/3998458/5591828/54358f88-91b9-11e4-92b8-b1f6f452828b.png)

Если отключить это правило, то контейнер будет на месте...

![2015-01-01 13 25 23](https://cloud.githubusercontent.com/assets/3998458/5591829/aa635700-91b9-11e4-8457-97c371e9d2ec.png)

Если вот так раскидать правила, то всё в порядке будет.

**Comment by zhukov** [comment]
Спасибо. Нашел настоящую проблему..
Можешь проверить на https://zhukov.github.io/webogram ?

**Comment by SeibelStan** [comment]
Да, поправлено.

**Comment by zhukov** [comment]
Спасибо. web.telegram.org тоже обновлен.

**Comment by SeibelStan** [comment]
![2015-01-13 23 23 49](https://cloud.githubusercontent.com/assets/3998458/5725239/4b5cc914-9b7b-11e4-852a-f6739b635fd4.png)

Вылезает + может появиться горизонтальный скролл даже на довольно большом окне.
