### ISSUE TITLE
New avatars for the mobile version

### ISSUE THREAD

**Issue by robin0van0der0v** [zhukov/webogram#629]
Telegram still uses the old UserAvatar.png files in the mobile version.
But in the desktop version the new avatars (colored circle with letters in the middle) are used.

Maybe we should also use them in the mobile version?

Screenshots:
![mobile](https://cloud.githubusercontent.com/assets/692029/5591479/595b76f4-915e-11e4-8616-d833ecf1f90e.png) ![desktop](https://cloud.githubusercontent.com/assets/692029/5591480/5eee8a48-915e-11e4-8fa3-a5e00443ef8f.png)

I already noticed that they are both in the same color, just like my other contacts. :smiley:

**Comment by zhukov** [comment]
This was fixed in 0.4.8
