### ISSUE TITLE
V 0.3.9 broken on Firefox

### ISSUE THREAD

**Issue by jaipradeesh** [zhukov/webogram#631]
![1649723055](https://cloud.githubusercontent.com/assets/4883668/5591718/58d0d840-91a5-11e4-9992-cd75e4e1fb7c.jpg)

User Agent : Firefox Developer Edition - 36.0a2 (2014-12-30)

**Comment by zhukov** [comment]
Hm.. Can't reproduce this on my Firefox DE OS X, same for Win 7.

**Comment by zhukov** [comment]
Could you please try to debug this with Firebug?

No idea, what is the problem..
