### ISSUE TITLE
Create a new app for Firefox OS, using Building Blocks and the other lines of design for Firefox OS

### ISSUE THREAD

**Issue by VictorOsorioMedrano** [zhukov/webogram#633]
The app for Firefox OS can be a lot much better using all the tools aproved by Mozilla.

here my concept for the new app using building blocks and the other lines of desing:

![firefox os concept telegram](https://cloud.githubusercontent.com/assets/8153074/5599517/cbf7640e-928d-11e4-9900-a86c41451ab2.png)

**Comment by zhukov** [comment]
I'm afraid I'm not going to implement something special for Firefox OS. On the contrary, I was going to change mobile layout to be more like desktop one with material design, no more bubbles for messages etc. This will make app responsive again and my life will be easier.
I hope, that mobile experience will not get worse.

If you really wish to implement this, feel free to fork to project and change the UI.

**Comment by VictorOsorioMedrano** [comment]
ok, material design looks good for me, good idea, will be incredible

**Comment by sergioad** [comment]
Yea, something more like the Android's Telegram :yum:
