### ISSUE TITLE
Implement weppy to support webp sticker everywhere

### ISSUE THREAD

**Issue by nukeador** [zhukov/webogram#636]
Since webp is not a standard, it's not implemented in all browsers.

If we want to support them, there is a need for this library:

https://github.com/antimatter15/weppy/

Ideally Telegram should implement just standards formats, but that's a different conversation, in the mean time this is a workaround ;)

**Comment by dlion** [comment]
I think http://webpjs.appspot.com/ is better.
https://github.com/antimatter15/weppy/issues/2

**Comment by KaiRo-at** [comment]
WebP is a patent-encumbered non-standard proprietary formmat from Google, it should not be used on the web in the first place.

**Comment by Skatox** [comment]
Yes, I believe webpjs is better. Their transparency support is better and stable, I guess that was the main reason that telegram used WebP, due to transparencies. But that format sucks because is not standard and it's implemented only on webkit browsers. You can check currenty support in this table: http://caniuse.com/#feat=webp

**Comment by nukeador** [comment]
@KaiRo-at It is not. The license grant is the same as that for WebM described right here: http://www.webmproject.org/license/

Reference: https://groups.google.com/a/webmproject.org/forum/#!topic/webp-discuss/W4_j7Tlofv8

**Comment by alex-mayorga** [comment]
The Firefox bug FWIW https://bugzilla.mozilla.org/show_bug.cgi?id=856375

**Comment by wilsonpage** [comment]
I heard PNG is a well supported format :wink:

**Comment by wilsonpage** [comment]
This is breaking webogram on FirefoxOS and Firefox Desktop.

**Comment by zhukov** [comment]
Weppy doesn't support Safari, since it doesn't support Webm. And I don't like webpjs - it's really heavy thing, that converts image to PNG. 

I think, this should be solved from server-side.

**Comment by zhukov** [comment]
Horray, libwebpjs suited all of our need and is just 25Kb gzipped.
