### ISSUE TITLE
Firefox prompt: "Add Telegram Web (mydomain.com) as an application for tg links?"

### ISSUE THREAD

**Issue by tdido** [zhukov/webogram#643]
After updating to the latest version, I started getting these prompt bars on Firefox:

Add Telegram Web (mydomain.com) as an application for tg links?
Add Telegram Web (mydomain.com) as an application for web+tg links?

Tried to close them, but they will come back next time. Found a similar issue on [this thread](http://forums.mozillazine.org/viewtopic.php?f=38&t=2819927), which links to [a solution](https://support.mozilla.org/en-US/questions/994725#answer-556640), but I'd prefer not to write custom styles to hide the prompts.

**Comment by zhukov** [comment]
I think, this is a Firefox bug, not a Webogram one. They should make either "disallow" button or hide this bar forever.

**Comment by zhukov** [comment]
Also, I have no callbacks for this "hide" or "allow" action, so I can't stop asking for permission.

**Comment by tdido** [comment]
I see. Thanks for the explanation, I'll try it from the Firefox side then.
