### ISSUE TITLE
Detouch notification 

### ISSUE THREAD

**Issue by Nhoya** [zhukov/webogram#644]
For Who use telegram on different platform recive a notification is really noizy cuz all the device will make sounds but if i, for example, turn off notification on web app, no sound in all devices... Add the possibility to select on wich platform have notification will be reall useful

**Comment by hharchani** [comment]
This is actually really annoying. If I'm chating on one device, it should not ring in other

**Comment by SpeedJack** [comment]
+1 this feature could be useful!

**Comment by Walkman100** [comment]
Wow, It's possible, just like that? I think I underestimated your JS skills :P
