### ISSUE TITLE
How to change header color

### ISSUE THREAD

**Issue by omarkerr** [zhukov/webogram#647]
Hello @zhukov is it possible you tell me how to change the header color when you hover over it?

**Comment by zhukov** [comment]
@omarkerr if you want to maintain your own customized version of Webogram, please take 5 minutes to learn basic CSS and JavaScript. I don't see any point for the project to spend time explaining such basic things.

**Comment by omarkerr** [comment]
@zhukov i know js and css, and i had change the color on my own i just wanted to know without looking for it seen you made it, thanks tho @zhukov
