### ISSUE TITLE
Convert to Less

### ISSUE THREAD

**Issue by cabloo** [zhukov/webogram#648]
I'll make a P.R. with the CSS converted to LESS or SASS and update the gulp tasks if that's desired.

**Comment by zhukov** [comment]
Let's try this. I have already added `gulp watch` task, to it will be easier to integrate.
LESS is a better option IMO.

**Comment by Cabloo** [comment]
Okay, I should have something up by the end of next weekend.

**Comment by ArtemFitiskin** [comment]
@cabloo What about this task, can I help you?

**Comment by cabloo** [comment]
Hi Artem,

I've just been very busy lately. If you can run the css through a less
converter and make sure it all looks correct, I can implement the gulp
tasks.
