### ISSUE TITLE
Self Destruction & Secret Chat Question 

### ISSUE THREAD

**Issue by flashbag** [zhukov/webogram#652]
I've read this issue #126 and understand that for self destruction messages we need secret chat, and for secret chat we need any SQL (or not SQL?) storage. Just want to ask 2 questions.
1. Is there any plans for this work? 
2. Will anyone help me (consultion, code review) if I will start with this?

**Comment by zhukov** [comment]
Hi @flashbag 

For now I don't have any plans to implement this feature. I like secret chats as it is right now -- on mobile device, which is private in most cases. Desktop is usually shared, especially its browser, so I don't like implementing Secret Chats in Webogram. Apart from this one, there are a lot of other important problems which we need to solve. Most of them are related to performance.

**Comment by zhukov** [comment]
Duplicate #126. Feed free to continue discussion in that thread
