### ISSUE TITLE
Hi there I am getting this error while starting telegram in web browser.

### ISSUE THREAD

**Issue by Radioactivesaksham** [zhukov/webogram#657]
How can i fix this please tell asap.
\
Method: auth.sendCode
Result: {"_":"rpc_error","error_code":420,"error_message":"FLOOD_WAIT_86300"}
Stack: Error
    at d (https://web.telegram.org/js/app.js:15:9005)
    at l (https://web.telegram.org/js/app.js:8:17075)
    at https://web.telegram.org/js/app.js:8:17247
    at u.$eval (https://web.telegram.org/js/app.js:8:24444)
    at u.$digest (https://web.telegram.org/js/app.js:8:22940)
    at https://web.telegram.org/js/app.js:8:24529
    at r (https://web.telegram.org/js/app.js:7:11339)
    at https://web.telegram.org/js/app.js:7:13337
    at n (https://web.telegram.org/js/app.js:2:10960)

Here are the snapshots
![screenshot 184](https://cloud.githubusercontent.com/assets/10598995/5801614/fce54468-a012-11e4-9b1e-d5d5b1ea8a56.png)
![screenshot 185](https://cloud.githubusercontent.com/assets/10598995/5801615/fce9d398-a012-11e4-8f12-b31fdf0ed681.png)

Thanks for making an amazing web messenger..

**Comment by zhukov** [comment]
It means that you have reached daily limit on login tries for the phone number.

**Comment by Radioactivesaksham** [comment]
Thanks..

**Comment by arVahedi** [comment]
Dear @zhukov is it daily limitation or request per second limitation? I have same problem when I want add contact. How many request can send in this limitation?

**Comment by stek29** [comment]
@arVahedi adding contacts limitation is different.
1. You can't have more than 10000 Contacts simultaneously
2. You can't add too much contacts in q short period of time (5000 hits the limit iirc, not sure when limitation is lifted, maybe a day or a week)
3. Removing contacts and adding others won't help.
