### ISSUE TITLE
Telegram.me - Links always open with telegram web

### ISSUE THREAD

**Issue by auchri** [zhukov/webogram#658]
Hi,

since the update which implemented telegram.me - links into the web version, all telegram.me - links opens in the web version.

I don't want this, they should open with telegram desktop.

I'm using Google Chrome 40 on Windows 8.1

**Comment by zhukov** [comment]
You can log out from web to disable this behavior.

**Comment by auchri** [comment]
That's not an optimal solution, please add an option to disable this

**Comment by Brawl345** [comment]
Yes, this is REALLY annoying! I have two accounts in Telegram Web and Telegram Desktop... Please change this...

**Comment by auchri** [comment]
This is still the case :*

**Comment by zhukov** [comment]
t.me now has the button to open in telegram web, tries to open in native app by default.

**Comment by dan-it** [comment]
@zhukov How is this intended to work?
I do not have the desktop app installed, but  I am logged into the web version. Telegram still tries to open tg:// and fails with a "The address wasn’t understood" error.
I see the page with the button to open it in Telegram web but it disappears too quickly.
