### ISSUE TITLE
replace the circle of confirmation by tics

### ISSUE THREAD

**Issue by VictorOsorioMedrano** [zhukov/webogram#659]

**Comment by zhukov** [comment]
Duplicate https://github.com/zhukov/webogram/issues/143

I don't like ticks since it's a entity to be displayed forever for every outgoing message. Dots disappear when the message is received, so the conversation stays clean.

**Comment by VictorOsorioMedrano** [comment]
@zhukov Zhukov But the ticks looks mucho better, please think more about this issue, all the other clients use ticks, Telegram Web not follow the design.

**Comment by HackToHell** [comment]
+1 Please use ticks instead of dots. Had to google to find out what they mean.

**Comment by ironjan** [comment]
@zhukov How about showing the ticks only for the last sent messages that did not receive an answer yet? That way, the ticks behave similar to the dots and unify the design.
