### ISSUE TITLE
Ошибка при более 10000 непрочитанных сообщениях

### ISSUE THREAD

**Issue by nekto** [zhukov/webogram#660]
Вчера вступил в один групповой чат, и за ночь пока я спал, там успели написать более 10 000 сообщений.
В мобильной и десктопной версиях счетчик работает исправно. А вот в веб-версии телеграма есть проблема: если написано более 10001 сообщения(непрочитанных), то отчет начинается с 10000.
Например открыта вкладка https://web.telegram.org и на счетчике показывает 12000 непрочитанных, если эту вкладку закрыть и открыть заново, то счетчик начнет считать с 10000. Если подождать пока набежит немного сообщений, например, до 10200 и повторить процедуру(закрыть-открыть вкладку), то счетчик опять будет начинать отчет с 10000.
Могу сделать видео, если надо. Или позвать в тот чат)

**Comment by zhukov** [comment]
Это серверная проблема, API не возвращает никогда больше 10000 непрочитанных. Воспроизведется в любом клиенте, если сделать log out, и зайти заново. Насколько знаю, её скоро починят.
