### ISSUE TITLE
Share from right click

### ISSUE THREAD

**Issue by AAraKKe** [zhukov/webogram#664]
Hi!
There had been a discusion a while ago in the Android github repo about URI support. That would be really great sin it would allow sites to place buttons to share to Telegram directly. I understand that this URI support might be also a concern about random messages being sent and so this should be thought carefully. 
In the meantime I think that something in between could be added to webogram or a browser extension which is an option to right click send from anywhere in the web. Since webogram has a chrome app I don't know if it would be possible to add support for an option in the right button as, for example, pushbullet has. In that way any picture or any link could be sent to the webogram extension and choose which contact you want to share the content with.

Imagina clicking with the right button on a link or image, hoer over the Telegram option and a list of most used contacts appears, you just select that contact and it is sent. At the end a "Other contacts" options will open webogram to select which contact do you want to share the content with.

What do you think? It would be really cool and will make possible sharing with ease.

**Comment by zhukov** [comment]
Thanks for the suggestion.
We already have one issue about Chrome extension: https://github.com/zhukov/webogram/issues/90
