### ISSUE TITLE
Add "unread messages" splitter when receiving messages in non-active tab or window

### ISSUE THREAD

**Issue by edencore** [zhukov/webogram#666]

**Comment by edencore** [comment]
Awesome, thanks !

**Comment by edencore** [comment]
Now webogram adds "unread messages" splitter, but chat still scrolls while tab is non-active. Can you also stop scrolling in that case ?

**Comment by zhukov** [comment]
I think, I've fixed that. It is available on zhukov.github.io/webogram and will be released to stable locations soon.
