### ISSUE TITLE
XSym confirm_modal.html error on chrome mobile

### ISSUE THREAD

**Issue by robertovergallo** [zhukov/webogram#672]
Hello,
I successfully installed Webogram on my Ubuntu 14.4 LTE along with Node.js
When visited from a desktop browser, it works like a charm.
Nevertheless, I encounter problems when viewing it on mobile browsers (Chrome and Safari).
The following error shows up when I click on the Next button in the login screen

![screenshot_2015-01-29-16-47-59](https://cloud.githubusercontent.com/assets/7581078/5960628/2f565132-a7d7-11e4-9c61-dc3a86d47519.png)

And the user can't go on.
Is it a bug or am I facing some misconfiguration in my environment?
Thanks
Roberto

**Comment by zhukov** [comment]
How do you run the web server? Did you try `node server.js` or `gulp watch`?

**Comment by zhukov** [comment]
This error is caused by web server incorrectly handling symlinks. `partials/mobile/confirm_modal.html` is a symlink to `partials/desktop/ confirm_modal.html`. This works fine on my OS X both with node server and gulp task.

**Comment by robertovergallo** [comment]
Thank you for your kind reply.
I tested Webogram on my OS X and it works perfectly.
The problem exists only on my Ubuntu 14.04 LTE machine.
Any hint?
Thanks
Roberto

**Comment by zhukov** [comment]
@robertovergallo again

>How do you run the web server? Did you try node server.js or gulp watch?

**Comment by robertovergallo** [comment]
Sorry!
node server.js

**Comment by robertovergallo** [comment]
I've tested also with "gulp watch" and the same happens...

**Comment by zhukov** [comment]
Try the same in your Webogram root directory:

```
$ ls -al app/partials/mobile/confirm_modal.html 
lrwxr-xr-x  1 igor  group  29 Oct  2 20:58 app/partials/mobile/confirm_modal.html -> ../desktop/confirm_modal.html
```

Do you see the symlink?

**Comment by robertovergallo** [comment]
It seems a regular file:
-rwxr--r-- 1 nobody nogroup 1067 gen 23 10:52 app/partials/mobile/confirm_modal.html

**Comment by zhukov** [comment]
How did you get the code? Did you download the zip file or cloned with git?

**Comment by robertovergallo** [comment]
Don't know why I had that real files instead of symlinks.. I've downloaded again the code and now it's fine.
Thanks for your help!
