### ISSUE TITLE
Copyrights

### ISSUE THREAD

**Issue by mateuszgwozdz** [zhukov/webogram#674]
My understanding of GNU v3 is that I can't actually modify the code to work with my website? How should I make it work with my sql database of users than? My plan was to use it on my platform as a chat between users + create a separate app. Something like Facebook and Facebook messenger

**Comment by zhukov** [comment]
No idea what you talking about.
Webogram is built to work with Telegram API. Are you going to make it work with your own backend? It's a pretty hard task.
