### ISSUE TITLE
Idea: Integrating WebRTC

### ISSUE THREAD

**Issue by christian667** [zhukov/webogram#679]
Just as a hint: 
Should be quite easy to integrate webrtc with a little help from

http://apprtc.appspot.com

Send a special encoded message that shows kind of a incoming call window to the chat partner and leads to an webrtc call if answered. Same functionality could be easily provided in the android version,
the apprtc demo above works as fine with chrome on android as chrome on desktop.

**Comment by zhukov** [comment]
I'm afraid there is no way to implement this, until this is supported by Telegram API.
