### ISSUE TITLE
French Translation!

### ISSUE THREAD

**Issue by loctauxphilippe** [zhukov/webogram#680]
I saw that there's not a French version of the website yet :disappointed:
I'd like to know how to make it! (Since I'm french)

**Comment by Walkman100** [comment]
https://github.com/zhukov/webogram/blob/master/CONTRIBUTING.md#localization

**Comment by zhukov** [comment]
Please, refer to the Contributing guide about localization. Telegram translations are not under my control.

**Comment by loctauxphilippe** [comment]
Thanks! I think I'll work on it!

**Comment by Chrisjow** [comment]
Hi, did anyone create the fr-fr.json file for French translation ?

**Comment by Chrisjow** [comment]
When you say "it was over", does it mean that the file exists somewhere or that you gave up the project ?

**Comment by ploctaux** [comment]
i gave up , sorry

**Comment by Chrisjow** [comment]
And does someone know if the file exists on Transifex ? I don't know how this website works.
I requested to join the French team but I had no news.

**Comment by Ryuno-Ki** [comment]
[French is translated 100%](https://www.transifex.com/telegram/telegram-web/), according to [README](https://github.com/zhukov/webogram/blob/master/app/js/locales/README.md) you can find the translations [under /app/js/locales](https://github.com/zhukov/webogram/tree/master/app/js/locales) where it does not show up :-/
