### ISSUE TITLE
A static url for a best access and more comfort for the user

### ISSUE THREAD

**Issue by VictorOsorioMedrano** [zhukov/webogram#685]
![telgram url](https://cloud.githubusercontent.com/assets/8153074/6098940/b0606578-afb2-11e4-9be1-79d84982cd47.png)

![telegram url static](https://cloud.githubusercontent.com/assets/8153074/6099088/04f90d40-afb5-11e4-8f32-f988d64ff0ee.png)

**Comment by zhukov** [comment]
Why? What's the point? This is a web app, why should we ignore URL?

**Comment by VictorOsorioMedrano** [comment]
was only a recommendation, it looks better :D

**Comment by zhukov** [comment]
It's harder to remove it now, than to leave as is.
And it allows to use bookmarks to add some conversation, allows to restore after browser restart, to use history (back / forward) and so on.
