### ISSUE TITLE
Group appears as "DELETED" since last hour's update

### ISSUE THREAD

**Issue by astorije** [zhukov/webogram#689]
One of my groups now shows up as "DELETED" although when attempting to edit the group, the name shows up fine. This only happened at the same time than the 0.4.0 update, for what it's worth.

I don't know if other members of the group also see "DELETED" on Webogram as well but I can ask if it's relevant.

**Comment by bvtsang** [comment]
This is happening to a couple of my group names too. It seems like words beginning with hashtag signs get removed.

**Comment by astorije** [comment]
That is correct, this group name starts with `#` too. Nice catch!

**Comment by zhukov** [comment]
Can you take a screenshot? Also check the error console.

**Comment by zhukov** [comment]
I've reproduced it with #. No need for more info. thanks

**Comment by zhukov** [comment]
Fixed this in https://github.com/zhukov/webogram/commit/acb09bd7b590e7fb98c2ae234883517c1717a707

**Comment by astorije** [comment]
Holy cow that was fast!

Thanks a lot @zhukov!
