### ISSUE TITLE
Links in chat don't parsed correctly ...

### ISSUE THREAD

**Issue by nickurt** [zhukov/webogram#690]
When you enter (e.g.) this url,
```
http://www.contoso.com/test.html
```
It will be parsed as this
```
<a href="http://www.contoso.com/test" target="_blank">http://www.contoso.com/test</a>
```

**Comment by ArtemFitiskin** [comment]
Sorry, maybe It is my mistake. 
But exclude ``()`` from URL maybe not better idea. This way is the reason to reopen #457 at least.

At the same time, if you remove ``()``, you gets new problems with links like: `(http://foo.com/blah_blah_(wikipedia))` or `(Something like http://foo.com/blah_blah) `. I have no idea how to fix it clear.

**Comment by zhukov** [comment]
I've seen library by Twitter I guess, which had some solutions about this. They inspected the URL contents and counted number of ( so ) will only balance opening brackets inside URL. This should fix wikipedia case.

**Comment by zhukov** [comment]
(reopened #457)
