### ISSUE TITLE
Pressing enter key after : symbol doesn't send message

### ISSUE THREAD

**Issue by polybuildr** [zhukov/webogram#691]
After the recent update where pressing `:` gives a list of possible emoji options, pressing the enter key after typing a `:string` that's not in the emoji list doesn't send the message.

Steps to reproduce:
1. Type `:P` in the chat box.
2. Press enter.

What should happen?
Message gets sent.

What does happen?
Nothing.

**Comment by daniellemccool** [comment]
I don't know what goes into these issues or commenting on them or whatever, but I'd like to add a side note that there doesn't seem to be any way to disable the smiley menu that pops up after the colon.
