### ISSUE TITLE
Update Telegram on Firefox Marketplace

### ISSUE THREAD

**Issue by Airon90** [zhukov/webogram#693]
The version of Telegram on Firefox Marketplace is outdated. Can someone update it to the latest version?

https://marketplace.firefox.com/app/telegram

Thank you very much!

**Comment by zhukov** [comment]
The app was successfully submitted.

**Comment by Airon90** [comment]
Thank you very much! I wait for the update!

**Comment by Airon90** [comment]
0.4.1 has been released. Please, can you update the version on Firefox Marketplace?

**Comment by zhukov** [comment]
We need to test it on web first.

**Comment by elninosi** [comment]
Any news about updating the version on Firefox Marketplace?

**Comment by Airon90** [comment]
@elninosi Please see #742. I'm sorry but I don't have spare time now because of university exams :(
