### ISSUE TITLE
Sharing websites with Telegram on Firefox OS

### ISSUE THREAD

**Issue by Airon90** [zhukov/webogram#694]
Hi dear devs,
I can't share website links with Telegram on Firefox OS.
Can someone change this line https://github.com/zhukov/webogram/blob/master/app/manifest.webapp#L54 so that it will be possible to share web links with Telegram? Thank you

**Comment by zhukov** [comment]
Hi
What line do you want to have here?
Where is the official documentation about sharing links?

**Comment by Airon90** [comment]
I think that you should just edit that line in this way:

```
  "activities": {
    "share": {
      "href": "/index.html",
      "disposition": "window",
      "filters": {
        "type": ["image/*","audio/*","video/*"]
      },
      "returnValue": false
    }
  },
```

to:

```
  "activities": {
    "share": {
      "href": "/index.html",
      "disposition": "window",
      "filters": {
        "type": ["image/*","audio/*","video/*", "url"],
        url: {
          required:true,
          regexp:/^https?:/
        }
      },
      "returnValue": false
    }
  },
```

Here is a documentation about web activities on Firefox OS: https://developer.mozilla.org/en-US/docs/Web/API/Web_Activities#Firefox_OS_activities

In this way you can make Telegram sharing contacts and emails by adding respectively "webcontacts/contact" and "webcontacts/email".

**Comment by zhukov** [comment]
I see 'url' only under 'view' activity. And Application = 'Browser' for this entry.

**Comment by Airon90** [comment]
Those are just examples. Telegram's "share" array is composed by "image/*", "audio/*" and "video/*" but in the MDN docs only "image/*" is used as example.

However, I tried to add "url" to the array but the app is not working on Firefox OS 2.2 simulator.

I think that it needs more code in order to implement sharing urls, contacts and email contacts. :/

**Comment by floppyrom** [comment]
It would be nice is this is fixed. I'm on Firefox OS 2.5 and cannot share anything from the Brower to Telegram :(
