### ISSUE TITLE
Add button to chat with Telegram directly from Contacts on Firefox OS

### ISSUE THREAD

**Issue by Airon90** [zhukov/webogram#695]
Hi,
this is just my wish.
Is it possible to add a button on the contact page to chat  with the user with Telegram?
Recently Mozilla is working on its client of Firefox Hello for Firefox OS and the app adds a button to make a call to other people using FxHello.

Here is an example:

![index](https://cloud.githubusercontent.com/assets/139841/6188717/66d9d0e8-b394-11e4-8e5a-3866e0cab307.png)

Here you can see an explanation of how to implement it: https://github.com/mozilla-b2g/firefoxos-loop-client/issues/449#issuecomment-71443257

**Comment by Ryuno-Ki** [comment]
Hello, @Airon90,

have you asked the Mozilla team about whether they plan to open up _their_ contacts app for third party IM clients? I assume, Telegram can little do otherwise.

**Comment by zhukov** [comment]
Great idea and it was pretty easy to implement.
I hope there will be no problem, that we override this activity :)

**Comment by nukeador** [comment]
Hey, it's confusing to get this on the contact since these buttons are expected to point you to a Firefox Hello chat (audio/video) and now you are being redirected to Telegram.

**Comment by soapdog** [comment]
Can a new section be added to the contacts app via WebExtensions ?
