### ISSUE TITLE
Can't send stickers

### ISSUE THREAD

**Issue by bigdawggi** [zhukov/webogram#696]
I could totally be missing something, but when I attempt to send a sticker from the web version (starting a message with a thumbs up for example), it just sends the emoji and not a sticker.

If someone sends me a sticker from their device version of the app, it appears in the messages just fine.

I don't hear anyone else saying anything about this, which is why I feel like I may be missing something - and please tell me if so. :)

**Comment by bigdawggi** [comment]
Oh, and I'm on ver 0.4.0 which mentions "full sticker support"
![2015-02-13 at 11 45 am](https://cloud.githubusercontent.com/assets/154625/6193197/f68af2ae-b375-11e4-8cb8-218e7d1e54a5.png)

**Comment by zhukov** [comment]
You can choose stickers from the last tab in emoji tooltip. Do you see them here?
![screen shot 2015-02-14 at 9 33 25 pm](https://cloud.githubusercontent.com/assets/775173/6200611/25aa7f2a-b491-11e4-8925-f6346ec34c41.png)

**Comment by bigdawggi** [comment]
Wow, yes, they're there.  Boy do I feel foolish ;)

I was thinking that star was like a "favorites" or something, and just never moused over.

Thanks for being patient!
