### ISSUE TITLE
Stickers don't sync in Firefox OS app

### ISSUE THREAD

**Issue by elninosi** [zhukov/webogram#708]
On desktop app I can see all my custom stickers.

![Custom stickers on desktop](http://i.imgur.com/Wcvmaex.png)
But on same account on Firefox OS stickers are not synced.

![no custom stickers on Firefox OS](http://i.imgur.com/s01sWNH.png)

**Comment by Walkman100** [comment]
> On desktop app

Telegram Web app or Telegram Desktop?

**Comment by elninosi** [comment]
Telegram Desktop.

**Comment by zhukov** [comment]
Telegram Web doesn't support custom stickers for the moment.

**Comment by elninosi** [comment]
Any update?

**Comment by zhukov** [comment]
Now we do support custom sticker sets, but we still don't support custom single stickers. I think with installed stickersets custom stickers feature is becoming marginal and I have no plans to support it.

**Comment by zhukov** [comment]
Still no plans to support custom stickers. Closing the issue, feel free to propose PR.
