### ISSUE TITLE
[Feature request] Add a "Switch to [mobile/desktop] version" option in the settings

### ISSUE THREAD

**Issue by astorije** [zhukov/webogram#710]
All of a sudden, webogram on my laptop asked me if I wanted to switch to mobile version (which I think might deserve its own GitHub issue). I was curious how the mobile version looked like so... I clicked yes.

I now have no way to switch back to the desktop version. Any way to hack around that? As a long-term fix, could there be a "Switch to [mobile/desktop] version" in the settings list of both versions?

**Comment by Walkman100** [comment]
#619

**Comment by astorije** [comment]
Right, I admit I only searched the most recently opened issues as I thought it was something related to the lastly released version.

I managed to trigger the "desktop switch" when resizing the window, but that would be definitely neat to have a button in the settings, as some windows cannot be resized (mobile browsers or embedded webkits).
