### ISSUE TITLE
Can message self - intended or issue?

### ISSUE THREAD

**Issue by bliz937** [zhukov/webogram#711]
Not sure if this is supposed to be like this or not, but when you are in a web chat and you click on your profile image in the chat, the contact info dialog shows with the ability to initiate a conversation with yourself. 

TL;DR: Chat -> your profile image -> chat with self option is there

**Comment by Walkman100** [comment]
Even if they disable chatting from your profile image, it's still possible via Telegram.me

**Comment by zhukov** [comment]
That's a feature. You can send an SMS to yourself, email your address etc, so why not in Telegram?

**Comment by bliz937** [comment]
I see. 

Though, is there supposed to be a copy of your message, ie, you send message A and message A get received as sent from another contact?

If so, I am not seeing it.

**Comment by zhukov** [comment]
Messages to self doesn't have duplicate, just one copy, which is marked as inbox.

I didn't understand the difference in mobile/web behaviour with sending messages to self. Can you please provide screenshots and full description about what is expected?

**Comment by bliz937** [comment]
My bad. 

After looking at how the web client displays the messages, I realized that it's different to how it is displayed on the mobile client. 

My thought was on the mobile client, it displays the message from you on the right and from the other party on the left. On the web version, it is all on the left.
