### ISSUE TITLE
Wrong message text on deleting messages

### ISSUE THREAD

**Issue by martin31821** [zhukov/webogram#713]
I use the german version of telegram web, 

Steps to reproduce:
Click "Edit" in the top right corner
Select a message
Click "Delete 1"

Then you get the message "Datei wirklich aus Zwischenablage senden?", in the english version there is the correct message

![Wrong text in Message Box](https://cloud.githubusercontent.com/assets/5557633/6324781/0c01544a-bb3f-11e4-92ff-556823fdfc7f.png)

**Comment by ibiBgOR** [comment]
I still get the wrong message. My Client is on version 0.4.0 . May it be possible, that the commit isn't released yet?

**Comment by ArtemFitiskin** [comment]
Yep.

![settings_modal_language](https://cloud.githubusercontent.com/assets/5507542/6657632/bef86cb8-cb62-11e4-8fbc-7b7c91c707a4.png)
