### ISSUE TITLE
emoji flickering on Firefox (v 34.0.5)

### ISSUE THREAD

**Issue by kaufi07** [zhukov/webogram#716]
In the left contacts bar (div.im_dialogs_col) and the main chat part (div.im_history_col) the emoji flicker in Firefox. You can see this with the :smile: emoji very good, because "it's teeth" move a bit. But that occurs also for other emojis. (e.g. :see_no_evil: )
by disabling the box-sizing attribute of
 *, *:after, *:before {
    box-sizing: border-box;
}
the flickering of the emojis stops. but this also hides the im_history_col :)
this issue does not belong to the mobile version. there everything is fine

**Comment by zhukov** [comment]
Can't reproduce this. Can you attach a screenshot and/or a video?
When does it flicker? Are you using stable Firefox? Do you have zoom enabled? Did you try to disable all extensions?

**Comment by zhukov** [comment]
Any updates here?

**Comment by kaufi07** [comment]
can't reproduce myself with the most actual version. I used the latest FF version.
the flickering occured in the chat view and apparently on all emojis. I did not use zoom functionality then.
But since this problem seems not to occur for the moment, not further action is needed.
I will upload a video/screen if I come across the problem again. thanks
