### ISSUE TITLE
[Feature request] Blinking taskbar icon on new message

### ISSUE THREAD

**Issue by delas** [zhukov/webogram#719]
When a new message is received, it would be useful if the desktop application icon, on the Windows taskbar, starts "blinking".

Like the "Notification Highlight" in this picture:
![image](https://cloud.githubusercontent.com/assets/867237/6410051/66dd5ee8-be6b-11e4-930e-ec655c043428.png)

**Comment by zhukov** [comment]
Do you know any web app sample with this feature? Or API documentation may be?

**Comment by delas** [comment]
Not really. Sorry... :disappointed:

**Comment by Ryuno-Ki** [comment]
After some research, I found three ways to deal with this task:

 1. Change the title. Obviously clever, if the browser is open.
 1. Play a sound. Be aware that there are hearing impaired users out there.
 1. Try out the new [Web Notification API](https://developer.mozilla.org/en-US/docs/Web/API/notification) (not supported by IE …).

@alexgibson even wrote a [small library](/alexgibson/notify.js) to abstract away platform differences. I haven't tested it on my own.

**Comment by anewuser** [comment]
Here's an example of web app that uses the first solution mentioned by @Ryuno-Ki: http://www.omegle.com/ .

**Comment by zhukov** [comment]
@Ryuno-Ki @anewuser we do have support for all the features mentioned in the list. Did you ever use Telegram Web? :laughing: 

Even more, we have [Virate API](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/vibrate) supported: https://github.com/zhukov/webogram/blob/master/app/js/services.js#L4585

**Comment by anewuser** [comment]
@zhukov time to close this issue then. :)

**Comment by zhukov** [comment]
Yeah, I think so.

@delas feel free to open the issue if you find any ways to notify user from the browser in a better way.

**Comment by Ryuno-Ki** [comment]
@zhukov Nope. Only the Firefox OS app.

**Comment by Royal2000H** [comment]
@zhukov There is still benefit to having the notification highlight as described in the first post.

Currently Telegram Desktop does this (it also adds a little numerical badge to the icon, not necessary in my opinion). But it's a full-fledged app.

Perhaps the web app by itself cannot implement the notification highlighting, but I think the **Chrome App version should highlighting**. For reference, the Hangouts chrome app is able to do this.
