### ISSUE TITLE
Stretched stickers

### ISSUE THREAD

**Issue by kosmodrey** [zhukov/webogram#720]
Stickers smaller then 260x260 px are stretched:
![bqd6r 2015-02-27 14 14 22](https://cloud.githubusercontent.com/assets/10274725/6412341/2d422a36-be8b-11e4-9456-2319d583b0cb.png)
Should be:
![fj09t 2015-02-27 14 15 05](https://cloud.githubusercontent.com/assets/10274725/6412340/2d3fc516-be8b-11e4-9294-7817af6c700d.png)
(when remove element width and height in style)

Webogram version: 0.4.0
Device: Firefox 36 on Windows 8.1 notebook

**Comment by Walkman100** [comment]
See #636

**Comment by zhukov** [comment]
Now the minimum size is 192px. And yes, it will be stretched if the image is smaller.
