### ISSUE TITLE
notification message across devices

### ISSUE THREAD

**Issue by snapo** [zhukov/webogram#724]
Hi , first of all thanks a lot for doing such great work.
I just noticed that if i not close the webogram chrome plugin telegram and then go out for a drink i would not receive any notification because the chrome telegram client marks them as read. is there a option or setting where i can say new notifications should appear on all devices?

if i close the chrome telegram app, notifications are working....

**Comment by zhukov** [comment]
Webogram stops reading messages after:
1) 30 seconds inactivity inside window
or
2) the window or tab lost its focus (e.g. you switched to another app)

Is it true for you, that it stops reading after 30 seconds of inactivity?

**Comment by zhukov** [comment]
Any updates here?

**Comment by snapo** [comment]
the problem was when i had tg open @home and tg was still focused when i
left the building....

On Tuesday, March 24, 2015, Igor Zhukov <notifications@github.com> wrote:

> Any updates here?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zhukov/webogram/issues/724#issuecomment-85591061>.
>


-- 
__________________
Mike Jans
Hauptstrasse 20
9555 Tobel
CH-Switzerland
Mobile: +41792498070

**Comment by zhukov** [comment]
What is the OS and browser? Can you reproduce this?

**Comment by snapo** [comment]
OS Windows, Browser Chrome. I try it just now because i didnt know that the
notifications should arrive after a few minutes when the windows gets in
inactive state.

__________________
Mike Jans
Hauptstrasse 20
9555 Tobel
CH-Switzerland
Mobile: +41792498070

2015-03-30 20:22 GMT+02:00 Igor Zhukov <notifications@github.com>:

**Comment by zhukov** [comment]
so can you reproduce this again?

**Comment by snapo** [comment]
no, seems that i didnt eait for the 5min timeout....

On Tuesday, March 31, 2015, Igor Zhukov <notifications@github.com> wrote:

> so can you reproduce this again?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zhukov/webogram/issues/724#issuecomment-88045024>.
>


-- 
__________________
Mike Jans
Hauptstrasse 20
9555 Tobel
CH-Switzerland
Mobile: +41792498070

**Comment by zhukov** [comment]
@snapo the timeout is just 30 seconds, not 5 minutes. Is that OK? Should we close the issue?

**Comment by snapo** [comment]
@zhukov , yes the issue can be closed.... as it worked i just waited 5 min instead of 30 sec
