### ISSUE TITLE
Unable to launch Firefox app under Android

### ISSUE THREAD

**Issue by mbnoimi** [zhukov/webogram#725]
I installed Telegram from Firefox Marketplace then launch it but unfortunately I always receive a white screen directly after the splash screen (the sky blue screen) although the other Firefox apps work fine.

* Android 4.4.2
* Firefox 36.0

![screenshot_2015-03-02-08-57-25](https://cloud.githubusercontent.com/assets/284547/6436680/7162a60e-c0bc-11e4-800a-bbf5d8680e71.jpg)
![screenshot_2015-03-02-08-59-25](https://cloud.githubusercontent.com/assets/284547/6436681/71661992-c0bc-11e4-8dd8-3f0467f88075.jpg)
![screenshot_2015-03-02-08-57-15](https://cloud.githubusercontent.com/assets/284547/6436682/71669598-c0bc-11e4-928c-99eb69b94ae9.jpg)

**Comment by auchri** [comment]
Same happens to me, Firefox and Android 4.4.4

**Comment by zhukov** [comment]
This issue is no longer actual since 
"These applications can only be installed on devices running Firefox OS." according to https://marketplace.firefox.com.
