### ISSUE TITLE
Bug (.jpg): "The photo dimensions are invalid, please select another file."

### ISSUE THREAD

**Issue by mikkovedru** [zhukov/webogram#726]
When I try to share a large 6.0MB .jpg file, I get an error: "The photo dimensions are invalid, please select another file."

Method: messages.sendMedia
Result: {"_":"rpc_error","error_code":400,"error_message":"PHOTO_INVALID_DIMENSIONS"}
Stack: p/d@https://web.telegram.org/js/app.js:16:24163
p/h/<@https://web.telegram.org/js/app.js:16:25153
c@https://web.telegram.org/js/app.js:8:6393
l/<@https://web.telegram.org/js/app.js:8:6565
jn/this.$get</u.prototype.$eval@https://web.telegram.org/js/app.js:8:13758
jn/this.$get</u.prototype.$digest@https://web.telegram.org/js/app.js:8:12250
jn/this.$get</u.prototype.$evalAsync/<@https://web.telegram.org/js/app.js:8:13845
r@https://web.telegram.org/js/app.js:7:708
Ht/p.defer/n<@https://web.telegram.org/js/app.js:7:2708
n@https://web.telegram.org/js/app.js:2:14644

Linux Mint. Firefox 36.0.
Example of the file:
![034_16679261266_a7189919cc_o](https://cloud.githubusercontent.com/assets/2521942/6497657/5b21d76c-c2eb-11e4-882f-24b83b3b986f.jpg)

**Comment by zhukov** [comment]
So, what's the problem? The UI states, that image is invalid: it's too big. Telegram API has limits on photos sent.

**Comment by auchri** [comment]
@mikkovedru Send the image as a file
