### ISSUE TITLE
Infinite loop in Chrome app on x64 when receiving large text messages

### ISSUE THREAD

**Issue by Sukasa** [zhukov/webogram#727]
I had someone try to send me a Share Code for a minecraft modpack, essentially an extremely long text string.  However, after being sent one this code, I cannot load up the conversation with that person, as otherwise the chrome process will get locked into an infinite loop at 100% of one CPU core.

**Comment by ArtemFitiskin** [comment]
@zhukov Perhaps this is due to the regular expressions? In that case, it might be worth checking the length of the message and if it exceeds a certain limit - handle it to the Worker.

**Comment by zhukov** [comment]
The maximum message length in Telegram is 4096 characters, so I don't think this is a problem.

We may need a message text and/or cup profile at the moment of problem.

**Comment by zhukov** [comment]
Any updates here?

**Comment by Sukasa** [comment]
I haven't tried again here, mostly because of the trouble it put me through to get the application un-frozen on desktop.

**Comment by db2k** [comment]
We just need the string so we can see how long it is and how we can handle it I think.

**Comment by Sukasa** [comment]
This is the same code that was sent, just via HTTP.  I've included the link instead of the content for size reasons.
http://dotuser.rustedlogic.net/share/sharecode

**Comment by zhukov** [comment]
Very nice bugreport. I've found a serious performance issue with regexp for finding URLs in big texts.

**Comment by zhukov** [comment]
//cc @ArtemFitiskin the commit  0fc08f1 might be interesting for you :)

**Comment by ArtemFitiskin** [comment]
@zhukov ¯\_(ツ)_/¯

p.s. I thought so.
