### ISSUE TITLE
Add oembedapi support

### ISSUE THREAD

**Issue by agung-wete** [zhukov/webogram#728]
Hi

First, thank you for this good software,
How about more oembed support please, something like http://oembedapi.com/

Thanks

**Comment by zhukov** [comment]
Please describe, which features you need with this oembed support. What is the use case?

**Comment by agung-wete** [comment]
http://oembedapi.com , https://iframely.com is providing kind of  "summary" to URL.
Something like when user share image / file in webogram, there is thumbnail of it, but this for URL

playground : https://iframely.com/embed

**Comment by zhukov** [comment]
This is no longer actual.
Telegram API now returns basic URL description + photo, and embed_url for some websites: https://telegram.org/blog/link-preview
The domains list will extend eventually.
