### ISSUE TITLE
Youtube links ending in s are not recognized as youtube links.

### ISSUE THREAD

**Issue by JeremybellEU** [zhukov/webogram#729]
https://www.youtube.com/watch?v=JUT2EX28-Ms for example ends in a 's', however when I post this in Webogram it creates a link up to 's', but not including, meaning the link becomes 'https://www.youtube.com/watch?v=JUT2EX28-M' which is not a valid youtube link making the previous and link not working.

**Comment by zhukov** [comment]
Duplicate of #697
This is already fixed on beta (zhukov.github.io/webogram). Will update stable soon.
