### ISSUE TITLE
[Feature request] Enabling pushState Within Angular

### ISSUE THREAD

**Issue by ArtemFitiskin** [zhukov/webogram#730]
What about using [html5Mode](https://docs.angularjs.org/api/ng/provider/$locationProvider) in $locationProvider?

From **docs.angularjs.org**:
> If true, will rely on history.pushState to change urls where supported. Will fall back to hash-prefixed paths in browsers that do not support pushState.

For example:
```
https://web.telegram.org/login
https://web.telegram.org/im
```

Instead of:
```
https://web.telegram.org/#/login
https://web.telegram.org/#/im
```

I test it locally and suppose this works OK. My steps:

1) Add **base** tag to index.html
```html
<base href="/">
```

2) Enable **html5mode** in app.js

```javascript
$locationProvider.html5Mode(true);
```

P. S. Possible compromise solution for #685
P. P. S. When I trying to logout from settings I get an error (page has a redirect loop). Maybe this is not the only error related to this.

**Comment by zhukov** [comment]
I thought about this, but I didn't like that, because in this case conversation name or group id will be exposed to external websites via referer header when opening external link.

**Comment by ArtemFitiskin** [comment]
I agree.
