### ISSUE TITLE
Blank page, while opening app page with JS error in JS console on Chrome Canary

### ISSUE THREAD

**Issue by ShockwaveNN** [zhukov/webogram#731]
Step to reproduce:
1. Open https://web.telegram.org/ or http://zhukov.github.io/webogram/ in standart\incognito mode

Result:
Blank Page, without any content 
JS Error in JS Console:
`Uncaught TypeError: Cannot set property memory of #<Console> which has only a getter
web.telegram.org/:1`

Test enviroment:
Win 8.1 x64 
Google Chrome Version 43.0.2334.0 canary (64-bit)

**Comment by ArtemFitiskin** [comment]
Same story, OS X / Canary 43

**Comment by ArtemFitiskin** [comment]
I don't fully understand this situation, but problem in [polyfil.js](https://github.com/paulmillr/console-polyfill). 

In 43.x ``console.memory`` does not a property.

**Canary** (43):
```javascript
console.hasOwnProperty('memory'); // false
```
![canary](https://cloud.githubusercontent.com/assets/5507542/6674454/cc183446-cc2a-11e4-8a90-78593b0ac232.png)

**Chrome** (41):
```javascript
console.hasOwnProperty('memory'); // true
```
![chrome](https://cloud.githubusercontent.com/assets/5507542/6674458/d663c9ba-cc2a-11e4-919f-1026c10c2565.png)

Possible solution simply use a try-cache statement:

```javascript
while (prop = properties.pop()) {
    try {
      con[prop] = con[prop] || empty;
    } catch (e) { }
}
```
