### ISSUE TITLE
Unexpected prompt when switching from mobile to fullsize versions by resizing the window

### ISSUE THREAD

**Issue by juanique** [zhukov/webogram#733]
Until a few days ago, I would use the Telegram web app as my example of how apps should be: "Look how responsive it is! see how it changes to the mobile version when it's small? all apps should do that."

Now there's a weird confirmation message when I resize the window: "Would you like to switch to the mobile version?". Of course I want to switch to the mobile version, the full desktop version is unusable in that size.

**Comment by zhukov** [comment]
Duplicate https://github.com/zhukov/webogram/issues/585.
