### ISSUE TITLE
Just blank window.

### ISSUE THREAD

**Issue by drkPu1se** [zhukov/webogram#735]
I'm running dev channel on my chromebook. Specifically  43.0.2334.0 dev (64-bit). I run the Chrome OS application and it shows only a blank window. However I run web.telegram.org and it runs no problem. 

Here's a screenshot.

![screenshot 2015-03-18 at 10 25 01 pm](https://cloud.githubusercontent.com/assets/9374174/6723391/ac4d3c62-cdbd-11e4-95a2-ab4a9e386e52.png)

**Comment by zhukov** [comment]
Duplicate #731. Will update Chrome App soon
