### ISSUE TITLE
[Enhancement]  Allow passing message text via URL

### ISSUE THREAD

**Issue by asdofindia** [zhukov/webogram#739]
When opening webogram, read message from URL and populate the input box with it.
For example,
https://web.telegram.org/#/im?p=@username&message="Hi there"
should open a conversation with username with the input box showing "Hi there"

This could also be extended to telegram.me

**Comment by zhukov** [comment]
Was partly implemented in 0.4.9. To be released soon (when will be supported server-side and in other clients).
