### ISSUE TITLE
Paste image from clipboard

### ISSUE THREAD

**Issue by kicOLD** [zhukov/webogram#74]
Great tool. Today we use skype's chat only because you can drop images right from your clipboard (ctrl + v). Would be very cool if you could add this feature to webogram!

Here is a snipped how this could work: http://stackoverflow.com/questions/6333814/how-does-the-paste-image-from-clipboard-functionality-work-in-gmail-and-google-c/6338207#6338207

**Comment by ArtemBernatskyy** [comment]
@zhukov  No updates for Safari ?

**Comment by stek29** [comment]
@ArtemBernatskyy most sites don't support pasting images from clipboard in safari :\

**Comment by ArtemBernatskyy** [comment]
@stek29 ok but i've tried now with gmail and vk.com and it works, my Safari is 11 version, so i believe now it works )
