### ISSUE TITLE
install webogram on my vps

### ISSUE THREAD

**Issue by spyexe** [zhukov/webogram#740]
Hello I try to install telegram on my vps but I can not 
how to do that anyone help me ???

**Comment by hebrew878** [comment]
just goto https://web.telegram.org/ from most popular web browsers
like chrome,firefox

**Comment by spyexe** [comment]
no I want to install it from my own vps and my own domain ?

**Comment by hebrew878** [comment]
try node server.js youdomain/ip 80

**Comment by zhukov** [comment]
@spyexe do you realise, that Webogram is just a client-side app? All your messages are stored in Telegram Cloud, on their servers. You can't have them on VPS. If the answer is yes, you can just build the app with `gulp build` and host the `dist` subfolder with any webserver.
