### ISSUE TITLE
Problem with Tags

### ISSUE THREAD

**Issue by danielquijada** [zhukov/webogram#741]
When you want to mention someone like *@StupidExample* in a comment, but you hit enter before completing the name, shouldn't it complete it with the first person on the list of posibilities on that group?

I'm a newbie dev, and I don't know even if it can be done, but if it can I think it would be a great QoL change, thanks! =D

PS: I don't know how to add labels here, sorry

**Comment by zhukov** [comment]
I don't think, this is a good behaviour. We have the same for emoji and if you type colon `:`, hit enter and it will select the first recent emoji, this will really annoying.

**Comment by danielquijada** [comment]
hm.. true, never tought of it that way, thanks for your opinion!
