### ISSUE TITLE
Latest version of Webogram not working on latest version of Firefox OS 

### ISSUE THREAD

**Issue by Airon90** [zhukov/webogram#742]
I [downloaded](https://github.com/zhukov/webogram/tree/9bf91e467a712cab7b24be312c8e2f514c3f97f1) latest version of Webogram, pushed on my Flame with latest version of Firefox OS and it only shows a blank screen.

**Comment by zhukov** [comment]
What errors do you see in console?

**Comment by asdofindia** [comment]
Hey @Airon90 , if you're following the [instructions in readme](https://github.com/zhukov/webogram/#running-as-firefox-os-app) and just opening the app folder in WebIDE, this is because of #737 
You've to compile less to css first.

**Comment by asdofindia** [comment]
@zhukov , if what I said is indeed the issue, wouldn't it be solved by not .gitignoring the app/css folder? It'd serve all people then. Shall I send a PR like that, with changes in README ?

**Comment by zhukov** [comment]
Duplicate #756
