### ISSUE TITLE
[Firefox OS] presence issue

### ISSUE THREAD

**Issue by TitanNano** [zhukov/webogram#745]
when i turn off the screen of my device and my contact replies very quickly I'll miss the message because I don't get any notification. I guess there is some problem with my presence status and the application thinks that I'm still present?

**Comment by zhukov** [comment]
The app catches 'blur' event and uses it to change presence as well as inactivity 30 sec timeout.

**Comment by TitanNano** [comment]
there is also the visibilitychange even most FxOS apps use it's better to use that on FxOS. I can just guess but on FxOS we have only one Gecko window so I assume that there is no blur even. 
visibilitychange is fired when ever the visibility status of the document changes. The current visibility status you can get by checking if document.hidden is true or false.
