### ISSUE TITLE
[Feature Request] Add a "end of messages" on bottom of conversation

### ISSUE THREAD

**Issue by becker990** [zhukov/webogram#747]
sometimes on long chats reading a long log like 4k messages, the client becomes a little slow and has to load the next messages and you dont know if is the end of the chat, so would it be very handy to have just a simple text signaling the end of chat

something like the image shows
![sample2](https://cloud.githubusercontent.com/assets/485533/6864521/28193e66-d441-11e4-984b-cab868a26792.png)

**Comment by ArtemFitiskin** [comment]
You can check messages time, or compare with the text of the last conversation message that is displayed in the contact list on the left. It's not enough?

**Comment by becker990** [comment]
@ArtemFitiskin yes it's enough, but its a palliative solution to the proposed problem, and not so obvious.

**Comment by becker990** [comment]
@ArtemFitiskin also by time of last message u cant really know if is the end of messages, like when people were not talking for some hours. Also i propose a code that only adds that text by comparing the last displayed message with the last message in the conversation.

**Comment by zhukov** [comment]
@becker990 I don't like this solution, since it adds more clutter in UI for 99% of time for solving very rare issue.

**Comment by becker990** [comment]
@zhukov I would'nt call it an issue, since is only an issue on memory hogging cases. But yes i agree, it adds clutter text. And thats ugly, im a bad designer. I propose a lighter approach with a:
.im_bottom_panel_wrap {
    border-top: 1 or 2px solid #f2f2f2; (or other color of choice such as client light blue)
}

when messages end, it gives a feel of page ending.

1px:
![1](https://cloud.githubusercontent.com/assets/485533/6925395/6a4e2e3c-d7b5-11e4-8c90-e6503dee662d.png)

2px:
![2](https://cloud.githubusercontent.com/assets/485533/6925410/7c760c24-d7b5-11e4-94e8-a27f9bc1fa17.png)

test:

**Comment by db2k** [comment]
Maybe we should add a simple sign at the end of the messages list. This way we don't clutter the UI but give users a way to see the end of a conversation.

**Comment by zhukov** [comment]
We have now nice progress so you can understand when history loading. No need to display any additional text.
![screen shot 2016-02-11 at 14 30 21](https://cloud.githubusercontent.com/assets/775173/12975341/bbdb16ce-d0b2-11e5-9597-9872c04f08e3.png)
