### ISSUE TITLE
Initially generating keys is broken by AdBlockPlus

### ISSUE THREAD

**Issue by hoodlm** [zhukov/webogram#749]
when trying to log-in initially in web.telegram.org, the "Generating Keys..." script hung indefinitely. It wasn't doing meaningful work (no elevated CPU usage in firefox process). When I disabled AdBlockPlus for web.telegram.org, it took ~5 seconds to successfully generate keys.

Firefox 36.0.4
AdBlockPlus 2.6.8
Windows 7

**Comment by zhukov** [comment]
I can't reproduce this.

Can you? In order to delete your authorization key you can launch following 5 commands in javascript console:

```
> delete localStorage.dc1_auth_key
> delete localStorage.dc2_auth_key
> delete localStorage.dc3_auth_key
> delete localStorage.dc4_auth_key
> delete localStorage.dc5_auth_key
```

and then reload a page (this will also log you out).

**Comment by zhukov** [comment]
Also I've found and issue which could affect 1/256 key generations.

**Comment by zhukov** [comment]
@hoodlm can you try again?
