### ISSUE TITLE
V. 0.4.2: Send button turns green in mobile view (Chrome OS)

### ISSUE THREAD

**Issue by noahleigh** [zhukov/webogram#752]
When in mobile view, the Send button that appears when text is entered into the input box has a green background, which a I assume is not the intended behavior.

App version: 0.4.2
Chrome OS version: Version 42.0.2311.60 beta (64-bit)

![screenshot 2015-03-29 at 12 56 55 pm](https://cloud.githubusercontent.com/assets/5957867/6886698/c608572c-d614-11e4-9699-5745952f86e0.png)

**Comment by db2k** [comment]
This really doesn't look right...
