### ISSUE TITLE
'css' folder is missing  inside 'app' folder

### ISSUE THREAD

**Issue by friend4chams** [zhukov/webogram#756]
hi,
 i can see the link of app/css/ in the index file but i can not find it inside the script and it can not run as well 

please upload the total package again, currently the script is not working

**Comment by profilink** [comment]
Hi, this is not for me the question, I am not the developer of this script.)
Here to it please contact https://github.com/zhukov - it developer of the script.

**Comment by friend4chams** [comment]
@proflilink thanks for reply
but i think this is the place to report the issues of script webogram, the developer can reply me here directly.

**Comment by zhukov** [comment]
You should run
```
sudo npm install -g gulp
sudp npm install
gulp watch
```

To generate CSS folder.

**Comment by friend4chams** [comment]
Thanks but i think this is for launching it locally , i have directly uploaded it on cpanel , do not know how to run it on cpanel, so copied the css files of web.telegram.org.

Anyways thanks.

**Comment by anewuser** [comment]
@zhukov Shouldn't it be visible from https://github.com/zhukov/webogram/tree/master/app too?

**Comment by zhukov** [comment]
@friend4chams  if you have no plans to modify the code, you can use the built app from [Releases section](https://github.com/zhukov/webogram/releases). I try to publish stable versions there.

**Comment by zhukov** [comment]
@anewuser no, we avoid duplicates, since we already have LESS files in the same folder.

**Comment by anewuser** [comment]
@zhukov ah. I didn't know about this technology. Thank you.
