### ISSUE TITLE
404 Not Found: /app/css/app.css, /app/css/desktop.css

### ISSUE THREAD

**Issue by BadBone2k** [zhukov/webogram#758]
For a few day now, my self-hostetd webogram seems to be broken:

![webogram-css-broken-2015-04-07](https://cloud.githubusercontent.com/assets/10176191/7021675/941e338c-dd24-11e4-9c6e-f37b472de0e3.png)

When loading the page I get the following:

```
node server.js 61011
Http Server running at http://localhost:61011/
...
404 Not Found: /app/css/app.css
...
404 Not Found: /app/css/desktop.css
...
404 Not Found: /favicon.ico
```

I already deleted my webogram folder and cloned the git again, but the error persists.

**Comment by friend4chams** [comment]
Check https://github.com/zhukov/webogram/issues/756
CSS folder is actually missing from source of the developer.

You can download them manually from http://web.telegram.org/css/app.css http://web.telegram.org/css/desktop.css and http://web.telegram.org/css/mobile.css (right click and save as) and then create a folder named 'css' inside 'web' and put these three .css inside that folder, it will start working fine.

**Comment by BadBone2k** [comment]
Thanks for the hint. Nice workaround, should've thought of that myself ;-)

**Comment by zhukov** [comment]
Duplicate #756.
