### ISSUE TITLE
Popup message for two step verification doesn't display Umlaute

### ISSUE THREAD

**Issue by TobsCore** [zhukov/webogram#761]
After successfully inserting the information for two-step-verification, the pop-up that informs the user, that an email will be sent, displays the wrong characters for the German Umlaute. 

I took a screenshot of it, just in case you don't know what popup-message I'm talking about.
_&#252;_ should be replaced with _ü_
![bildschirmfoto 2015-04-09 um 10 00 06](https://cloud.githubusercontent.com/assets/1383085/7062732/851ef5c4-dea0-11e4-8ff1-b1d332ff4967.png)

**Comment by Ryuno-Ki** [comment]
@TobsCore Hint: Either wrap the html entity in &lt;pre&gt; tag or use &amp;amp; for the leading &amp; :)

GitHub comes with a preview tab, too. Your bug description looks strange otherwise ;-)
