### ISSUE TITLE
Удаление пробелов

### ISSUE THREAD

**Issue by SeibelStan** [zhukov/webogram#762]
Зачем так жестко удаляются пробелы, даже в начале строки ни одного не оставляет.
Пусть будет опционально хотя бы. По-умолчанию - удаляет, с настройкой - нет. Или наоборот.
Мобильное приложение сохраняет.

**Comment by SeibelStan** [comment]
>> Или, еще лучше, разделить на разные кнопки: шифт+ентер - оставить как есть, а по просто ентеру - тримать.

**Comment by zhukov** [comment]
Пробелы удаляются на серверной стороне со всех клиентов.
