### ISSUE TITLE
keyboard shortcut to direct switch between conversations

### ISSUE THREAD

**Issue by Akronix** [zhukov/webogram#768]
As I wrote in #496 I think I would be interesting to have a shortcut just for switching directly to one conversation (without unreading the conversations in between). I'm very often talking to many people at the same time and this scenario happens to me every time; then, I have to use the mouse to go to the conversation I want to talk to. But the mouse is quite slow and I'd prefer to have a more direct way.
 
I propose to use:
<kbd>alt</kbd> + <kbd>shift</kbd> + <kbd>#</kbd>. Where # is the number of that conversation starting from the top in ascending order.
I think that there's no conflict with the shortcuts of the browser (I've tested on firefox, chrome, internet explorer and opera)

I'd like to (try to) implement this feature.

**Comment by zhukov** [comment]
Yeah, sure. Take a try. 

I suppose, the code should be placed around here: https://github.com/zhukov/webogram/blob/master/app/js/directives.js#L592
