### ISSUE TITLE
Soundcloud Links no longer display as Embeds

### ISSUE THREAD

**Issue by ErikAGriffin** [zhukov/webogram#770]
This was my favorite reason to use the web version of Telegram.

Now after this "link previews" update, instead of getting a live soundcloud object there is just a link.

Please restore this functionality

**Comment by zhukov** [comment]
Can you describe the use case? How do you use it?
The main problem I see is that embed which play sound can be hidden when you switch conversation. We could revert this feature but with some workaround for this case.

btw, did you click the link? It opens a modal window with the same embed.

**Comment by killarny** [comment]
Having the embed inline with the conversation was better - it's nice to be able to listen and chat simultaneously without having a browser window open.

**Comment by ErikAGriffin** [comment]
Yes. The modal looks nice, but if you close it the music stops and you cannot continue to chat while the modal box is open.

**Comment by zhukov** [comment]
Sorry, no plans to change this for now. May be later in universal manner.
