### ISSUE TITLE
Reap older messages in long-running session

### ISSUE THREAD

**Issue by mattking17** [zhukov/webogram#772]
When I leave webogram open for a few days, my message history becomes extremely long and starts hanging the browser. It would be nice to check for older messages and remove them from the DOM if they are old, without having to refresh the page.

I'd like to contribute to webogram by adding this feature.

**Comment by zhukov** [comment]
I've spent some time recently fixing similar issue in #705. The changes are already live in beta: https://zhukov.github.io/webogram/ and will be in web.telegram.org very soon if no problems found.

**Comment by zhukov** [comment]
Already released in 0.5.2.
