### ISSUE TITLE
Add tumblr image previews to messages

### ISSUE THREAD

**Issue by mattking17** [zhukov/webogram#773]
I would like to contribute by adding this feature.

**Comment by zhukov** [comment]
This is a server-side feature probably. Can you give the example of link?

**Comment by mattking17** [comment]
Sure, here ya go:

http://33.media.tumblr.com/175fc0918e1392e760a90059e9b7a300/tumblr_mvxajxwdIO1rnq0vfo1_500.gif

**Comment by zhukov** [comment]
I suppose this kind of previews is coming little later. This is not a web page, just a link to file. No meta tags, API etc.
Nn the meantime you can share this image with right click - copy image  and then paste it in Telegram Web.

**Comment by mattking17** [comment]
Okay, thanks!

**Comment by Ryuno-Ki** [comment]
Right-clicking on mobile? oO
