### ISSUE TITLE
Improve UX of user list selection

### ISSUE THREAD

**Issue by astorije** [zhukov/webogram#774]
The UX with username is quite counter-intuitive at the moment IMO.

A nice interaction pattern here would be that:

1. When the list of users in the group appears when typing `@`, the first line should be highlighted/selected. Right now one needs to go <kbd>up</kbd> or <kbd>down</kbd> to see the highlight appear, which therefore comes from nowhere.

2. <kbd>Enter</kbd> key is across all messenger application used to send the message. When I select a @user from the list, I always have this short hesitation before pressing <kbd>Enter</kbd>. And if by accident I press it twice, I send a message potentially unfinished. Using the <kbd>Tab</kbd> key would be more natural as it is consistently used for completion on messengers that support it (like IRC) or other applications (terminal, browser, file explorer, ...)

Does that make sense? :-)

**Comment by Ryuno-Ki** [comment]
Sometimes, <kbd>Space</kbd> is used for selection, too.

**Comment by astorije** [comment]
Hum, I think that would be confusing in this case. Here, both <kbd>Space</kbd> and <kbd>Enter</kbd> are already used for typing messages while <kbd>Tab</kbd> is idle.

**Comment by Ryuno-Ki** [comment]
On the other hand, <kbd>Tab</kbd> is used by [AT](https://en.wikipedia.org/wiki/Computer_accessibility) for navigating through web sites/apps …

**Comment by astorije** [comment]
I still believe it's less disruptive and less error-prone that `Space` and `Enter`.

Anyway, I stated my case, I'll be happy if @zhukov gives his feedback :-)

**Comment by zhukov** [comment]
I think Tab is totally OK for this.

**Comment by astorije** [comment]
Thanks @zhukov !
