### ISSUE TITLE
Enhancement: Add "Close current session" or "Disconnect" button

### ISSUE THREAD

**Issue by bluezed** [zhukov/webogram#787]
I'm using Telegram Web on several PCs and would find it very handy if there was a "Close current session" or "Disconnect" button somewhere in the menu or directly on the main page.

Currently when I just close the browser on one of the machines the session still shows up on other devices and I then close it from there. It would be more practical if I could actively close the session directly on the device I'm on once I'm done using it.

If this is already possible then please ignore but let me know how to do it ;)

Thanks!

**Comment by ArtemFitiskin** [comment]
What is missing with "Log out" link (bottom of the "Settings" popup)? :smile:

**Comment by bluezed** [comment]
DOH! Never saw that... probably cause resolution on some of my devices is low and I have to scroll down to see it.
Thanks ;)

**Comment by ArtemFitiskin** [comment]
No problem :-) 

p.s. Don't keep that in secret :flashlight:
