### ISSUE TITLE
multiple Username selection capability

### ISSUE THREAD

**Issue by 9px** [zhukov/webogram#788]
Telegram Username is a great solution to keeping my mobile number private.
but we can only select 1 username.
is there possible to add ability of multiple Username to telegram?

such as Yahoo, that allow users to select 5 alias (username) for chat and this is useful for me.
https://my.help.yahoo.com/kb/messenger/create-alias-sln1591.html

**Comment by hebrew878** [comment]
no

**Comment by zhukov** [comment]
yes, this is Telegram API restriction

**Comment by mjg** [comment]
Can the app deal with *two accounts* being used simultaneously?
Having at least two (1 business, 1 personal) would be nice to keep identities separated. Two accounts would allow two usernames.

**Comment by NoIE** [comment]
Having at least two (1 personal, 1 anonymous).
