### ISSUE TITLE
i can't paste simple text to input box, unless i refresh Webogram!

### ISSUE THREAD

**Issue by 9px** [zhukov/webogram#789]
hi. i have this problem many times & every day!
i use Firefox on multiple device (windows 7) and all of them has this problem :|

I'm sorry; i know that it isn't a useful error report, but i don't know when and why this problem accrues.
but i see that other users also report this problem, so i want to note you that is a public & serious issue.

**Comment by hebrew878** [comment]
i have also experienced this problem. Firefox on Win7

**Comment by zhukov** [comment]
Duplicate https://github.com/zhukov/webogram/issues/218#issuecomment-72832576
This is a Firefox bug, I've already reported it https://bugzilla.mozilla.org/show_bug.cgi?id=1129372
