### ISSUE TITLE
Generate random names for images (other than index.jpg)

### ISSUE THREAD

**Issue by anewuser** [zhukov/webogram#790]
Every time I right-click on an image  sent to me on Firefox to save it, it has the same name: index.jpg. If one saves all the pictures in the same folder, he/she keeps getting a dialog box asking if they want to overwritte the last picture. 

Please make the web version of Telegram generate random names for every new image on Firefox instead of using index.jpg for all them.

**Comment by dv2y** [comment]
Yeah, I noticed that too. Isn't it possible to save with  the original name?

**Comment by zhukov** [comment]
Sorry, this is not possible in Firefox. You either should use "Download" buttons in UI or use Chrome Browser. Firefox has no FileSystem API support, which allows to set blob name.
