### ISSUE TITLE
Sending video problems

### ISSUE THREAD

**Issue by dmoskovsov** [zhukov/webogram#793]
Recently I experience problems with sending video often. 
I just tried to send 23mg .m4v video from webogram to mobile. I can download it but not to play.
http://prntscr.com/71di4v

**Comment by zhukov** [comment]
Where do you want to play it? What error do you see?

**Comment by zhukov** [comment]
@dmoskovsov ping

**Comment by hamidpp** [comment]
h: please help me to invoke telegram api methods in c# or jquery ajax. please

**Comment by zhukov** [comment]
@hamidpp please refer to https://core.telegram.org/bots

**Comment by zhukov** [comment]
Closing the original issue. Feel free to open if more info collected.
