### ISSUE TITLE
Firefox Marketplace update

### ISSUE THREAD

**Issue by TitanNano** [zhukov/webogram#794]
Hey could we get an update on the marketplace? we are still on v0.4.0 :-/ 

thank you :)

**Comment by Airon90** [comment]
It seems that there were problems with css (see #742 and #756).
However, I just downloaded the code and installed on my Flame with Firefox OS 3.0 (not the latest one) and the screen is blank.

**Comment by TitanNano** [comment]
well you have to build the package, did you do that?

2015-05-13 17:54 GMT+02:00 Michael Moroni <notifications@github.com>:

**Comment by Airon90** [comment]
Stupid boy!
However I compiled as decribed in README but nothing changed :/

**Comment by DerManoMann** [comment]
Any news on this? Is there anything to help get a new version pushed?

**Comment by Airon90** [comment]
Please contact @zhukov :)

**Comment by TitanNano** [comment]
well this is his repo ^^

**Comment by Airon90** [comment]
I know that this is his repo but if you had seen his profile you'd have noticed that he wasn't working on webogram since days ;)
I tried to compile latest version for Firefox OS but I got stuck: see #842

**Comment by TitanNano** [comment]
@zhukov can you push a new version to the marketplace??

**Comment by zhukov** [comment]
@TitanNano sure, but last thing before it is to try to merge your PR: https://github.com/zhukov/webogram/pull/840

**Comment by TitanNano** [comment]
@zhukov yes sure :+1:

**Comment by Airon90** [comment]
I built latest version under Linux and still a blank screen is shown when the app is loaded.

Does someone confirm that I just have to give those two commands on terminal in the main folder, as written [here](https://github.com/zhukov/webogram#technical-details)?

**Comment by TitanNano** [comment]
do a 'make package' and then install the dist dir

2015-07-10 23:05 GMT+02:00 Michael Moroni <notifications@github.com>:

**Comment by Airon90** [comment]
Thank you very much!

**Comment by zhukov** [comment]
Done
