### ISSUE TITLE
A way to escape login on DEV localhost environment

### ISSUE THREAD

**Issue by sahanDissanayake** [zhukov/webogram#801]
Hi @zhukov 

Just seen this and very impressive :+1: 

Can you advice on on how to escape or go through the authentication state without having to enter phone number and all please ?

If I can remove some code to achieve that

Im in to Angular js,

Thanks so much

**Comment by zhukov** [comment]
Hi
I don't understand the problem. What account do you want to log in?

**Comment by sahanDissanayake** [comment]
i do not have an account, I tried to login using my mobile number, nothing happens at all,, im still waiting for a code :cry: 

So i tried to run a the code locally, but I do not know how to remove the login completely,, and just browse around,, any tips ??

**Comment by zhukov** [comment]
what is your browser, OS? did you check javascript console for errors?

**Comment by sahanDissanayake** [comment]
get this error on web.telegraph

```javascript
[811.308] Error 303 NETWORK_MIGRATE_3 false 2
```
Chrome browser / Mac
5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.152 Safari/537.36

**Comment by zhukov** [comment]
This is not actual error, just redirect to another address. Any other messages after this one? Can you check "Network" panel for red (error) requests?

**Comment by sahanDissanayake** [comment]
Nope, Network requests get a 200 Ok response back

![screen shot 2015-05-20 at 11 45 21 pm 1](https://cloud.githubusercontent.com/assets/5580680/7724961/544d36b6-ff4a-11e4-8de2-24b1efb91e43.png)

**Comment by sahanDissanayake** [comment]
Hope this might help you a little bit, this is in localhost, so you see the file names

![screen shot 2015-05-20 at 11 46 41 pm](https://cloud.githubusercontent.com/assets/5580680/7724987/8b078b48-ff4a-11e4-8cf7-ff0d3d9a29ff.png)

**Comment by zhukov** [comment]
hmm.. this log says Telegram have sent a code to your phone number. Did the UI change? Do you see the form with code input ?

**Comment by sahanDissanayake** [comment]
Ui change to this
![screen shot 2015-05-20 at 11 49 08 pm](https://cloud.githubusercontent.com/assets/5580680/7725013/d39d5d4c-ff4a-11e4-9725-c6883b6aef4c.png)

**Comment by zhukov** [comment]
so why did you say this? 

> , nothing happens at all,

If the only problem is that you don't actually receive the code?

Is this your actual number? Can you receive other SMS / calls with it?

**Comment by sahanDissanayake** [comment]
OK UPDATED,, yes waiting for the code

**Comment by sahanDissanayake** [comment]
just got it by the way,, JUST DID

**Comment by zhukov** [comment]
:+1:
