### ISSUE TITLE
Search for ".." results in an error

### ISSUE THREAD

**Issue by stefan-niedermann** [zhukov/webogram#802]
i will add a screenshot if necessairy - just use the left top search to look for ".." - dot dot. there will be an error-pop-up.

**Comment by zhukov** [comment]
What version are you using? I can't reproduce this.

**Comment by stefan-niedermann** [comment]
Currently don't have access to webogram (am @ work). i think its the latest version of firefox marketplace.

**Comment by zhukov** [comment]
This was fixed with #794.
