### ISSUE TITLE
"3: Incorrect/incomplete header." pop-up on firefox

### ISSUE THREAD

**Issue by fhoshino** [zhukov/webogram#805]
Got a pop-up on firefox written "3: Incorrect/incomplete header."
Not sure where it came from.

**Comment by davidhdz** [comment]
Confirm, error appeared after add third party stickers.

**Comment by zhukov** [comment]
Probably the same as #806.
Please let me know if not fixed with the upcoming update.

**Comment by mbasaglia** [comment]
I'm on Firefox 48 and often get that same message when browsing stickers.
