### ISSUE TITLE
Custom stickers broken in Firefox

### ISSUE THREAD

**Issue by Streetwalrus** [zhukov/webogram#806]
I made a custom sticker pack (https://telegram.me/addstickers/Walrii) with a single sticker, but the image doesn't load properly in Firefox. The sample animals pack works perfectly fine however. I tried both Firefox 38.0 and nightly 41.0 on Linux 64 bit, both have the same problem, but Chromium doesn't. Moving the profile and deleting cache doesn't help. The "image" displayed instead is https://zhukov.github.io/webogram/false which is a 404.

Here's a screenshot :
![img](http://a.pomf.se/oqzmco.png)

**Comment by zhukov** [comment]
Did you try opening the same sticker in stable version? I mean https://web.telegram.org

May be I have broken something in the latest update.

**Comment by Streetwalrus** [comment]
Yeah, I did. In that version Firefox only shows a blank, no broken image.

**Comment by Streetwalrus** [comment]
Hmmm looks like it's just one sticker pack that has the issue. https://telegram.me/addstickers/dagaem doesn't have that problem. I'll try it on windows.

**Comment by LelixSuper** [comment]
Also I have the same problem with some custom stickers! I use the same browser and operating system.
![kazam_screenshot_00000](https://cloud.githubusercontent.com/assets/8456809/8023852/07ae61fe-0d1e-11e5-9637-aa2ab1930f57.png)

**Comment by zhukov** [comment]
This was fixed here

https://github.com/zhukov/webogram/commit/4b0bd16aab2a1dd8d107fc995f95909c086f6298

**Comment by zhukov** [comment]
Will be in master soon.
