### ISSUE TITLE
Link previews drop modifed Latin characters from titles

### ISSUE THREAD

**Issue by anewuser** [zhukov/webogram#807]
I've sent this link to someone: http://www.skyscrapercity.com/showthread.php?t=1759139

The title preview on Telegram should read "São Paulo, ângulos contemporâneos - SkyscraperCity", but it says "So Paulo, ngulos contemporneos - SkyscraperCity".

![Screenshot](https://infotomb.com/p3wrm.png)

I'm running https://web.telegram.org/ on Firefox Beta 38.0.5 for Windows.

**Comment by zhukov** [comment]
This was fixed from server side. Thanks!
