### ISSUE TITLE
Stickers tab

### ISSUE THREAD

**Issue by danielquijada** [zhukov/webogram#808]
I can't put labels here, this is just a suggestion. Plus, sorry for my poor english, haven't spoken in a while and not my first language.

With the amount of stickers we have, more and more "officials" plus the ones people make themselves, maybe we could have stickers "tabs", so we can see different types.. the animals, the officials, the customs..

Or, at least, a tab with the most recently used, like we have with the emojis.

I really haven't seen your implementation, and I don't know if this would be hard to implement, just commenting this 100% as a user.

PS: I love your Telegram <3 I think most people do xD keep the good work going!

**Comment by BadBone2k** [comment]
I think, this wopuld be a great addition, also see https://github.com/zhukov/webogram/issues/864 for a similar suggestion.

**Comment by zhukov** [comment]
Fixed in 0.4.9. Will be published soon, currently in beta: https://zhukov.github.io/webogram
