### ISSUE TITLE
NoScript and Telegram Web.

### ISSUE THREAD

**Issue by dv2y** [zhukov/webogram#809]
Hello guys,

I'm using this extension: https://addons.mozilla.org/en-US/firefox/addon/telegram-desktop/ on Firefox 38.0.5.

Some days ago pages just stopped loading. Trying to find the cause of the issue I've disabled the extension, restarted the browser and voila, pages just started working again.

So I tried to use Telegram in both "web.telegram.org" and "zhukov.github.io/webogram" directly and the same thing happens: After I load the tab with Telegram, nothing more loads, Fiferox can't even connect to its update server.

So started disabling my extensions one by one to see if it is some there's some issue in between one of them and noticed that with NoScript disabled everything works again. I have "telegram.org", "github.io" and "zhukov.github.io" all whitelisted on NoScript.

Extensions I'm using: http://i.imgur.com/tuBLI82.png.

Someone can replicate the issue?

**Comment by nylocx** [comment]
Jep, I have the same issue 100% CPU load on one core and not being able to login to web.telegram.org while noscript is enabled (telegram.org and telegram.me are whitlisted). Also Firefox can not connect to the Internet any more. I don't have the telegram plugin installed. I tested it with a clean firefox user plugin with just noscript installed and the problem persists.
I'm using Firefox 38.0.1 on Arch Linux.

**Comment by murth** [comment]
I can also confirm this. I troubleshooted for a long time between my machines before I finally found it was loading web.telegram.com that cuases this!
My firefox sits on about 25-30% CPU constantly, and stops processing data in any meaningful way.

**Comment by zhukov** [comment]
I can't reproduce this on my Firefox 38.0.5 OS X. Can you try again and see if this is still actual?
@dv2y @nylocx @murth

**Comment by dv2y** [comment]
Looks like it's working now.

I was away and have not noticed an update on the extension itself, maybe it was a Firefox bug?

**Comment by zhukov** [comment]
May be. Feel free to open if this reproduces again.
