### ISSUE TITLE
ability to schedule a message

### ISSUE THREAD

**Issue by zaxebo1** [zhukov/webogram#810]
in gliph messenger, we can schedule a message to be send at a particular time in future.
Please implement it in telegram's webogram too.
This scheduling feature is very useful for scheduling a message to be sent on somebody's birthday etc

**Comment by ArtemFitiskin** [comment]
@zaxebo1 as I know is not possible in webogram (that's client only) while that feature not present in Telegram API.

**Comment by bb010g** [comment]
I'd message Telegram Support and recommend it there.

**Comment by zaxebo1** [comment]
@bb010g 
thanks for your support for idea. 
Just request that "in the API", the scheduled message should be supported for secret chat also. (this is really important)

**Comment by zhukov** [comment]
This is not a client-side feature. You should request it in Telegram Support.

**Comment by bb010g** [comment]
[**@zaxebo1**](https://github.com/zaxebo1) commented on [May 24, 2015, 9:37 PM PDT](https://github.com/zhukov/webogram/issues/810#issuecomment-105122426 "2015-05-25T04:37:58Z - Replied by Github Comment Enhancer"):
> Just request that "in the **API**  ", the **scheduled message should be supported for secret chat** also. (this is really important)

...it sounds like you want me to request it? You can request it yourself perfectly fine.
