### ISSUE TITLE
Webp stickers makes firefox hangs

### ISSUE THREAD

**Issue by fhoshino** [zhukov/webogram#812]
The libwebpjs script causes firefox to freeze once a while.
If there is no other libary for webp, suggesting an option to disable webp stickers.

**Comment by fhoshino** [comment]
I'm still getting this alert once a while.

"A script on this page may be busy, or it may have stopped responding. You can stop the script now, open the script in the debugger, or let the script continue.

Script: http://127.0.0.1:8000/vendor/libwebpjs/libwebp-0.2.0.min.js:79"

**Comment by zhukov** [comment]
You have previous version of library working. Did you switch to 'bots' branch?

**Comment by fhoshino** [comment]
No, I'm on master branch,
killed the folder and clone again,
did the glup thing, and when loading stickers,
got this
"A script on this page may be busy, or it may have stopped responding. You can stop the script now, open the script in the debugger, or let the script continue.

Script: http://127.0.0.1:8000/vendor/libwebpjs/libwebp-0.2.0.min.js:29"

**Comment by zhukov** [comment]
@fhoshino So I didn't push it to master yet. If you want to test it, you should use another branch.

**Comment by fhoshino** [comment]
Confirming bots branch workarround fix this hang.
