### ISSUE TITLE
Possibility to filter hyperlinks

### ISSUE THREAD

**Issue by revolter** [zhukov/webogram#813]
It would be a great addition the option to filter url addresses sent in a chat, besides the existing media filters.

**Comment by thob** [comment]
:+1: url filtering should be in all versions

**Comment by zhukov** [comment]
This is a server-side feature. We need the API support, sorry.

**Comment by revolter** [comment]
@zhukov, is the server side open source?

**Comment by zhukov** [comment]
@revolter Nope :(
https://telegram.org/faq#q-why-not-open-source-everything

**Comment by revolter** [comment]
@zhukov, But still it can be done. I almost made it work, I'll send you a PR when I have some time.

**Comment by mousavian** [comment]
I've [added this filter](https://github.com/mousavian/webogram/commit/8ae921b9f39e56a22b98582104a4ed0d863bbbe4) since the server-side APIs now support filtering URLs.
Please confirm so I can do a pull request.
