### ISSUE TITLE
Remote calls like in telegram-cli

### ISSUE THREAD

**Issue by lepetal** [zhukov/webogram#815]
Is it possible to allow webogram accept requests from other applications on the same machine over HTTP or file socket?

I mean the ability to build wrappers for additional functionality like here:
https://github.com/zyberspace/php-telegram-cli-client

and use webogram as a daemon responding to requests:
/tg/bin/telegram-cli -k package.key -dWS /tmp/tg.sck & 

Thank you!

**Comment by zhukov** [comment]
I guess, there is no need for this, since Bots API release: https://telegram.org/blog/bot-revolution

**Comment by bb010g** [comment]
I could see there still being a need, e.g. scheduling messages from a personal account.
