### ISSUE TITLE
Only secure origins are allowed.

### ISSUE THREAD

**Issue by mikasoukhov** [zhukov/webogram#817]
DOMException: Only secure origins are allowed.

In Console Chrome

**Comment by mattrick16** [comment]
Is it causing you problems...?

**Comment by mikasoukhov** [comment]
Not sure, but many features do not works (cannot see images and video). Maybe I did wrong installation (with prev year version actually was ok). Is the any instruction here?

**Comment by zhukov** [comment]
To use HTML5 Crypto API and NaCl you have to launch Telegram via HTTPS or via localhost.
