### ISSUE TITLE
[Feature Request] Edit last message by pressing "Up" in empty message box

### ISSUE THREAD

**Issue by pavelhritonenko** [zhukov/webogram#818]
I want ability to fast fix typo error in last message by pressing "Up" arrow for edit last message.

**Comment by edencore** [comment]
As far as I know, Telegram's API don't have a method for fixing typos. The only way to implement this on client is to send a message second time with fixed errors.

**Comment by Airon90** [comment]
for such feature request you should write to Telegram developers, not Telegram Web ones

**Comment by hebrew878** [comment]
i think as of now, edit message feature is not implemented yet in telegram .?

**Comment by zhukov** [comment]
Sorry, this feature requires server side support.
