### ISSUE TITLE
How to get PeerID from phone

### ISSUE THREAD

**Issue by itorian** [zhukov/webogram#819]
Thanks for the awesome work zhukov.
Please let me know how to get PeerID from phone number (off-course which is registered on Telegram). In the code below, I noticed when I put break-point on 'foundUserID' this holds PeerID. Is there any better way to get PeerID from phone.

    function addPhoneNumber(phone, first_name, last_name) {
        AppUsersManager.importContact(phone, first_name || '', last_name || '').then(function (foundUserID) {
            if (!foundUserID) {
                console.log('User not using telegram, so PeerID not found.');
            }
            else {
                console.log('User using telegram with PeerID : ' + foundUserID);
            }
        });
    }

**Comment by zhukov** [comment]
I guess this is correct way.

However I would suggest using new Bot Platform API for those purposes: https://telegram.org/blog/bot-revolution

It doesn't allow sending message to user first (only as a reply), but this way you will not be banned for spam messages :smile:
