### ISSUE TITLE
Adding custom stickers from Telegram Web

### ISSUE THREAD

**Issue by Zelgadis87** [zhukov/webogram#820]
Hello,

currently stickers are added via the tg:// protocol from the official site. Clicking the Add Stickers button on the browser, which is just a link to tg://addstickers?set=Animals, however does not have any effect right now, since the tg protocol is not handled by any application. The only thing you can do right now is use the Android/iOs version to add the sticker set and wait for the synchronization, which is mostly inconvenient. 

I have no idea if a web application can be registered to handle a certain protocol, which would obviously be the preferred solution, but we really need a better solution right now. Even a modal window asking for the set name to add would be a great improvement over the current solution.

Thoughts?

**Comment by edencore** [comment]
Right now you can send a link to the set to yourself (or somebody else, of course) and click on it. It will open a window where you will be able to install a selected pack.

**Comment by Zelgadis87** [comment]
That's really nice to know, thanks! Still incovenient, but waaay better than my previous "solution"!
