### ISSUE TITLE
No desktop notifications

### ISSUE THREAD

**Issue by guillermogf** [zhukov/webogram#821]
I've had desktop notifications until a couple of weeks ago. I don't know why they are no longer working.

I've just installed Chromium and there they are working propperly, but on Firefox I can't get them to work. Neither the visual nor the sound notification.

I've also tried clearing the cache.

Debian Testing. Linux 3.16 64 bits. Iceweasel (Firefox) 38

**Comment by marfous** [comment]
That's very painful issue. I can confirm that notification don't work in FF at all. Please could you take a look on this JSFiddle? It looks that the universal shouldn't be difficult to implement:
http://jsfiddle.net/robnyman/TuJHx/

Thanks in advance for fixing this - it's pretty unpleasant issue.

**Comment by zhukov** [comment]
Is this still actual? I have Firefox 38.0.5 on OS X and can't reproduce this.

What is the OS, Fx version? Can you check Javascript console for errors?

**Comment by marfous** [comment]
Yes, it is. I'm still able to reproduce it. I have that confirmed also from my friend using similar OS and FF.
Browser: 38.0
OS: Ubuntu Mate 15.04 (friend's OS is Kubuntu 14.10)

Console output:
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://vesta.web.telegram.org/apiw1. (Reason: CORS request failed). <unknown>
TypeError: asm.js type error: duplicate name 'n' not allowed app.js:12:19024
"[0.382]" "Api call" "updates.getState" app.js:16:10252
"[0.555]" "Api call" "messages.getDialogs" app.js:16:10252
Use of Mutation Events is deprecated. Use MutationObserver instead. app.js:3:0
<source> element has no "src" attribute. Media resource load failed. web.telegram.org
All candidate resources failed to load. Media load paused. web.telegram.org
<source> element has no "src" attribute. Media resource load failed. web.telegram.org
All candidate resources failed to load. Media load paused. web.telegram.org
: Successfully compiled asm.js code (total compilation time 1ms; not stored in cache (too small to benefit)) rusha.js
"[1.232]" "Rpc response" "updates.state" app.js:16:23318
"[1.233]" "Rpc response" "messages.dialogs"

**Comment by zhukov** [comment]
Please clear the console, then reproduce the problem and copy console output after it. The one you provided is just from app boot, I guess.

**Comment by marfous** [comment]
Ok, done but in the log isn't anything suspicious:
"[39.898]" "Api call" "account.updateStatus" app.js:16:10252
"[40.051]" "Rpc response" true app.js:16:23318

BTW. as I mentioned earlier if I go to the attached jsfiddle sample, notifications work well to me there.

**Comment by zhukov** [comment]
Of course we have already this code from jsfiddle implemented for Webogram.

Can you please launch the following line in your javascript console:
```
Notification.permission
```

It will result in something like:

![screen shot 2015-07-01 at 12 11 03 pm](https://cloud.githubusercontent.com/assets/775173/8451218/47ab8456-1fea-11e5-9928-ceb331ccbce1.png)

**Comment by zhukov** [comment]
You can also click on the site icon in address bar, in the "Permissions" tab you'll see Notifications permission.

**Comment by marfous** [comment]
Hmmm, that looks ok:
Notification.permission
"granted"

**Comment by guillermogf** [comment]
Same for me
Notification.permission
"granted"

And when I receive a message nothing related to notifications appears in the console.

**Comment by zhukov** [comment]
Hello again. Sorry for the long delay. I still can't reproduce this on my OS X / Win Firefox'es.
Can you open javascript console in the tab with problem and launch following:

```javascript
window.Notification = function (title, options) { console.log('notification', title, options); }
window.Notification.permission = 'granted'
```

Then switch to another tab, receive a message and check if something new appeared in console.

**Comment by guillermogf** [comment]
I no longer have this problem, I can see desktop notifications normally, but I don't know why the issue stopped.

**Comment by zhukov** [comment]
@marfous what about you?

**Comment by marfous** [comment]
I'm sorry, I'm on the long-term vacation. I'll try that and let you know in
about 3 weeks. Thanks for your understanding.

On Fri, Jun 10, 2016 at 7:46 PM, Igor Zhukov <notifications@github.com>
wrote:

> @marfous <https://github.com/marfous> what about you?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/zhukov/webogram/issues/821#issuecomment-225249004>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABXAaHG2AYisW0-GNmSn_booUzx56O88ks5qKaL6gaJpZM4E6g0v>
> .
>



--
