### ISSUE TITLE
Heavy script, very slow to load.

### ISSUE THREAD

**Issue by friend4chams** [zhukov/webogram#824]
Hi,

I can see this script is heavy take time to load, 

Please improve it and make it faster, 

and also make it more mobile friendly and wap friendly for those whose mobile does not support the telegram apps,

**Comment by fhoshino** [comment]
It is a problem with #812

**Comment by friend4chams** [comment]
No i am not talking about hang, it does not get hang, it load properly but takes very much time. even the official telegram web app takes time to load. it is a mobile web it must load faster.

**Comment by zhukov** [comment]
Duplicate #812
