### ISSUE TITLE
Telegram and iFrame

### ISSUE THREAD

**Issue by minhld** [zhukov/webogram#825]
Hi,
I would like to add Telegram as a chat panel inside my web application using iFrame. But whenever the iFrame is loaded, the Telegram automatically opens itself in the parent browser not inside the iFrame. 
I'm not very familiar with the source and I couldn't find the code where triggers this action, could you please help?

**Comment by minhld** [comment]
I found a line in the init.js file 
top.location = self.location
This causes the problem I met. However either I tried to disable this line or reloaded the Telegram, the iFrame always returns a blank page, though all the script and css files have been loaded

**Comment by ArtemFitiskin** [comment]
It's click-jacking protection. 

If you need to remove that simply replace (https://github.com/zhukov/webogram/blob/master/app/js/init.js#L6):

```javascript
 // Prevent click-jacking
  try {
    if (window == window.top || window.chrome && chrome.app && chrome.app.window) {
      document.documentElement.style.display = 'block';
    } else {
      top.location = self.location;
    }
  } catch (e) {console.error('CJ protection', e)};
```

to:
```javascript
document.documentElement.style.display = 'block';
```

But this is bad practice. Maybe, [X-Frame-Options](https://developer.mozilla.org/en-US/docs/Web/HTTP/X-Frame-Options) header helps you to do it right if your app is self-hosted.

**Comment by minhld** [comment]
@ArtemFitiskin Thank you so much. That is really what I need.

**Comment by SymbianSyMoh** [comment]
Hi, I agree with @ArtemFitiskin, JS busting techniques could be bypassed

Check this out: https://www.seekurity.com/blog/general/telegram-web-client-clickjacking-vulnerability/
