### ISSUE TITLE
Microsoft Edge detected as Chrome

### ISSUE THREAD

**Issue by jdalton** [zhukov/webogram#826]
I noticed web.telegram detects MS Edge as Chrome under its settings > active session panel.
I'm not totally sure but does [scripts/ua_handler.js](https://github.com/zhukov/webogram/blob/976b83708befdf11d31c5911bbb142d3d11e6a0c/scripts/ua_handler.js) handle that detection?

Info on the MS Edge UA for mobile and desktop can be found [here](https://msdn.microsoft.com/en-us/library/hh869301%28v=vs.85%29.aspx?f=255&MSPPError=-2147217396).

The bit detected is usually "Edge/".

**Comment by jdalton** [comment]
Ping @zhukov.

**Comment by zhukov** [comment]
This was fixed from server side, thanks. You can try in couple of hours.
