### ISSUE TITLE
Turn off autocorrection for French-speaking person

### ISSUE THREAD

**Issue by pmrotule** [zhukov/webogram#830]
The new autocorrection feature is so anoying for those who can't find their language in the settings (like me, a French-speaking person). In any case, there is a lot of people who don't like autocorrection even if it's the right language. Please, provide a way to turn it off...

Thank you.

**Comment by TitanNano** [comment]
I don't know of any auto correction feature in Telegram. Are you sure this isn't your system?

**Comment by pmrotule** [comment]
Oh man! I feel so dumb! That was my system! Thank you so much!
