### ISSUE TITLE
Preview images before pasting them

### ISSUE THREAD

**Issue by edencore** [zhukov/webogram#835]
When you paste images into Webogram it asks "Are you sure to send file from clipboard?". It would be wonderful if this window will have a preview of pasted images. If you're using slack, you know what I mean.

**Comment by mautematico** [comment]
It would be a nice feature, and it sounds not *that hard* to implement. :+1: 

> If you're using slack, you know what I mean.
I'm not using slack. What you mean? :)

**Comment by edencore** [comment]
@mautematico 
When you inserting image into slack, you see this popup with image's preview and ability to cancel upload: 
![image](https://cloud.githubusercontent.com/assets/2963477/9146539/3be095f0-3d66-11e5-8f52-2709cc1274a1.png)
Also, I had noticed that Desktop Telegram has this feature

**Comment by mautematico** [comment]
Can you please share a URL, @edencore ?

**Comment by edencore** [comment]
Excuse me ? A URL for what ? If you mean slack, you need to join some team to use it. For example, you can join a frontenddevelopers.org which is free. I hope I've answered your question

**Comment by mautematico** [comment]
I had no idea what slack is. But now I understand. I'm not an expert, but I'll see if I can do something about this. :)

**Comment by edencore** [comment]
Oh, you difinitely should give it a try, it is awesome :+1: 
You also can take a desktop telegram as a reference:
![image](https://cloud.githubusercontent.com/assets/2963477/9146825/c82744f8-3d68-11e5-8501-c3f423ea4cfe.png)

Thank you in advance !

**Comment by mautematico** [comment]
So far, this is what I've got.

![screenshot-2](https://cloud.githubusercontent.com/assets/1238928/9148051/deee5942-3d36-11e5-9b05-97ebc9e7eced.png)


Give me some minutes to push to my fork, and then give me more time to get that image being a *preveiew* (or at least a scaled image) instead of the actual full-size image.
![captura el 2015-08-07 a las 19 04 10](https://cloud.githubusercontent.com/assets/1238928/9148062/1ee1b80a-3d37-11e5-8f07-8fa6aba55353.png)

**Comment by mautematico** [comment]
Ups. Sorry for that commit-spam.

**Comment by mautematico** [comment]
![captura el 2015-08-07 a las 19 19 06](https://cloud.githubusercontent.com/assets/1238928/9148172/3f6f931a-3d39-11e5-9b88-b01b0bdb366f.png)

**Comment by edencore** [comment]
Looks awesome !

2015-08-08 3:19 GMT+03:00 Mauricio Navarro Miranda <notifications@github.com

**Comment by Ryuno-Ki** [comment]
@mautematico Well, bootstrap has an ` .img-responsive` [css class](http://getbootstrap.com/css/#images) for that ;-)
