### ISSUE TITLE
Unresponsive script

### ISSUE THREAD

**Issue by FlyingPumba** [zhukov/webogram#836]
Hi!
After some using of the Telegram web app I get a warning in Mozilla:
```
A script on this page may be busy, or it may have stopped responding. You can stop the script now, open the script in the debugger, or let the script continue.

Script: https://web.telegram.org/js/app.js:8
```
My OS is: Ubuntu 14.04
Mozilla Firefox version is: 38.0
Web Telegram version is: 0.4.6

**Comment by hebrew878** [comment]
Got same error so many times.

**Comment by FlyingPumba** [comment]
It's driving me crazy, each time it pops up I choose ```stop script``` but it keeps showing up.

**Comment by zhukov** [comment]
Duplicate #812
