### ISSUE TITLE
Webogram can't find bot via URL with query string parameters

### ISSUE THREAD

**Issue by amurchick** [zhukov/webogram#843]
Browser: Chrome Version 43.0.2357.130 (64-bit)
OS: Mac OS X 10.10.4

When I am open link like `http://telegram.me/iVedroBot?start=1234567890abcdef1234567890abcdef` in Chrome - Webogram opens an tell me `User not found`, technical details:
```
Method: contacts.resolveUsername
Result: {"_":"rpc_error","error_code":400,"error_message":"USERNAME_NOT_OCCUPIED"}
```

If I am open link like `http://telegram.me/iVedroBot` - Webogram opens chat with @iVedroBot

**Comment by zhukov** [comment]
Yep, it's the same as #839.
Will release the update soon.
