### ISSUE TITLE
UI problem with file location dialog popping up at the end of the file transfer

### ISSUE THREAD

**Issue by akaleeroy** [zhukov/webogram#844]
Google Chrome, set to ***Ask where to save*** each file. I click ***Download***, the file transfer starts, and I get back to typing or switch to another tab. 

Because the ***Save to... dialog*** only appears at the end of the transfer, and I don't know when that is, the dialog pops up unexpectedly, grabs focus and I find myself accidentally typing in the file name field, overwriting it.

Maybe ask where to save at the beginning, when I'm actually involved with that task?

**Comment by zhukov** [comment]
It's impossible in usual web mode, sorry.
We do that in standalone app, where access to local file system is allowed.
