### ISSUE TITLE
Telegram as Chrome web-shortcut doesn't load images

### ISSUE THREAD

**Issue by edgard** [zhukov/webogram#845]
If you create a web-shortcut from Chrome, none of the user-sent images are loaded, others are fine.

**Comment by zhukov** [comment]
What is your OS? How do you create the shortcut?

**Comment by edgard** [comment]
Hi Igor, I'm on Linux (Fedora 22). Creating through the regular Menu->More Tools->Create application shortcut.

Interesting enough I just noticed that if I reload the page (F5) within the "application", the images starts to appear normally.

**Comment by zhukov** [comment]
Do you see any errors when image load fails? Please check javascript error console.
