### ISSUE TITLE
Does not work when I try to open in browser extension

### ISSUE THREAD

**Issue by cawa-93** [zhukov/webogram#846]
Tried to open the page https://web.telegram.org in the sidebar of the Opera as a browser extension:
<iframe src="https://web.telegram.org/#/login" frameborder="0"></iframe>
But, nothing is displayed. In console we can see the JavaScript errors:
![2015-07-10 14 28 10](https://cloud.githubusercontent.com/assets/1662812/8617772/ecf3b47a-270f-11e5-9b53-d8e8f7e8bc20.png)

Source code: https://github.com/cawa-93/sidebar-telegram

What am I doing wrong?

**Comment by zhukov** [comment]
This is due to click jacking protection:
https://github.com/zhukov/webogram/blob/master/app/js/init.js#L3

Webogram doesn't support working inside an iframe. If you want to make it work, you should fork the code and remove protection. But I will not merge this to master due to security reasons.
