### ISSUE TITLE
Emoji box is broken on mobile

### ISSUE THREAD

**Issue by TitanNano** [zhukov/webogram#847]
Hello,

just wanted to report that the emoji box is broken on mobile with latest master.

![2015-07-10-21-19-02](https://cloud.githubusercontent.com/assets/4500858/8627221/ca31d4f0-2749-11e5-8a30-a08e078e5d56.png)

Basically the box doesn't have a fixed height anymore.

**Comment by zhukov** [comment]
Can't reproduce this one. What is the browser, OS?

**Comment by TitanNano** [comment]
yes it's already fixed!
