### ISSUE TITLE
I can't connect to 149.154.171.5

### ISSUE THREAD

**Issue by Irsut** [zhukov/webogram#848]
I run a gulp watch on localhost. web.telegram.org works though.

**Comment by Irsut** [comment]
The web.telegram.org doesn't work now. Neither the clients.

**Comment by fhoshino** [comment]
Suggest to add more dc nodes to the host list in mtproto.js for connection trying in case of such DDoS situation.

**Comment by zhukov** [comment]
Please read blog article https://telegram.org/blog/ddos

Telegram was under DDOS.
