### ISSUE TITLE
RTL text overlaps the grey smiley when writing message

### ISSUE THREAD

**Issue by timor-raiman** [zhukov/webogram#851]
![webogram-bug](https://cloud.githubusercontent.com/assets/3657337/8696093/3a3f94fc-2af2-11e5-86d3-1f828331317e.png)

**Comment by mohebifar** [comment]
:+1:

![webogram-rtl-problem](https://cloud.githubusercontent.com/assets/6104558/8783267/fdfdd4a8-2f2f-11e5-8b39-fbae2e44985b.png)

**Comment by mankurt** [comment]
![screenshot from 2016-10-29 23-09-23](https://cloud.githubusercontent.com/assets/15964583/19832472/e928070c-9e2c-11e6-88c6-825e5d4fdd1f.png)
