### ISSUE TITLE
Can't scroll chat window with keyboard

### ISSUE THREAD

**Issue by alex-mayorga** [zhukov/webogram#853]
Steps:
- Load a conversation that's longer that the current window at https://web.telegram.org/#/im
- Press Up arrow key or Pg Up on the keyboard

Result:
The conversation does NOT scroll up

Expected result:
The conversation scrolls up

Environment:
Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:42.0) Gecko/20100101 Firefox/42.0 ID:20150715095506 CSet: 16e30af059b7

**Comment by hossainalikram** [comment]
Followed the same steps on Google chrome (Version 43.0.2357.134 m) and have the same result like Alex! I think, it was from the past! If it is, maybe We can request to work on it to Webogram team!

Regards!

**Comment by mautematico** [comment]
At ver. 0.4.7, I **can** scroll with keyboard, if, first, i clic/tap/touch the conversation area.
>Firefox Aurora: 41.0a2 (2015-08-06)
