### ISSUE TITLE
Chrome(Chromium) Zoom-Level and Font-Size settings ignored --> Everything too small :(

### ISSUE THREAD

**Issue by Tormen** [zhukov/webogram#855]
Hi,

The app does not use the chromium settings for font-size and zoom.

Nor does there seem to be a way to influence the font-size / zoom-level within th e chromium Telegram app.

Do you see a chance you could fix this ?

Tormen

**Comment by zhukov** [comment]
Duplicate #274.


As a temp solution, you can use browser page version with zoom enabled.
