### ISSUE TITLE
Whole messages shouldn't be clickable

### ISSUE THREAD

**Issue by martinml** [zhukov/webogram#858]
Recently the Chrome extension was updated to 0.4.7 and a new behavior appeared: the messages in the chat, in their whole, are clickable and enter a special selecting mode.

My suggestion is that this behaviour should only happen when clicking in the ticks, and not in the whole message. Otherwise, it's a bit annoying: when the window is in the background, you have to be very careful when clicking it in order to bring it to the front. If you click in a -seemingly!- empty space, you end accidentally selecting messages and can't type until you deselect them.

**Comment by auchri** [comment]
Or just select the message when the windows is already in the front

**Comment by zhukov** [comment]
Can't reproduce this on Mac: the first click just always makes window focused. But I tried to fix this. Can you check if that helped? @martinml

**Comment by martinml** [comment]
If I did the build correctly, it's still happening for me, using 90df02e10bca7d594c3ee20987cd54ca08611f58.

Here is a GIF, using Windows 8.1 and Chrome 44.

![Testing #858](https://cloud.githubusercontent.com/assets/217925/8903353/af815818-3457-11e5-93ba-b4a30d7b9d11.gif)
