### ISSUE TITLE
Error while publishing (to gh-pages)

### ISSUE THREAD

**Issue by vedant1811** [zhukov/webogram#860]
I am successfully running this app locally using `gulp watch`.

Now want to publish it to my gh-pages, like `https://zhukov.github.io/webogram`.

It is unclear on how should I do that (there is no mention of it in the README). I tried doing `make publish` but I am getting an error:

    [01:25:27] Finished 'add-appcache-manifest' after 85 ms
    echo -n "Please open http://localhost:8000/dist/index.html and check if everything works fine." && read -e
    Please open http://localhost:8000/dist/index.html and check if everything works fine./bin/sh: 1: read: Illegal option -e
    Makefile:10: recipe for target 'publish' failed
    make: *** [publish] Error 2

Am I doing stuff incorrectly or is there something else that is wrong?

**Comment by zhukov** [comment]
What is your OS?
I'm using OS X and this Makefile is for my configuration. Your system seems to have '-e' option for 'read' command.

You can try to comment this line in Makefile and launch again.
https://github.com/zhukov/webogram/blob/master/Makefile#L13
