### ISSUE TITLE
Better stickers menu?

### ISSUE THREAD

**Issue by ALCC01** [zhukov/webogram#864]
I don't like the current format of the stickers menu. When you have many packs, each of them formed by many stickers, you've to scroll a lot to find out the sticker you're looking for.

Could I suggest a menu that shows the packs only, and then once you've selected one, you're shown an interface with the pack's stickers?

**Comment by arieljannai** [comment]
+1 for that.
in #808 there's also a suggestion for a new menu

**Comment by zhukov** [comment]
Fixed in 0.4.9. Will be published soon, currently in beta: https://zhukov.github.io/webogram
