### ISSUE TITLE
Telegram is eating Battery :(

### ISSUE THREAD

**Issue by SunboX** [zhukov/webogram#868]
The Telegram App is eating up my Battery on Firefox OS 2.5. You can find a `adb logcat` and a `adb shell top -m 5` file attached. There are two versions of both files, one **with** and one **without** Telegram installed. In both cases, the Device is locked and the Screen is disabled.

In normal case, the Battery lasts a day. With Telegram running, it lasts only 3 hours with locked Screen. And the Device is getting hot without using it.

The Device is a Nexus 4 running this ROM: https://yalam.co.uk/b2g/mako/fxos-mako-15-07-29-spark.zip

## Log Files

https://gist.github.com/SunboX/8e5e1ee1fccc903e87f9

## Device Information:

**OS Version** 2.5.0.0-prerelease
**Hardware Manufacturer** LGE
**Hardware Platform** mako
**Hardware Revision** mako
**Build Number** eng.yousef.20141013.160703
**Platform Version** 42.0a1
**Build Identifier** 20150724204804
**Update Channel** default
**Git Commit Info** 2015-07-24 17:19:26 / c0c218fe

**Comment by SunboX** [comment]
# Some typical values from the Log Files

## Telegram installed
```txt
User 24%, System 9%, IOW 0%, IRQ 0%
User 48 + Nice 11 + Sys 22 + Idle 162 + IOW 0 + IRQ 0 + SIRQ 0 = 243

  PID PR CPU% S  #THR     VSS     RSS PCY UID      Name
  179  0  45% S    86 670276K 289896K     root     /system/b2g/b2g
 2710  0   2% S    24 180208K  54856K  bg u0_a2710 /system/b2g/plugin-container
 3501  0   2% R     1   1300K    488K     root     top
 2765  0   1% S    24 187668K  63472K  bg u0_a2765 /system/b2g/b2g
  182  0   1% S     6   7496K    492K     radio    /system/bin/qmuxd
```
```txt
E/Telegram( 2765): Content JS ERROR: Push register error [object Event] [object Event] 
E/Telegram( 2765):     at C/e.onerror (app://{5757f8d2-8c53-4e25-ad6d-f1577a05515a}/js/app.js:19:10078)
W/SocketClient(  170): write error (Broken pipe)
W/SocketClient(  170): write error (Broken pipe)
W/SocketClient(  170): write error (Broken pipe)
E/Telegram( 2765): Content JS ERROR: Push register error [object Event] [object Event] 
E/Telegram( 2765):     at C/e.onerror (app://{5757f8d2-8c53-4e25-ad6d-f1577a05515a}/js/app.js:19:10078)
W/SocketClient(  170): write error (Broken pipe)
```

## Without Telegram
```txt
User 1%, System 4%, IOW 0%, IRQ 0%
User 6 + Nice 0 + Sys 13 + Idle 283 + IOW 1 + IRQ 0 + SIRQ 0 = 303

  PID PR CPU% S  #THR     VSS     RSS PCY UID      Name
 1926  0   3% R     1   1300K    488K     root     top
  179  0   2% S    79 454332K 111948K     root     /system/b2g/b2g
  185  0   0% S     7   7220K    488K     root     /system/bin/mpdecision
    5  0   0% S     1      0K      0K     root     kworker/u:0
 1671  0   0% S    25 131744K  38288K  bg u0_a1671 /system/b2g/b2g
```

**Comment by TitanNano** [comment]
the issue is not caused by telegram it self. Telegram is trying to register a simple push endpoint. 
But your simple push service is broken, see `W/SocketClient(  170): write error (Broken pipe)`. I fixed this by switching to the telefonica push service.

**Comment by SunboX** [comment]
Just for reference: https://bugzilla.mozilla.org/show_bug.cgi?id=1152264

**Comment by SunboX** [comment]
And https://bugzilla.mozilla.org/show_bug.cgi?id=1201138
