### ISSUE TITLE
I'm not getting the verification call

### ISSUE THREAD

**Issue by weitzhandler** [zhukov/webogram#869]
Hi,

My phone number doesn't have SMS, and thus I'm relying on the call that's being initiated after two minutes.  
However, this feature seems to have stopped working, I don't get that call. It might be a problem with my carrier, but again, this used to work.

**Comment by mautematico** [comment]
Are you able to get the call if you use another client? Let's say, Telegram on Android, iOS or Desktop?
If you are unable to get the call on all of them, I think it's time to try luck and get in touch with the *core* or *api* team.

If you **can** get the call on those other clients, may be it's indeed an issue with webogram. Please, try to get the call with other Telegram clients :)

**Comment by weitzhandler** [comment]
@mautematico thanks for your reply!

I'm actually able to use Telegram on Android, and I did that by activating by phone call, about a couple of months ago, which means it's the web-app causing the problem.

**Comment by mautematico** [comment]
That was a couple of months ago. Are you able to do it again, at this time? :)

**Comment by weitzhandler** [comment]
@mautematico 
No. Unfortunately issue is still on.

**Comment by weitzhandler** [comment]
@mautematico 
No. Unfortunately issue is still on.

It says "Telegram dialed your number" but no call has been received.

However, it sent me a Telegram message to my phone, so now it works.

**Comment by bobcanthelpyou** [comment]
@weitzhandler what @mautematico meant is: try to activate Telegram on Android with a phone call again.

**Comment by weitzhandler** [comment]
@bobcanthelpyou @mautematico 
I don't want to take the risk in reinstalling Telegram on phone. But anyway, last time I did it which was a couple of weeks ago, it worked just fine, and I got the call. It was only the webogram not calling me.

**Comment by zhukov** [comment]
@weitzhandler It's not Webogram, who makes a call, it's Telegram API.

Do you receive other phone calls (not from Telegram)? If yes, you should contact support (mobile apps have "Ask a question" in Settings.
