### ISSUE TITLE
Telegram on Firefox OS should be able to go through my Contacts and suggest import of all who have account in the Telegram.

### ISSUE THREAD

**Issue by mcepl** [zhukov/webogram#872]
Is it possible?

**Comment by mautematico** [comment]
I think it does.
When you first install telegram [0] from marketplace, it ask you to access contact list. And I think it indeed import all them into telegram's one.

[0] http://marketplace.firefox.com/app/telegram

**Comment by bobcanthelpyou** [comment]
It is possible to import all contacts from the phonebook manually, too (Contacts -> New Contact -> Phonebook -> Import contacts) 

Maybe webogram could suggest to import contacts from the phone book automatically when new contacts are added to the contact list.

**Comment by mcepl** [comment]
You are right, so this is not a bug, just discoverability issue.
