### ISSUE TITLE
Webogram Windows 10 Web App

### ISSUE THREAD

**Issue by bdbch** [zhukov/webogram#873]
Hello @zhukov,

I think it would be really nice to have a running Windows 10 App for Telegram. Since there are no apps in the Windows Appstore for now, it would be great to have one really nice running up and working.

Check out this documentation on how to embed remote websites into a webframe. What do you think about it?

http://microsoftedge.github.io/WebAppsDocs/en-US/win10/CreateHWA.htm

**Comment by db2k** [comment]
@zhukov I already tried to do it and I managed to make it work. It's running on Windows Phone and Windows 10 already and also sending out notifications.

**Comment by sergioad** [comment]
when will be it ready on the WIndows store? the price for good apps there is cheaper than on Android :smile:
