### ISSUE TITLE
Notifications are delayed in Firefox OS compared to other Telegram instances

### ISSUE THREAD

**Issue by marco-c** [zhukov/webogram#875]
I have Telegram installed on Android and Firefox OS.
I've noticed the Android version receives messages as soon as they are sent, the Firefox OS one instead receives messages after a delay.

I've also noticed that if a message has arrived to the Android instance and not yet to the Firefox OS one, if I interact with the phone I receive the message right away.

**Comment by zhukov** [comment]
What is an average delay time? Did you compare this delay with other FxOS applications with push notifications?

**Comment by marco-c** [comment]
I can't reproduce this anymore. I'll reopen if I can reproduce again.
