### ISSUE TITLE
Cut & paste unsupported on Firefox OS

### ISSUE THREAD

**Issue by marco-c** [zhukov/webogram#877]
There's no way to copy/paste text in webogram.

**Comment by elninosi** [comment]
Which version of Firefox OS are you using?

**Comment by marco-c** [comment]
I'm using a Nightly build.

**Comment by TitanNano** [comment]
I can copy and paste text in telegram on FxOS 2.2

**Comment by bobcanthelpyou** [comment]
@marco-c which nightly build for which Firefox OS version is it?

**Comment by marco-c** [comment]
> @marco-c which nightly build for which Firefox OS version is it?

2.5. I'll update again and re-test soon.

**Comment by floppyrom** [comment]
I have the same problem with Firefox 2.5, a recent build: copy paste doesn't work in Telegram. This is quite frustrating in many use cases.

**Comment by TitanNano** [comment]
this specifically an issue with 2.5. But I still couldn't figure out whats the problem. I guess it's some issue in FxOS.

**Comment by floppyrom** [comment]
Hm...Copy paste works in all the apps except Telegram...I wouldn't say that

**Comment by floppyrom** [comment]
This is fixed with the Firefox OTA of 17 Nov.

**Comment by aethanyc** [comment]
[Bug 1206545](https://bugzilla.mozilla.org/show_bug.cgi?id=1206545) which fixed this issue is landed on v2.5, too.
