### ISSUE TITLE
Sometimes sending a message on Firefox OS opens the attachment dialog

### ISSUE THREAD

**Issue by marco-c** [zhukov/webogram#880]
Sometimes a tap on the "send" icon is recognized as two subsequent taps, so the message is sent and unexpectedly the attachment dialog is opened.

**Comment by floppyrom** [comment]
I also have this issue in Firefox OS 2.5

**Comment by floppyrom** [comment]
This issues happens almost everytime I send a message on Telegram from Firefox OS 2.5...it's quite annoying.

**Comment by marco-c** [comment]
This is still happening for me (Sony Xperia Z3 Compact).
