### ISSUE TITLE
New line /n works differently in web version compare to desktop\mobile versions

### ISSUE THREAD

**Issue by r88r** [zhukov/webogram#883]
Problem appeared when a bot was sending a message containing /command.

If the text message contains a command and immediately after command there is '\n\n' that suppose to insert empty line between the command and the text after, then in order to make it work in web client one has to insert single space in front and right after the command. That is **not** required on desktop/mobile versions. 

Here are examples:

* This message **will not** have empty line after /space_off command:
```send_message( 'You subscribed to the following topics:\n/space_off\n\n...click to unsubscribe',  message=m)```
* This message **will** have empty line after /space_off command:
```send_message( 'You subscribed to the following topics:\n /space_off \n\n...click to unsubscribe',  message=m)```

Note the spaces before and after /space_off

![desktop](https://cloud.githubusercontent.com/assets/485961/9293468/84f55180-4456-11e5-8a95-70c66e044029.jpg)
![web](https://cloud.githubusercontent.com/assets/485961/9293469/84fcdc34-4456-11e5-93d4-92944ca5de25.jpg)

I hope that I'm explaining it clearly.

**Comment by zhukov** [comment]
This was fixed in my local branch. To be released soon, thanks.
