### ISSUE TITLE
Notify user if someone mentions her/his name

### ISSUE THREAD

**Issue by hharchani** [zhukov/webogram#885]
In group chats, if someone types @username, It gets highlighted and links to its profile. The user whose name is mentioned should get some notification that he or she was mentioned by someone.

**Comment by zhukov** [comment]
don't you get notification about this message, you were mentioned in?

**Comment by hharchani** [comment]
No. I don't.
Say when I open my browser, or come back after sometime and there are 100s of messages in the group chat. If someone mentions me somewhere, I don't get notified about that.

**Comment by zhukov** [comment]
This is a general Telegram feature request, not a webogram one. We do notify user at the moment he was mentioned if the web app was open. But we don't store all the mentions somewhere. We could possbily add this feature when it is present in API / other clients.
