### ISSUE TITLE
Network error on Firefox ESR 38 & IceWeasel

### ISSUE THREAD

**Issue by ry60003333** [zhukov/webogram#888]
On both TenFourFox 38.2.1 and the latest build of IceWeasel on Debian, WeboGram does not function and immediately displays this error:

To Reproduce: Load WebOGram

`Method: help.getNearestDc
Result: {"data":{},"status":404,"config":{"method":"POST","transformRequest":null,"transformResponse":[null],"responseType":"arraybuffer","url":"https://venus.web.telegram.org/apiw1","data":{},"headers":{}},"statusText":"Not Found"}
Stack: m/h@https://web.telegram.org/js/app.js:16:26020
l@https://web.telegram.org/js/app.js:8:6393
c/<@https://web.telegram.org/js/app.js:8:6565
jn/this.$get</u.prototype.$eval@https://web.telegram.org/js/app.js:8:13758
jn/this.$get</u.prototype.$digest@https://web.telegram.org/js/app.js:8:12250
jn/this.$get</u.prototype.$apply@https://web.telegram.org/js/app.js:8:14016
l@https://web.telegram.org/js/app.js:7:22417
f@https://web.telegram.org/js/app.js:7:24226
cn/</b.onload@https://web.telegram.org/js/app.js:7:24766`

![picture 1](https://cloud.githubusercontent.com/assets/3422003/9565382/fc3331fc-4e99-11e5-82d5-7b07c97079cb.png)

**Comment by Fluupkethy** [comment]
Help me I do not already know what to do!
this is my error
![wdxvxie](https://cloud.githubusercontent.com/assets/12993688/9570560/833a4cc8-4f65-11e5-9d1f-aab6d3be1fd8.png)

**Comment by Aokromes** [comment]
https://github.com/zhukov/webogram/issues/516 generic ticket.
