### ISSUE TITLE
Weird scrollbar near textarea on Chrome (with overlay scrollbars flag enabled)

### ISSUE THREAD

**Issue by stylemistake** [zhukov/webogram#890]
Here's an image:

![bug](https://cloud.githubusercontent.com/assets/1516236/9151631/d47e03aa-3e11-11e5-905c-e3e504e76315.png)

This happens on Chrome with enabled "Overlay scrollbars" flag.

**Comment by zhukov** [comment]
Does it happen on rtl message? Why do you have scrollbar on the left?

**Comment by stylemistake** [comment]
@zhukov i have no idea. It would make sense for RTL, but I'm not using RTL input.

By the way, overlay scrollbars on Chrome are known for weird rendering (they always render on top of the page regardless depth), but it shouldn't be an issue here, it's something different.

**Comment by jeremija** [comment]
This could be fixed by removing the `overflow-y: scroll` property (or setting it to `auto`) for class `.composer_rich_textarea`. However, I am not sure if this would mess up the interface in other browsers.
