### ISSUE TITLE
message not seen - blue dot not visible when window size is reduced

### ISSUE THREAD

**Issue by raunaqrox** [zhukov/webogram#895]
after I increase the size of the window the blue dot re-appears

**Comment by zhukov** [comment]
Can you show a screenshot? We usually have two ticks on the right when there is no space for the dot on the left.

**Comment by raunaqrox** [comment]
oh I didn't see the ticks, sorry. But why add the ticks and remove the dots?

**Comment by zhukov** [comment]
There is not enough space for the dot and tick to the left.
