### ISSUE TITLE
Desktop notification does not disappear after some time

### ISSUE THREAD

**Issue by nisargjhaveri** [zhukov/webogram#897]
Desktop notification does not disappear after some time. It stays there forever unless you open telegram or close the notification. I think it should disappear after some time, let say 5-10 seconds?

Under, Google Chrome, Ubuntu 14.04

**Comment by TitanNano** [comment]
Handling the notification behavior is job of the platform, not the application. Chrome doesn't close it's notifications.

**Comment by nisargjhaveri** [comment]
Umm, okay. But other applications seems to manage it work somehow. For example FB messenger closes its notification after some time.

**Comment by TitanNano** [comment]
facebook messenger in chrome? I can just tell that for exampe Tweetdeck also closes it's notifications. This has the result that on OS X with firefox the notification gets removed from the notification center. Actually chrome should use the systems native notifications or close them by it self (like Firefox on Windows)

**Comment by nisargjhaveri** [comment]
Okay.

We can probably use browser specific code for this one as every browser works differently... Or we can change Chromium!

IMHO, we really should fix this. I'm sure there are lot of people using Chrome. And, it is really annoying when I'm working on something and I cannot ignore the notification just by not looking at it as it stays there forever.. :(

**Comment by TitanNano** [comment]
Well it might sound ridiculous, but yes we should just change Chromium. Go there and file a bug. 

The point is the method Notification.close() means to take back the notification from the system and make it unavailable for the user. 

This is not an issue with telegram, it's an issue with how Chromium treats it's notifications. So what I want to say is, yes we can close the notification in telegram, but thats not how it should work. Chromium should set a timeout and hide it on it's own.

**Comment by akashnimare** [comment]
This issue needs to be solved. I am having the same problem. And yes FB desktop notifications disappear after 5-10 seconds.
