### ISSUE TITLE
Hosting on Github Pages

### ISSUE THREAD

**Issue by kennetham** [zhukov/webogram#898]
How does Telegram Webogram be hosted on Github Pages?

**Comment by Ryuno-Ki** [comment]
Via [gh-pages](https://github.com/zhukov/webogram/tree/gh-pages).

[Read the docs](https://pages.github.com/).

**Comment by kennetham** [comment]
Hi @Ryuno-Ki , as in it worked by just deploying as github pages? doesn't this require node.js?

**Comment by Ryuno-Ki** [comment]
Hello, @kennetham,

webogram is just a Telegram client. @zhukov uses [a Makefile](https://github.com/zhukov/webogram/blob/e538e76ffd9ca94ea8361bf612d1382c427dcee9/Makefile#L11) for publishing.

**Comment by kennetham** [comment]
@Ryuno-Ki which means, if I want to host webogram, i just deploy the entire repo will do isn't it?
sounds great.

Thank you.

**Comment by Ryuno-Ki** [comment]
I'd say, try it. It's [even documented](https://github.com/zhukov/webogram#running-locally).

If you encounter any problems, provide the steps you take + your OS/browser/environment details.

**Comment by zhukov** [comment]
1. Fork the project
2. Create a branch 'gh-pages'
3. Clone master to you local folder
4. Run `make ghdist` to create dist folder
5. Run `make publish` every time you want to deploy your changes to github pages.
