### ISSUE TITLE
Huge and abnormal data consumption on Firefox OS 2.2

### ISSUE THREAD

**Issue by Flore-mozfr** [zhukov/webogram#899]
I installed the telegram app from the marketplace a while ago (about one year, maybe) and it went smooth.
Until recently, when I noticed that when I launched the telegram my battery was draining rapidly.

I audited the network activity on the telegram app using WEB IDE and it appears that the app constantly  sends requests to the telegram server vesta/flora-1/pluto/venus.web.telegram.org. Constantly means every few seconds (see screenshot). This is responsible for abnormal data consumption and battery draining.
I deleted the app and reinstalled it to no avail (I had to test, one never knows).
I very recently encountered a similar bug on Firefox OS (https://bugzilla.mozilla.org/show_bug.cgi?id=1189729), maybe both bugs have similar causes?

I can post a log if needed

![web telegram excessive data consumption](https://cloud.githubusercontent.com/assets/6987429/9722714/9baa741a-55b2-11e5-91f9-d88681744543.png)

**Comment by TitanNano** [comment]
which device are you using?

**Comment by Flore-mozfr** [comment]
I'm using a flame.
But it seems the problem is now resolved.
2 days ago, it seems that the app was unable to stay on the same server, always jumping between servers (as you can see on the screenshot). But now, it's steadily connected on vesta and I can't see any abnormal data consumption.
Maybe I was too quick to open an issue. But I monitor closely data and battery usage since this bug on Firefox OS, so I notice quickly this kind of problem...

**Comment by marco-c** [comment]
I've experienced huge data consumption as well. Uninstalling and reinstalling Telegram fixed it for a while, but then the problem reappeared.

**Comment by elninosi** [comment]
Can you recheck with the new version (0.5.1) that was just pushed to Firefox Marketplace? 

I'm using Firefox OS 2.5 and didn't notice abnormal data usage.
