### ISSUE TITLE
Safari for Mac not responding after file download

### ISSUE THREAD

**Issue by sergey-tyan** [zhukov/webogram#900]
Telegram crashed Safari when I was trying to download a 32 mb 7z archive. At first, I received a file and Download button appeared. After pressing Download button, progress bar appeared and download started. After download has ended and progress bar has reached the end, "Save file" button appeared instead of "Download". Pressing "Save file" button caused browser to open an archive in the new tab in "text" mode and here the freeze happened. I guess opening 32 mb archive as a text was too much for my Mac

**Comment by zhukov** [comment]
Sorry, I can't do anything with this, there is Safari issue with downloading files: https://github.com/eligrey/FileSaver.js/issues/12.
