### ISSUE TITLE
Detect long url failed

### ISSUE THREAD

**Issue by NamPNQ** [zhukov/webogram#904]
See
![](https://cdn.pbrd.co/images/FIOAeEa.png)

**Comment by yuriteixeira** [comment]
Looks like it stops parsing after 4096 chars. I tested it with url:

http://www.longurlmaker.com/go?id=GBDPCHMLGOBYSUGZYQUYPUVNZSPCRCCYDFNGNASTOTRHNXGMNBKDWGRVYGXPIAOMFCTTCLMQFEXTBEGPGRTCXKXVQVLZVZMBBFUERHUWLSPMXWCDNVFKFDGWYRWURIVTNPXEWSBIKRUHNXLASRKYURUTIRNZZITNYQSVITDSKYAXVMXODIMYZHRIYEIYNBLLRDHZWLSHJTEFGCTJLGILNZTMECKRDVDVZLVVWOCFIHLOKEYVKGGYGAKKCUBGQFBPQXKMLNSTVDIFIGATNHRTIBDKWFRMKTBBQMOBZHVVLEATKBMXJERRGUCCATOLMPMDBAEBIAXTEXMPZZNIEEZKZBMZUBKHQXKSYPUGQRZUPMKOMYWQCVBCXNCRONZFKJYJZTPPLPKACUOOSLFVGGYDUAVJNUOYENHDGXTSMDSPYHDRSJMZPKCJLYSYTHWYVDCCBVUOYMDWTHNLQAKFLNPWMIVGQRELVGOWBIKAVOXOVLALLLRXZGUMPPSFGWRCCFZENKFIYCXTNYEZKVXJCRVSGOYNKPQNVPSIZXRYZPRNOVNYRKIUCEMJSKXCANQVDIEDFWBFLSTAOHYGSHAULNDDYBGYOXURFYVLUWRGOLGDSFJKMKFXYIBXJIWYFQQLOLXJHOPWAVZSAJDMUIKTRMQBUMZACQLRBIAJXPFXLFQLPTYKBJDTVTUQFUQIKCZMLAVIPBGAHXMWQLGSUKLQDGGJAXRLZRXKRTTHVAICXVZNGGGBQSSUYZDYWVKVNHGFBAMWAUZXPZLWGSYXKQRIPVHMRRHEZOJBOWXPQXNGWZCDRBABSSJHNRTFIBJIQTJFPHUGEHMBHPEYRFZJXJQKAKQJMASCTBHJICPNKCORSTPJYPSVYJGZUXJGXBJQCRALUQYESNVLGLUFBMBZWIZQFJXCKGTNYTZSJXWCLSNSEHXFUZFRHFHNOEPZLIMKCLCLJZNURAMWIKBDJGURMBEAGUZSDMCFYEQIEECWFPSOATRJALBMNFNUANNDZPIYUZGYEJVKZNYZHPJIBKUPQIKRVXUVNDTIDZHHJCRIPQHWGREHCZXTHHKDFEYSIRALRHSAJKJZARWGIAOKAMEITOLYTKRBBSNTZGTJQCJRUFYCGMNGYRPSGARAKICMAPFAVZKMCTDWZBZFOMMNEBFLCXLMGNZGDEHYESKGMNDLPCREPDRUEXGGURTAFSHJXOHBHSITGMEVOWZEZRYEOFKIXEJCWQLUFTWMLFFRRKNFGNKGEIKSNUBKZLNVBZQHTMTERZWIKKORXYXCHHVVCXGBIUXJTNQNAKSSJOBTZPLWOIZVPUQSRXTZRRJLFZYFKQXTFYNEOYBCHAXWUOOMLILDZUOEUMKEDIYIHMNVLOXSPVPKKEWWMIZMDOQXBACEIBNQOALZPJSEFHPPLLMYUMKXBAVCBXGKZTANTMNJVFOANDQZPDXJQIGRJBTKZZVZTWNNIAWEGKFTOVTDZQNPZTGIVASVZOVSKIGTICXPNCIBYCFYTSNSMUAIUTEUHZNSHTLPVJEJMNKLQQJJIWBVRBDLUHGCGTUOMGEIQJRCXCNNSWWBTXWKZAWUICWPWRDIYHQORHQOKEBCBXEUVBFVBCPKFMZBDDJBLAQCIHQSLRVMOZHKANFCQVMWHMXLPHNAIDCQKSIWKEIZEQJEEPHUKURRGODVWQWETYUERDABIJAMAKREZYZKSQBZFFUBVRFPQATHDUJLDKXDUOIUNHEGYGFDLAEHRKWHKPPOKYANJYRENZYAGDGEJMIVMNCEXYLHOBWYAWMJUDNICMIJPPOZBWVOJXSGWEOLGLKGHWQCADKCQTLGJZFLWAZFYSMVXBGDMQKTNAWNDHPUABAJBFUXGUCFNPAKQGNCXYWKYSXCANWAOWKPCFNIAPNNFOXVULXRJTCHMZJMMGNBCYREDENDUBQZPOUKZSBJMERZDBLQHZSJXJOBOBFICWHSKCCKVEUHILGMMSCUSVDQERRSTXBVTJOELQPGUJODVVPIOSCGNFWSXOLQLMMFVAJHQYOLICODYDLMVNTJTPBQEGBDPCHMLGOBYSUGZYQUYPUVNZSPCRCCYDFNGNASTOTRHNXGMNBKDWGRVYGXPIAOMFCTTCLMQFEXTBEGPGRTCXKXVQVLZVZMBBFUERHUWLSPMXWCDNVFKFDGWYRWURIVTNPXEWSBIKRUHNXLASRKYURUTIRNZZITNYQSVITDSKYAXVMXODIMYZHRIYEIYNBLLRDHZWLSHJTEFGCTJLGILNZTMECKRDVDVZLVVWOCFIHLOKEYVKGGYGAKKCUBGQFBPQXKMLNSTVDIFIGATNHRTIBDKWFRMKTBBQMOBZHVVLEATKBMXJERRGUCCATOLMPMDBAEBIAXTEXMPZZNIEEZKZBMZUBKHQXKSYPUGQRZUPMKOMYWQCVBCXNCRONZFKJYJZTPPLPKACUOOSLFVGGYDUAVJNUOYENHDGXTSMDSPYHDRSJMZPKCJLYSYTHWYVDCCBVUOYMDWTHNLQAKFLNPWMIVGQRELVGOWBIKAVOXOVLALLLRXZGUMPPSFGWRCCFZENKFIYCXTNYEZKVXJCRVSGOYNKPQNVPSIZXRYZPRNOVNYRKIUCEMJSKXCANQVDIEDFWBFLSTAOHYGSHAULNDDYBGYOXURFYVLUWRGOLGDSFJKMKFXYIBXJIWYFQQLOLXJHOPWAVZSAJDMUIKTRMQBUMZACQLRBIAJXPFXLFQLPTYKBJDTVTUQFUQIKCZMLAVIPBGAHXMWQLGSUKLQDGGJAXRLZRXKRTTHVAICXVZNGGGBQSSUYZDYWVKVNHGFBAMWAUZXPZLWGSYXKQRIPVHMRRHEZOJBOWXPQXNGWZCDRBABSSJHNRTFIBJIQTJFPHUGEHMBHPEYRFZJXJQKAKQJMASCTBHJICPNKCORSTPJYPSVYJGZUXJGXBJQCRALUQYESNVLGLUFBMBZWIZQFJXCKGTNYTZSJXWCLSNSEHXFUZFRHFHNOEPZLIMKCLCLJZNURAMWIKBDJGURMBEAGUZSDMCFYEQIEECWFPSOATRJALBMNFNUANNDZPIYUZGYEJVKZNYZHPJIBKUPQIKRVXUVNDTIDZHHJCRIPQHWGREHCZXTHHKDFEYSIRALRHSAJKJZARWGIAOKAMEITOLYTKRBBSNTZGTJQCJRUFYCGMNGYRPSGARAKICMAPFAVZKMCTDWZBZFOMMNEBFLCXLMGNZGDEHYESKGMNDLPCREPDRUEXGGURTAFSHJXOHBHSITGMEVOWZEZRYEOFKIXEJCWQLUFTWMLFFRRKNFGNKGEIKSNUBKZLNVBZQHTMTERZWIKKORXYXCHHVVCXGBIUXJTNQNAKSSJOBTZPLWOIZVPUQSRXTZRRJLFZYFKQXTFYNEOYBCHAXWUOOMLILDZUOEUMKEDIYIHMNVLOXSPVPKKEWWMIZMDOQXBACEIBNQOALZPJSEFHPPLLMYUMKXBAVCBXGKZTANTMNJVFOANDQZPDXJQIGRJBTKZZVZTWNNIAWEGKFTOVTDZQNPZTGIVASVZOVSKIGTICXPNCIBYCFYTSNSMUAIUTEUHZNSHTLPVJEJMNKLQQJJIWBVRBDLUHGCGTUOMGEIQJRCXCNNSWWBTXWKZAWUICWPWRDIYHQORHQOKEBCBXEUVBFVBCPKFMZBDDJBLAQCIHQSLRVMOZHKANFCQVMWHMXLPHNAIDCQKSIWKEIZEQJEEPHUKURRGODVWQWETYUERDABIJAMAKREZYZKSQBZFFUBVRFPQATHDUJLDKXDUOIUNHEGYGFDLAEHRKWHKPPOKYANJYRENZYAGDGEJMIVMNCEXYLHOBWYAWMJUDNICMIJPPOZBWVOJXSGWEOLGLKGHWQCADKCQTLGJZFLWAZFYSMVXBGDMQKTNAWNDHPUABAJBFUXGUCFNPAKQGNCXYWKYSXCANWAOWKPCFNIAPNNFOXVULXRJTCHMZJMMGNBCYREDENDUBQZPOUKZSBJMERZDBLQHZSJXJOBOBFICWHSKCCKVEUHILGMMSCUSVDQERRSTXBVTJOELQPGUJODVVPIOSCGNFWSXOLQLMMFVAJHQYOLICODYDLMVNTJTPBQEs

**Comment by zhukov** [comment]
Telegram API has a limit on message length: 4096 characters. If you want to send a longer URL, consider using url-shortener services :smile:
