### ISSUE TITLE
New incoming chats are annoying

### ISSUE THREAD

**Issue by the9ull** [zhukov/webogram#905]
With the @username Telegram feature a lot of people started to contact other people searching for random usernames, so users with simple/common names are flooded by new messages of strangers.

A way to mitigate this problem would be add an option to disable the notifications of new incoming messages from strangers (who doesn't know the phone number of the user). If the user reply the notifications could be automatically enabled.

**Comment by Akronix** [comment]
[Telegram advise you to not set up a telegram username if you don't want to be contacted by strangers](https://telegram.org/faq#q-what-are-usernames-how-do-i-get-one).

In telegram desktop app, [they have recently added an option to report people who you don't know as spam when they start to talk to you](https://github.com/telegramdesktop/tdesktop/commit/a9319bf6a35c5087bead294e010b74833f6cfa2d). Maybe this could be added to webogram too.

**Comment by zhukov** [comment]
@the9ull This is an API feature request. Please address it to Telegram Support.
