### ISSUE TITLE
'Too fast' error message when loading stickers

### ISSUE THREAD

**Issue by arieljannai** [zhukov/webogram#907]
Hi,

Every time when I open the stickers menu after I freshly open the [app](https://web.telegram.org), I get this error message:

`Too fast`

`You are performing too many actions. Please try again later.`

`Method: upload.getFile
Result: {"_":"rpc_error","error_code":420,"error_message":"FLOOD_WAIT_410"}
Stack: Error
    at h (https://web.telegram.org/js/app.js:16:26020)
    at https://web.telegram.org/js/app.js:16:27238
    at l (https://web.telegram.org/js/app.js:8:6393)
    at https://web.telegram.org/js/app.js:8:6565
    at u.$eval (https://web.telegram.org/js/app.js:8:13762)
    at u.$digest (https://web.telegram.org/js/app.js:8:12258)
    at https://web.telegram.org/js/app.js:8:13847
    at s (https://web.telegram.org/js/app.js:7:744)
    at https://web.telegram.org/js/app.js:7:2742
    at n (https://web.telegram.org/js/app.js:2:16525)`

From what I've seen with the developer tools, it's trying to make a lot of requests to get each sticker I have. Since I have plenty of stickers, I get this message each time.

**Comment by arieljannai** [comment]
Added some suggestions for the stickers loading and experience at #908

**Comment by zhukov** [comment]
Was fixed in https://github.com/zhukov/webogram/pull/926.
Now stickers are loading on demand: we only send requests when you scroll to new stickers in the list.
