### ISSUE TITLE
Improving stickers loading

### ISSUE THREAD

**Issue by arieljannai** [zhukov/webogram#908]
Hi,

after I got this bug (#907) I thought about some things that could improve the stickers user experience.

* What was suggested at #808 and #864 
* Caching the stickers. It's not changing much, and could really improve the speed for the next times.
* Load the stickers in blocks in quantities it's possible to handle, so no errors such as #907 will be shown to the user.
* If caching the stickers - instead of loading every time in blocks, just check if something have changed (the user added a new sticker pack, the sticker pack was updated by author and etc.)
* Fetch the stickers in the background, after the page is loaded - and not waiting until I open the menu, cause then I need to wait for them, and it's a bit annoying.

Hope you guys find it useful!
I think it can really improve the experience of using them.

Thanks,
Ariel

**Comment by zhukov** [comment]
This was fixed in https://github.com/zhukov/webogram/pull/926.
