### ISSUE TITLE
Broadcast List in WebApp

### ISSUE THREAD

**Issue by spectrojin** [zhukov/webogram#909]
There is no broadcast list option on telegram Web App. Why create a web app when u can't even send a web link to multiple friends ? A web app is supposed to be more in functionality than the mobile app. Telegram team please incorporate this option to make me stop using whatsapp. It would be a great addition, as it would make sending common messages to multiple people very easy.

**Comment by zhukov** [comment]
Broadcasts have been disabled in favour of channels.
