### ISSUE TITLE
Open links in browser - not working in Chromium

### ISSUE THREAD

**Issue by alindt** [zhukov/webogram#910]
When running webogram as an app from inside Chromium, clicking on http(s) links in conversations doesn't open them in the browser - nothing happens. It works fine when using Chrome to run the webogram app.

Running Linux, xdg-open works fine, the default browser is Chromium

**Comment by zhukov** [comment]
Can you record a video? Also can you check the errors console if anything strange appears at the moment of click?

**Comment by alindt** [comment]
Nothing interesting in console:
```
[167.820] Api call account.updateStatus
[167.978] Rpc response true
[174.258] Api call users.getFullUser
[174.563] Rpc response userFull
[216.270] Api call account.updateStatus
[216.466] Rpc response true
[259.996] Api call account.updateStatus
[260.126] Rpc response true
update reply markup 39675321 false
[263.274] Api call messages.getHistory
[263.393] Rpc response messages.messagesSlice
update reply markup 30912080 false
[279.991] Api call account.updateStatus
[280.094] Rpc response true
```

It seems that for each and every link click in webogram app, a new process is spawned and it dies immediately, e.g. after clicking the same link 4 times I get these 4 new processes:

```
$ ps ax | grep chrom
[...]
16691 ?        Sl     0:00 chromium-browser --disable-new-tab-first-run --enable-user-scripts --ppapi-flash-path=/usr/lib/adobe-flashplugin/libpepflashplayer.so --ppapi-flash-version --enable-pinch https://youtu.be/vq_pjh1y2Ec                           
16725 ?        Z      0:00 [chromium-browse] <defunct>
[...]
16836 ?        Sl     0:00 chromium-browser --disable-new-tab-first-run --enable-user-scripts --ppapi-flash-path=/usr/lib/adobe-flashplugin/libpepflashplayer.so --ppapi-flash-version --enable-pinch https://youtu.be/vq_pjh1y2Ec                           
16871 ?        Z      0:00 [chromium-browse] <defunct>
[...]
16962 ?        Sl     0:00 chromium-browser --disable-new-tab-first-run --enable-user-scripts --ppapi-flash-path=/usr/lib/adobe-flashplugin/libpepflashplayer.so --ppapi-flash-version --enable-pinch https://youtu.be/vq_pjh1y2Ec                           
16997 ?        Z      0:00 [chromium-browse] <defunct>
[...]
17013 ?        Sl     0:00 chromium-browser --disable-new-tab-first-run --enable-user-scripts --ppapi-flash-path=/usr/lib/adobe-flashplugin/libpepflashplayer.so --ppapi-flash-version --enable-pinch https://youtu.be/vq_pjh1y2Ec
17149 ?        Z      0:00 [chromium-browse] <defunct>
[...]
```

Running the exact command by hand in terminal works fine and a new tab opens the URL:

```
$ chromium-browser --disable-new-tab-first-run --enable-user-scripts --ppapi-flash-path=/usr/lib/adobe-flashplugin/libpepflashplayer.so --ppapi-flash-version --enable-pinch https://youtu.be/vq_pjh1y2Ec
Using PPAPI flash.
Created new window in existing browser session.
$ 
```

**Comment by zhukov** [comment]
Can you try the same with some different  Chromium App?

**Comment by alindt** [comment]
I tried with Hangouts - the links open just fine.
I ticked "Collect errors" in chrome://extensions for Telegram and right after clicking links I get these two errors, one after enother:

![1](https://cloud.githubusercontent.com/assets/1379385/10697689/df2cb4b0-79b5-11e5-9674-8603b5cf37ef.png)
![2](https://cloud.githubusercontent.com/assets/1379385/10697690/df2dedbc-79b5-11e5-860a-eb40f2c157f9.png)

**Comment by zhukov** [comment]
Chrome Apps are going to be deprecated. https://blog.chromium.org/2016/08/from-chrome-apps-to-web.html.
Closing the issue.
