### ISSUE TITLE
Make links preview not copyable in order to keep chat log clean

### ISSUE THREAD

**Issue by maximal** [zhukov/webogram#911]
When we copy a chat log and paste it elsewhere, the history is polluted with web link previews which are also copied to the clipboard.

I’m not a wizard of CSS but maybe something like this would solve the problem:

```html
<style>
	.no-copy {
		/* :before content is not selectable by default
		    but maybe there are some solutions without pseudo-classes */
		/*-webkit-touch-callout: none;
		-webkit-user-select: none;
		 -khtml-user-select: none;
		   -moz-user-select: none;
		    -ms-user-select: none;
		        user-select: none;*/
		border-left: blue 2px solid;
	}
</style>

<!-- … -->
<div>Message text copied</div>
<div>Message text copied</div>

<blockquote id="bq111" class="no-copy" unselectable="on"></blockquote>
<style>#bq111:before {content: 'Link preview text is not copied.';}</style>

<div>Message text copied</div>

<blockquote id="bq222" class="no-copy" unselectable="on"></blockquote>
<style>#bq222:before {content: 'Another link preview text is not copied';}</style>

<div>Message text copied</div>
<div>Message text copied</div>
<!-- … -->
```

Some demo: https://sijeko.ru/temp/no-copy.html (Russian text)

## Disadvantage

We cannot copy even a part of the preview text (if we want it).

**Comment by anton-makarov** [comment]
This would be usefull, +1

**Comment by mctep** [comment]
:+1:

**Comment by LucidLynx** [comment]
+1

**Comment by Ryuno-Ki** [comment]
"Web link previews" are previews rendered out of copied URLs?

At least I don't get what you are asking for, @maximal. As far as I understand, links should not be rendered as such if they're pasted into Telegram. Please specify, from where you copy (what "chat log") and where you paste it into (say, a text editor?).

An example would be nice for both, what you expect to happen and what actually happened.

**Comment by maximal** [comment]
In this context, _preview_ is a text displayed after the mesasge with any link in its contents:

![Web link preview in Telegram](https://habrastorage.org/files/907/5cd/e14/9075cde1465b4f8b934c8d6d37e67fc5.png)

**Comment by zhukov** [comment]
I would implement this, but I can't find any good solution to hide text just from copying. The one @maximal provided requires Javascript (we don't want langpack inside CSS).

**Comment by maximal** [comment]
Does my solution require Javascript?

**Comment by zhukov** [comment]
Ok, I've found that we can use `data-content` attribute + `content: attr(data-content);` for this. Will try it.

**Comment by maximal** [comment]
:+1:

**Comment by zhukov** [comment]
I'm afraid I don't see any solution for this problem. `content` attribute can't contain nested elements and we need them for webpage rich description (hashtags, links, mentions etc).

https://github.com/zhukov/webogram/blob/master/app/partials/desktop/message_attach_webpage.html#L55

**Comment by maximal** [comment]
Yeah, that is a problem :-(
