### ISSUE TITLE
Sign-in country detection incorrect

### ISSUE THREAD

**Issue by bluezed** [zhukov/webogram#914]
When I open the page https://web.telegram.org/#/login on a Win10 PC at home then instead of my actual country (Germany +49) it shows up with "Suedossetien" and code +995 34.

My ISP is Deutsche Telekom and the current IP is 80.138.230.108 but that changes every 24 hours. The login screen appears the same though after an IP change.

Here's a screenshot: 
![Screenshot](http://s19.postimg.org/eepvbia1v/Login_Telegram.png)

**Comment by mrandri19** [comment]
Try clearing the cookies and the browser cache. If it doesn't work you could try to login through a German VPN

**Comment by bluezed** [comment]
Cache and Cookies didn't help. I tried on another Win10 PC at home and it's the same issue.
Weirdly, when I use Firefox on my phone to connect it detects the country correctly so that would lead me to believe it might have something to do with Win10!?

Anyway... why should I use a VPN? I am in Germany already and my IPs are from Deutsche Telekom, a German ISP. They show up on IP geolocation sites correctly as being in Germany.

**Comment by zhukov** [comment]
You can always just enter correct country code manually. Auto-detection is just for speeding up the process when possible.
