### ISSUE TITLE
[Secure Issue] 5 issues

### ISSUE THREAD

**Issue by caiodias** [zhukov/webogram#915]
#[1] my.telegram.org Denial Of Service
#[2] Bypass 5 minutes limit to input token
#[3] Telegram Denial Of Service in token request
#[4] User identity validation absence
#[5] Hijacking account and importing contacts

Read full disclosure on [Telegram - Multiple Vulnerabilities on SETLIST.org](http://seclists.org/fulldisclosure/2015/Oct/2)

**Comment by zhukov** [comment]
Thanks for the investigation!

I thought that security issue is when attacker can do something bad.
So [1] and [3] are not the case. And they are not webogram-related, btw. I guess it's just some server-side protection so you can't brute force phone numbers or verification codes.

[2]
> After the web.telegram.org asks for a new token, we have 5 minutes to send
it.

Really? Why do you think so? Where is this 5 minute restriction from?

[4] It's a web app. Of course if you have direct access to target machine, you can get cookies with access to Facebook, Twitter and get Webogram auth key. But you could easily just watch the screen of victim in any case.

[5] Not Webogram related. We do not have automatic contacts import.

**Comment by edudx1** [comment]
Hi zhukov.


About previous  token presentation:

![token-in-web](https://cloud.githubusercontent.com/assets/15003991/10322139/cb10336e-6c52-11e5-8ff4-0db9009a350d.png)

![screen_xfce](https://cloud.githubusercontent.com/assets/15003991/10322152/df245eb6-6c52-11e5-8f3d-1293093ca339.jpg)

Can you observe? it is easier to get them

[2] - Yes, there are a restriction !
![code_sent]
(https://cloud.githubusercontent.com/assets/15003991/10321926/beb38540-6c51-11e5-8399-0ab36ad2cf5e.png)
After 5 minutes, no longer works, but in Telegram-CLI, yes.

[4] - We can discuss some solution
![simul](https://cloud.githubusercontent.com/assets/15003991/10322036/38027bc2-6c52-11e5-860a-f5ab85ef7742.png)

[5] Yes, contacts are imports after the victim login.
![contacts2](https://cloud.githubusercontent.com/assets/15003991/10321982/00f64ea6-6c52-11e5-90f4-0bc706bff2be.png)

**Comment by zhukov** [comment]
> [2] - Yes, there are a restriction !

do you see the text? It says that Telegram will call you in 5 minutes. Nothing about restrictions.


> [4] - We can discuss some solution

Interesting. What solution?

> [5] Yes, contacts are imports after the victim login.

But this is mobile app issue, not a Webogram one. Please report to Telegram Support or to corresponding github repo.
