### ISSUE TITLE
Forward slash causing duplicated text

### ISSUE THREAD

**Issue by thefryscorer** [zhukov/webogram#917]
After the most recent update, it seems that a '/' followed by a character causes all text before the forward slash to be duplicated. This behaviour didn't occur before, and started occurring immediately after clicking OK to the prompt to launch the updated version. 

This only seems to affect the displaying of the message locally, as after refreshing the page, the text is correct. It also doesn't affect links as far as I've been able to tell.

My browser is Google Chrome on Linux.

**Comment by bluezed** [comment]
+1
Just noticed that too on Win7 with Firefox 41.0.1

**Comment by zhukov** [comment]
Already fixed, thanks.
