### ISSUE TITLE
Enhancement: Allow user to change background

### ISSUE THREAD

**Issue by bluezed** [zhukov/webogram#92]
Would be nice if the user could change the background and choose from different pre-defined ones or upload his own.
Or if possible use the same background as set in the mobile app.

**Comment by zhukov** [comment]
We have no bubbles (unlike other Telegram apps), so custom backgrounds approach is not suitable here.

**Comment by glepretre** [comment]
@zhukov I think the use case was to quickly and visually distinct one conversation from another. 

For exemple, we are using webogram as Telegram client at work every day (thanks to you) and I regularly send messages to the wrong person/team :fearful::wink: 

The second benefit I would see is on images preview: I once sent a PNG file of a white logo on a transparent background. I couldn't see the preview in the conversation.
