### ISSUE TITLE
Autolinking breaks URL with MIDDLE DOT (U+00B7)

### ISSUE THREAD

**Issue by jmontane** [zhukov/webogram#920]
Hi,

Autolinking feature breaks URLs with MIDDLE DOT · char (U+00B7) in domain part.
If you paste/type one URL with · in a message or group, then link is broken and unusable.

Sample URL with · char:
www.l·l.cat
http://www.l·l.cat

Such domains are allowed, at least, in .cat, .es and .eu TLD

**Comment by zhukov** [comment]
I will fix it in Webogram parser, but the links are highlighted on server-side. So you should contact Telegram support.
