### ISSUE TITLE
Clicking in certain area of text field moves cursor and prevents typing

### ISSUE THREAD

**Issue by bluezed** [zhukov/webogram#922]
Since this morning I have a strange effect...

I have Telegram open in Firefox 41.0.1 on Windows 7 and after I change to a different tab work in a different window and then come back to Telegram and click into the text field to write a message the cursor has moved to the right, where the smiley icon sits. Once that has happened I cannot type any more. See screenshot here:
![Screenshot](http://s19.postimg.org/baeucddcz/Telegram_Cursor.png)

Sometimes it helps if I leave the windows again and come back to restore functionality but I also had to re-load the whole application to get it working again.

As I said, this has not happened at all before this morning... very strange...

**EDIT:** I can reproduce it now. When I click in a certain area of the text field that is when the cursor moves to the right. The area is just above the "heart" in the screenshot above. If I click into the text area just above there the cursor moves to the right and I cannot type any more.

Hope this helps solving the issue...

**Comment by LelixSuper** [comment]
I've the same bug! Firefox 41.0.1 on Ubuntu 14.04.3.

**Comment by albu** [comment]
Same here. If I click on the second row of input field (row below "Write message" text) - it reproduces.
Firefox 41.0.1 Windows 7/10

**Comment by blandin** [comment]
I'm experiencing the same behavior in Firefox 41.0.1 on Ubuntu 14.04.0.

**Comment by bluezed** [comment]
Also just verified this on SLES12 with Firefox 31.6.0.

I cannot reproduce it with IE11 or Chrome 45 so seems like a Firefox only issue.
