### ISSUE TITLE
Received SPAM sms when trying to login through the webclient

### ISSUE THREAD

**Issue by abuisman** [zhukov/webogram#924]
A friend of mine just tried to login on Telegram through the official web client hosted on https://web.telegram.org/ and received a SPAM SMS with something along the lines of 'Your mobile number has been selected to win 1.000.000 pounds. Click here... etc' She deleted the message straight away, so sadly I don't have it, but I believe this is still very noteworthy and it seems like too big of a coincidence that she received it at the same time as the login code from Telegram.

To be precise:
- The Telegram SMS code was delivered
- She received a SPAM message from a number starting with +44. The SMS client showed the spam message in a different SMS thread on android than the confirmation code from Telegram
- She did not use the received code for Telegram

**Comment by zhukov** [comment]
@abuisman You should contact Telegram support (in mobile app via telegram or by email support@telegram.org) about this situation with your phone number.
