### ISSUE TITLE
Actions for scrolling on new emoji toolbar

### ISSUE THREAD

**Issue by Akronix** [zhukov/webogram#929]
Hi there!

I've just seen the new emoji toolbar added to webogram. Intuitively, I moved the wheel on the stickers bar to get the packs scrolling and go to the pack I was looking for, but scrolling the mouse didn't lead to anything.

I think we could add these actions to the emoji toolbar when the user use the mouse wheel there:
 1. if the user scrolls on the emoji bar, the emojis being displayed change upward/forward depending on the wheel direction.
 2. if the user scrolls on the stickers pack, the sticker bar packs being shown shift to the previous/next packs.

Whatever we decide, I'd be pleased to contribute on the implementation of this.

**Comment by zhukov** [comment]
Hm. What browser / OS are you using? It works fine for me on OS X + Chrome / Safari / Firefox.

**Comment by zhukov** [comment]
And please write a more detailed description. Where exactly is your cursor, when you are scrolling (screenshot / video might be helpful)
