### ISSUE TITLE
Cannot share link to Telegram from the Browser on Firefox OS 2.5

### ISSUE THREAD

**Issue by floppyrom** [zhukov/webogram#933]
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:43.0) Gecko/20100101 Firefox/43.0
Build ID: 20150919030207

Steps to reproduce:

I tried to share a link from the Browser to Telegram v0.4.7. I use a Flame device running Boot2Gecko 2.5.0.0-prerelease 20150820200530 git commit c6705f73

Actual results:

From the Browser, when I click on Share, I cannot see the option to share to Telegram

Expected results:

If installed, Telegram should be present in the available options when I want to share a link from the Browser.

**Comment by floppyrom** [comment]
A Mozilla developer gave this feedback on Bugzilla 

https://bugzilla.mozilla.org/show_bug.cgi?id=1206535#c3
"the app needs to implement Web Activities https://developer.mozilla.org/en-US/docs/Web/API/Web_Activities which is specific to Firefox OS.

Maybe Telegram doesn't implement this."

Can you guys please check?

**Comment by Ryuno-Ki** [comment]
IMHO duplicates #694.

**Comment by zhukov** [comment]
Duplicate #694 

This issue is resolved.
