### ISSUE TITLE
Add formatting option to express activity

### ISSUE THREAD

**Issue by nakami** [zhukov/webogram#936]
A lot of messengers have this - I'd love to see this in telegram, too.

Writing
``/me feels hungry``
Resulting in
``$user feels hungry``

On skype and IRC-clients you can use the /me command to do so.

But I can imagine it also being activated by double asterix:
``*feels hungry*``
Resulting in 
``$user feels hungry``

Ideally, the usual text-message bubble (username as headline and profilepicture) doesn't show up, but it being handled as if a narrator was describing the activity happening.

example in skype: http://i.imgur.com/tdq6lp8.png

**Comment by zhukov** [comment]
This is an API feature request. Please address it to Telegram Support.
