### ISSUE TITLE
Attempted to use a group join link and now telegram gives me 500

### ISSUE THREAD

**Issue by emilfihlman** [zhukov/webogram#943]
I attempted to join a groupchat by an invite link. Instead got:

Server error

Internal server error occured. Please try again later.
Technical details here

Which opens

Method: messages.getDialogs
Result: {"_":"rpc_error","error_code":500,"error_message":"RPC_CALL_FAIL"}
Stack: Error
    at h (https://web.telegram.org/js/app.js:30:3722)
    at https://web.telegram.org/js/app.js:30:4940
    at l (https://web.telegram.org/js/app.js:15:10195)
    at https://web.telegram.org/js/app.js:15:10367
    at m.$eval (https://web.telegram.org/js/app.js:15:17773)
    at m.$digest (https://web.telegram.org/js/app.js:15:16204)
    at https://web.telegram.org/js/app.js:15:17860
    at a (https://web.telegram.org/js/app.js:14:1293)
    at https://web.telegram.org/js/app.js:14:2747
    at n (https://web.telegram.org/js/app.js:3:17045)

And now the whole web thing is broken for me. Web.telegram.org leads me to https://web.telegram.org/#/im and the same error message.

**Comment by emilfihlman** [comment]
Issue persists across different browsers (Chrome and Firefox) and my mobile application is stuck on "updating".

This invite link came from a trusted source.

**Comment by fhoshino** [comment]
related to 
https://github.com/zhukov/webogram/issues/942

**Comment by zhukov** [comment]
There were some server-side problems during last day. They should be all fixed now.
