### ISSUE TITLE
Don't Generating Keys at start

### ISSUE THREAD

**Issue by chmod0777** [zhukov/webogram#944]
Heya 

i have DS214play and use Firefox 41.0.2. When check the first keys start he loop generating key... and after stop.

My line it's OK and  don't think it's a Firefox problem.

Can u help me???

http://s20.postimg.org/s4aswsj1p/Immagine.jpg

**Comment by zhukov** [comment]
You use very outdated version of Webogram. Please update to the recent one (clear the cache, or install a new package).

**Comment by chmod0777** [comment]
TY =)

**Comment by Haktrum** [comment]
Why don't you use Firefox?
You can make your own spk, too, if they won't update it.

**Comment by chmod0777** [comment]
i use ALWAYS Firefox... but i can't create my .spk 'cause i'm not good for create it.

I see this https://amigotechnotes.wordpress.com/2014/05/17/how-to-create-a-spk-for-synology-dsm-to-distribute-your-lamp/

and this http://forum.synology.com/wiki/index.php/Synology_package_files

and this http://forum.synology.com/enu/viewtopic.php?f=27&t=10807



If u help me =)

**Comment by zhukov** [comment]
Sorry, I don't support older versions and this one is not maintained by me. It would be good, if you contacted the author and asked to update this package.
