### ISSUE TITLE
forward to multiple people

### ISSUE THREAD

**Issue by 9px** [zhukov/webogram#945]
hi. one of the most useful pros of Webogram is: **forward item(s) to multiple recipient**
in new update (0.5.0) this feature gone away!
i understand that you remove this feature (multiple recipient) to make the user enabling add a note before forwarded message(s), but you can remain the old desirable feature (multiple recipient) for who pressed a special keyboard (for example Ctrl) when selecting recipient.
thanks.

**Comment by zhukov** [comment]
You can now forward channel posts to multiple people with click on the date.

**Comment by azzimuth** [comment]
@zhukov is it possible to implement this the same way as it works in the app? I.e. small arrow icon besides the post, like on following screenshot.
![2017-01-12 07 50 43](https://cloud.githubusercontent.com/assets/1640148/21881531/145a6ad4-d8a5-11e6-8513-a6ae3576d110.png)
