### ISSUE TITLE
Major lagg on new messages

### ISSUE THREAD

**Issue by JeremybellEU** [zhukov/webogram#946]
When I receive a ping from a chat I am currently not active in, Webogram laggs for about a second. Any keyboard input received during this period is delayed and will instantly enter when the lagg ends. I only experience this for chats I receive pings for too (the sound). So maybe it is related to starting/playing the sound?

I have Windows 7 with Chrome 46.0.2490.80 m (64-bit) and Webogram 0.4.9

**Comment by zhukov** [comment]
Can you check errors console? Are there any red errors present?

**Comment by JeremybellEU** [comment]
There are none. I do see however a lot of requests in the network tab and console.logs in my console

**Comment by zhukov** [comment]
What are the requests? can you copy some log here?

**Comment by JeremybellEU** [comment]
I have not encountered major lagg the past week, so I will close this issue for now.
