### ISSUE TITLE
When will the new iOS emojis arrive in web.telegram.org?

### ISSUE THREAD

**Issue by mwld** [zhukov/webogram#947]
iOS 9.1 included new emojis:http://thenextweb.com/apple/2015/09/09/ios-9-1-finally-brings-new-emoji-including-cheese-burrito-and-more/

I think the Android version of Telegram already included those in the last release.

When will those be available in the web version too? Currently I only see gibberish when someone sends me one of those new emojis :|

**Comment by Akronix** [comment]
+1
I confirm they are in Android too.
What is it needed for webogram to get them?

**Comment by zhukov** [comment]
Duplicate #760
