### ISSUE TITLE
Update app in Firefox Marketplace

### ISSUE THREAD

**Issue by python273** [zhukov/webogram#954]
https://marketplace.firefox.com/app/telegram/

**Comment by holztest08** [comment]
Yes, would be great to have the latest version in firefox os.

**Comment by floppyrom** [comment]
Yes, please pretty please :D

**Comment by elninosi** [comment]
App was just updated to latest 0.5.1 version so this issue can be closed.

**Comment by elninosi** [comment]
Please reopen the issue and upload the new version which adds improvements (GIF). Thanks!

**Comment by elninosi** [comment]
Ping @zhukov.
