### ISSUE TITLE
gulp usemin task error

### ISSUE THREAD

**Issue by hoyangtsai** [zhukov/webogram#956]
When I use the Makefile of make package, it goes through a batch of gulp processes, but it suspended due to a issue of gulp-usemin cannot edit multiple files (index.html & badbrowser.html) with single task at the same time that would cause file streaming error, even I updated gulp-usemin to version 0.3.14.

I came out a solution to avoid it by changing around the gulpfile "build" task a little bit.

```javascript
gulp.task('usemin-badbrowser', function() {
  return gulp.src('app/badbrowser.html')
    .pipe($.usemin({
      html: [$.minifyHtml({empty: true})],
      css: ['concat', $.minifyCss({compatibility: true, keepBreaks: true})],
    }))
    .pipe(gulp.dest('dist'));
});

gulp.task('usemin', ['templates', 'enable-production'], function() {
  return gulp.src('app/index.html')
    .pipe($.usemin({
      html: [$.minifyHtml({empty: true})],
      js: ['concat', $.ngAnnotate(), $.uglify({outSourceMap: false})],
      css: ['concat', $.minifyCss({compatibility: true, keepBreaks: true})]
    }))
    .pipe(gulp.dest('dist'));
});

...

gulp.task('build', function(callback) {
  runSequence(
    'less',
    'usemin',
    'usemin-badbrowser',
    ['copy', 'copy-locales', 'copy-images', 'disable-production'],
    callback
  );
});

...
```

**Comment by zhukov** [comment]
Please provide PR, so I can try it and see the diff.

**Comment by guystein** [comment]
I for now installed a previous version of gulp-usemin:

gulp-usemin version 0.3.11:
npm uninstall gulp-usemin
npm install gulp-usemin@0.3.11
