### ISSUE TITLE
Add support for bold and italics

### ISSUE THREAD

**Issue by jessicah** [zhukov/webogram#957]
Would be nice to have support for *bold* and _italics_ text in the client(s).

**Comment by zhukov** [comment]
Telegram Bots (https://core.telegram.org/bots/api) can create messages with bold and italics. And Webogram will display them correctly.

But users can only send messages with `code` blocks. This is also supported by Webogram. See #147

**Comment by andrew-kennedy** [comment]
Is there a reason we don't allow users to send anything other than formatted code blocks? why not other markdown?
