### ISSUE TITLE
There is no document for new functions!!!

### ISSUE THREAD

**Issue by EmRa228** [zhukov/webogram#958]
When document is not available, how you(@zhukov) could implement new functions?

Like this:
https://core.telegram.org/method/channels.getDialogs

Please send us a document to be able to develop new functions.
Thank you.

**Comment by Haktrum** [comment]
You already have all you need but to clarify some things:
* Your link defines an interface, you don't know nor care how it works, you just use it.
* You should actually implement functionality, not functions.
* If you want to add new functionality to Telegram's API, contact Telegram support.
* If you want to add something that's missing, Telegram's and AngularJS' documentations have most of what you need.
* If you want to fix something that's broken, you have to debug.

**Comment by EmRa228** [comment]
@Haktrum 
I want description of each function and what do and what return.
Important of all, what errors can occurred after calling a function.
These are missing!


What is this function?
What do that?
When must use it?
What do it return?
and ...???
https://core.telegram.org/method/messages.migrateChat

All those questions need a document!

**Comment by zhukov** [comment]
Sorry, I don't write any documents for server-side API. Please contact Telegram support.

**Comment by EmRa228** [comment]
@zhukov 


  function openChatInviteLink (hash) {
    return MtpApiManager.invokeApi('messages.checkChatInvite', {
      hash: hash
    }).then(function (chatInvite) {
      var chatTitle;
      if (chatInvite._ == 'chatInviteAlready') {
        AppChatsManager.saveApiChat(chatInvite.chat);
        if (!chatInvite.chat.pFlags.left) {
          return $rootScope.$broadcast('history_focus', {
            peerString: AppChatsManager.getChatString(chatInvite.chat.id)
          });
        }
        chatTitle = chatInvite.chat.title;
      } else {
        chatTitle = chatInvite.title;
      }
      ErrorService.confirm({
        type:  chatInvite.flags & 1 ? 'JOIN_CHANNEL_BY_LINK' : 'JOIN_GROUP_BY_LINK',
        title: chatTitle
      }).then(function () {
        return MtpApiManager.invokeApi('messages.importChatInvite', {
          hash: hash
        }).then(function (updates) {
          ApiUpdatesManager.processUpdateMessage(updates);

          if (updates.chats && updates.chats.length == 1) {
            $rootScope.$broadcast('history_focus', {peerString: AppChatsManager.getChatString(updates.chats[0].id)
            });
          }
          else if (updates.updates && updates.updates.length) {
            for (var i = 0, len = updates.updates.length, update; i < len; i++) {
              update = updates.updates[i];
              if (update._ == 'updateNewMessage') {
                $rootScope.$broadcast('history_focus', {peerString: AppChatsManager.getChatString(update.message.to_id.chat_id)
                });
                break;
              }
            }
          }
        });
      });
    });
  }



If you haven't document, how you write this:
type:  chatInvite.flags & 1 ? 'JOIN_CHANNEL_BY_LINK' : 'JOIN_GROUP_BY_LINK'

telegram where say about "chatInvite.flags" ?
what's the link?

**Comment by EmRa228** [comment]
Yes you right. You don't write document but telegram give you a document!
Please share it with us.
در تاریخ ۱۰ نوامبر ۲۰۱۵ ۱۴:۰۲، "Igor Zhukov" <notifications@github.com>
نوشت:
