### ISSUE TITLE
Incorrect display of the message sender

### ISSUE THREAD

**Issue by D-Jet** [zhukov/webogram#960]
My message is shown as it were sent by the my conversational partner, but not mine. On Example 1 shows that they are not read (because I have sent them, and not my conversational partner).

Sometimes it's shown in the other option - my messages just appear as sent on behalf of the conversational partner, without re-displayed icons of the sender. This is shown in Example 2.

This happens on different computers (OS Windows 7), browsers (Chrome and Mozilla Firefox) and at the my conversational partner too.

P. S. After some time these messages shown correctly.

Example 1 (I hid the icons and the name of a friend):
![error](https://cloud.githubusercontent.com/assets/2864295/10996722/3947ef02-8490-11e5-85bc-83519d9df332.jpg)

Example 2 (just the remade image, it's not a screenshot):
![error-2](https://cloud.githubusercontent.com/assets/2864295/10996806/fd205a18-8490-11e5-9394-0c4830acef2b.jpg)

**Comment by zhukov** [comment]
We have already fixed this issue in 0.5.0 version. Did you update to it? When was the last time you reproduce the issue? Can you reproduce it again? What are the steps?

**Comment by D-Jet** [comment]
Last time that this issue seen was 1st of November.
Now it's showing version 0.5.0.
I'll write if I succeed reproduce it again.
