### ISSUE TITLE
Suggestion: collapsing user/group list

### ISSUE THREAD

**Issue by kevinhikaruevans** [zhukov/webogram#962]
It would be nice if I could collapse the user list pane on the left-hand side of the application.

I usually just stay in one conversation, so it would be beneficial to be able to expand out the main chat pane. Let me know if that needs clarification or if it is doable.

Cheers

**Comment by zhukov** [comment]
You can resize browser window and go to mobile layout. We don't have plans to collapse left column in desktop layout. Or you can use this link https://web.telegram.org/?mobile=1 without resizing.
