### ISSUE TITLE
using the source in a php project

### ISSUE THREAD

**Issue by MohamadSH** [zhukov/webogram#963]
Hi,
I was wondering if someone could help me with this.
I want to use this source to add an editor to my Telegram project which has been implemented by PHP. Now my question is which one of the Webogram's modules do I have to use. I asked this because I don't need most of the `Webogram` features and the only thing I need is sending a complete message(containing emoji and other stuffs) through an editor like the one we have in this web application.So I'll be so much grateful if some one guides me through this and saves me a lot of time. 
Thanks in advance.

**Comment by zhukov** [comment]
I think you should take a look at Bots API: https://core.telegram.org/bots.
PHP is a server-side language, which is far from Webogram.
