### ISSUE TITLE
Can't see all emojis

### ISSUE THREAD

**Issue by azzimuth** [zhukov/webogram#964]
I see only 'recent' emojis. Where is the rest?
![image](https://cloud.githubusercontent.com/assets/1640148/11061793/c3ff6f78-87a9-11e5-9528-74333c8484f3.png)

**Comment by zhukov** [comment]
@azzimuth Where do you see this? It seems like some invalid with css files. Try to clear cache or update the source code.

**Comment by azzimuth** [comment]
I see this when I hover the mouse pointer over the smiley icon. I've updated the source code several times and cleared the cache right now - didn't help.

**Comment by zhukov** [comment]
Does it reproduce on web.telegram.org from the same browser?

**Comment by azzimuth** [comment]
It works fine at web.telegram.org. I run Weborgram on Node.js locally. Can that cause the problem?

**Comment by zhukov** [comment]
Sure, it cause the problem. You probably forgot gulp task for less or did it wrong.

Read the docs https://github.com/zhukov/webogram#running-locally.

**Comment by azzimuth** [comment]
It doesn't work but I guess it's caused by our corporate proxy :(
