### ISSUE TITLE
Telegram reload names for contacts

### ISSUE THREAD

**Issue by idgy** [zhukov/webogram#966]
I set my own name for contact using "contact_info->edit", but sometimes it appears with original name/nickname. it seems to me that it's wrong behaviour

**Comment by zhukov** [comment]
Please provide steps to reproduce.

**Comment by idgy** [comment]
ok, i'll try do this, but maybe i should send you a patch when i can definitely say how it can be reproduce?:) now it looks like as suddenly event. i use telegram on 3 devices: ipad, android phone and web form firefox. sometimes i see that names have reloaded with original versions.

**Comment by zhukov** [comment]
Any news here?
