### ISSUE TITLE
[Suggestion] Win10 / W10M UWP app

### ISSUE THREAD

**Issue by sergioad** [zhukov/webogram#973]
Hello @zhukov I am a fan of Telegram and a Windows 10 user, and because that I have a good proposition for you; why do you not grab Telegram web into the Microsoft's Project westminster? Project westminster is a tool wich lets to the developers to put a web application on it and turn it into a Windows 10 / Windows 10 mobile / XBOX one / Microsoft Hololens universal Windows plataform (UWP) app with not many work, why do you not do that? doing it will not take many efforts and will make Telegram web an universal Windows app wich can run on Windows 10 10 mobile and XBOX one

Actually the Windows phone Telegram app is horrible and the Wiindows phone users needs a better app, with Windows 10 mobile in the corner why not make a good app for it? maybe an UNIVERSAL app wich can run in most of the Windows plataforms even on tablets? this is your oportunity @zhukov to try to make Telegram web (and Telegram in general) a greater multiplataform app wich also Works in a videogame console

If you want to try it and maybe learm more about Project westminster just visit https://blogs.windows.com/buildingapps/2015/07/06/project-westminster-in-a-nutshell/

**Comment by yonaesp** [comment]
+1 I want telegram with a better desing on my Phone and Xbox!

**Comment by sergioad** [comment]
Yes, could be awesome to have a nice looking Windows 10 / Windows 10 mobile and XBOX one telegram app :smile:

**Comment by ztl8702** [comment]
+1 Actually I saw someone making one for his own use.

**Comment by sergioad** [comment]
Yes, indeed :smile:

**Comment by zhukov** [comment]
Duplicate #873
