### ISSUE TITLE
[Suggestion] Clipboard preview when pasting image

### ISSUE THREAD

**Issue by kevinhikaruevans** [zhukov/webogram#974]
Instead of having this dialog box (Are you sure you want to send file from clipboard?), would it be possible to also include a preview of the image you're pasting? I am concerned that I may copy/paste the wrong image, so it would be nice to include a preview thumbnail.

![image](https://cloud.githubusercontent.com/assets/4730591/11341912/639d3416-91b9-11e5-8f66-4073a1efaece.png)

**Comment by zhukov** [comment]
Duplicate #835
