### ISSUE TITLE
[Suggestion] Add option to show all URLs in a conversation

### ISSUE THREAD

**Issue by FacundoAcevedo** [zhukov/webogram#975]
I think it's a good idea have  an option to get all URLs written in a conversation. Like we have the button to filter images, video, voices message, etc.

**Comment by arieljannai** [comment]
+1

**Comment by romeroyonatan** [comment]
+1

**Comment by alexkoster** [comment]
+1

**Comment by kiddick** [comment]
+1

**Comment by mydexterid** [comment]
I thought the different versions of telegram have to work exactly the same.
Desktop has shared links, web doesn't.

**Comment by muzzol** [comment]
is this being worked on?

I miss this feature a lot.
