### ISSUE TITLE
[Suggestion] Customizable emoticon shortcuts

### ISSUE THREAD

**Issue by BumbleDevDotCom** [zhukov/webogram#976]
How about the possibility to add your own shortcuts for emoticons and maybe even for stickers, so one can enter for e.g. :D and it will be replaced by :joy: 
I like using emoticons in chats, but I don't like switching to the mouse to achieve that, because I personally cannot remember the official shortcuts (with the double point notations except for :joy:)
That would be cool! Thanks!

**Comment by zhukov** [comment]
Sorry, no plans to implement this feature by myself. Feel free to provide PR. Closing the issue for now.
