### ISSUE TITLE
Use Service Workers instead of AppCache

### ISSUE THREAD

**Issue by marco-c** [zhukov/webogram#979]
AppCache can sometimes be confusing (see for example #638), with Service Workers you have more control.

Service Workers could also be used to implement #399.

**Comment by marco-c** [comment]
`oghliner` [1] would allow simplifying the creation of the service worker and would also take care of the deployment to gh-pages (so you could simplify the Makefile scripts that are currently doing that).

[1] https://github.com/mozilla/oghliner

**Comment by Ryuno-Ki** [comment]
Since @marco-c already mentioned oghliner, read the article concerning [Service Worker for Offline First](https://hacks.mozilla.org/2015/11/offline-service-workers/) on Mozilla Hacks, too. (They have another one for the mentioned oghliner…).

**Comment by marco-c** [comment]
I submitted #980 to deploy to GitHub Pages using `oghliner`. I can take care of the service worker generation in another PR.

**Comment by marco-c** [comment]
I'm working on implementing this.
@zhukov in the patch I'm writing, I'm using service workers and appcache as a fallback. What do you think?

**Comment by marco-c** [comment]
In theory, if you want to use service workers for offlining, it'd be better to ditch AppCache (otherwise you'd end up caching the same files twice).

**Comment by marco-c** [comment]
Actually, forget my last comment. AppCache will be disabled when using Service Workers automatically: http://www.w3.org/TR/service-workers/#activation-algorithm

**Comment by marco-c** [comment]
@zhukov this is going to be necessary eventually, since Firefox is going to remove AppCache (https://bugzilla.mozilla.org/show_bug.cgi?id=1237782) and I suppose Chrome too.

**Comment by marco-c** [comment]
Yes, Chrome is going to deprecate it too in the future: http://stackoverflow.com/questions/28271843/is-service-worker-intended-to-replace-or-coexist-with-appcache/28806487#28806487
