### ISSUE TITLE
Support Push Notifications using Web Push

### ISSUE THREAD

**Issue by marco-c** [zhukov/webogram#981]
This would also require modifying the server.

**Comment by zhukov** [comment]
Can you provide some details, docs may be?

**Comment by marco-c** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/Push_API
https://developer.mozilla.org/en-US/docs/Web/API/Push_API/Using_the_Push_API

And there are some examples in the Service Worker Cookbook:
https://serviceworke.rs/

Web Push is somewhat similar to Simple Push (that I think you're already using).

**Comment by dolohow** [comment]
:+1:

**Comment by boghison** [comment]
Any news on this?

**Comment by TitanNano** [comment]
this is a elementary feature, especially for mobile user agents. @zhukov any plans for this?

**Comment by zhukov** [comment]
Yep. We'll start with GCM for Chrome in #703 and then may add Web Push for Fx.

**Comment by marco-c** [comment]
@zhukov why starting with GCM when both Chrome and Firefox support the Web Push standard?

**Comment by TitanNano** [comment]
@zhukov @marco-c yes chrome will ship web push soon. I also think focusing on web push first and adding GCM later, would make more sense.

**Comment by zhukov** [comment]
hmm.. may be I was wrong. can you point me to the most recent docs about Web Push for Chrome?

**Comment by marco-c** [comment]
So, Chrome will support the Web Push standard from Chrome 52 (which is due to be released in a couple of weeks, IIRC).

See the paragraph `Web Push Protocol and VAPID Support` in http://blog.chromium.org/2016/06/chrome-52-beta-css-containment-simpler.html.

**Comment by TitanNano** [comment]
@zhukov https://www.chromestatus.com/features/5748876422152192

**Comment by zhukov** [comment]
Thanks! Then I agree, it makes more sense to support Web Push at first.

**Comment by marco-c** [comment]
There are a few libraries for Web Push here (https://github.com/web-push-libs), if you need to check something. The Node.js one is the most up to date.

**Comment by FluorescentHallucinogen** [comment]
Any progress?

**Comment by kskarthik** [comment]
Well, we have multiple duplicate issues filed  ;)

**Comment by kskarthik** [comment]
Wow! Thanks !

**Comment by kskarthik** [comment]
@zhukov I am not getting any notifications 😐 

I'm on android M chrome. Notification test is positive https://tests.peter.sh/push-generator/#source=1;;payload=It

**Comment by TitanNano** [comment]
@kskarthik where are you testing the source? self-hosted? because web.telegram.org hasn't been updated yet.

**Comment by kskarthik** [comment]
But, I just see the commit on gh-pages !

**Comment by TitanNano** [comment]
then you need to test zhukov.github.io/webogram

**Comment by kskarthik** [comment]
Oh! Thanks for the help!

**Comment by zhukov** [comment]
@kskarthik Try https://zhukov.github.io/webogram
Was updated already

**Comment by kskarthik** [comment]
Just tried. Notifications are not working for me :(

**Comment by zhukov** [comment]
@kskarthik Do you see 'background notifications' options in settings? Try to reload the page.

**Comment by kskarthik** [comment]
Yes. I could see push notifications option enabled in settings. But I don't get any notifications. I have reset the site settings in chrome but no use. 

Are there any debugging options I could operate ?

**Comment by zhukov** [comment]
@kskarthik Is it desktop / mobile?

**Comment by kskarthik** [comment]
Mobile / Android 6 / Chrome

**Comment by kskarthik** [comment]
Asked my fried to test the same. He is on mobile/android L/chrome he too not getting notifications.

**Comment by zhukov** [comment]
@kskarthik Didn't try it on mobile yet. Will test today

**Comment by kskarthik** [comment]
Now its working after an update !

**Comment by TitanNano** [comment]
@zhukov I saw you removed simplePush support when you implemented the web push service. Would it be possible for you to opt it back in? I'm still using a FxOS device and FxOS never got the WebPush API. Once you remove simplePush support I won't be able to update telegram anymore :(

**Comment by TitanNano** [comment]
@zhukov I saw you set a time out of 1 min until the service worker will start triggering notifications. Wouldn't it be better to see if there are active windows and then display a notification if no instance is open? right now I don't get notifications when people send me a message less than 60 seconds after I closed the window.

**Comment by MasterGroosha** [comment]
Still not working (native notification appear for a moment and instantly hides itself). Chrome 55

**Comment by zhukov** [comment]
@TitanNano yep, added that here:
https://github.com/zhukov/webogram/commit/41bdb545a1508f682e4e9d1b1dafaedc9306f34c
