### ISSUE TITLE
Network Error on Wii U

### ISSUE THREAD

**Issue by Nama** [zhukov/webogram#982]
I tried to login with the browser of the Wii U and I am getting the "Network Error" directly after opening the website and as I try to login, similar to these two:
https://github.com/zhukov/webogram/issues/888
https://github.com/zhukov/webogram/issues/516

I can't imagine that this error is related to the CPU architecture, but the Wii U is powered also by a PowerPC.
I would test it also on a 3DS, but I don't have one to test it right now.

Since the other two reports aren't regarding the Wii U, I opened a new issue :3

![img_20151125_224349](https://cloud.githubusercontent.com/assets/2297270/11419226/38e004aa-9426-11e5-9a7c-efc4e9f72e6b.jpg)
![img_20151125_224410](https://cloud.githubusercontent.com/assets/2297270/11419227/38e56e86-9426-11e5-859d-8810495f72b7.jpg)

**Comment by Ryuno-Ki** [comment]
Doesn't even load on Nintendo 3DS (blank page).

But I didn't expect to do it - 3DS isn't even HTML5 capable :-/

`help.getNearestDc` receives a 404 (according to the screenshots).

**Comment by elraro** [comment]
Same error with Pale Moon 26.2.2 (x64)

**Comment by requeijaum** [comment]
Same error with TenFourFox 45.4.0.

**Comment by Aokromes** [comment]
#516 generic ticket
