### ISSUE TITLE
Telegram.me/share/ links inside webogram opens the @share user

### ISSUE THREAD

**Issue by asdofindia** [zhukov/webogram#988]
I just saw telegram share buttons on telegram blog that has the format

https://telegram.me/share/url?url=urlOfTheWebsite&text=TextToAccompany

When I send this sharing link in a telegram conversation and click on it from inside other apps, it opens the share view with the correct message.

When I click on this link inside webogram, it opens the telegram user with username share.

**Comment by mohamadaliakbari** [comment]
I have same issue in https://tarafdari.com

Example: https://www.tarafdari.com/node/627635
