### ISSUE TITLE
Supergroup support

### ISSUE THREAD

**Issue by FiveYellowMice** [zhukov/webogram#989]
Telegram has introduced new feature [supergroup](https://www.telegram.org/blog/supergroups) and it's already implemented on many platforms. However the web version still does not support it yet

**Comment by zhukov** [comment]
what do you mean? we do have basic support for supergroups in 0.5.1. Please provide screenshot and detailed description

**Comment by FiveYellowMice** [comment]
Sorry, it's just the Chrome App on my computer hasn't auto-updated yet, closing this issue.
