### ISSUE TITLE
View counters for every post in channels

### ISSUE THREAD

**Issue by Kondra007** [zhukov/webogram#990]
It would be **very nice** if you make Webogram show view counter for every post in channels.
I see that messages here are combined, but views are different.

![image](https://cloud.githubusercontent.com/assets/2780044/11459304/aa8ac926-96e4-11e5-9a49-d254ba7b8d57.png)

When message selected, the real second post view conter is seen

![image](https://cloud.githubusercontent.com/assets/2780044/11459355/e3cc4d94-96e5-11e5-897d-d0bcb638bcc3.png)

**Comment by zhukov** [comment]
Sorry, this is a feature, no plans to change this behaviour.
