### ISSUE TITLE
Вебограм не скрывает "last seen"

### ISSUE THREAD

**Issue by anya-gordeychuk** [zhukov/webogram#991]
Вижу в Вебограме, когда один мой друг онлайн и сколько минут назад вышел, хотя у него в настройках стоит "скрывать last seen от всех, кроме контактов", а я у него не в контактах. С Telegram Desktop и Telegram для Android всегда вижу у него только надпись "last seen recently".

При этом у второго друга стояла такая же настройка, и тоже я была не в контактах, но в вебе отображалось, как и должно быть, last seen recently.

Возможно тут дело в том, что первому другу я когда-то отправила контакт в одностороннем порядке, а второму нет. Либо дело в операционной системе - первый человек использует обычно веб и Андроид, второй айфон и мак.

**Comment by zhukov** [comment]
А с тем, у кого отображается, хотя не должно, происходит общение? Мы форсированно проставляем статус онлайн, когда получаем событие от человека, например "набирает текст" или "отправил сообщение" или "прочитал историю".

**Comment by anya-gordeychuk** [comment]
Да, общение происходит. Знаю про форсированный статус онлайн, но он отображается не только в течение нескольких секунд после написания мне сообщения или прочтения моего, как с Андроида и ТДесктоп, а намного дольше, и также с Web подробно видно, сколько минут назад (1, 2, 4...) заходил, вместо last seen recently.

**Comment by zhukov** [comment]
А можно ли получить подробный план действий со скриншотами?

**Comment by anya-gordeychuk** [comment]
Пожалуйста.
![1](https://cloud.githubusercontent.com/assets/16072445/11539592/88c0ab64-9930-11e5-97a0-7c4fe22f5a59.png)
![2](https://cloud.githubusercontent.com/assets/16072445/11539594/8bc6de00-9930-11e5-9d5c-22ce367e5680.png)
![3](https://cloud.githubusercontent.com/assets/16072445/11539595/8e42bd7a-9930-11e5-9c1f-db3f9d41cf74.png)
![4](https://cloud.githubusercontent.com/assets/16072445/11539597/90eb438a-9930-11e5-94e0-10f799459fcd.png)
![5](https://cloud.githubusercontent.com/assets/16072445/11539602/93b28fe2-9930-11e5-8851-4e127200415d.png)
![6](https://cloud.githubusercontent.com/assets/16072445/11539604/968b5c44-9930-11e5-9cbc-6ddb6e55652f.png)

![7](https://cloud.githubusercontent.com/assets/16072445/11539606/99e620b8-9930-11e5-8302-013b13a5e924.png)

**Comment by zhukov** [comment]
Спасибо, воспроизвел и поправил. Скоро появится на сайте.
