### ISSUE TITLE
Unable to reply to changed group title or group icon

### ISSUE THREAD

**Issue by fhoshino** [zhukov/webogram#997]
![2015-12-06_12-04-00](https://cloud.githubusercontent.com/assets/771955/11611613/c7f421d8-9c11-11e5-8788-d8d7fd4805ee.png)

For mobile client, users are able to reply to change of group title and group icon.
Webogram could also show this, but unable to perform the action.

**Comment by zhukov** [comment]
It's kinda hard to implement this feature right now in Webogram and I see no point in replying to service messages.
